/* GENERATED by music/export.ts from music/tracks/*.ts. Play each file looping [loopStart, loopStart + loopSeconds]. */
export type TrackInfo = { file: string; loopStart: number; loopSeconds: number };
export const TRACKS: Record<string, TrackInfo> = {
  'airlock': { file: 'music/airlock.mp3', loopStart: 0.336259, loopSeconds: 49.655172 }, // Red Button Bossa
  'ballpark': { file: 'music/ballpark.mp3', loopStart: 0.523923, loopSeconds: 51.428571 }, // Dead Reckoning
  'bracket-brawl': { file: 'music/bracket-brawl.mp3', loopStart: 0.831565, loopSeconds: 55.652174 }, // Main Event Neon
  'comment-section': { file: 'music/comment-section.mp3', loopStart: 0.368639, loopSeconds: 49.655172 }, // Doomscroll
  'finale': { file: 'music/finale.mp3', loopStart: 0.325329, loopSeconds: 54.857143 }, // Curtain Call
  'menu': { file: 'music/menu.mp3', loopStart: 0.751519, loopSeconds: 49.655172 }, // Hijinks!
  'odd-one-in': { file: 'music/odd-one-in.mp3', loopStart: 0.766259, loopSeconds: 46.451613 }, // Trench Coat Tiptoe
  'podium': { file: 'music/podium.mp3', loopStart: 0.416893, loopSeconds: 45.714286 }, // Victory Lap
  'quip-clash': { file: 'music/quip-clash.mp3', loopStart: 0.717007, loopSeconds: 50.526316 }, // Open Mic Swing
  'quiz-panic': { file: 'music/quiz-panic.mp3', loopStart: 0.338322, loopSeconds: 41.73913 }, // Checkout Waltz
  'reveal': { file: 'music/reveal.mp3', loopStart: 0.556825, loopSeconds: 42.666667 }, // Envelope, Please
  'shirt-show': { file: 'music/shirt-show.mp3', loopStart: 0.579955, loopSeconds: 60 }, // Title Belt Strut
  'sketch-bluff': { file: 'music/sketch-bluff.mp3', loopStart: 0.806689, loopSeconds: 41.73913 }, // Velvet Rope Waltz
  'split-decision': { file: 'music/split-decision.mp3', loopStart: 0.450635, loopSeconds: 48.813559 }, // Two Minds, One Rift
  'spooky': { file: 'music/spooky.mp3', loopStart: 0.826825, loopSeconds: 51.428571 }, // Creepy Crawl
  'tall-tales': { file: 'music/tall-tales.mp3', loopStart: 0.782404, loopSeconds: 43.636364 }, // Hot Off the Press
  'think-2': { file: 'music/think-2.mp3', loopStart: 0.280658, loopSeconds: 55.384615 }, // Doodle Hop
  'think': { file: 'music/think.mp3', loopStart: 0.610567, loopSeconds: 62.608696 }, // Scribble Time
  'vote': { file: 'music/vote.mp3', loopStart: 0.707619, loopSeconds: 46.451613 }, // Ballot Bounce
};
