import { useEffect, useRef, useState } from 'react';
import { DRAWING_COLORS, DRAWING_LIMITS, parseDrawing, type Drawing, type DrawingPoint } from '../../party-contract/src/index';
import { ArcadeButton } from './primitives';
export function DrawingRenderer({ drawing, label = 'Player drawing', className = '' }: { drawing: Drawing; label?: string; className?: string }) {
  return <svg className={`kp-drawing ${className}`} viewBox="0 0 1000 1000" role="img" aria-label={label}><rect width="1000" height="1000" fill="var(--kp-cream)" />{drawing.strokes.map((stroke, index) => <polyline key={index} points={stroke.points.map(point => `${point.x * 1000},${point.y * 1000}`).join(' ')} fill="none" stroke={stroke.color} strokeWidth={stroke.width * 1000} strokeLinecap="round" strokeLinejoin="round" />)}</svg>;
}
export function DrawingPad({ value, onChange, disabled = false, label = 'Draw here' }: { value: Drawing; onChange(drawing: Drawing): void; disabled?: boolean; label?: string }) {
  const [color, setColor] = useState<string>(DRAWING_COLORS[0]);
  const active = useRef<number | null>(null);
  const current = useRef(value); current.current = value;
  const surface = useRef<HTMLDivElement>(null);
  const release = () => { if (active.current !== null && surface.current?.hasPointerCapture(active.current)) surface.current.releasePointerCapture(active.current); active.current = null; };
  useEffect(() => { window.addEventListener('blur', release); return () => { window.removeEventListener('blur', release); release(); }; }, []);
  useEffect(() => { if (disabled) release(); }, [disabled]);
  function point(event: React.PointerEvent): DrawingPoint { const box = event.currentTarget.getBoundingClientRect(); return { x: Math.round(Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)) * 1000) / 1000, y: Math.round(Math.max(0, Math.min(1, (event.clientY - box.top) / box.height)) * 1000) / 1000 }; }
  function update(drawing: Drawing) { current.current = parseDrawing(drawing); onChange(current.current); }
  const count = value.strokes.reduce((sum, stroke) => sum + stroke.points.length, 0);
  return <div className="kp-drawing-pad"><div className="kp-row" aria-label="Ink color">{DRAWING_COLORS.map(ink => <button key={ink} className="kp-swatch" style={{ background: ink }} aria-label={`Ink ${ink}`} aria-pressed={ink === color} disabled={disabled} onClick={() => setColor(ink)} />)}</div><div ref={surface} className="kp-drawing-surface" aria-label={label} onPointerDown={event => { if (disabled || active.current !== null || value.strokes.length >= DRAWING_LIMITS.strokes || count > DRAWING_LIMITS.points - 2) return; event.preventDefault(); active.current = event.pointerId; event.currentTarget.setPointerCapture(event.pointerId); update({ strokes: [...value.strokes, { color, width: 0.012, points: [point(event), point(event)] }] }); }} onPointerMove={event => { if (active.current !== event.pointerId || disabled) return; const drawing = current.current; if (drawing.strokes.reduce((sum, stroke) => sum + stroke.points.length, 0) >= DRAWING_LIMITS.points) return; const next = point(event), last = drawing.strokes.at(-1)!, previous = last.points.at(-1)!; if (Math.hypot(next.x - previous.x, next.y - previous.y) < 0.006) return; update({ strokes: [...drawing.strokes.slice(0, -1), { ...last, points: [...last.points, next] }] }); }} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={() => { active.current = null; }}><DrawingRenderer drawing={value} label={label} /></div><div className="kp-row"><ArcadeButton tone="ghost" size="sm" disabled={disabled || !value.strokes.length} onClick={() => { release(); update({ strokes: value.strokes.slice(0, -1) }); }}>Undo stroke</ArcadeButton><ArcadeButton tone="ghost" size="sm" disabled={disabled || !value.strokes.length} onClick={() => { release(); update({ strokes: [] }); }}>Clear</ArcadeButton><span role="status">Ink detail: {count}/{DRAWING_LIMITS.points}</span></div></div>;
}
