/* Sketch Bluff content banks (server only; never imported by client code). All prompts and titles are original. */

/** Secret drawing prompts: absurd, drawable in 80 seconds, at most 40 characters, written as gallery titles. */
export const PROMPTS: readonly string[] = [
  'a dignified walrus filing taxes', 'a snail winning a drag race', 'a ghost afraid of the dark', 'a cactus giving free hugs',
  'a pigeon running for mayor', 'a shark at the dentist', 'a haunted vending machine', 'a giraffe stuck in a tunnel',
  'a cat judging a baking contest', 'a volcano with a cold', 'a robot learning to knit', 'a penguin on a sunbed',
  'a cowboy riding a goldfish', 'a sandwich with stage fright', 'a wizard at the car wash', 'a dragon roasting marshmallows',
  'a llama in a ball gown', 'a toaster falling in love', 'a mermaid at the laundrette', 'a sloth delivering pizza',
  'an octopus doing the dishes', 'a vampire at the beach', 'a grumpy cloud raining on a picnic', 'a hamster lifting weights',
  'a pirate afraid of water', 'a moose at a tea party', 'a skeleton playing the xylophone', 'a frog proposing marriage',
  'a burrito in a sleeping bag', 'a dinosaur trying to clap', 'a banana slipping on a person', 'a lighthouse with no friends',
  'a hedgehog at a balloon party', 'an alien buying groceries', 'a bear stuck in a revolving door', 'a knight fighting a vacuum cleaner',
  'a duck in a business suit', 'the tooth fairy on strike', 'a lobster playing the bagpipes', 'a carrot escaping a salad',
  'a lonely sock looking for love', 'a superhero doing laundry', 'a yeti at the hairdresser', 'a crab directing traffic',
  'a kangaroo with an overfull pouch', 'a mummy unravelling on the dancefloor', 'a bee allergic to flowers', 'a worm with a moustache',
  'a pancake doing a backflip', 'a gorilla with a tiny umbrella', 'a snowman in a sauna', 'a horse taking a selfie',
  'a chicken crossing a motorway', 'a turtle late for work', 'a goldfish playing fetch', 'a unicorn stuck in traffic',
  'a castle made of jelly', 'a bat hanging from a ceiling fan', 'a squirrel robbing a bank', 'a rhino in ballet shoes',
  'a teapot having a tantrum', 'an owl who can’t stay awake', 'a zombie at a job interview', 'a camel at an ice rink',
  'a pizza delivering a pizza', 'a baby elephant on a seesaw', 'a polar bear selling ice cream', 'a lemon telling a sad story',
  'a raccoon at a fancy dinner', 'a fish riding a bicycle', 'a bodybuilding broccoli', 'a giant at a tiny restaurant',
  'a spider knitting a jumper', 'a mole with a sunburn', 'a parrot hosting a talk show', 'a magician sawing a sandwich in half',
  'a cupcake in a boxing ring', 'a bus full of ducks', 'a flamingo doing yoga', 'a scarecrow scared of crows',
  'a peacock having a bad hair day', 'a tiny knight riding a cat', 'a worm on a waterslide', 'a jellyfish at a rock concert',
  'a hippo in a bubble bath', 'a goat eating someone’s homework', 'a dog driving a convertible', 'the moon getting a haircut',
  'a ninja stepping on a rake', 'a whale in a goldfish bowl', 'a sock puppet with a sock puppet', 'a postbox full of bees',
  'a fox playing chess with a hen', 'a train made of sausages', 'a pirate with seven parrots', 'a candle afraid of birthdays',
  'a sunflower wearing sunglasses', 'a koala hugging a lamppost', 'a bird nesting in a beard', 'a kettle singing opera',
  'a skunk at a perfume counter', 'a pumpkin on a diet', 'a beaver building a skyscraper', 'a dentist brushing a crocodile',
  'a time traveller missing the bus', 'a lion getting a perm', 'a pig flying a kite', 'a monster scared of a toddler',
  'a snail with a jetpack', 'an ant carrying a whole sandwich', 'a cheese wheel rolling downhill', 'a seagull stealing a hot dog',
  'a cow abducting an alien', 'a royal corgi on a throne', 'a caveman inventing the selfie', 'a chef cooking a boot',
  'an astronaut walking a dog', 'a mouse lifting an elephant', 'a turtle wearing a tutu', 'a referee at a pillow fight',
  'a tornado tidying a bedroom', 'a hot dog at a dog show', 'a pineapple in a hammock', 'a bulldozer picking flowers',
  'a giraffe with a very long scarf', 'a hen hatching a football', 'a sheep counting people', 'a ladder too short for the job',
  'a baby dragon’s first sneeze', 'a wedding between two snowmen', 'a squid playing the drums', 'a lamp reading a bedtime story',
  'a frog on a pogo stick', 'a bathtub sailing the ocean', 'a mouse guarding a giant cheese', 'a sleepy sun refusing to rise',
  'a doughnut lifeguard', 'a bear in a shopping trolley', 'a werewolf getting a shave', 'a penguin delivering the post',
  'a cyclops at the optician', 'a wizard with a baguette wand', 'a snake wearing socks', 'a dancing traffic cone',
  'an egg hatching a tiny car', 'a duck teaching swimming lessons', 'a badly parked spaceship', 'a bowl of soup with a shark in it',
  'a pillow fight between clouds', 'a garden gnome guarding treasure', 'a horse playing hopscotch', 'a crocodile buying a handbag',
  'a phone that needs a nap', 'a balloon escaping a party', 'a tree hugging a person', 'a baby with a briefcase',
  'a strawberry sunbathing on cream', 'a cat running a lemonade stand', 'a rocket-powered bathtub', 'a goose chasing a tractor',
  'a ghost doing a magic trick', 'a beetle pulling a carriage', 'a reindeer on a skateboard', 'a slug in a racing car',
  'a clown car with one clown', 'a cat stuck in a wizard hat', 'a camel with three humps', 'a polar bear in a heatwave',
  'a pug in a superhero cape', 'a castle with a drive-through', 'a lighthouse at a disco', 'a sock monster eating laundry',
  'a rainbow running out of colours', 'a tortoise at speed dating', 'a puppet cutting its own strings', 'a cactus at a pool party',
  'a viking in a canoe', 'a sausage dog on a treadmill', 'a leaf blower chasing one leaf', 'a mountain climbing a person',
  'an alarm clock that overslept', 'a hamster wheel power station', 'a toad wearing a crown', 'a birthday cake on fire',
  'a dragon guarding a sandwich', 'a moose trying on hats', 'a snowball in a frying pan', 'a fridge full of penguins',
  'a ghost with the hiccups', 'a kitten with a lion’s shadow', 'a mermaid learning to ride a bike', 'a disco ball feeling left out',
  'a toaster launching a waffle into space', 'a wizard stuck in a phone box', 'a lobster conducting an orchestra', 'a knight jousting on a lawnmower',
  'a goat on a trampoline', 'a gingerbread man running a marathon', 'a cloud eating a rainbow', 'a bat with a torch',
  'a carrot getting a tan', 'a hen giving a speech', 'a squirrel hoarding phones', 'a shoelace tying itself in knots',
  'a robot walking a robot dog', 'a dinosaur doing homework', 'a bear’s first day at school', 'a slice of pizza surfing',
  'a mermaid selling fish fingers', 'a teabag in a hot tub', 'a cowboy lassoing a cloud', 'a jellyfish wearing a hat',
  'a llama spitting at a mime', 'a shoe that is afraid of feet', 'a tiny dragon in a teacup', 'a wolf in a wool shop',
  'a parrot in a library', 'a hippo tiptoeing past a mouse', 'a vampire at a garlic festival', 'a submarine in a puddle',
  'an elephant hiding behind a lamp', 'a tired superhero on a bench', 'a ghost hanging out the washing', 'a spider on roller skates',
  'a sandcastle at high tide', 'a frog in a business meeting', 'a rabbit pulling a magician from a hat', 'a cow on a rollercoaster',
  'a ladybird with no spots', 'a gargoyle on its lunch break', 'a pirate getting a parking ticket', 'a duck in wellies',
  'an octopus juggling', 'a giraffe in a tiny car', 'a cabbage at a beauty pageant', 'a koala bodyguard',
  'a bowl of spaghetti escaping', 'a sheep at the barber', 'a flying fish on an aeroplane', 'a cupcake volcano erupting',
  'a tiny horse riding a big horse', 'a robot crying at a movie', 'a centipede buying shoes', 'a cat walking a human on a lead',
  'a dancing pickle', 'a balloon animal coming to life', 'a mime trapped in a real box', 'a goldfish with a snorkel',
  'a llama on a unicycle', 'a ghost shopping for bedsheets', 'a penguin in a tuxedo shop', 'a broom flying without a witch',
  'a bear juggling fish', 'a snail on a tightrope', 'the sun wearing sunscreen', 'a dragon at the fire station',
  'a castle with a moat of soup', 'an elephant sneezing', 'a hamster in a hot air balloon', 'a whale blowing bubbles',
  'a king on a bouncy castle', 'a worm reading a book', 'a crab giving haircuts', 'a rubber duck ship captain',
  'a cat in a space suit', 'an angry carrot chasing a rabbit', 'a snowman with a hairdryer', 'a cactus learning to juggle',
  'a bee driving a tiny bus', 'a walrus brushing its tusks', 'a hedgehog in a hug queue', 'a wizard losing at rock paper scissors',
  'a tea party in a submarine', 'a snake doing the limbo', 'a nervous bowling pin', 'a duck feeding the humans',
];

/** Cheekier prompts, only when family mode is off. */
export const ADULT: readonly string[] = [
  'a skeleton with a hangover', 'a cat doing the walk of shame', 'a wine glass at a toddler party', 'a vampire on a dating app',
  'a snowman’s awkward first kiss', 'a pirate in his underpants', 'a bear getting his back waxed', 'a mermaid’s dating profile photo',
  'a cocktail ordering a cocktail', 'a beer belly with a face', 'a grandma at a rave', 'a stag do of penguins',
  'a robot sneaking out of a bar', 'a mummy in a bikini', 'a goat that drank all the punch', 'a ghost streaking through a museum',
  'a toilet with stage fright', 'a pigeon in a nightclub queue', 'a dog wearing only a bow tie', 'a superhero’s regrettable tattoo',
  'a raccoon with a beer gut', 'a tipsy cupid missing the target', 'a llama at speed dating', 'a frog’s terrible chat-up line',
  'a nudist beach for snowmen', 'a hen at a hen party', 'a vampire with a wine stain', 'a hungover tooth fairy',
  'a unicorn on a stag do', 'a baby with stubble', 'a moose at a karaoke afterparty', 'a pigeon doing a sneaky wee',
];

/** House titles: decoys that pad the guess list to four and fill "Title for me". Same voice as the prompts. */
export const DECOYS: readonly string[] = [
  'a confused emu learning the tuba', 'a sad potato at the opera', 'a lizard selling insurance', 'a cheerful iceberg',
  'a moth in love with a lamp', 'a nervous blender', 'a seal balancing a wedding cake', 'the world’s smallest volcano',
  'a goose with a secret', 'a pelican in a phone box', 'a badger doing stand-up comedy', 'a haunted wheelbarrow',
  'a hamster in a bow tie', 'a cloud with a toothache', 'a duck auditioning for ballet', 'a worried lighthouse keeper',
  'an otter with a briefcase', 'a jellybean on trial', 'a muffin running for office', 'a crocodile in a canoe',
  'a parrot reading the news', 'a very tired dinosaur', 'a pigeon wearing a monocle', 'a lion at the launderette',
  'a sheep on a motorbike', 'a deer in a bubble bath', 'a turnip at a tea dance', 'a koala at the cinema',
  'a fish who forgot its lines', 'a cat hosting a quiz', 'a goat at the opera', 'a giant baby on a small horse',
  'a wizard looking for his keys', 'a hedgehog in a hammock', 'a bear on a pedalo', 'a robot ordering soup',
  'a chicken in a ball pit', 'an angry bagel', 'a ghost at the gym', 'a mole playing golf',
  'a lobster learning to whistle', 'a snail with a mortgage', 'a rhino in a rowing boat', 'a sausage at a pool party',
  'a beaver with a chainsaw', 'a wombat on a tightrope', 'a poodle in a puddle', 'a pirate at a spelling bee',
  'a camel at the post office', 'a chef chasing a chicken', 'a dog doing its taxes', 'a pancake in a tutu',
  'a squid at a job interview', 'a lettuce with a grudge', 'a gorilla on a pogo stick', 'a meatball on a skateboard',
  'a heron on a treadmill', 'a jealous lamp post', 'a crab at a pottery class', 'a dragon in a dressing gown',
  'a sloth winning gold', 'a teapot on a tightrope', 'a cactus in a sleeping bag', 'a bat at a sleepover',
  'a mermaid at the car boot sale', 'a cowboy on a rocking horse', 'a mushroom with an umbrella', 'a penguin at the airport',
  'a raccoon in a ball gown', 'a hippo at a piano recital', 'a duck with a tax refund', 'a goldfish on holiday',
  'a monkey at a museum', 'a yeti on a beach towel', 'a vampire knitting a scarf', 'a frog at the hairdresser',
  'a pigeon in a top hat', 'a cheese at a candlelit dinner', 'a horse in pyjamas', 'a spider at a disco',
  'a unicorn with a cold', 'a tortoise in a race car', 'an owl doing the crossword', 'a sardine on a surfboard',
  'a grizzly bear at ballet class', 'a walrus in a wetsuit', 'a lamb at a rock concert', 'a donkey in a deckchair',
  'a scarecrow on a date', 'a flamingo on stilts', 'a robot at a wedding', 'a bulldog in a beret',
  'a mouse running a marathon', 'a swan with stage fright', 'a pineapple in a party hat', 'a toad in a top hat',
  'a ferret in a fur coat', 'a sloth at the starting line', 'a carrot with a cape', 'an ostrich at the opera',
  'a llama at the library', 'a shrimp lifting weights', 'a goose at the ballet', 'a panda with a paintbrush',
  'a giraffe at the dentist', 'a shark in a sweater', 'a hen on a hoverboard', 'a seagull with a sandwich board',
  'a portrait of a very proud potato', 'a still life with an angry pear', 'a self-portrait of a goose', 'a duck’s retirement party',
];

/** Cheekier house titles, only when family mode is off. */
export const ADULT_DECOYS: readonly string[] = [
  'a walrus with a wine problem', 'a goose doing a stag do', 'a snail’s regrettable tattoo', 'a hamster at happy hour',
  'a vampire’s morning-after selfie', 'a badger in a bathrobe', 'a llama on a bender', 'a clown’s divorce party',
  'a pigeon with a hangover', 'a mermaid’s bad first date', 'a poodle at a pub crawl', 'a grumpy nan at a nightclub',
];

export const promptPool = (family: boolean) => family ? PROMPTS : [...PROMPTS, ...ADULT];
export const decoyPool = (family: boolean) => family ? DECOYS : [...DECOYS, ...ADULT_DECOYS];
