import { useState } from 'react';
import { ArcadeButton, Modal, Panel, TextInput, type LobbyViewProps } from '../../../party-ui/src/index';
import { FIGHTERS, type FighterKind, type LobbyChoice, type Settings } from './model';
import { getStage, STAGE_IDS, type StageId } from './stages';
import { FighterChoices, FighterDetails, StageCard, StagePreview, portrait } from './selection';
export function Lobby({ players, playerId, settings, connected, error, onChoice, onReady }: LobbyViewProps<Settings>) {
  const me = players.find(p => p.id === playerId), choice = me?.lobbyChoice as LobbyChoice | undefined;
  const [step, setStep] = useState<'fighter' | 'map'>(choice?.kind ? 'map' : 'fighter'), [preview, setPreview] = useState<FighterKind>(choice?.kind ?? 'mario'), [query, setQuery] = useState(''), [details, setDetails] = useState(false);
  const stage = choice?.stage ?? 'cloudbreak', votes = players.flatMap(p => { const c = p.lobbyChoice as LobbyChoice | undefined; return c?.stage ? [c.stage] : []; });
  if (!me) return <Panel className="sky-clash-lobby sc-lobby-display"><h2>Choose while your friends join</h2><p>Pick a fighter, vote for a map, then tap Ready. Starting locks the votes. Most votes wins; ties are drawn randomly.</p><div className="sc-lobby-seats">{players.map(p => { const c = p.lobbyChoice as LobbyChoice | undefined; return <article key={p.id}>{c?.kind && <img src={portrait(c.kind)} alt="" width="80" height="80"/>}<strong>{p.name}</strong><span>{c?.kind ? FIGHTERS[c.kind].name : 'Choosing a fighter'}</span><span>{c?.stage ? getStage(c.stage).name : 'Map vote pending'}</span><small>{p.ready ? 'Ready' : p.connected ? 'Choosing' : 'Offline'}</small></article>; })}</div><div className="sc-lobby-leaders">{STAGE_IDS.filter(id => votes.includes(id)).map(id => <article key={id}><StagePreview id={id}/><strong>{getStage(id).name} · {votes.filter(v => v === id).length} votes</strong></article>)}</div></Panel>;
  if (me.ready) return <Panel className="sky-clash-controller sky-clash-lobby sc-lobby-ready"><h2>You’re ready, {me.name}</h2><img src={portrait(choice!.kind!)} alt={FIGHTERS[choice!.kind!].name} width="100" height="100"/><strong>{FIGHTERS[choice!.kind!].name}</strong><StagePreview id={choice!.stage!}/><p>Your vote: {getStage(choice!.stage!).name}</p><p>{players.filter(p => p.ready).length}/{players.length} ready · Waiting for the host to start.</p><ArcadeButton tone="ghost" disabled={!connected} onClick={() => onReady(false)}>Not ready · change choices</ArcadeButton><details><summary>Controls & match rules</summary><p>Move with the left pad. Tap Jump for a short hop, hold for a full jump, and press again for air jumps. Tilt while using Attack, Smash or Special for directional moves. Hold Shield to guard. Higher damage launches farther; lose all stocks and you’re out.</p></details></Panel>;
  const chooseStage = (stage: StageId) => onChoice({ kind: choice?.kind ?? preview, stage });
  return <Panel className="sky-clash-controller sky-clash-lobby sc-menu" style={{ '--sc-color': FIGHTERS[preview].color } as React.CSSProperties}>
    <header className="sc-menu-header"><div><h2>{step === 'fighter' ? 'Choose your fighter' : 'Vote for a map'}</h2><p>{me.name} · {players.length}/4 joined · Choose while friends arrive</p></div><span className="sc-step">{step === 'fighter' ? '1 / 2' : '2 / 2'}</span></header>
    {step === 'fighter' ? <FighterChoices value={preview} disabled={!connected} onChange={kind => { setPreview(kind); onChoice({ kind, stage: choice?.stage ?? null }); }}/>
      : <><div className="sc-menu-tools"><TextInput type="search" aria-label="Search maps" placeholder="Search 30 maps" value={query} onChange={e => setQuery(e.target.value)}/><button className="sc-more" onClick={() => setStep('fighter')}>← Fighter</button></div><div className="sc-map-tiles" role="group" aria-label="Maps" tabIndex={0}>{STAGE_IDS.filter(id => `${getStage(id).name} ${getStage(id).source ?? ''}`.toLowerCase().includes(query.trim().toLowerCase())).map(id => <button type="button" key={id} className={`sc-map-tile${choice?.stage === id ? ' sc-tile-on' : ''}`} aria-label={getStage(id).name} aria-pressed={choice?.stage === id} disabled={!connected} onClick={() => chooseStage(id)}><StagePreview id={id}/><strong>{getStage(id).name}</strong><small>{votes.filter(v => v === id).length} votes</small></button>)}</div></>}
    <footer className="sc-menu-footer"><button className="sc-more" aria-label={`Details for ${step === 'fighter' ? FIGHTERS[preview].name : getStage(stage).name}`} onClick={() => setDetails(true)}><strong>{step === 'fighter' ? FIGHTERS[preview].name : getStage(stage).name}</strong><small>Details</small></button>{step === 'fighter' ? <ArcadeButton tone="lime" disabled={!connected} onClick={() => { onChoice({ kind: preview, stage: choice?.stage ?? null }); setStep('map'); }}>Next: map vote</ArcadeButton> : <ArcadeButton tone="lime" disabled={!connected || !choice?.kind || !choice?.stage} onClick={() => onReady(true)}>Ready to play</ArcadeButton>}{error && <p className="sc-menu-error" role="alert">{error}</p>}</footer>
    {details && (step === 'fighter' ? <FighterDetails kind={preview} onClose={() => setDetails(false)}/> : <Modal title={getStage(stage).name} onClose={() => setDetails(false)}><StageCard choice={stage} hazards={settings.hazards ?? true}/></Modal>)}
  </Panel>;
}
