// Server-only original content. Never import this module from a client entry.
export const prompts = [
  'The tiny complaint printed inside every fortune cookie:',
  'A suspicious new button on the office microwave:',
  'The worst thing to hear from a talking houseplant:',
  'The secret third setting on a toaster:',
  'A very unreasonable demand from your laundry basket:',
  'The slogan for a gym run entirely by sloths:',
  'What pigeons put on their business cards:',
  'A terrible name for a fancy umbrella:',
  'The reason your socks have formed a committee:',
  'A warning label that should come with glitter:',
  'The first rule of a book club for squirrels:',
  'The least useful feature on a smart spoon:',
  'The title of a dramatic movie about a lost remote:',
  'The surprise item in a wizard’s grocery basket:',
  'A polite way to tell a dragon to stop using your driveway:',
  'The official job title of the person who sorts confetti:',
  'A terrible excuse for being late to your own surprise party:',
  'The thing a snowman keeps in a secret drawer:',
  'What a vacuum cleaner writes in its diary:',
  'A restaurant special that makes the waiter whisper:',
  'The real reason the elevator plays music:',
  'An inspirational quote for a very tired sandwich:',
  'A rejected event at the neighborhood Olympics:',
  'The name of a luxury hotel for garden gnomes:',
  'A weird thing to announce over the supermarket speakers:',
  'The one item missing from every pirate’s packing list:',
  'What your couch would say in a job interview:',
  'The least impressive trick a magician could perform:',
  'A new holiday invented by the dishwasher:',
  'The headline in a newspaper written by ants:',
  'A questionable upgrade to the humble pencil:',
  'The real purpose of that mysterious kitchen drawer:',
  'What aliens think a salad spinner is for:',
  'The first thing a cat would ban as mayor:',
  'A terrible prize for winning a staring contest:',
  'The name of a detective agency run by ducks:',
  'The announcement nobody expected at the library:',
  'A surprisingly emotional review of a paperclip:',
  'The password to an exclusive club for potatoes:',
  'The fine print on a coupon from a genie:',
  'What a robot brings to a potluck:',
  'The complaint department’s response to a squeaky moon:',
  'A motivational poster in a snail’s office:',
  'The least practical pocket to add to pajamas:',
  'A name for a band made entirely of substitute teachers:',
  'What happens when a calendar takes a day off:',
  'The first sentence in a cactus’s autobiography:',
  'A suspiciously specific rule at the bowling alley:',
  'The terrible secret behind a winning pumpkin:',
  'The customer service message from your broken magic wand:',
  'What a cloud orders at a drive-through:',
  'The newest badge available to adult scouts:',
  'The emergency announcement at a teddy bear picnic:',
  'An invention that makes brushing your teeth much harder:',
  'The name of a cooking show hosted by a smoke alarm:',
  'A surprising item on a mermaid’s chore chart:',
  'The reason a pancake needs a tiny briefcase:',
  'What a traffic cone says to impress a date:',
  'The worst slogan for a company that sells ladders:',
  'A strongly worded note from the neighborhood moon:',
  'The official excuse for a haunted printer:',
  'The next big trend in competitive napping:',
  'A very bad hiding place for a marching band:',
  'The announcement at an airport for migrating geese:',
  'The unexpected side effect of alphabet soup:',
  'A grand achievement for a nervous doorbell:',
  'The inscription on a trophy for doing absolutely nothing:',
  'A surprising requirement for joining a secret knitting society:',
  'What an octopus writes on a sick note:',
  'The one thing you should never say to a fancy cheese:',
  'The title of a self-help book for tangled headphones:',
  'A terrible new feature in the next version of stairs:',
] as const;
