"""Reproduce 27 pinned public DAT profiles; six bonus fighters are explicit adaptations."""
import hashlib,json,re,struct,sys
from pathlib import Path
from urllib.parse import quote
ROOT=Path(__file__).resolve().parents[1]
roster=json.loads((ROOT/'fidelity/roster.json').read_text())
header=Path(sys.argv[2]).read_bytes()
assert hashlib.sha256(header).hexdigest()=='1c1d616d42a91b083d8fb5cac5a1b494e22c92779e7817dec9daa875289967ff'
fields=re.findall(r'/\* \+([0-9A-Fa-f]{3}) fp\+[0-9A-Fa-f]+ \*/ (float|int) (\w+);',header.decode())
dumps={}
for r in roster:
 if r['bonus']:continue
 raw=(Path(sys.argv[1])/r['file']).read_bytes();assert hashlib.sha256(raw).hexdigest()==r['sha256'],r['id']
 d=json.loads(raw);dumps[r['id']]=(d,next(n['data'] for n in d['nodes'] if n['name']==r['node']))
attrs={};scripts={}
names={'Attack11','AttackS3S','AttackS3','AttackS31','AttackHi3','AttackLw3','AttackS4','AttackS4S','AttackS41','AttackHi4','AttackLw4','AttackAirN','AttackAirF','AttackAirB','AttackAirHi','AttackAirLw'}
for r in roster:
 if r['bonus']:continue
 kind=r['id'];d,data=dumps[kind];values={}
 for off,typ,key in fields:
  if int(off,16)>0xb8 and not 0xe4<=int(off,16)<=0xf8:continue
  entry=data['attributes'][int(off,16)//4];v=entry['value']
  if typ=='int' and '?' in entry['name']:v=struct.unpack('>i',struct.pack('>f',v))[0]
  values[key]=v
 attrs[kind]=values;actions=[]
 for index,a in enumerate(data['subactions']):
  # Nana shares Popo's animation table but has her own action-command stream.
  animationDump,animationData=dumps['popo'] if kind=='nana' else (d,data)
  animation=animationData['subactions'][index];name=animation.get('shortName','')
  if name not in names:continue
  anim=animationDump['animationFiles'][animation['animationFile']] if 'animationFile' in animation else None
  actions.append({'name':name,'frames':anim['nodes'][0]['data']['numFrames'] if anim else 0,'events':[bytes.fromhex(e['bytes']).hex() for e in a['events']]})
 routines={k:[bytes.fromhex(e['bytes']).hex() for e in v] for k,v in data['subroutines'].items()}
 # Retain only subroutines reachable from chosen normal attacks, avoiding unused presentation data.
 needed={};pending=[a['events'] for a in actions]
 while pending:
  for event in pending.pop():
   if int(event[:8],16)>>26 not in [5,7]:continue
   offset=str(int(event[8:16],16))
   assert offset in routines,(kind,offset)
   if offset not in needed:needed[offset]=routines[offset];pending.append(routines[offset])
 scripts[kind]={'source':{'url':'https://melee.theshoemaker.de/dat-dumps/'+quote(r['file']),'sha256':r['sha256'],'revisionVerified':False,'animationProfile':'popo' if kind=='nana' else kind},'actions':actions,'subroutines':needed}
for r in roster:
 if r['bonus']:attrs[r['id']]=dict(attrs[r['profile']])
for file,variable,data in [('attributes','ATTRIBUTES',attrs),('scripts','SCRIPTS',scripts)]:
 (ROOT/'fidelity'/(file+'.ts')).write_text('// Generated by tools/import_roster.py; source revision unverified.\nexport const '+variable+' = '+json.dumps(data,indent=2)+' as const;\n')
metadata={r['id']:{k:v for k,v in r.items() if k not in ['id','file','sha256','node','archive']} for r in roster}
(ROOT/'src/roster.ts').write_text('// Generated from fidelity/roster.json by tools/import_roster.py.\nexport const ROSTER_DATA = '+json.dumps(metadata,indent=2)+' as const;\nexport type FighterKind = keyof typeof ROSTER_DATA;\nexport const ROSTER = Object.keys(ROSTER_DATA) as FighterKind[];\n')
print(f'Imported {len(scripts)} sourced profiles × 53 scalar attributes; 6 explicit bonus profiles; {sum(len(s["actions"]) for s in scripts.values())} normal scripts')
