"""Import every combat subaction (normals, specials, grabs/throws, ledge/getup/tech/dodge actions) from the 27 pinned dumps.

Usage: python3 tools/import_moves.py [dump-dir]   (default: ~/Documents/ChatGPT/partyplay/output/melee-fidelity)
Writes fidelity/actions.ts: per sourced profile, action name -> [animation frames, filtered command stream] plus the
subroutines those streams reach. Only combat-relevant opcodes are kept (timers, loops, calls, hitboxes and their edits,
autocancel/flag toggles, IASA, throw data/release, projectile spawns, body-collision states, jab follow-ups, self damage,
smash charge); graphics, sounds, rumble and texture commands are dropped. Dumps are sha256-pinned by fidelity/roster.json.
"""
import hashlib, json, re, sys
from pathlib import Path
from urllib.parse import quote
ROOT = Path(__file__).resolve().parents[1]
DUMPS = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / 'Documents/ChatGPT/partyplay/output/melee-fidelity'
roster = json.loads((ROOT / 'fidelity/roster.json').read_text())
# Opcodes (command byte >> 2) the engine interprets; see src/moveset.ts compile().
KEEP = {0, 1, 2, 3, 4, 5, 6, 7, 11, 12, 13, 15, 16, 19, 20, 23, 24, 26, 29, 30, 34, 51, 56}
COMMON = re.compile(r'^(Attack|Special|Catch|Throw|Cliff|Down(Bound|Wait|Stand|Attack|Foward|Back|Spot)|Passive|Escape|Guard|Landing|Appeal[RL]?$|Rebound$|FuraFura$|Squat|Turn|Dash$|RunBrake$|JumpF$|JumpAerialF|Capture(Cut|Jump)$|Entry$|Eat)')
dumps = {}
for r in roster:
  if r['bonus']: continue
  raw = (DUMPS / r['file']).read_bytes()
  assert hashlib.sha256(raw).hexdigest() == r['sha256'], r['id']
  d = json.loads(raw); dumps[r['id']] = (d, next(n['data'] for n in d['nodes'] if n['name'] == r['node']))
out = {}; total = 0
for r in roster:
  if r['bonus']: continue
  kind = r['id']; d, data = dumps[kind]
  # Nana shares Popo's animation table (names, frame counts) but has her own command streams.
  ad, adata = dumps['popo'] if kind == 'nana' else (d, data)
  keep = lambda events: ' '.join(h for h in (e['bytes'].replace(' ', '') for e in events) if int(h[:2], 16) >> 2 in KEEP)
  actions, seen = {}, {}
  for i, a in enumerate(data['subactions']):
    anim = adata['subactions'][i] if i < len(adata['subactions']) else a
    name = anim.get('shortName') or ''
    if not COMMON.match(name): continue
    seen[name] = seen.get(name, 0) + 1
    key = name if seen[name] == 1 else f'{name}#{seen[name]}'
    frames = ad['animationFiles'][anim['animationFile']]['nodes'][0]['data']['numFrames'] if 'animationFile' in anim else 0
    actions[key] = [int(frames), keep(a['events'])]
  routines = {k: v for k, v in data['subroutines'].items()}
  needed, pending = {}, [s for _, s in actions.values()]
  while pending:
    for h in filter(None, pending.pop().split(' ')):
      if int(h[:2], 16) >> 2 not in (5, 7): continue
      off = str(int(h[8:16], 16)); assert off in routines, (kind, off)
      if off not in needed: needed[off] = keep(routines[off]); pending.append(needed[off])
  out[kind] = {'source': {'url': 'https://melee.theshoemaker.de/dat-dumps/' + quote(r['file']), 'sha256': r['sha256'], 'revisionVerified': False,
    'animationProfile': 'popo' if kind == 'nana' else kind}, 'actions': actions, 'routines': needed}
  total += len(actions)
body = ',\n'.join(f'  {json.dumps(k)}: {{ "source": {json.dumps(v["source"])},\n    "actions": {{\n' + ',\n'.join(f'      {json.dumps(n)}: {json.dumps(a)}' for n, a in v['actions'].items())
  + '\n    },\n    "routines": ' + json.dumps(v['routines']) + ' }' for k, v in out.items())
(ROOT / 'fidelity/actions.ts').write_text('// Generated by tools/import_moves.py from sha256-pinned dumps; source revision unverified.\n'
  '// action name -> [animation frames, space-separated combat commands (hex)]. Repeated names are suffixed #2, #3...\n'
  'export const ACTIONS: Record<string, { source: { url: string; sha256: string; revisionVerified: boolean; animationProfile: string }; actions: Record<string, [number, string]>; routines: Record<string, string> }> = {\n' + body + '\n};\n')
print(f'Imported {total} combat actions for {len(out)} sourced profiles')
