"""Import a pinned research dump; no network, inferred values, or runtime defaults."""
import hashlib, json, re, struct, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
EXPECTED = '4533034a5db1b2d7949763b196f5a9cb2361b567da8ba6f8ad7c5a898a55e98f'
raw = Path(sys.argv[1]).read_bytes()
if hashlib.sha256(raw).hexdigest() != EXPECTED:
    raise SystemExit('Unexpected dump hash. Audit the new source before importing.')
dump = json.loads(raw)
if dump['sourceFile'] != 'PlFx.dat': raise SystemExit('Expected PlFx.dat')
data = next(n['data'] for n in dump['nodes'] if n['name'] == 'ftDataFox')
header = Path(sys.argv[2]).read_text()
if hashlib.sha256(header.encode()).hexdigest() != '1c1d616d42a91b083d8fb5cac5a1b494e22c92779e7817dec9daa875289967ff':
    raise SystemExit('Unexpected decompilation attribute header')
# Restrict semantic mapping to the fully scalar common prefix. Later fields include vectors/unions.
fields = re.findall(r'/\* \+([0-9A-Fa-f]{3}) fp\+[0-9A-Fa-f]+ \*/ (float|int) (\w+);', header)
attrs = {}
for offset,kind,name in fields:
    if int(offset,16) > 0xB8: continue
    entry=data['attributes'][int(offset,16)//4]; value=entry['value']
    if kind == 'int' and '?' in entry['name']: value=struct.unpack('>i',struct.pack('>f',value))[0]
    attrs[name]=value
if len(attrs) != 47 or attrs['max_jumps'] != 2: raise SystemExit('Unexpected common attribute layout')
def events(items):
    result=[]
    for e in items:
        b=bytes.fromhex(e['bytes'])
        if len(b)!=e['length']: raise SystemExit('Event byte length mismatch')
        result.append({'name':e.get('name', 'unknown:'+e['commandId']),'hex':b.hex()})
    return result
actions=[]
for a in data['subactions']:
    animation=dump['animationFiles'][a['animationFile']] if 'animationFile' in a else None
    frames=animation['nodes'][0]['data']['numFrames'] if animation else None
    actions.append({'name':a.get('shortName',''), 'offset':a['eventsOffset'], 'animationOffset':a['animOffset'], 'animationBytes':a['animSize'], 'animationFrames':frames, 'events':events(a['events'])})
subroutines=[{'offset':int(offset),'events':events(items)} for offset,items in data['subroutines'].items()]
result={'source':{'url':'https://melee.theshoemaker.de/dat-dumps/Fox.json','sha256':EXPECTED,'archive':'PlFx.dat','revisionVerified':False,'decompCommit':'d504219dba4a5c5350aecd8e2f4969adeacb8b72'},'attributes':attrs}
text=json.dumps(result,indent=2)[:-2]
for name,items in [('actions',actions),('subroutines',subroutines)]:
    text+=',\n  "'+name+'": [\n'+',\n'.join('    '+json.dumps(a,separators=(',', ':')) for a in items)+'\n  ]'
text+='\n}'
(ROOT/'fidelity'/'fox-data.ts').write_text('// Generated by tools/import_fox.py. Raw commands preserved; revision not independently verified.\nexport const foxData = '+text+' as const;\n')
print(f'Imported {len(attrs)} offset-mapped attributes and {len(actions)} raw action scripts')
