/* Split Decision content banks (server only; never imported by client code). Every template and house blank is original.
   Dilemma and Big Split templates have one blank that takes a clause ("…, but ____."); would-you-rather templates have two
   blanks that take actions ("…would you rather ____ or ____?"). */

/** Round 1 dilemmas for everyone. */
export const DILEMMAS: readonly string[] = [
  'You can teleport anywhere instantly, but ____. Would you do it?',
  'You get free pizza for life, but ____. Deal?',
  'You can talk to animals, but ____. Would you take the gift?',
  'A genie grants you unlimited wishes, but ____. Would you rub the lamp?',
  'You never have to sleep again, but ____. Would you sign up?',
  'You can fly, but ____. Would you take the wings?',
  'You become the best singer in the world, but ____. Deal?',
  'You get a robot butler that does every chore, but ____. Would you buy it?',
  'You can read minds, but ____. Would you accept the power?',
  'You can pause time whenever you like, but ____. Would you use it?',
  'You win a lifetime supply of chocolate, but ____. Do you claim the prize?',
  'You can live in a real castle rent-free, but ____. Would you move in?',
  'You get a pet dragon, but ____. Would you adopt it?',
  'Your house cleans itself every night, but ____. Would you take the deal?',
  'You can speak every language fluently, but ____. Would you do it?',
  'You get to go to space tomorrow, but ____. Would you go?',
  'You can eat anything you like and stay perfectly healthy, but ____. Deal?',
  'You will never wait in a queue again, but ____. Would you accept?',
  'You can breathe underwater, but ____. Would you take the gills?',
  'You can turn invisible whenever you want, but ____. Would you do it?',
  'Every traffic light turns green for you, but ____. Would you take it?',
  'You get a brand-new car every year for free, but ____. Deal?',
  'You can rewind your life by ten seconds once a day, but ____. Would you use it?',
  'You become a famous film star overnight, but ____. Would you sign the contract?',
  'You can control the weather, but ____. Would you accept the power?',
  'You get paid double for doing your job, but ____. Would you take the raise?',
  'You will always find a parking space, but ____. Deal?',
  'You can visit any moment in history, but ____. Would you step into the time machine?',
  'Your phone battery never runs out, but ____. Would you take it?',
  'You win the lottery tomorrow, but ____. Would you cash the ticket?',
  'You can shrink to the size of a mouse at will, but ____. Would you do it?',
  'You can make any plant grow instantly, but ____. Would you accept?',
  'You get to live forever, but ____. Would you drink the potion?',
  'You can retire tomorrow on full pay, but ____. Would you do it?',
  'You get a free holiday anywhere in the world, but ____. Would you pack your bags?',
  'You can be the funniest person in every room, but ____. Deal?',
  'You can magically fix anything you touch, but ____. Would you take the gift?',
  'You are given a mansion with an indoor water slide, but ____. Would you move in?',
  'You can see ten seconds into the future, but ____. Would you accept?',
  'You get to spend a day with your favourite celebrity, but ____. Would you go?',
  'Your cooking always tastes amazing, but ____. Deal?',
  'You can run as fast as a cheetah, but ____. Would you take the legs?',
  'You get unlimited free flights, but ____. Would you sign up?',
  'You can make anyone laugh on command, but ____. Would you use it?',
  'You can swap bodies with your pet for a day, but ____. Would you do it?',
  'You can have any job in the world, but ____. Would you take it?',
  'You get a personal chef for life, but ____. Would you hire them?',
  'You will never catch a cold again, but ____. Deal?',
  'You can jump as high as a house, but ____. Would you do it?',
  'You can instantly play any musical instrument, but ____. Would you take the talent?',
  'Your hair always looks perfect, but ____. Deal?',
  'You can find anything you have ever lost, but ____. Would you use the power?',
  'You get front-row seats to every concert, but ____. Would you go?',
  'You can turn into any animal once a week, but ____. Would you do it?',
  'You can have a secret room in your house that only you know about, but ____. Would you build it?',
  'You will win every argument you ever have, but ____. Would you accept?',
  'You get a whole theme park to yourself for a day, but ____. Would you go?',
  'You can clone yourself, but ____. Would you do it?',
  'You get a magic flying carpet, but ____. Would you take a ride?',
  'You will know the answer to every quiz question, but ____. Deal?',
  'You will be on the cover of every magazine, but ____. Would you do the photoshoot?',
  'You can eat pudding for every meal, but ____. Would you do it?',
  'You get a real glowing laser sword, but ____. Would you take it?',
  'You can live on a tropical island, but ____. Would you move there?',
  'You get to name a newly discovered planet, but ____. Would you accept the honour?',
  'You can become a world-class athlete overnight, but ____. Would you take it?',
  'You get a treehouse with every gadget imaginable, but ____. Would you move in?',
  'Your laundry washes and folds itself, but ____. Deal?',
  'You can glow in the dark whenever you like, but ____. Would you take the power?',
  'You get a remote that skips the boring parts of your day, but ____. Would you use it?',
  'You are invited to a party hosted by friendly aliens, but ____. Would you go?',
  'You can understand everything babies say, but ____. Would you accept?',
  'You get to be king or queen for a year, but ____. Would you take the crown?',
  'You can turn anything into ice cream, but ____. Deal?',
  'You will never lose a board game again, but ____. Would you accept?',
  'You can see through walls, but ____. Would you do it?',
  'You get a hoverboard that really hovers, but ____. Would you ride it?',
  'You get to star in your favourite TV show, but ____. Would you do it?',
  'You can summon any object into your hand, but ____. Would you take the power?',
  'You get a talking car that drives itself, but ____. Would you get in?',
  'You get a perfect memory, but ____. Deal?',
  'You can make it snow on any day you choose, but ____. Would you use it?',
  'You can bring back one dinosaur as a pet, but ____. Would you do it?',
  'You never have to fill in a form again, but ____. Deal?',
  'You become a genius overnight, but ____. Would you take the pill?',
  'You get a giant library with every book ever written, but ____. Would you move in?',
  'You get free haircuts for life, but ____. Deal?',
  'You can sleep for one hour and feel fully rested, but ____. Would you do it?',
  'You can hold your breath for an hour, but ____. Would you take the gift?',
  'You get to be the boss of your workplace, but ____. Would you accept the promotion?',
  'You can ride a friendly whale to work, but ____. Would you do it?',
  'You get your own submarine, but ____. Would you take it?',
  'You can always tell when someone is lying, but ____. Would you accept?',
  'You can change your appearance at will, but ____. Would you do it?',
  'You can command an army of loyal squirrels, but ____. Would you take charge?',
  'You get a fridge that refills itself every night, but ____. Deal?',
  'You can chat with ghosts, but ____. Would you accept the gift?',
  'You can phone your future self once, but ____. Would you make the call?',
  'You get a jetpack, but ____. Would you strap it on?',
  'You get a lifetime pass to every museum, zoo and aquarium, but ____. Would you claim it?',
  'Any song you think of starts playing out loud, but ____. Deal?',
  'You can keep every pet you have ever wanted, but ____. Would you do it?',
  'You can be in two places at once, but ____. Would you do it?',
  'You get one free do-over of any day in your life, but ____. Would you use it?',
  'You become the world champion of rock, paper, scissors, but ____. Would you take the title?',
  'You can turn any room into a ball pit, but ____. Would you do it?',
  'You can heal any injury with a touch, but ____. Would you accept the power?',
  'You can get a table at any restaurant without booking, but ____. Deal?',
  'You get an elephant the size of a cat, but ____. Would you adopt it?',
  'You can move things with your mind, but ____. Would you take the power?',
  'A spaceship lands in your garden and it is yours to keep, but ____. Would you keep it?',
  'You get shoes that let you walk on water, but ____. Would you wear them?',
  'You can design and build your dream house for free, but ____. Would you build it?',
  'You can control any video game with your thoughts, but ____. Deal?',
  'You get a real map to buried treasure, but ____. Would you start digging?',
  'You can make it your birthday whenever you want, but ____. Would you do it?',
  'You get to drive a race car every weekend, but ____. Would you do it?',
  'You can live in a giant bouncy castle, but ____. Would you move in?',
  'You can taste colours, but ____. Would you take the gift?',
  'Your voice calms down anyone who hears it, but ____. Deal?',
  'You get to be the first person on Mars, but ____. Would you go?',
  'You can sleep on a real cloud every night, but ____. Would you do it?',
  'You can have a puppy that never grows old, but ____. Would you adopt it?',
  'You find a wardrobe that leads to a magical land, but ____. Would you step inside?',
  'You can make one famous person your best friend, but ____. Deal?',
  'You get paid to judge baking competitions, but ____. Would you take the job?',
  'A taxi appears whenever you whistle, anywhere on Earth, but ____. Would you use it?',
  'You can become a real superhero, but ____. Would you put on the cape?',
  'You get a key that unlocks any door, but ____. Would you take the key?',
  'A personal rainbow follows you everywhere, but ____. Deal?',
  'You can live inside your favourite book for a week, but ____. Would you go?',
  'You can sneeze confetti whenever you want, but ____. Would you take the gift?',
  'You get a parrot that only says nice things about you, but ____. Would you adopt it?',
  'You become the world’s greatest dancer, but ____. Deal?',
  'You can make any queue move twice as fast, but ____. Would you use it?',
];

/** Round 1 dilemmas only when family mode is off: nights out, dating, work and money. */
export const DILEMMAS_ADULT: readonly string[] = [
  'You will never have a hangover again, but ____. Deal?',
  'You find your perfect match, but ____. Would you go on the date?',
  'You get a free bar tab for life, but ____. Would you take it?',
  'Your ex disappears from the internet forever, but ____. Deal?',
  'You can quit your job and still get paid the same, but ____. Would you do it?',
  'You can read your partner’s mind, but ____. Would you accept?',
  'You get to skip every awkward first date, but ____. Would you do it?',
  'You can delete one embarrassing night from everyone’s memory, but ____. Would you do it?',
  'You always look amazing in photos, but ____. Deal?',
  'A dating app only ever shows you perfect matches, but ____. Would you download it?',
  'Your boss offers you a huge raise, but ____. Would you accept?',
  'You win a wild weekend in Las Vegas, all paid, but ____. Would you go?',
  'You can drink as much as you like and never get drunk, but ____. Deal?',
  'You can marry a billionaire tomorrow, but ____. Would you say yes?',
  'Your in-laws will adore you forever, but ____. Deal?',
  'Nobody can ever see your search history, but ____. Deal?',
  'You become irresistible to everyone you meet, but ____. Would you drink the potion?',
  'You never have to go to another work party, but ____. Deal?',
  'You can say exactly what you think at work with no consequences, but ____. Would you do it?',
  'You can find out everyone who ever had a crush on you, but ____. Would you look?',
  'Every bill you owe is wiped out, but ____. Would you sign?',
  'You get paid to party every weekend, but ____. Would you take the job?',
  'You can unsend any text you have ever sent, but ____. Deal?',
  'Your dream wedding is paid for in full, but ____. Would you accept?',
  'You can sleep in every workday for a year, but ____. Would you do it?',
  'You get a wine cellar that never runs dry, but ____. Would you take it?',
];

/** Round 2 would-you-rathers for everyone: the author fills both actions. */
export const RATHERS: readonly string[] = [
  'For the rest of your life, would you rather ____ or ____?',
  'For one whole week, would you rather ____ or ____?',
  'On your next holiday, would you rather ____ or ____?',
  'At a wedding, would you rather ____ or ____?',
  'To become famous, would you rather ____ or ____?',
  'On your first day at a new school, would you rather ____ or ____?',
  'To win a million, would you rather ____ or ____?',
  'Every single morning, would you rather ____ or ____?',
  'At a fancy dinner party, would you rather ____ or ____?',
  'As a superhero, would you rather ____ or ____?',
  'On a long car journey, would you rather ____ or ____?',
  'To save the world, would you rather ____ or ____?',
  'In a zombie apocalypse, would you rather ____ or ____?',
  'On your birthday, would you rather ____ or ____?',
  'At the beach, would you rather ____ or ____?',
  'To escape a boring meeting, would you rather ____ or ____?',
  'On a space station, would you rather ____ or ____?',
  'Stranded on a desert island, would you rather ____ or ____?',
  'At a theme park, would you rather ____ or ____?',
  'To impress your neighbours, would you rather ____ or ____?',
  'For the next family photo, would you rather ____ or ____?',
  'In a haunted house, would you rather ____ or ____?',
  'At the gym, would you rather ____ or ____?',
  'As a pirate captain, would you rather ____ or ____?',
  'In a talent show, would you rather ____ or ____?',
  'On a rainy Sunday, would you rather ____ or ____?',
  'To get free food forever, would you rather ____ or ____?',
  'As ruler of a tiny country, would you rather ____ or ____?',
  'In a job interview, would you rather ____ or ____?',
  'At the supermarket, would you rather ____ or ____?',
  'When you meet royalty, would you rather ____ or ____?',
  'As a wizard, would you rather ____ or ____?',
  'At a sleepover, would you rather ____ or ____?',
  'On a camping trip, would you rather ____ or ____?',
  'To never pay rent again, would you rather ____ or ____?',
  'At a museum, would you rather ____ or ____?',
  'On a cruise ship, would you rather ____ or ____?',
  'In a spelling contest, would you rather ____ or ____?',
  'On your perfect day off, would you rather ____ or ____?',
  'In the school play, would you rather ____ or ____?',
  'When the aliens land, would you rather ____ or ____?',
  'At a fancy-dress party, would you rather ____ or ____?',
  'To win an Olympic gold medal, would you rather ____ or ____?',
  'Snowed in for a week, would you rather ____ or ____?',
  'As a famous chef, would you rather ____ or ____?',
  'On a long flight, would you rather ____ or ____?',
  'Back in the Middle Ages, would you rather ____ or ____?',
  'On a TV game show, would you rather ____ or ____?',
  'With a working time machine, would you rather ____ or ____?',
  'As a dog for a day, would you rather ____ or ____?',
  'At a huge concert, would you rather ____ or ____?',
  'To make your best friend happy, would you rather ____ or ____?',
  'For a whole year, would you rather ____ or ____?',
  'At a school reunion, would you rather ____ or ____?',
  'Lost in the jungle, would you rather ____ or ____?',
  'At a party you weren’t invited to, would you rather ____ or ____?',
];

/** Round 2 would-you-rathers only when family mode is off. */
export const RATHERS_ADULT: readonly string[] = [
  'On a first date, would you rather ____ or ____?',
  'At the office party, would you rather ____ or ____?',
  'The morning after a big night out, would you rather ____ or ____?',
  'To escape a terrible date, would you rather ____ or ____?',
  'Meeting your partner’s parents, would you rather ____ or ____?',
  'On your honeymoon, would you rather ____ or ____?',
  'To land the big promotion, would you rather ____ or ____?',
  'In a group chat with your boss, would you rather ____ or ____?',
  'At your ex’s wedding, would you rather ____ or ____?',
  'On a stag or hen weekend, would you rather ____ or ____?',
];

/** The Big Split (final round) for everyone: one dilemma, everyone's take. */
export const FINALS: readonly string[] = [
  'A mysterious stranger offers you a billion in cash, but ____. Would you take it?',
  'You can move into any fictional world you like, but ____. Would you go?',
  'You get a ticket on the first trip to another galaxy, but ____. Would you go?',
  'You can know the date of every big event in your future, but ____. Would you look?',
  'Every wish you make from now on comes true, but ____. Would you start wishing?',
  'You can become the most famous person on Earth, but ____. Would you do it?',
  'You can press a button that makes everyone on Earth a little happier, but ____. Do you press it?',
  'The Dilemma Machine offers you any superpower you like, but ____. Do you accept?',
  'You can end traffic jams forever, but ____. Do you do it?',
  'A portal opens to a world where you rule as king or queen, but ____. Do you step through?',
  'You will never be bored again, but ____. Would you take it?',
  'You can swap lives with anyone on Earth for a year, but ____. Would you do it?',
  'You can have the house of your dreams for free, but ____. Would you move in?',
  'You can bring back any extinct animal, but ____. Would you do it?',
  'You can stay twenty-one years old forever, but ____. Deal?',
  'You can visit every country on Earth in a single year, but ____. Would you go?',
  'Every meal you ever eat will taste incredible, but ____. Deal?',
  'You can become the smartest person who ever lived, but ____. Would you accept?',
  'You can bring your favourite cartoon character to life, but ____. Would you do it?',
  'You win a lifetime trip around the world, but ____. Would you go?',
  'Your phone can answer any question perfectly, but ____. Would you keep it?',
  'You can make one new law that everyone must follow, but ____. Would you do it?',
  'You can relive your favourite day as often as you like, but ____. Would you do it?',
  'You will never feel embarrassed again, but ____. Deal?',
  'You get a role in every blockbuster film next year, but ____. Would you sign?',
  'A mad scientist offers you robot arms that can do anything, but ____. Would you upgrade?',
  'You can choose your own dreams every night, but ____. Would you do it?',
  'You can make every day a public holiday, but ____. Would you do it?',
  'You can own a whole island with your name on it, but ____. Would you take it?',
  'You can have an hour-long chat with anyone from history, but ____. Would you do it?',
  'You will never lose your keys, phone or wallet again, but ____. Deal?',
  'You can freeze time for everyone but you for one day a year, but ____. Would you use it?',
];

/** The Big Split only when family mode is off. */
export const FINALS_ADULT: readonly string[] = [
  'You can learn every secret your friends have ever kept, but ____. Would you look?',
  'You can retire at thirty with a fortune, but ____. Would you do it?',
  'You will meet the love of your life tomorrow, but ____. Would you go for it?',
  'You can erase every embarrassing photo of yourself online, but ____. Would you do it?',
  'You get a lifetime of free nights out, but ____. Deal?',
  'You can quit your job to become a famous influencer overnight, but ____. Would you do it?',
];

/** House blanks for dilemmas (clauses): the machine's fill when a player is stuck or runs out of time. */
export const HOUSE_CLAUSES: readonly string[] = [
  'you have to wear a full chicken costume', 'you must sing everything you say', 'everyone can hear your thoughts on Tuesdays',
  'you sneeze glitter every hour', 'you can only eat beige food', 'a mime follows you everywhere', 'your voice becomes really squeaky',
  'you have to hop on one foot all day', 'your nose glows red at night', 'you lose one sock every single day',
  'you must high-five every stranger you meet', 'your hair changes colour every hour', 'a goose moves into your kitchen forever',
  'you can never use a spoon again', 'you can only speak in rhymes', 'your name changes to Gary', 'your shoes squeak with every step',
  'a tiny brass band follows you around', 'you can only ever whisper', 'your eyebrows grow an inch a day',
  'you have to narrate everything you do out loud', 'you hiccup whenever someone says your name', 'you smell faintly of onions forever',
  'you can only travel by pogo stick', 'your phone autocorrects every word to banana', 'you have to wear socks on your hands',
  'dramatic music plays wherever you go', 'you burp loudly every time you laugh', 'you can never sit down again',
  'every photo of you comes out blurry', 'your laugh sounds like a donkey', 'you must carry a live lobster everywhere',
  'you can only watch one film, forever', 'you have to wear a cape every day', 'your fridge talks back to you',
  'you forget the ending of every story', 'you have to eat cold soup for breakfast', 'you get a new accent every day',
  'every chair you sit on squeaks loudly', 'your socks never match again', 'you have to sleep in the bath',
  'a pigeon becomes your new boss', 'you sweat maple syrup', 'your shadow does its own thing', 'you must clap after every sentence',
  'your teeth glow in the dark', 'you can’t remember anyone’s name', 'you are always slightly damp', 'you can only walk backwards',
  'you get a terrible haircut every Monday', 'your nose whistles when you breathe', 'you must wear a top hat in the shower',
  'everything you touch is a bit sticky', 'you share a flat with your old maths teacher', 'a seagull steals your lunch every day',
  'you have to wear a wetsuit everywhere', 'you can never eat cheese again', 'every song gets stuck in your head for a week',
  'your elbows are always itchy', 'all your clothes are two sizes too small', 'you end every phone call with “over and out”',
  'you have to say “moo” before you speak', 'your feet are permanently cold', 'you must wear clown shoes to work',
  'a talking cat judges all your decisions', 'you can only eat with your fingers', 'you have to wear a tutu to every meeting',
];

/** House blanks for would-you-rathers (actions). */
export const HOUSE_OPTIONS: readonly string[] = [
  'wear a wet sock forever', 'eat only cold beans', 'sing every word you say', 'live in a treehouse', 'swim with sharks',
  'eat a whole raw onion', 'run a marathon in flip-flops', 'talk like a pirate', 'skip everywhere you go', 'sleep in a hammock',
  'dance in public every hour', 'wear a tuxedo to bed', 'carry a goose under your arm', 'tell everyone your secrets', 'only whisper',
  'shout everything', 'eat spaghetti with your hands', 'fight a giant chicken', 'hug a cactus', 'lick a frozen lamppost',
  'moonwalk everywhere', 'wear a fish as a hat', 'never use a phone again', 'move in with your grandparents', 'be chased by bees',
  'clean a stranger’s fridge', 'juggle raw eggs', 'read the dictionary aloud', 'wear clown make-up to work', 'adopt fifty cats',
  'eat a bowl of worms', 'give up chocolate forever', 'ride a unicycle to work', 'sleep on a bed of crisps', 'yodel at every red light',
  'wear a suit of armour', 'bathe in custard', 'live without a fridge', 'arm-wrestle a gorilla', 'speak only in questions',
  'paint your house hot pink', 'smell like garlic forever', 'learn the bagpipes', 'live on a canal boat', 'eat only soup',
  'wear sunglasses at night', 'star in a toothpaste advert', 'crawl through a tunnel of jelly',
];

export const dilemmaPool = (family: boolean) => family ? DILEMMAS : [...DILEMMAS, ...DILEMMAS_ADULT];
export const ratherPool = (family: boolean) => family ? RATHERS : [...RATHERS, ...RATHERS_ADULT];
export const finalPool = (family: boolean) => family ? FINALS : [...FINALS, ...FINALS_ADULT];
