/**
 * Renders Hijinks music loops to public/games/hijinks/music/<id>.mp3 and regenerates src/core/audio/tracks.ts.
 * Usage (platform root): flock /tmp/hijinks-heavy.lock node --import tsx packages/games/hijinks/music/export.ts [--all | <id>…]
 * With no arguments only tracks without an mp3 are rendered. Every module in music/tracks/ is one Track (default export).
 * Each file holds the loop plus one wrapped extra second. MP3 coding noise differs between the two copies of that second,
 * so the loop start is placed where the decoded copies match best (no click at the seam); it stays clear of encoder padding.
 */
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loopSeconds, type Track } from './kit';
import { SR, bus, wav } from './synth';

const dir = import.meta.dirname, out = join(dir, '../../../../public/games/hijinks/music'), args = process.argv.slice(2);
const tracks: Track[] = [];
for (const file of readdirSync(join(dir, 'tracks')).filter(f => f.endsWith('.ts')).sort()) tracks.push((await import(join(dir, 'tracks', file))).default);
for (const id of args.filter(a => a !== '--all')) if (!tracks.some(t => t.id === id)) throw Error(`Unknown track ${id}`);
mkdirSync(out, { recursive: true });

/** Integrated loudness (EBU R128) of an audio file. */
const lufs = (file: string) => Number(/Summary:[\s\S]*?I:\s+(-?[\d.]+) LUFS/.exec(spawnSync('ffmpeg', ['-hide_banner', '-nostats', '-i', file, '-af', 'ebur128', '-f', 'null', '-'], { encoding: 'utf8' }).stderr)?.[1]);
for (const t of tracks.filter(t => args.includes('--all') || args.includes(t.id) || !args.length && !existsSync(join(out, `${t.id}.mp3`)))) {
  const start = performance.now(), loop = t.render(), n = loop.l.length, seconds = loopSeconds(t);
  if (Math.abs(n - Math.round(seconds * SR)) > 1) throw Error(`${t.id} rendered ${n / SR}s, expected ${seconds}s`);
  const padded = bus(n + SR); for (let i = 0; i < n + SR; i++) { padded.l[i] = loop.l[i % n]; padded.r[i] = loop.r[i % n]; }
  const file = join(out, `${t.id}.wav`); writeFileSync(file, wav(padded));
  // Linear gain to the loudness target keeps the seam intact; the synth limiter already holds peaks at -1 dBFS.
  let peak = 0; for (let i = 0; i < n; i++) peak = Math.max(peak, Math.abs(loop.l[i]), Math.abs(loop.r[i]));
  const measured = lufs(file), want = (t.lufs ?? -16) - measured, gain = Math.min(want, 20 * Math.log10(.89 / peak));
  execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', file, '-af', `volume=${gain.toFixed(2)}dB`, '-codec:a', 'libmp3lame', '-b:a', '128k', join(out, `${t.id}.mp3`)]); rmSync(file);
  console.log(`${t.id}: ${seconds.toFixed(3)} s loop, ${measured.toFixed(1)} → ${(measured + gain).toFixed(1)} LUFS${gain < want - .05 ? ' (peak-limited)' : ''}, ${((performance.now() - start) / 1000).toFixed(1)} s`);
}
/** Decodes a loop file and finds the start in [0.25, 0.85] s whose few samples best match those one loop later. */
function seam(file: string, n: number) {
  const raw = execFileSync('ffmpeg', ['-loglevel', 'error', '-i', file, '-f', 'f32le', '-ac', '2', '-ar', String(SR), '-'], { maxBuffer: 1 << 29 }), a = new Float32Array(raw.buffer, raw.byteOffset, raw.byteLength >> 2);
  let best = SR >> 1, cost = Infinity;
  for (let k = Math.round(.25 * SR); k < Math.round(.85 * SR); k++) {
    let c = 0; for (let j = -2; j <= 1 && c < cost; j++) c += (a[2 * (k + j)] - a[2 * (k + n + j)]) ** 2 + (a[2 * (k + j) + 1] - a[2 * (k + n + j) + 1]) ** 2;
    if (c < cost) { cost = c; best = k; }
  }
  return best / SR;
}
const listed = tracks.filter(t => existsSync(join(out, `${t.id}.mp3`))).map(t => `  '${t.id}': { file: 'music/${t.id}.mp3', loopStart: ${seam(join(out, `${t.id}.mp3`), Math.round(loopSeconds(t) * SR)).toFixed(6)}, loopSeconds: ${+loopSeconds(t).toFixed(6)} }, // ${t.title}`);
writeFileSync(join(dir, '../src/core/audio/tracks.ts'), `/* GENERATED by music/export.ts from music/tracks/*.ts. Play each file looping [loopStart, loopStart + loopSeconds]. */
export type TrackInfo = { file: string; loopStart: number; loopSeconds: number };
export const TRACKS: Record<string, TrackInfo> = {
${listed.join('\n')}
};
`);
