/* Ballpark content banks (server only; never imported by client code). Every question and statement is original.
   A leading '+' marks a harmless question whose reveal may show who said what ("on the record"); the rest stay anonymous. */

export type Question = { id: string; text: string; open?: true; adult?: true };
export type WantedSet = { id: string; title: string; items: string[]; adult?: true };

/** Yes/no survey questions for everyone. */
export const FAMILY: readonly string[] = [
  'Have you ever pretended to be on the phone to avoid someone?',
  'Have you ever waved back at someone who was actually waving at the person behind you?',
  'Have you ever laughed along at a joke you didn’t understand?',
  'Have you ever said “you too” when a waiter told you to enjoy your meal?',
  'Have you ever pushed a door that very clearly said pull?',
  'Have you ever sung in the shower loud enough for the neighbours to hear?',
  '+Do you talk to your pets in a special voice?',
  '+Do you sleep with your socks on?',
  'Have you ever searched for your own name online?',
  'Have you ever re-gifted a present?',
  'Have you ever cried at an advert?',
  'Have you ever fallen asleep in a cinema?',
  '+Do you know your best friend’s phone number by heart?',
  'Have you ever claimed to have read a book you never finished?',
  'Have you ever had a peek inside someone else’s bathroom cabinet?',
  'Have you ever mumbled along to a song pretending to know the words?',
  'Have you ever walked straight into a glass door?',
  'Have you ever sent a message about someone to that exact person?',
  'Have you ever eaten cereal for dinner?',
  '+Do you still own a toy from when you were little?',
  'Have you ever been shushed by a librarian?',
  'Have you ever rehearsed an argument in the shower?',
  'Have you ever hidden from a neighbour inside your own home?',
  'Have you ever eaten a whole large pizza by yourself?',
  'Have you ever forgotten someone’s name seconds after they told you?',
  'Have you ever got lost while following a map app?',
  '+Can you whistle using your fingers?',
  '+Can you touch your nose with your tongue?',
  '+Have you ever broken a bone?',
  '+Have you ever been on TV?',
  'Have you ever met a famous person?',
  '+Do you pour the milk in before the cereal?',
  'Have you ever stopped a stranger just to pet their dog?',
  'Have you ever left a voicemail by accident?',
  '+Have you ever clapped when a plane landed?',
  'Have you ever watched a whole series in one weekend?',
  'Have you ever invented a busy evening to get out of a party?',
  'Have you ever sniffed milk, decided it was “probably fine” and drunk it?',
  'Have you ever read the last page of a book first?',
  '+Have you ever been stuck in a lift?',
  '+Have you ever won a trophy?',
  'Have you ever cut your own hair?',
  'Have you ever eaten pudding before your main course?',
  '+Have you ever given a name to your car, bike or houseplant?',
  '+Do you talk to your plants?',
  'Have you ever regretted a haircut before you even left the salon?',
  'Have you ever faked being ill to skip school?',
  'Have you ever been sent to the head teacher’s office?',
  'Have you ever cheated at a board game?',
  'Have you ever stormed off in the middle of a board game?',
  '+Have you ever stayed up all night without sleeping?',
  'Have you ever fallen off a bike as a grown-up?',
  'Have you ever ducked behind a shelf to avoid someone you know in a shop?',
  'Have you ever eaten dinner straight out of the pan?',
  'Have you ever made a birthday wish that actually came true?',
  '+Do you believe in ghosts?',
  '+Do you think aliens have already visited Earth?',
  '+Would you go to space tomorrow if the ticket was free?',
  '+Would you eat a live cricket for a year of free pizza?',
  'Have you ever kept a diary?',
  'Have you ever written a poem for someone?',
  'Have you ever had a nickname you secretly hated?',
  'Have you ever laughed extra loudly at a boss’s joke?',
  'Have you ever tripped over nothing and turned it into a little jog?',
  'Have you ever been chased by an animal?',
  '+Have you ever been bitten by an animal?',
  'Have you ever cried during a children’s film?',
  'Have you ever searched everywhere for your phone while holding it?',
  'Have you ever put the milk in the cupboard and the cereal in the fridge?',
  'Have you ever eaten in your car so nobody would ask for some?',
  '+Do you make your bed every single morning?',
  'Have you ever slept for more than twelve hours straight?',
  '+Have you ever missed a flight?',
  '+Have you ever sung karaoke?',
  'Have you ever danced alone in your kitchen like nobody was watching?',
  '+Have you ever performed on a stage in front of an audience?',
  'Have you ever broken something in a shop and quietly walked away?',
  'Have you ever called a teacher “Mum” or “Dad” by accident?',
  '+Do you have a song stuck in your head right now?',
  'Have you ever started a diet on Monday and quit by Tuesday?',
  'Have you ever bought something you didn’t need just because it was on sale?',
  'Have you ever returned something you had clearly already used?',
  'Have you ever said your battery was dying to escape a phone call?',
  'Have you ever sent a message to the wrong group chat?',
  'Have you ever quietly left a group chat?',
  'Have you ever muted your family group chat?',
  'Have you ever ignored a call from a parent and then texted “what’s up?”',
  'Have you ever been called the wrong name for months and never corrected it?',
  'Have you ever fibbed about your age?',
  'Do you have a secret talent that nobody in this room knows about?',
  '+Have you ever won a raffle or a prize draw?',
  'Have you ever found money on the street and kept it?',
  'Have you ever eaten something you hated just to be polite?',
  'Have you ever hidden vegetables in a napkin?',
  'Have you ever slipped your dinner to a pet under the table?',
  'Have you ever forgotten a close friend’s birthday?',
  'Have you ever pretended to remember someone who clearly remembered you?',
  'Have you ever been the very last to hear some big news?',
  'Have you ever accidentally spread a rumour that turned out to be untrue?',
  'Have you ever ridden a rollercoaster with your eyes shut the whole time?',
  'Have you ever been frightened by a cartoon?',
  'Have you ever checked under the bed for monsters as a grown-up?',
  'Have you ever been startled by your own reflection?',
  'Have you ever greeted a total stranger because you thought they were a friend?',
  'Have you ever had a whole conversation while basically asleep?',
  '+Have you ever sleepwalked?',
  'Has anyone ever told you that you snore?',
  'Has anyone ever told you that you talk in your sleep?',
  'Have you ever made up a word and used it like it was real?',
  'Have you ever corrected someone’s grammar out loud?',
  'Have you ever typed nonsense on a keyboard just to look busy?',
  'Have you ever fallen asleep on a bus or train and missed your stop?',
  'Have you ever sprinted for a bus and still missed it?',
  'Have you ever set off the smoke alarm while cooking?',
  'Have you ever called a pet by a family member’s name?',
  '+Did you have an imaginary friend when you were little?',
  'Have you ever blamed a bad smell on the dog?',
  'Have you ever pretended to be asleep to get out of a chore?',
  'Have you ever hidden the last biscuit so nobody else could have it?',
  'Have you ever eaten the last slice without asking anyone?',
  'Have you ever licked a plate clean when nobody was looking?',
  'Have you ever drunk straight from the bottle in the fridge?',
  'Have you ever worn the same outfit three days in a row?',
  'Have you ever worn a top inside out all day without noticing?',
  'Have you ever left the house wearing two different shoes?',
  'Have you ever popped to the shops in your slippers?',
  'Have you ever fallen into a swimming pool with your clothes on?',
  '+Have you ever been stung by a jellyfish?',
  'Have you ever built a sandcastle as a grown-up and taken it very seriously?',
  'Have you ever shouted “speak to a human!” at an automated phone line?',
  '+Do you say thank you to voice assistants?',
  'Have you ever said sorry to a piece of furniture you bumped into?',
  'Have you ever apologised to someone who bumped into you?',
  'Have you ever stayed in the bath until the water went cold?',
  'Have you ever read an entire book in a single day?',
  'Have you ever made a playlist for one specific person?',
  '+Have you ever written a fan letter?',
  '+Have you ever been in a newspaper?',
  '+Have you ever ridden a horse?',
  '+Have you ever milked a cow?',
  '+Have you ever eaten a snail?',
  '+Could you do a cartwheel right now?',
  '+Can you juggle three things?',
  '+Can you do the splits?',
  '+Can you play a musical instrument?',
  '+Can you speak three or more languages?',
  '+Can you name all eight planets in order?',
  '+Do you know how to change a car tyre?',
  'Have you ever built flat-pack furniture and had screws left over?',
  'Have you ever ignored the instructions and deeply regretted it?',
  'Have you ever jabbed a lift button over and over to make it come faster?',
  'Have you ever tried to unlock your front door with your car key?',
  'Have you ever nodded along to a fancy restaurant menu you didn’t understand?',
  '+Do you order the same thing every time at your favourite restaurant?',
  'Have you ever sent food back at a restaurant?',
  'Have you ever been too shy to send back the wrong order?',
  'Have you ever taken a photo of your food before eating it?',
  'Have you ever eaten a whole tub of ice cream in one go?',
  'Have you ever opened a present early and wrapped it back up?',
  '+Have you ever cried at a wedding?',
  'Have you ever got the giggles at the worst possible moment?',
  '+Have you ever visited another continent?',
  '+Have you ever slept in a tent?',
  '+Have you ever seen the Northern Lights?',
  'Have you ever gone swimming in the sea at night?',
  'Have you ever climbed a tree as a grown-up?',
  '+Have you ever been seasick?',
  '+Have you ever seen a shooting star?',
  '+Have you ever been up in a hot-air balloon?',
  '+Have you ever jumped out of a plane?',
  'Have you ever eaten a snack you dropped in the sand?',
  'Do you still sleep with a cuddly toy?',
  'Have you ever had a crush on a cartoon character?',
  'Have you ever written your name on your food in a shared fridge?',
  'Have you ever eaten someone else’s labelled food from a shared fridge?',
  'Have you ever answered the phone in a fake accent?',
  '+Have you ever practised your autograph?',
  'Have you ever practised an award acceptance speech in the mirror?',
  '+Have you ever had a parking ticket?',
  '+Have you ever locked yourself out of your own home?',
  'Have you ever climbed in through a window of your own home?',
  'Have you ever put something in the oven and completely forgotten about it?',
  'Have you ever found your phone somewhere truly strange, like the fridge?',
  'Have you gone to bed without brushing your teeth this month?',
  '+Have you ever eaten a raw onion like an apple?',
  'Have you ever worn a fancy-dress costume that nobody understood?',
  '+Have you ever been told you look like someone famous?',
  'Have you ever been mistaken for shop staff and just helped anyway?',
  'Have you ever forgotten your own phone number?',
  'Have you ever genuinely had to work out how old you are?',
  'Have you ever ended an argument by sending a thumbs-up emoji?',
  'Have you ever used an emoji without knowing what it meant?',
  '+Do you have more than a thousand unread emails?',
  '+Do you have more than twenty tabs open on your phone right now?',
  'Have you ever cleaned only the half of a room that guests would see?',
  'Have you ever shoved everything into a cupboard because guests were coming?',
  'Have you ever answered a question you misheard and just rolled with it?',
  'Have you ever gone to the cinema mainly for the snacks?',
  'Have you ever got so hungry that you were rude to someone?',
  'Have you ever argued out loud with a sat-nav?',
  'Have you ever given a stranger directions while having no idea where it was?',
  'Have you ever confidently led a group the wrong way?',
  'Have you ever got on a train going in completely the wrong direction?',
  'Have you ever finished a thousand-piece jigsaw on your own?',
  'Have you ever kept talking after realising you were wrong, just to win?',
  'Have you ever been caught singing in the car at traffic lights?',
  'Have you ever reread an old message of yours and cringed?',
  'Have you ever kept a secret for more than ten years?',
  'Have you ever forgotten to switch off your camera on a video call?',
  'Have you ever talked for a full minute on a video call while muted?',
  'Have you ever googled how to do something you claimed you already knew?',
  'Have you ever taken a nap in your parked car?',
  'Have you ever won an argument and later realised you were wrong?',
  'Have you ever kept a plant alive for more than five years?',
  'Have you ever stood in a queue without knowing what it was for?',
  'Have you ever laughed so hard that a drink came out of your nose?',
  'Have you ever peeled the stickers off a puzzle cube to solve it?',
  'Have you ever eaten a sandwich so big you needed a plan?',
  'Have you ever bought a gym membership and gone fewer than five times?',
  'Have you spent an entire day in your pyjamas this month?',
  'Have you ever started a hobby, bought all the gear and quit a week later?',
  '+Have you ever grown your own vegetables?',
  '+Have you ever baked bread from scratch?',
  'Have you ever secretly enjoyed a song you publicly claim to hate?',
  'Have you ever sniffed a new book just for the smell?',
  'Have you ever counted the stairs as you walk up them?',
  'Have you ever avoided stepping on the cracks in the pavement?',
  // Opinions, hypotheticals and right-now checks: the splits nobody can predict.
  '+Is a hot dog a sandwich?',
  '+Is cereal with milk technically a soup?',
  '+Does pineapple belong on pizza?',
  '+Is it okay to wear socks with sandals?',
  '+Would you eat a biscuit you dropped on the kitchen floor?',
  '+Would you take a one-way ticket to live on Mars?',
  '+Would you spend a night alone in a haunted house for a free holiday?',
  '+Could you survive a week alone in the wilderness?',
  '+Could you beat a goose in a fair fight?',
  '+Would you swap lives with your pet for a day?',
  '+Are you a morning person?',
  '+Do you prefer cats to dogs?',
  '+Are you wearing odd socks right now?',
  '+Is your phone on less than half battery right now?',
  '+Did you eat breakfast today?',
  '+Are you hungry right now?',
  '+Do you squeeze the toothpaste from the middle of the tube?',
  '+Do you prefer a night in to a night out?',
  '+Would you want to be famous?',
  '+Would you keep working if you won the lottery tomorrow?',
  '+Would you give up chocolate for a year for a free holiday?',
  '+Could you go a whole week without your phone?',
  '+Would you rather be funny than clever?',
  '+Would you go on a reality TV show if you were asked?',
  '+Would you eat insects if it helped save the planet?',
  '+Do you sleep with the window open?',
  '+Do you think you’d make a good secret agent?',
  '+Do you know your blood type?',
  '+Do you think you’re a good singer?',
  'Do you secretly think you’re the funniest person in this room?',
  'Do you think you’re going to win this game?',
  'Do you think someone in this room has lied to this survey tonight?',
  'Are you secretly relieved when plans get cancelled?',
  'Would you let this room scroll through your photos right now?',
  'Would you read a friend’s diary if they left it open?',
  'Do you have a favourite person in this room?',
  'Would you trust everyone in this room with a big secret?',
  'Have you ever pretended to be busier than you really are?',
  'Are you still holding a grudge from your school days?',
  'Would you tell a stranger they had spinach in their teeth?',
  'Do you think you could win an arm-wrestle against anyone here?',
];

/** Spicier questions: dating, nights out, work drama. Filtered when the family setting is on. */
export const ADULT: readonly string[] = [
  'Have you ever been dumped by text message?',
  'Have you ever dumped someone by text message?',
  'Have you ever scrolled through an ex’s photos at two in the morning?',
  'Have you ever drunk-texted an ex?',
  'Have you ever asked a friend to fake an emergency call to rescue you from a date?',
  'Have you ever lied on a dating profile?',
  'Have you ever used a dating profile photo that was more than five years old?',
  'Have you ever kissed someone without knowing their name?',
  'Have you ever woken up with no memory of how you got home?',
  'Have you ever been thrown out of a bar?',
  'Have you ever called in sick because of a hangover?',
  'Have you ever lied to your boss about why you were late?',
  'Have you ever had a crush on a friend’s partner?',
  'Have you ever had a crush on a co-worker?',
  'Have you ever dated two people at the same time?',
  'Have you ever been caught checking someone out?',
  'Have you ever been ghosted?',
  'Have you ever ghosted someone?',
  'Have you ever read a partner’s messages without them knowing?',
  'Have you ever gone skinny-dipping?',
  'Have you ever sent a flirty message to the wrong person?',
  'Have you ever had a one-night stand?',
  'Have you ever lied about how many people you’ve slept with?',
  'Have you ever kissed someone at a wedding you were a guest at?',
  'Have you ever cried in the toilets at work?',
  'Have you ever danced on a table?',
  'Have you ever got a tattoo you regret?',
  'Have you ever woken up still holding last night’s takeaway?',
  'Have you ever invented an excuse to skip a wedding?',
  'Have you ever had a crush on someone in this room?',
  'Have you ever started a fight in a group chat?',
  'Have you ever been on a blind date?',
  'Have you ever said something drunk that you regretted for weeks?',
  'Have you ever sent a photo that you instantly regretted sending?',
  'Have you ever pretended to be single?',
  'Have you ever invented a partner to dodge someone’s advances?',
  'Have you ever taken a glass home from a pub?',
  'Have you ever sneaked into a party you weren’t invited to?',
  'Have you ever had a secret relationship?',
  'Have you ever walked out halfway through a date?',
  'Have you ever looked up an ex’s new partner online?',
  'Have you ever accidentally liked an ex’s ancient photo while snooping?',
  'Have you ever given a fake name to someone at a bar?',
  'Have you ever got back together with an ex you swore you were done with?',
  'Have you ever gone to work still a little bit drunk?',
  'Have you ever complained about your boss in a message sent to your boss?',
  'Have you ever kissed someone and instantly regretted it?',
  'Have you ever had a crush on a teacher?',
  'Would you date someone in this room?',
  'Do you still have an ex’s number saved in your phone?',
  'Would you read a partner’s messages if they left their phone unlocked?',
  'Do you think you’re a good kisser?',
  'Would you forgive a partner for cheating once?',
  'Would you go on a dating show?',
];

/** Most Wanted: nine statements per set; players tick what applies to them, then guess the room's top three. */
export const WANTED_FAMILY: readonly (readonly [string, readonly string[]])[] = [
  ['Kitchen Crimes', ['Has eaten food off the floor', 'Has drunk milk straight from the carton', 'Has had cereal for dinner', 'Has set off the smoke alarm cooking', 'Has eaten cake for breakfast', 'Has licked the knife after spreading', 'Has put metal in the microwave', 'Has eaten cold pizza straight from the fridge', 'Has hidden snacks from the household']],
  ['Phone Habits', ['Has twenty apps they never open', 'Has dropped their phone down the toilet', 'Has dropped their phone on their face in bed', 'Has typed “haha” with a straight face', 'Has a cracked screen right now', 'Has screenshotted a chat to show someone else', 'Has over 500 photos they’ll never look at', 'Has pretended their phone was on silent', 'Has fallen asleep mid-scroll']],
  ['School Days', ['Has been sent out of class', 'Has copied someone’s homework', 'Has fallen asleep in a lesson', 'Has called a teacher “Mum” or “Dad”', 'Has won a school award', 'Has been in a school play', 'Has had a detention', 'Has “forgotten” their PE kit on purpose', 'Has been teacher’s pet']],
  ['Travel Tales', ['Has missed a flight', 'Has slept on an airport floor', 'Has lost their luggage', 'Has got on the wrong train', 'Has got hopelessly lost abroad', 'Has eaten something they couldn’t identify', 'Has packed at midnight the night before', 'Has been seasick', 'Has bought a souvenir they instantly regretted']],
  ['Party Animals', ['Has fallen asleep at a party', 'Has left a party without saying goodbye', 'Has hidden in the bathroom at a party', 'Has started a conga line', 'Has arrived first and waited outside', 'Has eaten most of the party snacks', 'Has turned up in the wrong dress code', 'Has done the worm in public', 'Has been the last to leave a party']],
  ['Animal Magnetism', ['Has talked to a pet in a baby voice', 'Has been bitten by a pet', 'Has dressed up a pet', 'Lets a pet sleep on the bed', 'Has been chased by a goose', 'Has rescued a spider instead of squashing it', 'Has been chased by a dog', 'Has blamed a smell on the dog', 'Has talked to a squirrel']],
  ['Bedtime Secrets', ['Sleeps with socks on', 'Travels with their own pillow', 'Sleeps with a cuddly toy', 'Has hit snooze five times in a row', 'Talks in their sleep', 'Has fallen out of bed as a grown-up', 'Falls asleep with the TV on', 'Has eaten a midnight snack in the dark', 'Has slept for over twelve hours']],
  ['Shopping Sins', ['Has bought something just because it was on sale', 'Has returned something they’d already used', 'Has hidden a purchase from their household', 'Went in for one thing and left with ten', 'Has got lost in a giant furniture store', 'Has argued with a self-checkout machine', 'Has bought the same thing twice by accident', 'Has abandoned a full trolley', 'Has tried on clothes they could never afford']],
  ['Hidden Talents', ['Can whistle with their fingers', 'Can do a cartwheel', 'Can juggle', 'Can do an impression of someone here', 'Can touch their nose with their tongue', 'Can wiggle their ears', 'Can play an instrument', 'Can solve a puzzle cube', 'Can raise just one eyebrow']],
  ['Awkward Moments', ['Has waved at someone who wasn’t waving at them', 'Has said “you too” to a waiter', 'Has pushed a pull door', 'Has called someone by the wrong name', 'Has walked into a glass door', 'Has laughed at exactly the wrong moment', 'Has had food in their teeth all day', 'Has tripped going up the stairs', 'Has gone in for a hug that became a handshake']],
  ['Screen Time', ['Has watched a whole series in a weekend', 'Has cried at a cartoon', 'Has rewatched the same show five times', 'Has fallen asleep during a film they picked', 'Has shushed someone at the cinema', 'Has pretended to have seen a famous film', 'Has spoiled an ending by accident', 'Has shouted answers at a TV quiz show', 'Has watched a cooking show while eating toast']],
  ['Game Night', ['Has cheated at a board game', 'Has stormed off during a game', 'Has won a medal', 'Has been picked last for a team', 'Has scored an own goal', 'Has thrown a controller', 'Has let someone win to be nice', 'Has taken a game way too seriously', 'Has invented their own house rules']],
  ['Little White Lies', ['Has lied about reading a book', 'Has said “five minutes away” from the sofa', 'Has pretended to like a gift', 'Has blamed a sibling for something', 'Has faked being ill', 'Has pretended to know a song', 'Has fibbed about their age', 'Has claimed they “already ate”', 'Has said “I’m fine” while clearly not fine']],
  ['Fashion Files', ['Has worn a top inside out all day', 'Has worn odd socks on purpose', 'Has cut their own hair', 'Has owned an outfit they now deny', 'Has worn sunglasses indoors', 'Has dyed their hair a wild colour', 'Has worn pyjamas to the shops', 'Has borrowed clothes and never returned them', 'Has a lucky item of clothing']],
  ['Music Matters', ['Has sung karaoke', 'Has played air guitar in public', 'Has had a song stuck in their head for days', 'Has sung the wrong lyrics with confidence', 'Has been to a concert alone', 'Has cried to a song in the car', 'Has made a playlist for a crush', 'Has a guilty-pleasure song on repeat', 'Has performed music on a stage']],
  ['Food Fights', ['Likes pineapple on pizza', 'Cuts the crusts off sandwiches', 'Puts ketchup on almost everything', 'Has eaten a whole cake alone', 'Can’t stand mushrooms', 'Has eaten a raw chilli for a dare', 'Has finished a family-size bag of crisps alone', 'Eats the same breakfast every day', 'Dips chips in milkshake']],
  ['The Great Outdoors', ['Has slept in a tent', 'Has climbed a mountain', 'Has fallen into a river or lake', 'Has been stung by a bee', 'Has seen a shooting star', 'Has got lost on a country walk', 'Has eaten a wild berry they couldn’t name', 'Has built a sandcastle as a grown-up', 'Has been caught in a storm without a coat']],
  ['Home Truths', ['Has hidden from a neighbour', 'Has pretended not to be home', 'Has shoved mess into a cupboard before guests', 'Has locked themselves out', 'Has climbed in through their own window', 'Has broken something and hidden it', 'Has built flat-pack furniture with screws left over', 'Has a drawer full of mystery cables', 'Has a mug that is technically a science experiment']],
  ['Childhood Confessions', ['Had an imaginary friend', 'Was scared of the dark', 'Wanted to be an astronaut', 'Hid vegetables in a napkin', 'Gave a friend a haircut', 'Ran away from home for about an hour', 'Ate a bug on purpose', 'Got stuck somewhere they climbed', 'Believed something silly for way too long']],
  ['Tech Troubles', ['Says thank you to voice assistants', 'Has messaged the wrong person', 'Has left a voicemail by accident', 'Has hit reply-all by mistake', 'Has reset a password three times in a week', 'Has shouted at a printer', 'Has talked on a video call while muted', 'Has fixed something by turning it off and on', 'Has more than ten browser tabs open right now']],
  ['Brave Faces', ['Has ridden a giant rollercoaster', 'Has bungee jumped or skydived', 'Has held a snake', 'Has sung solo in public', 'Has gone on stage totally unprepared', 'Has eaten something they couldn’t pronounce', 'Has swum with fish in the sea', 'Has spoken in front of a hundred people', 'Has stood up to a bully']],
  ['Things That Go Bump', ['Is scared of spiders', 'Is scared of heights', 'Is scared of clowns', 'Is scared of deep water', 'Checks the back seat of the car', 'Sleeps with a light on', 'Is nervous around big birds', 'Hates needles', 'Runs up the stairs after switching off the lights']],
  ['Social Butterflies', ['Has made a friend in a queue', 'Has chatted to a stranger for an hour', 'Remembers everyone’s birthday', 'Has organised a group trip', 'Has hosted a dinner party', 'Has introduced two people who ended up dating', 'Has a friend from more than twenty years ago', 'Has gone to a party where they knew nobody', 'Has accidentally joined a stranger’s photo']],
  ['On the Move', ['Has missed their stop', 'Has run for a bus and missed it', 'Has argued with a sat-nav', 'Has forgotten where they parked', 'Has sung loudly at traffic lights', 'Has fallen asleep on a train', 'Has caught a bus going the wrong way', 'Has stepped in gum on the way to something important', 'Has travelled across town in fancy dress']],
  ['Holiday Mode', ['Has had a seriously silly sunburn', 'Has eaten ice cream every day of a trip', 'Has left something important at home', 'Has bought a hat they never wore again', 'Has learned “thank you” in a new language', 'Has ordered food using only hand gestures', 'Has ridden an animal on holiday', 'Has spent a whole holiday day in pyjamas', 'Has sent a postcard that arrived after they got home']],
  ['Messy Truths', ['Has a chair that is really a wardrobe', 'Has left washing in the machine for a day', 'Has eaten a whole meal in bed', 'Hasn’t made their bed this week', 'Has a pile of letters they’re avoiding', 'Has lost a sock this month', 'Has a junk drawer', 'Has hidden something under the bed for guests', 'Has found a mystery item in a coat pocket']],
  ['Money Matters', ['Has found money in an old coat', 'Has lent money and never got it back', 'Has bought a lottery ticket', 'Has won a raffle prize', 'Has a savings jar', 'Has spent far too much on a takeaway', 'Has bought something online in the middle of the night', 'Has haggled at a market', 'Has kept a receipt for over a year']],
  ['Brush with Fame', ['Has met a famous person', 'Has been on TV', 'Has been in a newspaper', 'Has a signed photo', 'Has been told they look like someone famous', 'Has been in the crowd on live TV', 'Has written a fan letter', 'Has queued for hours for an event', 'Has had a reply from a celebrity online']],
  ['Self-Care Secrets', ['Talks to themselves out loud', 'Has practised a speech in the mirror', 'Has given themselves a pep talk', 'Has napped in a parked car', 'Has stayed in the bath until it went cold', 'Has cancelled plans just to stay home', 'Has eaten ice cream to cheer up', 'Has cried at a happy ending', 'Has a playlist just for cleaning']],
  ['Odd Habits', ['Counts the stairs', 'Smells new books', 'Talks to their car', 'Eats food in a strict order', 'Has a lucky number', 'Avoids cracks in the pavement', 'Reads the end of a book first', 'Names their houseplants', 'Sorts sweets by colour before eating']],
  ['Nine to Five', ['Has fake-typed to look busy', 'Has fallen asleep at work', 'Has emailed the wrong person', 'Has eaten someone’s lunch from the work fridge', 'Has hidden in the toilets at work', 'Has nodded through a meeting they didn’t follow', 'Has worn the same outfit to work twice in a row', 'Has taken a “sick day” for something fun', 'Has laughed at their boss’s joke a bit too hard']],
];

/** Spicier Most Wanted sets. Filtered when the family setting is on. */
export const WANTED_ADULT: readonly (readonly [string, readonly string[]])[] = [
  ['Dating Disasters', ['Has been ghosted', 'Has ghosted someone', 'Has been on a blind date', 'Has lied on a dating profile', 'Has had a friend fake an emergency to end a date', 'Has dated two people at once', 'Has been dumped by text', 'Has looked up an ex online at night', 'Has dated someone they met that same day']],
  ['Big Night Out', ['Has danced on a table', 'Has been thrown out of a bar', 'Has lost their shoes on a night out', 'Has woken up fully dressed', 'Has eaten a takeaway on the walk home at 3 a.m.', 'Has drunk-texted an ex', 'Has called in sick with a hangover', 'Has lost their keys on a night out', 'Has given a fake name at a bar']],
  ['Romance Confessions', ['Has had a crush on a friend’s partner', 'Has had a crush on a co-worker', 'Has kissed a stranger', 'Has had a secret relationship', 'Has gone skinny-dipping', 'Has had a one-night stand', 'Has written a love poem', 'Has been caught checking someone out', 'Has had a crush on someone in this room']],
  ['Office Drama', ['Has cried in the toilets at work', 'Has lied about why they were late', 'Has slept through a meeting', 'Has complained about the boss to the boss by mistake', 'Has quit a job dramatically', 'Has worked in pyjama bottoms on a video call', 'Has gone to an interview hungover', 'Has dated a co-worker', 'Has pretended their internet died to leave a call']],
  ['Bad Decisions', ['Has a tattoo they regret', 'Has got back together with an ex', 'Has spent the rent on something silly', 'Has said “I love you” first and regretted it', 'Has sent a photo they instantly regretted', 'Has gone to work still tipsy', 'Has woken up with no memory of the night', 'Has started a fight they couldn’t finish', 'Has signed up for something while tipsy']],
  ['The Morning After', ['Has woken up somewhere unexpected', 'Has found a receipt they can’t explain', 'Has found food in their bed', 'Has had to retrace their steps to find their phone', 'Has apologised to the whole group chat', 'Has eaten breakfast at four in the afternoon', 'Has worn sunglasses indoors for a hangover', 'Has promised “never again” and lied', 'Has checked their bank balance through their fingers']],
];

/** Short stable id for a piece of content (for the night-long `api.used` memory). */
function key(prefix: string, text: string) {
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = (h * 33 + text.charCodeAt(i)) >>> 0;
  return `${prefix}${h.toString(36)}`;
}
const question = (adult: boolean) => (line: string): Question => {
  const text = line.replace(/^\+/, '');
  return { id: key('q', text), text, ...(line.startsWith('+') ? { open: true as const } : {}), ...(adult ? { adult: true as const } : {}) };
};
const wanted = (adult: boolean) => ([title, items]: readonly [string, readonly string[]]): WantedSet =>
  ({ id: key('w', title), title, items: [...items], ...(adult ? { adult: true as const } : {}) });

export const QUESTIONS: readonly Question[] = [...FAMILY.map(question(false)), ...ADULT.map(question(true))];
export const WANTED: readonly WantedSet[] = [...WANTED_FAMILY.map(wanted(false)), ...WANTED_ADULT.map(wanted(true))];
export const questionPool = (family: boolean) => family ? QUESTIONS.filter(q => !q.adult) : QUESTIONS;
export const wantedPool = (family: boolean) => family ? WANTED.filter(w => !w.adult) : WANTED;
