/* Tall Tales fact bank (server only; never imported by client code). Every story is true; the wording, teasers and house
   lies are original. Each entry: teaser (the category the chooser sees), the story with one ___ blank, the answer plus
   accepted variants ("answer|variant|…") and at least three plausible house lies. Adult/edgy entries are filtered in family mode. */

export type Fact = { teaser: string; text: string; answer: string; alts: string[]; lies: string[]; adult?: true };
const t = (teaser: string, text: string, answers: string, lies: string): Fact => {
  const [answer, ...alts] = answers.split('|');
  return { teaser, text, answer: answer!, alts, lies: lies.split('|') };
};

export const FAMILY: readonly Fact[] = [
  // ---------- people and history ----------
  t('The Longest Hiccups', 'Iowa farmer Charles Osborne hiccupped almost nonstop for ___ years.', '68|sixty eight', '41|23|12'),
  t('Blink and You Missed It', 'The 1896 war between Britain and Zanzibar, the shortest on record, lasted roughly ___ minutes.', '38|40|45|39|41|42|43|44', '12|90|5'),
  t('Older Than You Think', 'The University of Oxford is older than the ___ Empire.', 'Aztec|Aztecs', 'Roman|Persian|Byzantine'),
  t('Imperial Ambush', 'Napoleon was once attacked by a horde of ___ during a hunt held in his honour.', 'rabbits|bunnies', 'geese|ducks|squirrels'),
  t('Losing Battle', 'In 1932, Australian soldiers armed with machine guns were sent to fight ___, and lost.', 'emus', 'kangaroos|koalas|crocodiles'),
  t('History’s Rounding Error', 'The Hundred Years’ War actually lasted ___ years.', '116|one hundred and sixteen|one hundred sixteen', '99|83|142'),
  t('London Burning', 'The Great Fire of London destroyed over 13,000 houses, but only ___ deaths were officially recorded.', '6', '2|40|300'),
  t('Medieval Courtroom', 'In 1386, a ___ was put on trial in France, found guilty of murder and executed.', 'pig|sow|swine|hog', 'goat|rooster|horse'),
  t('A Job Offer', 'In 1952, Albert Einstein was offered the job of ___.', 'President of Israel|Israeli president|Israel’s president|president|president of the state of Israel', 'head of NASA|mayor of Princeton|King of Belgium'),
  t('Honest Abe’s Hobby', 'Abraham Lincoln is in the National ___ Hall of Fame.', 'Wrestling', 'Boxing|Chess|Woodchopping'),
  t('Wartime Royal', 'During World War II, the future Queen Elizabeth II trained as a ___.', 'mechanic|truck mechanic|driver|lorry driver|truck driver|army mechanic|ambulance driver|military driver|driver and mechanic|motor mechanic', 'pilot|codebreaker|spy'),
  t('Tsar Taxes', 'Russian tsar Peter the Great introduced a tax on ___.', 'beards|facial hair', 'hats|bells|pet cats'),
  t('Taxing Times', 'From 1696, England taxed homes based on how many ___ they had.', 'windows', 'doors|staircases|bathtubs'),
  t('Egyptian Bedtime', 'Ancient Egyptians often rested their heads at night on headrests made of ___.', 'stone|wood|ivory|limestone|alabaster|stone or wood|wood or stone', 'feathers|bread|sheep’s wool'),
  t('Helmet Hair', 'Despite the pictures, there’s no evidence Viking warriors wore helmets with ___.', 'horns|wings|horns on them', 'nose guards|leather straps|iron rims'),
  t('Boston Flood', 'In 1919, a giant wave of ___ flooded the streets of Boston.', 'molasses|treacle', 'custard|maple syrup|tomato soup'),
  t('London Flood', 'In 1814, a flood of ___ swept through a street in London.', 'beer|porter|ale', 'gravy|custard|tea'),
  t('Strasbourg Fever', 'In 1518, dozens of people in Strasbourg were struck by an uncontrollable urge to ___.', 'dance|dancing|dance for days', 'sneeze|sing|whistle'),
  t('Emperor’s Pick', 'The Roman emperor Caligula reportedly planned to make his ___ a consul.', 'horse|favourite horse|favorite horse|Incitatus|steed', 'barber|cat|cook'),
  t('Pirate Ransom', 'When pirates kidnapped a young Julius Caesar, he insisted they ___ his ransom.', 'raise|increase|double|up|raised|increased|more than double|higher|bump up', 'lower|waive|split'),
  t('Generous Will', 'In his will, Shakespeare left his wife his second-best ___.', 'bed', 'quill|horse|hat'),
  t('Gone Missing', 'In 1926, crime writer Agatha Christie mysteriously vanished for ___ days.', '11', '3|40|6'),
  t('Twain’s Timing', 'Mark Twain was born when ___ passed Earth, and died the day after it came back.', 'Halley’s Comet|Halley comet|Halley|comet|comet Halley', 'a solar eclipse|a blue moon|Venus'),
  t('Usual Suspects', 'When the Mona Lisa was stolen in 1911, the artist ___ was questioned by police.', 'Picasso|Pablo Picasso', 'Claude Monet|Henri Matisse|Salvador Dalí'),
  t('Leonardo’s Notes', 'Leonardo da Vinci often wrote his notes ___.', 'backwards|in mirror writing|mirror writing|in reverse|right to left|reversed|mirrored|in mirror script|from right to left|back to front', 'in invisible ink|upside down|in Latin'),
  t('Unsinkable Nurse', 'Violet Jessop survived the Titanic sinking, and later the sinking of its sister ship, the ___.', 'Britannic|HMHS Britannic', 'Lusitania|Mauretania|Carpathia'),
  t('Not Wooden', 'George Washington’s false teeth were made from ivory, metal and ___ teeth, but not wood.', 'human|animal|cow|horse|human and animal|people’s', 'shark|dolphin|whale'),
  t('Lightning Magnet', 'Park ranger Roy Sullivan survived being struck by lightning ___ times.', '7', '4|12|19'),
  t('Phone Etiquette', 'Alexander Graham Bell wanted people to answer the telephone by saying “___”.', 'Ahoy|Ahoy-hoy', 'Greetings|Speak|Hark'),
  t('Darwin’s Club', 'As a student, Charles Darwin belonged to a club devoted to ___ unusual animals.', 'eating|tasting|cooking and eating', 'racing|painting|dressing up'),
  t('Inventor’s Sweetheart', 'Inventor Nikola Tesla said he loved a white ___ as a man loves a woman.', 'pigeon|dove|bird', 'horse|owl|cat'),
  t('Dorm Pet', 'Poet Lord Byron kept a pet ___ at university because dogs weren’t allowed.', 'bear|tame bear', 'goat|fox|badger'),
  t('Walkies', 'Artist Salvador Dalí was photographed walking a pet ___ on a lead in Paris.', 'anteater|ant eater', 'tortoise|penguin|flamingo'),
  t('Poet’s Pet', 'The French poet Gérard de Nerval reportedly walked a pet ___ on a ribbon.', 'lobster', 'goldfish|snail|tortoise'),
  t('Iron Stomach', 'Michel Lotito, a French entertainer, once ate an entire ___.', 'airplane|plane|aeroplane|aircraft|Cessna|Cessna 150|light aircraft', 'submarine|lighthouse|double-decker bus'),
  t('Deep Breath', 'With help from pure oxygen, a Croatian diver held his breath for over ___ minutes.', '24', '11|38|7'),
  t('Miracle Mike', 'In 1945, a chicken named Mike lived for 18 months after losing his ___.', 'head', 'wings|legs|voice'),
  t('Golf Ban', 'In 1457, King James II of Scotland banned golf because it distracted men from practising ___.', 'archery|the longbow|bow and arrow|shooting arrows|bowmanship', 'sword fighting|farming|going to church'),
  t('Tour de Cheat', 'In the 1904 Tour de France, some riders cheated by catching ___.', 'trains|a train|cars|lifts|car rides|rides in cars', 'horses|hot air balloons|boats'),
  t('Speed Demon', 'The first person convicted of speeding in Britain, in 1896, was doing ___ mph.', '8', '30|15|45'),
  t('Explosive Debut', 'The first traffic light, put up in London in 1868, ran on ___, and later exploded.', 'gas|gaslight|coal gas|gas lamps', 'steam|candles|whale oil'),
  t('Feared Food', 'In the 1700s, many Europeans feared that ___ were poisonous.', 'tomatoes', 'carrots|apples|bananas'),
  t('Lost Olympic Sports', 'From 1900 to 1920, ___ was an official Olympic event.', 'tug of war|tug o’ war', 'pillow fighting|sack racing|hopscotch'),
  t('Olympic Medals', 'Between 1912 and 1948, the Olympics awarded medals for ___.', 'art|arts|painting|art competitions|sculpture|music|architecture|literature|poetry|paintings', 'cooking|juggling|ballroom dancing'),
  t('Marathon Maths', 'The marathon is 26.2 miles because the 1908 London course was stretched to finish in front of the ___.', 'royal box|royal family|King|Queen|royals|royal box at the stadium', 'nearest pub|Prime Minister’s house|finish-line bakery'),
  t('Hidden Treasure', 'During World War II, an Italian official hid the football World Cup trophy in a shoebox under his ___.', 'bed', 'piano|chicken coop|floorboards'),
  t('Good Boy', 'When the World Cup trophy was stolen in 1966, it was found by a dog called ___.', 'Pickles', 'Biscuit|Rover|Sherlock'),
  t('Two Little Letters', 'The word “OK” began in 1839 as a jokey abbreviation of “___”.', 'oll korrect|oll korrekt|all correct|orl korrect|ol korrect', 'only kidding|orderly kitchen|on kue'),
  t('Coined by Whom?', 'The first known printed use of the word “nerd” was in a 1950 book by ___.', 'Dr. Seuss|Seuss|Doctor Seuss|Theodor Geisel|Theodor Seuss Geisel', 'Roald Dahl|Mark Twain|J. R. R. Tolkien'),
  t('Robot Roots', 'The word “robot” comes from a Czech word meaning ___.', 'forced labour|forced labor|drudgery|hard work|labour|labor|work|servitude|serf labour|serf labor|forced work|slave labour|slave labor', 'tin man|thinking machine|clockwork'),
  t('Cat Mourners', 'The historian Herodotus wrote that ancient Egyptians shaved off their ___ to mourn a pet cat.', 'eyebrows|brows', 'sideburns|ponytails|toe hair'),
  t('Inventor’s Urn', 'Fredric Baur, a chemist from Ohio, had some of his ashes buried in ___.', 'a Pringles can|Pringles tube|Pringles|Pringle can|crisp tube|chip can', 'a cookie jar|a lunchbox|a gravy boat'),
  t('A Toymaker’s Last Wish', 'Toy designer Ed Headrick had his ashes moulded into ___.', 'Frisbees|flying discs|discs|memorial discs', 'bowling balls|golf tees|garden gnomes'),
  // ---------- food ----------
  t('Tomb Raiders’ Snack', 'Archaeologists have found pots of ___ in ancient Egyptian tombs that were still edible.', 'honey', 'date jam|salted butter|pickled figs'),
  t('Fit for Prisoners', 'In colonial New England, ___ was so plentiful it was seen as cheap food for prisoners and servants.', 'lobster', 'turkey|chocolate|bacon'),
  t('Doctor’s Orders', 'In the 1830s, ___ was sold in America as a medicine.', 'ketchup|tomato ketchup|catsup|tomato pills|tomato extract', 'mayonnaise|bubble gum|popcorn'),
  t('Original Lanterns', 'Before pumpkins, Irish jack-o’-lanterns were carved out of ___.', 'turnips|swedes|rutabagas|potatoes|beets|mangelwurzels', 'melons|onions|cabbages'),
  t('Carrot Colours', 'Before the 1600s, most farmed carrots were purple or ___.', 'yellow|white', 'blue|green|striped'),
  t('Botany Says What?', 'Botanically speaking, a banana counts as a ___.', 'berry', 'nut|legume|tuber'),
  t('Hot Fruit', 'Bananas are very slightly ___ because of the potassium they contain.', 'radioactive', 'magnetic|explosive|carbonated'),
  t('Fortune’s Origin', 'Fortune cookies are thought to have started in ___, not China.', 'Japan|Japanese|California|San Francisco|America|USA|United States|US|Kyoto', 'Italy|Mexico|Korea'),
  t('Hail Caesar', 'The Caesar salad was invented in ___.', 'Mexico|Tijuana|Tijuana, Mexico', 'Rome|Greece|Spain'),
  t('Tropical Mystery', 'Hawaiian pizza, with ham and pineapple, was invented in ___.', 'Canada|Ontario|Chatham|Chatham, Ontario', 'Hawaii|Sweden|Australia'),
  t('Heavy Cake', 'Pound cake got its name from using a pound each of flour, butter, eggs and ___.', 'sugar', 'milk|lard|raisins'),
  t('Cranberry Quality Control', 'Ripe cranberries can ___, which growers use to sort out the good ones.', 'bounce|bouncing', 'glow|squeak|whistle'),
  t('Pink Gum', 'Bubble gum is usually pink because pink was the only ___ its inventor had on hand.', 'food colouring|food coloring|dye|colouring|coloring|food dye|colour|color|food color|food colour', 'glitter|crayon|paint'),
  t('Fairground Treat', 'Cotton candy was co-invented by a ___.', 'dentist', 'baker|clown|sheep farmer'),
  t('Shiny Sweets', 'The shiny glaze on some sweets comes from secretions of the ___.', 'lac bug|lac insect|insects|bugs|lac beetle|female lac bug', 'silkworm|garden snail|jellyfish'),
  t('Red Alert', 'The red food colouring carmine is made from crushed ___.', 'insects|bugs|cochineal|cochineal insects|beetles|cochineal bugs|scale insects', 'beetroot|rubies|tomatoes'),
  t('Expensive Brew', 'Some of the world’s priciest coffee is made from beans eaten and pooped out by a ___.', 'civet|civet cat|Asian palm civet|palm civet|elephant|jacu|jacu bird', 'sloth|peacock|goat'),
  t('Festive Feast', 'In Japan, a popular Christmas dinner tradition is eating ___.', 'KFC|fried chicken|Kentucky Fried Chicken|KFC chicken|chicken|Christmas cake|strawberry cake|strawberry shortcake|cake', 'spaghetti|hot dogs|beef burgers'),
  // ---------- inventions and brands ----------
  t('Squishy Origins', 'Play-Doh was originally invented to clean ___.', 'wallpaper|walls|soot off wallpaper|coal soot', 'false teeth|windows|bowling balls'),
  t('Pop Goes the Plan', 'Bubble Wrap was first invented as a type of ___.', 'wallpaper|textured wallpaper|wall covering|insulation|greenhouse insulation', 'bath mat|raincoat|mattress'),
  t('Nintendo’s First Job', 'Before video games, Nintendo started in 1889 making ___.', 'playing cards|cards|card games|hanafuda|hanafuda cards', 'umbrellas|paper lanterns|tea sets'),
  t('Before the Phones', 'Before mobile phones, Nokia began in 1865 as a ___.', 'paper mill|pulp mill|paper company|wood pulp mill|paper factory', 'fishing company|toy shop|bakery'),
  t('What’s in a Name', 'The name LEGO comes from Danish words meaning ___.', 'play well|leg godt|play good', 'tiny bricks|build big|click together'),
  t('Humble Beginnings', 'Samsung started out in 1938 selling dried fish, fruit and ___.', 'noodles|vegetables|groceries', 'socks|bicycles|umbrellas'),
  t('Search Party', 'Before it was called Google, the search engine was named ___.', 'BackRub|back rub', 'SearchBot|Lookie|WebDog'),
  t('Electronics Debut', 'Sony’s first attempt at a product, in 1945, was an electric ___.', 'rice cooker|rice-cooker', 'toaster|kettle|fan'),
  t('Wartime Fizz', 'Fanta was invented in 1940 in ___ when Coca-Cola syrup couldn’t be imported.', 'Germany|Nazi Germany', 'Brazil|Sweden|Mexico'),
  t('Small-Screen Star', 'The first toy ever advertised on American TV, in 1952, was ___.', 'Mr. Potato Head|Potato Head|Mister Potato Head', 'the Hula Hoop|a rubber duck|the Frisbee'),
  t('Sticky Inspiration', 'The inventor of Velcro got the idea from ___ stuck to his dog’s fur.', 'burrs|burdock burrs|burdock|burs|seed burrs|burdock seeds', 'chewing gum|pine sap|sticky lizards'),
  t('Kid Inventor', 'The ice lolly on a stick was invented by accident in 1905 by a boy aged ___.', '11', '8|15|6'),
  t('Melted Discovery', 'The microwave oven was invented after a radar engineer noticed a ___ had melted in his pocket.', 'chocolate bar|candy bar|chocolate|peanut bar|peanut cluster bar|peanut cluster|chocolate peanut bar', 'lip balm|crayon|jelly bean'),
  t('Apollo Toolkit', 'Apollo 8 astronauts took ___ along to help hold their tools in place.', 'Silly Putty|putty', 'Blu Tack|chewing gum|marshmallows'),
  t('Sticky Accident', 'Super Glue was discovered by accident during work on clear plastic ___ for guns.', 'gunsights|gun sights|sights|gun-sights', 'triggers|bullets|holsters'),
  t('Happy Failure', 'Post-it notes exist because a scientist failed to make a super-strong ___.', 'glue|adhesive|superglue', 'magnet|paper|tape'),
  t('Actual Bug', 'The first recorded computer “bug”, in 1947, was a real ___ stuck in the machine.', 'moth', 'cockroach|beetle|spider'),
  t('Cambridge Livestream', 'One of the first webcams was set up to watch a ___ at Cambridge University.', 'coffee pot|coffee machine|coffee maker|coffee|coffeepot|Trojan Room coffee pot|coffee percolator', 'goldfish tank|sleeping professor|parking space'),
  t('Going Once', 'The first item ever sold on eBay was a broken ___.', 'laser pointer|laser pen|laser', 'toaster|calculator|lamp'),
  t('Day at the Zoo', 'The first video ever uploaded to YouTube was filmed in front of the ___.', 'elephants|elephant enclosure|elephant pen', 'penguins|giraffes|monkeys'),
  t('Fiery Fox', 'The animal the Firefox web browser is named after is the ___.', 'red panda|lesser panda|firefox', 'fennec fox|red squirrel|raccoon'),
  t('Blue Tooth, Who?', 'Bluetooth technology is named after a Danish ___.', 'king|Viking king|King Harald|Harald Bluetooth|Harald|Viking', 'dentist|sailor|fisherman'),
  t('@ in Italy', 'In Italian, the @ symbol is nicknamed “chiocciola”, meaning ___.', 'snail|little snail', 'curly pasta|whirlpool|pig’s tail'),
  t('Seventies Craze', 'In 1975, millions of people paid good money for a “pet” ___ in a box.', 'rock|stone|pebble|pet rock', 'potato|cloud|sponge'),
  t('Security Risk', 'In 1999, the US National Security Agency banned ___ from its offices.', 'Furbies|Furby|Furbys', 'Tamagotchis|yo-yos|Beanie Babies'),
  t('Beep!', 'The first product ever scanned with a barcode, in 1974, was a pack of ___.', 'chewing gum|gum|Wrigley’s gum|Juicy Fruit|Juicy Fruit gum|Wrigley’s Juicy Fruit|Wrigley gum', 'cigarettes|biscuits|batteries'),
  t('Ancient Vending', 'The first known vending machine, from ancient Egypt, dispensed ___.', 'holy water|water|sacred water', 'olive oil|honey|perfume'),
  t('Singapore Rules', 'Since 1992, selling ___ has been banned in Singapore.', 'chewing gum|gum|bubble gum', 'water pistols|ketchup|skateboards'),
  // ---------- words and games ----------
  t('Tiny Details', 'The dot over a lowercase i or j is called a ___.', 'tittle|superscript dot', 'speck|pip|freckle'),
  t('Lace Up', 'The little plastic tip on a shoelace has a name: the ___.', 'aglet|aiglet', 'eyelet|nubbin|lacelet'),
  t('Face Geography', 'The smooth patch of skin between your eyebrows is called the ___.', 'glabella', 'browgap|frontlet|mid-brow'),
  t('After the Rain', 'The pleasant earthy smell after rain is called ___.', 'petrichor', 'pluvium|dampling|ozonia'),
  t('Symbol Minded', 'The # symbol’s official-sounding name is the ___.', 'octothorpe|octothorp|octotherp|hash|hashtag|pound sign|number sign|hash sign|sharp', 'quadrigrid|tic-tac-mark|crosshatchet'),
  t('Seven Letters, No Vowels', 'The longest common English word without a, e, i, o or u is “___”.', 'rhythms|rhythm', 'crypts|glyphs|nymphs'),
  t('Short Alphabet', 'The Hawaiian alphabet has just ___ letters.', '13|12', '9|18|21'),
  t('Card Sharp', 'In a standard deck, the King of ___ is the only king without a moustache.', 'Hearts', 'Spades|Clubs|Diamonds'),
  t('Mandela Moment', 'Despite what many people remember, the Monopoly man doesn’t wear a ___.', 'monocle|eyeglass', 'top hat|moustache|bow tie'),
  t('Doll Details', 'Barbie’s full name is Barbara Millicent ___.', 'Roberts', 'Johnson|Kensington|Malibu'),
  t('Wordy Beginnings', 'Before it was called Scrabble, the board game was named ___.', 'Criss-Crosswords|Lexiko', 'Word Wizard|Letter Lotto|Tile Tango'),
  t('Puzzling Name', 'The Rubik’s Cube was first sold in Hungary as the ___.', 'Magic Cube|Bűvös kocka', 'Puzzle Box|Brain Brick|Colour Cube'),
  t('Game With a Message', 'Monopoly grew out of an earlier game designed to show the evils of ___.', 'landlords|landlordism|monopolies|monopoly|rent|greedy landlords|land grabbing|land monopolies|renting', 'gambling|banking|taxes'),
  t('Net Gains', 'Volleyball was originally called ___.', 'Mintonette', 'Bounceball|Sky Tennis|Handnet'),
  t('Table Talk', 'An early name for table tennis was ___.', 'whiff-whaff|ping-pong|gossima|whiff-waff', 'flip-flap|tap-tap|bat-ball'),
  t('Hoop Dreams', 'The first basketball games used ___ as hoops.', 'peach baskets|baskets|fruit baskets|peach crates|crates', 'buckets|bicycle wheels|barrels'),
  t('Centre Court Guard', 'The Wimbledon tennis championships employ a ___ to scare away pigeons.', 'hawk|Harris hawk|Harris’s hawk|bird of prey', 'owl|scarecrow|cat'),
  t('Poll Position', 'When Britain asked the public to name a new polar research ship, the winning name was ___.', 'Boaty McBoatface|Boaty|Boaty Mc Boatface', 'Shippy McShipface|Sir Floats-a-Lot|Captain Splashy'),
  t('Famous Shriek', 'A stock scream heard in hundreds of films is known as the “___ scream”.', 'Wilhelm', 'Gregory|Howard|Bernard'),
  t('Long Concert', 'A German church organ is playing a John Cage piece that won’t finish until the year ___.', '2640', '2100|3000|2525'),
  t('Orbital Music', 'The first song played in space, in 1965, was “___”, on a harmonica and bells.', 'Jingle Bells', 'Happy Birthday|Twinkle Twinkle Little Star|Yankee Doodle'),
  // ---------- animals ----------
  t('Wombat Business', 'Wombats are famous for producing poop shaped like ___.', 'cubes|dice|squares|blocks|cubed', 'stars|tiny hearts|spirals'),
  t('Heart Surplus', 'An octopus has ___ hearts.', '3', '2|5|8'),
  t('Strange Gangs: Flamingos', 'A group of flamingos is called a ___.', 'flamboyance|stand|colony', 'fabulousness|pinkening|parade'),
  t('Strange Gangs: Owls', 'A group of owls is called a ___.', 'parliament', 'senate|library|jury'),
  t('Strange Gangs: Ferrets', 'A group of ferrets is called a ___.', 'business|busyness|fesnying', 'racket|scramble|hustle'),
  t('Strange Gangs: Pugs', 'A group of pugs is sometimes called a ___.', 'grumble', 'snort|wrinkle|pancake'),
  t('Strange Gangs: Porcupines', 'A group of porcupines is called a ___.', 'prickle', 'pinch|needlework|ouch'),
  t('Strange Gangs: Jellyfish', 'A group of jellyfish can be called a ___.', 'smack|bloom|swarm|smuck', 'wobble|jiggle|sting'),
  t('Strange Gangs: Rhinos', 'A group of rhinos is called a ___.', 'crash', 'thud|bulldozer|honk'),
  t('Strange Gangs: Zebras', 'A group of zebras is called a ___.', 'dazzle|zeal|herd', 'barcode|stripe|static'),
  t('Strange Gangs: Giraffes', 'A group of giraffes standing around is called a ___.', 'tower|herd|journey', 'steeple|skyline|stretch'),
  t('Strange Gangs: Cats', 'A group of cats is called a ___.', 'clowder|glaring|clutter|pounce', 'judgement|snub|purrade'),
  t('National Treasure', 'The official national animal of Scotland is the ___.', 'unicorn', 'Highland cow|haggis|dragon'),
  t('Ancient Swimmers', 'Sharks have been around longer than ___.', 'trees', 'jellyfish|the Moon|sponges'),
  t('Otter Nap Time', 'Sea otters sometimes hold ___ while they sleep so they don’t drift apart.', 'hands|paws|each other’s paws|each other’s hands', 'tails|ears|whiskers'),
  t('Art Critics With Wings', 'Scientists trained pigeons to tell paintings by Monet apart from paintings by ___.', 'Picasso|Pablo Picasso', 'Van Gogh|Rembrandt|da Vinci'),
  t('Crime Scene Confusion', '___ have fingerprints so similar to ours that they could confuse a crime scene.', 'koalas|koala bears', 'raccoons|sloths|otters'),
  t('Lonely Hearts Law', 'In Switzerland it is illegal to own just one ___, because they get lonely.', 'guinea pig|cavy', 'hamster|tortoise|iguana'),
  t('Grudge Holders', 'Crows can recognise individual human ___ and hold grudges for years.', 'faces', 'voices|handwriting|shoes'),
  t('Dolphin Chat', 'Bottlenose dolphins use signature whistles that work like ___.', 'names|their names|nicknames|name tags', 'passwords|jokes|alarm clocks'),
  t('A Knight to Remember', 'In 2008, a ___ at Edinburgh Zoo was knighted by the Norwegian King’s Guard.', 'penguin|king penguin|Nils Olav', 'seal|parrot|tortoise'),
  t('Penguin Proposals', 'Gentoo penguins court a mate by offering a ___.', 'pebble|stone|rock', 'fish|feather|shell'),
  t('Horse Limits', 'Horses are physically unable to ___.', 'vomit|throw up|puke|be sick|regurgitate|barf|burp', 'sweat|lie down|yawn'),
  t('Tongue Twister', 'A giraffe’s tongue is a dark ___ colour.', 'purple|blue|black|blue-black|bluish|navy|purplish|purple-black|dark blue', 'green|orange|yellow'),
  t('Barkless Breed', 'The basenji is a dog breed that can’t really bark. Instead, it ___.', 'yodels|yodelling|yodeling|barroos|yodels and howls', 'whistles|purrs|hiccups'),
  t('Puppy Surprise', 'Dalmatian puppies are born completely ___.', 'white|spotless|without spots|plain white|pure white|all white', 'black|brown|grey'),
  t('Sniff Test', 'Many dogs’ paws smell like ___, thanks to the bacteria on them.', 'corn chips|popcorn|tortilla chips|Fritos|corn crisps|nachos|crisps|chips|corn', 'lavender|maple syrup|fresh bread'),
  t('Cow ID', 'A cow’s ___ print is as unique as a human fingerprint.', 'nose|muzzle|snout', 'hoof|tongue|ear'),
  t('Garden Monster', 'A garden snail has thousands of ___.', 'teeth|tiny teeth', 'eyes|hearts|toes'),
  t('Wiggly Hearts', 'An earthworm has ___ hearts.', '5|10|five pairs of', '2|3|9'),
  t('Bee Directions', 'Honeybees tell each other where to find flowers by ___.', 'dancing|dance|waggle dance|dances|waggle dancing|wiggling|waggling|doing a dance', 'humming|tapping|whistling'),
  t('Pocket Rocket', 'A mantis shrimp punches so fast that the water around its claw can ___.', 'boil|flash boil|cavitate|bubble|form bubbles|glow|light up|flash', 'freeze|turn pink|catch fire'),
  t('Lobster Lifeblood', 'Lobsters have ___ blood.', 'blue|bluish|blue coloured|blue colored|clear|colourless|colorless', 'green|purple|yellow'),
  t('Jellyfish Superpower', 'Turritopsis dohrnii is nicknamed the “___ jellyfish” because it can turn itself young again.', 'immortal', 'phoenix|zombie|boomerang'),
  t('Old Timer', 'The Greenland shark may live for around ___ years.', '400|four hundred|300|500|272|392|390', '90|1,000|60'),
  t('Hippo Skincare', 'Hippos ooze a ___ liquid that works like sunscreen.', 'red|reddish|red and orange|pink|orange|red-orange|orange-red|blood red', 'blue|green|purple'),
  t('Sloth Hair Day', 'Sloths move so slowly that ___ grows in their fur.', 'algae|alga|green algae|moss', 'grass|ivy|cress'),
  t('Woodpecker Secrets', 'A woodpecker’s tongue is so long it wraps around its ___.', 'skull|brain|head', 'neck|beak|wing'),
  t('Ostrich Proportions', 'An ostrich’s eye is bigger than its ___.', 'brain', 'heart|stomach|foot'),
  t('Starfish Dinner', 'Starfish eat by pushing their ___ out of their bodies.', 'stomach|guts|belly', 'tongue|teeth|heart'),
  t('Butterfly Tasting', 'Butterflies taste their food using their ___.', 'feet|legs', 'wingtips|knees|eyelashes'),
  t('Shrimp Anatomy', 'A shrimp’s heart is located in its ___.', 'head', 'tail|legs|claws'),
  t('Picky Cats', 'Cats are unable to taste ___ flavours.', 'sweet|sweetness|sugary|sugar', 'salty|sour|bitter'),
  t('Tickle Fight', 'Scientists discovered that rats ___ when they are tickled.', 'laugh|giggle|chirp|squeak', 'sneeze|hiccup|blush'),
  t('Elephant Limits', 'The elephant is one of the few mammals that can’t ___.', 'jump|leap', 'swim|kneel|lie down'),
  t('Under the Fur', 'Under its white fur, a polar bear’s skin is ___.', 'black|dark|dark grey|dark gray|blackish', 'pink|blue|orange'),
  t('Flamingo Babies', 'Flamingo chicks are born with ___ feathers.', 'grey|gray|white|grey and white|greyish|whitish|gray and white|fluffy grey|fluffy white', 'pink|black|yellow'),
  t('Party Glow', 'Under ultraviolet light, a platypus’s fur glows ___.', 'blue-green|green|blue|cyan|teal|greenish blue|bluish green|turquoise|greenish|bluish', 'pink|orange|gold'),
  t('Breath Holder', 'By slowing its heart rate, a sloth can hold its breath for up to ___ minutes.', '40', '12|90|3'),
  t('Hummingbird Habits', 'Hummingbirds can perch and fly, but they can’t really ___.', 'walk|hop|walk or hop|walk around', 'fly backwards|sleep|hover'),
  t('Unusual Breathing', 'Some turtles can absorb oxygen through their ___.', 'butts|bum|bottom|cloaca|rear|backside|rear end|bottom end', 'shells|eyelids|toenails'),
  t('Seahorse Parenting', 'In seahorses, it’s the ___ who gets pregnant and gives birth.', 'father|male|dad|daddy', 'eldest daughter|strongest female|herd leader'),
  t('Beetle Satnav', 'Dung beetles can find their way at night using the ___.', 'Milky Way|stars|starlight|galaxy', 'smell of dew|street lights|sound of crickets'),
  t('Chicken Record', 'The longest recorded flight by a chicken lasted ___ seconds.', '13', '4|45|90'),
  // ---------- people, bodies, records ----------
  t('Space Body', 'In space, astronauts temporarily get ___ because their spines stretch out.', 'taller|tall|longer', 'shorter|freckles|hiccups'),
  t('Hum Along', 'It’s almost impossible to hum while holding your ___.', 'nose|nose closed|nostrils|nose shut', 'ears|tongue|elbows'),
  t('Some Assembly Required', 'Babies are born without hard, bony ___.', 'kneecaps|patellas|patella|knee caps', 'ribs|elbows|fingers'),
  t('One-Passenger Station', 'A Japanese railway station stayed open for years just so one ___ could get to school.', 'girl|student|schoolgirl|teenager|high school student|pupil|teen|child|kid|teenage girl|high school girl', 'teacher|goat|dog'),
  t('Mayor Material', 'The town of Rabbit Hash, Kentucky, has elected several ___ as its mayor.', 'dogs|pets|pet dogs', 'goats|toddlers|parrots'),
  // ---------- places ----------
  t('Tower Growth Spurt', 'Thanks to thermal expansion, the Eiffel Tower gets a little taller every ___.', 'summer|hot weather|heatwave|heat wave|hot day', 'full moon|leap year|winter'),
  t('Not Built to Last', 'The Eiffel Tower was originally only meant to stand for ___ years.', '20', '5|50|100'),
  t('Shiny Lady Liberty', 'When it was new, the Statue of Liberty was the colour of a shiny ___.', 'penny|copper|coin|new penny|copper coin|copper pot|copper penny', 'gold bar|banana|fire engine'),
  t('Big Ben Who?', 'Strictly speaking, Big Ben is the name of the clock tower’s ___.', 'bell|great bell|bell inside', 'clock hands|weathervane|clockmaker'),
  t('Sign of the Times', 'The Hollywood sign originally read “___”.', 'Hollywoodland|Hollywood Land', 'Hollywood Hills|Hollywoodville|Holly Wood Estates'),
  t('Tiny Country', 'The whole country of Monaco is smaller than New York’s ___.', 'Central Park', 'Times Square|Statue of Liberty|Grand Central Station'),
  t('Aussie Lake', 'Lake Hillier in Western Australia is naturally ___.', 'pink|bubblegum pink|pink coloured|pink colored|bright pink', 'fizzy|boiling|glow-in-the-dark'),
  t('Quick Trip', 'The world’s shortest scheduled flight, between two Scottish islands, can take under ___ minutes.', '2|1|90 seconds|a minute and a half', '5|10|15'),
  t('Nordic Village', 'There is a village in Norway called ___.', 'Hell', 'Frozen|Brrr|Snowhere'),
  t('Sister Cities', 'The town of Boring, Oregon, is officially paired with a Scottish village called ___.', 'Dull', 'Drab|Meh|Snooze'),
  t('Clock Watching', 'Russia spans ___ time zones.', '11', '7|14|9'),
  t('Down Under, Out Wide', 'Australia is wider from east to west than the ___.', 'Moon|Moon’s diameter|diameter of the Moon', 'Sahara Desert|United States|Atlantic Ocean'),
  t('Christmas Commute', 'In Caracas, it’s a tradition to travel to early Christmas church services on ___.', 'roller skates|rollerskates|skates|rollerblades|skating|roller skating|roller blades', 'stilts|camels|unicycles'),
  t('Icelandic Christmas', 'In Iceland, people traditionally give each other ___ on Christmas Eve and spend the night reading.', 'books|novels', 'puzzles|seashells|fishing rods'),
  t('Witch Proofing', 'In Norway, some families hide their ___ on Christmas Eve so witches can’t steal them.', 'brooms|broomsticks|mops', 'boots|spoons|cats'),
  t('Tree Trimmings', 'In Ukraine, some people decorate Christmas trees with artificial ___.', 'spider webs|spiderwebs|cobwebs|spiders|webs', 'fish bones|onions|teeth'),
  t('Doomed Decoration', 'Since 1966, vandals have repeatedly tried to burn down a Swedish town’s giant Christmas ___.', 'goat|straw goat|Yule goat|Gävle goat|julbock', 'reindeer|elf|snowman'),
  t('Heavy Prize', 'The winner of the Wife Carrying World Championships wins the wife’s weight in ___.', 'beer', 'cheese|gold coins|sausages'),
  t('Downhill Dash', 'Every year in Gloucestershire, people chase a wheel of ___ down a very steep hill.', 'cheese|Double Gloucester|cheese wheel|Double Gloucester cheese|Gloucester cheese', 'pork pie|haggis|Christmas pudding'),
  t('Welsh Water Sports', 'Every year in Wales, competitors race in the World ___ Snorkelling Championships.', 'Bog|peat bog', 'Puddle|Custard|Gravy'),
  t('Outback Regatta', 'Alice Springs holds a boat race on a riverbed that is almost always ___.', 'dry|empty|waterless|bone dry|dried up|sandy', 'frozen|on fire|pink'),
  t('Party for Locals', 'Every year in Lopburi, Thailand, the town throws a giant buffet for ___.', 'monkeys|macaques|the monkeys', 'stray cats|pigeons|crocodiles'),
  t('Devilish Leap', 'In a Spanish village festival, men dressed as devils leap over rows of ___.', 'babies|infants|newborns|newborn babies', 'sleeping cows|pumpkins|tortoises'),
  // ---------- space ----------
  t('Venusian Oddity', 'On Venus, a single ___ lasts longer than a whole year.', 'day|rotation|spin', 'storm|sunset|eclipse'),
  t('Space Odour', 'Astronauts say space has a smell, a bit like seared ___.', 'steak|meat|beef|metal', 'popcorn|coffee|marshmallows'),
  t('Martian Evenings', 'On Mars, sunsets look ___.', 'blue|bluish|blue-ish|blue coloured|blue colored|blueish', 'green|purple|silver'),
  t('Ringed Giant', 'Saturn is so light for its size that, in a big enough bathtub, it would ___.', 'float|bob|bob around', 'melt|fizz|dissolve'),
  t('Space Pioneers', 'The first animals deliberately sent into space, in 1947, were ___.', 'fruit flies|flies|fruitflies', 'mice|frogs|goldfish'),
  t('French Astronaut', 'In 1963, France launched a ___ named Félicette into space.', 'cat|kitten|stray cat|cat called Félicette', 'poodle|rabbit|parrot'),
  t('Insurance Policy', 'Apollo astronauts couldn’t get life insurance, so they signed ___ for their families to sell if needed.', 'autographs|envelopes|postal covers|covers|signed envelopes|autographed envelopes|first day covers', 'moon rocks|blank cheques|spacesuits'),
  t('Lucky Souvenir', 'Neil Armstrong carried a piece of the ___ with him to the Moon.', 'Wright Flyer|Wright brothers’ plane|Wright brothers’ airplane|first airplane|first aeroplane|1903 Wright Flyer|Wright brothers’ flyer|Wright plane', 'Titanic|Hindenburg|Statue of Liberty'),
  t('Moon Sports', 'In 1971, astronaut Alan Shepard played ___ on the Moon.', 'golf|golf balls|a round of golf', 'frisbee|cricket|baseball'),
  t('Pluto’s Slow Life', 'Since its discovery in 1930, Pluto has not yet completed a single ___.', 'orbit|orbit of the Sun|lap|year|trip around the Sun|lap of the Sun|orbit around the Sun|revolution', 'rotation|sunrise|day'),
  t('Ocean Riches', 'The world’s oceans hold an estimated 20 million tonnes of dissolved ___.', 'gold', 'diamonds|rubies|sapphires'),
  t('Party Gas', 'Breathing in sulfur hexafluoride makes your voice sound ___.', 'deeper|deep|lower|low|lower pitched', 'squeakier|robotic|louder'),
  t('Saturn’s Hat', 'At Saturn’s north pole there’s a giant storm shaped like a ___.', 'hexagon', 'triangle|star|square'),
  t('Drifting Apart', 'The Moon drifts about 3.8 centimetres further from Earth every ___.', 'year', 'day|month|century'),
  t('Space Cloud', 'Astronomers have found a giant cloud in space full of ___.', 'alcohol|ethyl alcohol|ethanol|booze|vinyl alcohol|methanol', 'soap bubbles|glitter|hot chocolate'),
  t('Many Mornings', 'Astronauts on the International Space Station see about ___ sunrises every day.', '16|15', '3|40|1'),
  t('Special Delivery', 'In 2001, a ___ was delivered to the International Space Station.', 'pizza|salami pizza', 'birthday cake|goldfish|love letter'),
  t('Dinosaur Timeline', 'The T. rex lived closer in time to humans than to the ___.', 'Stegosaurus|stegosaur|stegosauruses', 'Triceratops|Velociraptor|Ankylosaurus'),
  t('Mammoth News', 'Woolly mammoths still roamed an Arctic island while Egyptians were building the ___.', 'pyramids|Great Pyramid|pyramids of Giza|Great Pyramids|Great Pyramid of Giza', 'Suez Canal|Aswan Dam|Cairo Tower'),
  t('Tiny Space Survivors', 'Microscopic animals called ___ have survived being exposed to outer space.', 'tardigrades|water bears|moss piglets', 'sea monkeys|glass shrimp|dust mites'),
];

/** Adult/edgy stories: rude, gross or grim. Only in play when family mode is off. */
export const ADULT: readonly Fact[] = [
  t('Rude Renaming', 'An Austrian village tired of sign thefts over its rude name changed it in 2021 to ___.', 'Fugging', 'Fluffing|Fudging|Funking'),
  t('Guacamole Origins', 'The word “avocado” comes from an Aztec word that also meant ___.', 'testicle|testicles|balls|testes|nuts', 'green butter|tree egg|little heart'),
  t('Happy Accident', 'Viagra was originally developed to treat ___.', 'angina|chest pain|heart disease|high blood pressure|hypertension|heart problems|blood pressure|heart pain', 'hair loss|asthma|insomnia'),
  t('Bland Intentions', 'Graham crackers came from a preacher who believed bland food would curb ___.', 'lust|sexual desire|sexual urges|desire|masturbation|sex drive|libido|impure thoughts|sexual appetite|urges|carnal desire', 'laziness|gossip|snoring'),
  t('Original Recipe', 'Until the early 1900s, Coca-Cola contained small amounts of ___.', 'cocaine|coca|coca leaf|coca leaves|coke', 'whisky|opium|gunpowder'),
  t('Cough It Up', 'The drug company Bayer once sold ___ as a cough medicine, including for children.', 'heroin', 'LSD|snake venom|whisky'),
  t('Medical Endorsement', 'A 1940s advert claimed “More ___ smoke Camels than any other cigarette.”', 'doctors|physicians|docs', 'dentists|astronauts|babies'),
  t('Spice Trip', 'Eating large amounts of ___ can cause hallucinations.', 'nutmeg', 'cinnamon|paprika|oregano'),
  t('Classical Cheek', 'Mozart wrote a cheerful song for six voices called “Lick Me in the ___”.', 'Arse|ass|butt|bum|behind|backside|rear|bottom|Arsch', 'Ear|Elbow|Garden'),
  t('Fatal Attraction', 'When a male honeybee mates, his ___ snaps off and he dies.', 'genitals|penis|endophallus|privates|manhood|willy|member|genitalia|bits|reproductive organ|sex organ|organ|junk', 'wings|stinger|antennae'),
  t('Hide and Seek', 'Pearlfish hide by living inside a sea cucumber’s ___.', 'bottom|anus|butt|bum|backside|rear|rear end|behind|cloaca|bum hole|butthole|arse|ass', 'mouth|ears|shell'),
  t('Dream Job', 'Henry VIII had a servant called the Groom of the ___, who helped him on the toilet.', 'Stool|Close Stool', 'Throne|Chamber|Potty'),
  t('First Aid Gone Wrong', 'In the 1700s, doctors tried to revive drowning victims by blowing tobacco smoke up their ___.', 'bottoms|butts|bums|rectum|anus|backsides|rears|arses|asses|rear ends', 'noses|ears|sleeves'),
  t('Ancient Birth Control', 'Ancient Egyptian contraceptive recipes included ___ dung.', 'crocodile|croc', 'camel|hippo|cat'),
  t('Money Doesn’t Smell', 'The Roman emperor Vespasian put a tax on ___ collected from public toilets.', 'urine|pee|wee|piss|public urine|wee wee', 'toilet paper|sponges|graffiti'),
  t('Game Night Scandal', 'Rivals accused the game Twister of being “___ in a box”.', 'sex', 'chaos|yoga|trouble'),
  t('Founding Father’s Essay', 'Benjamin Franklin wrote an essay urging scientists to improve the smell of ___.', 'farts|flatulence|wind|farting|gas|passing gas|breaking wind', 'feet|armpits|cheese'),
  t('Souvenir', 'After Albert Einstein died, a pathologist secretly kept his ___.', 'brain', 'violin|pipe|slippers'),
  t('Science Hurts', 'Isaac Newton once poked a long needle behind his own ___ to study light.', 'eye|eyeball|eyes|eye socket', 'ear|nose|tooth'),
  t('Nativity Surprise', 'Catalan Christmas nativity scenes traditionally include a little figure who is ___.', 'pooping|defecating|pooing|doing a poo|taking a dump|going to the toilet|squatting|crapping|having a poo|shitting|taking a poo|doing a number two', 'sneezing|dancing|juggling'),
  t('Spring Festival', 'Every spring, a shrine in Kawasaki, Japan, holds a festival celebrating the ___.', 'penis|phallus|willy|genitals|steel phallus|male member', 'elbow|noodle|umbrella'),
  t('Bitter Pill', 'For centuries, Europeans swallowed powdered ___ as medicine.', 'mummies|mummy|mummy powder|Egyptian mummies|human remains|corpses|mummified bodies|human flesh|human skulls|skull', 'dragon scales|garden gnomes|old shoes'),
  t('Posing With Grandpa', 'Victorian families sometimes posed for portraits with relatives who were ___.', 'dead|deceased|recently dead|corpses|dead bodies|recently deceased|not alive', 'on stilts|upside down|underwater'),
  t('Flavour Source', 'A vanilla-like flavouring called castoreum comes from glands near a ___’s bottom.', 'beaver', 'skunk|hedgehog|otter'),
  t('Olympic Low Point', 'At the 1900 Paris Olympics, competitors shot at live ___.', 'pigeons|birds|doves', 'rabbits|chickens|ducks'),
  t('Permafrost Rules', 'In the Arctic town of Longyearbyen, people can’t be ___ there, because bodies don’t decompose.', 'buried|burried', 'naked|married|bald'),
].map(fact => ({ ...fact, adult: true as const }));

export const factPool = (family: boolean): readonly Fact[] => family ? FAMILY : [...FAMILY, ...ADULT];
