import { lazy, Suspense, useState, useEffect, useRef, useMemo } from 'react';
import { ArcadeButton, HoldButton, Modal, Panel, SteerPad, type GameClientModule, type GameViewProps } from '../../../party-ui/src/index';
import { BLOCKS, BENCH, CHEST, FURNACE, dayLength, isNight, W, H, type Action, type Command, type Input, type PrivateView, type Settings, type View } from './model';
import { readQuality, writeQuality } from './quality';
import { loadCommand, storeCommand } from './commands';
import { terrain } from './terrain';
import { changeInput, controls, resetInput } from './controls';
import { Meter, itemName } from './items';
import { loadHotbar, storeHotbar, type Hotbar } from './hotbar';
import { Slot, Workbench, type Tab } from './workbench';
import { uiSound } from './ui-sound';
import './style.css';
function IslandMap({view}:{view:View}){
 const ref=useRef<HTMLCanvasElement>(null),cache=useMemo(()=>{const base=terrain(view.seed,view.terrainVersion);return{base,grid:base.slice(),edits:new Map<number,number>(),painted:false};},[view.seed,view.terrainVersion]);
 useEffect(()=>{const next=new Map(view.edits),columns=new Set<number>();if(!cache.painted)for(let i=0;i<W*W;i++)columns.add(i);for(const [i,b]of next)if(cache.grid[i]!==b){cache.grid[i]=b;columns.add(i%(W*W));}for(const i of cache.edits.keys())if(!next.has(i)){cache.grid[i]=cache.base[i]!;columns.add(i%(W*W));}cache.edits=next;cache.painted=true;const c=ref.current!.getContext('2d')!;for(const column of columns){let y=H-1;while(y>0&&!cache.grid[column+y*W*W])y--;c.fillStyle=BLOCKS[cache.grid[column+y*W*W]!]!.color;c.fillRect(column%W,Math.floor(column/W),1,1);}},[cache,view.revision]);
 return <div className="bw-map"><canvas ref={ref} width={W} height={W} aria-label="Island map with terrain and explorer locations"/>{view.caches.map(c=><span className="bw-map-cache" key={c.id} title={`Recovery supplies: ${view.players.find(p=>p.id===c.ownerId)?.name??'explorer'}`} style={{left:`${c.x/W*100}%`,top:`${c.z/W*100}%`}}>▣</span>)}{view.players.map((p,i)=><span key={p.id} title={p.name} style={{left:`${p.x/W*100}%`,top:`${p.z/W*100}%`,background:p.color}}>{i+1}</span>)}</div>;
}
const World=lazy(()=>import('./scene'));
type Props=GameViewProps<Input,Action,View,PrivateView>;
type Filter='All'|'Smelting';
const coarse=()=>typeof matchMedia==='function'&&matchMedia('(pointer: coarse)').matches;
function Controller({publicView:v,privateView,playerId,roundId,connected}:Props){
 const [modal,setModal]=useState<'bench'|'map'|'help'|null>(null),[tab,setTab]=useState<Tab>('inventory'),[filter,setFilter]=useState<Filter>('All'),[notice,setNotice]=useState(''),[pending,setPending]=useState<Command|null>(null),[message,setMessage]=useState(''),[hurt,setHurt]=useState(false),[sneak,setSneak]=useState(false),[flash,setFlash]=useState(false),[touch]=useState(coarse),[edges,setEdges]=useState({left:false,right:false});
 const p=v.players.find(a=>a.id===playerId),inv=privateView?.inventory??{},station=privateView?.station,creative=v.mode==='creative',version=v.terrainVersion;
 const key=`blockwild.command:${roundId}:${playerId}`,hotbarKey=`blockwild.hotbar:${roundId}:${playerId}`;
 const [hotbar,setHotbar]=useState(()=>loadHotbar(hotbarKey,version,inv)),slot=hotbar.slots[hotbar.active]??0,selected=p?.selected;
 const previousHealth=useRef(p?.health),shortcut=useRef<(key:string)=>void>(()=>{}),strip=useRef<HTMLDivElement>(null),mounted=useRef(false);
 useEffect(()=>{setMessage(privateView?.message??'');const timer=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(timer);},[privateView?.message]);
 useEffect(()=>{const health=p?.health;if(health!==undefined&&previousHealth.current!==undefined&&health<previousHealth.current)setHurt(true);previousHealth.current=health;const timer=setTimeout(()=>setHurt(false),600);return()=>clearTimeout(timer);},[p?.health]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||(e.target as HTMLElement)?.closest('input,textarea,select,button,[role=dialog],dialog'))return;if(e.key.length===1&&'123456789cemr'.includes(e.key.toLowerCase())){e.preventDefault();shortcut.current(e.key.toLowerCase());}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{setPending(loadCommand(key,privateView?.commandAck??0));setNotice(privateView?.commandResult??'');return()=>{controls.input.command=null;};},[key]);
 useEffect(()=>{setHotbar(loadHotbar(hotbarKey,version,privateView?.inventory??{}));},[hotbarKey,version]);
 useEffect(()=>{if(!notice||modal)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice,modal]);
 useEffect(()=>{if(!pending)return;if((privateView?.commandAck??0)>=pending.seq){setNotice(privateView?.commandResult??'');storeCommand(key,null);setPending(null);changeInput({command:null});return;}const resend=()=>{if(connected!==false&&!document.hidden)changeInput({command:pending});};resend();const timer=setInterval(resend,200);return()=>clearInterval(timer);},[pending,privateView?.commandAck,connected,key]);
 // The scene resets controls on mount, so keep re-sending the hotbar choice until the server reports it.
 useEffect(()=>{if(selected===undefined||selected===slot||connected===false)return;changeInput({slot});const timer=setInterval(()=>changeInput({slot}),400);return()=>clearInterval(timer);},[slot,selected,connected]);
 // Briefly name the selected item and keep the active slot visible in the scrolling strip.
 useEffect(()=>{reveal();if(!mounted.current){mounted.current=true;return;}setFlash(true);const timer=setTimeout(()=>setFlash(false),1600);return()=>clearTimeout(timer);},[hotbar.active,slot]);
 // Overflow cues for the hotbar carousel: which side still hides slots.
 const measure=()=>{const el=strip.current;if(!el)return;const next={left:el.scrollLeft>2,right:el.scrollLeft+el.clientWidth<el.scrollWidth-2};setEdges(e=>e.left===next.left&&e.right===next.right?e:next);};
 const reveal=()=>{strip.current?.querySelector<HTMLElement>('[aria-pressed=true]')?.scrollIntoView({block:'nearest',inline:'nearest'});measure();};
 useEffect(()=>{measure();window.addEventListener('resize',reveal);return()=>window.removeEventListener('resize',reveal);},[]);
 // Sneak is a toggle; it must never linger after focus loss, a dialog, disconnect or unmount.
 const stance=(next:boolean)=>{setSneak(next);changeInput({sneak:next});};
 useEffect(()=>{const clear=()=>stance(false),hidden=()=>{if(document.hidden)clear();},dialog=()=>{if(document.activeElement?.closest('dialog')){resetInput();setSneak(false);}};window.addEventListener('blur',clear);window.addEventListener('resize',clear);document.addEventListener('visibilitychange',hidden);document.addEventListener('focusin',dialog);return()=>{window.removeEventListener('blur',clear);window.removeEventListener('resize',clear);document.removeEventListener('visibilitychange',hidden);document.removeEventListener('focusin',dialog);};},[]);
 useEffect(()=>{if(connected===false||modal)stance(false);},[connected,modal]);
 if(!p)return <Panel>Watching this world. Join the next world to play.</Panel>;
 const action=(a:Action)=>{if(pending||a.type==='finish')return;const command:Command={...a,seq:(privateView?.commandAck??0)+1};storeCommand(key,command);setPending(command);setNotice('');};
 // Deliberate hotbar changes only; persisted restoration goes through setHotbar directly and stays silent.
 const update=(next:Hotbar)=>{if(next.active!==hotbar.active||next.slots[next.active]!==hotbar.slots[hotbar.active])uiSound('select');setHotbar(next);storeHotbar(hotbarKey,next);changeInput({slot:next.slots[next.active]??0});};
 const setActive=(i:number)=>update({...hotbar,active:i}),pick=(id:number)=>update({...hotbar,slots:hotbar.slots.map((s,i)=>i===hotbar.active?id:s)});
 const open=(kind:'bench'|'map'|'help',t:Tab='inventory',f:Filter='All')=>{if(document.pointerLockElement)document.exitPointerLock();resetInput();setSneak(false);setTab(t);setFilter(f);setModal(kind);uiSound(t==='chest'?'chest-open':'open');};
 const chestShowing=modal==='bench'&&station?.kind===CHEST&&tab!=='inventory',close=()=>{uiSound(chestShowing?'chest-close':'close');setModal(null);},swap=(kind:'map'|'help')=>{uiSound('open');setModal(kind);};
 const useStation=()=>{if(!station)return;if(station.kind===CHEST)open('bench','chest');else if(station.kind===BENCH)open('bench','craft');else if(station.kind===FURNACE&&!station.readyAt)open('bench','craft','Smelting');else action({type:'use'});};
 shortcut.current=k=>{if(modal||connected===false)return;if(/^[1-9]$/.test(k))setActive(Number(k)-1);else if(k==='c')open('bench','craft');else if(k==='m')open('map');else if(k==='e'){if(station)useStation();else open('bench');}else if(k==='r')action({type:'eat'});};
 const quality=readQuality()==='low'?'balanced':'low',toggleQuality=()=>{if(writeQuality(quality)){resetInput();location.reload();}else setNotice('Graphics preference could not be saved in this browser.');};
 // Pushing the stick toward its rim while heading forward sprints; letting go clears movement and sprint together.
 const steer=({x,y}:{x:number;y:number})=>changeInput({x,z:y,sprint:Math.hypot(x,y)>.85&&y<-.3});
 const stationName=station?BLOCKS[station.kind]?.name??'station':'';
 return <div className="bw-controller" data-touch={touch}>
 {hurt&&<div className="bw-hurt" aria-hidden="true"/>}
 <div className="bw-message" role="status" key={notice||message}>{modal?'':notice||message}</div>
 {privateView&&privateView.air<12&&<div className="bw-air" role="status">Air {Math.ceil(privateView.air)}s · swim up</div>}
 {privateView?.recovery&&<button className="bw-recovery" onClick={()=>open('map')}>Crate · {Math.round(Math.hypot(p.x-privateView.recovery.x,p.z-privateView.recovery.z))}m</button>}
 <div className="bw-crosshair" aria-hidden="true"/><div className="bw-target">{p.target!==null&&p.progress>0&&<progress max={1} value={p.progress} aria-label="Mining progress"/>}</div>
 {touch&&<><div className="bw-stick"><SteerPad label="Move" onChange={steer}/></div>
 <div className="bw-cluster">
  {p.flying&&<div className="bw-down"><HoldButton label="Down" onChange={down=>changeInput({down})}>Down</HoldButton></div>}
  <div className="bw-jump"><HoldButton label={p.flying?'Up':'Jump'} onChange={jump=>changeInput({jump})}>{p.flying?'Up':'Jump'}</HoldButton></div>
  <div className="bw-place">{station?<button type="button" className="bw-round bw-use" aria-label={`${[CHEST,BENCH].includes(station.kind)?'Open':'Use'} ${stationName}`} disabled={!!pending} onClick={useStation}>{[CHEST,BENCH].includes(station.kind)?'Open':'Use'}</button>:<HoldButton label="Place block" onChange={place=>changeInput({place})}>Place</HoldButton>}</div>
  <div className="bw-mine"><HoldButton label="Mine / attack" onChange={mine=>changeInput({mine})}>Mine</HoldButton></div>
 </div></>}
 {!touch&&station&&<div className="bw-desk-hint">E · {[CHEST,BENCH].includes(station.kind)?'Open':'Use'} {stationName}</div>}
 <div className={`bw-selected${flash?' bw-show':''}`} aria-hidden="true">{itemName(slot)}{slot&&!creative?` · ${inv[slot]??0}`:''}</div>
 <div className="bw-vitals"><Meter value={p.health} kind="health"/><Meter value={p.food} kind="food"/></div>
 <div className="bw-bottom"><div className="bw-strip" data-left={edges.left||undefined} data-right={edges.right||undefined}><div className="bw-hotbar" aria-label="Hotbar: swipe or scroll for more slots" ref={strip} onScroll={measure} onWheel={e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX))e.currentTarget.scrollLeft+=e.deltaY;}}>{hotbar.slots.map((id,i)=><Slot key={i} id={id} index={i+1} count={id?creative?'∞':inv[id]??0:undefined} dim={!!id&&!creative&&!inv[id]} pressed={hotbar.active===i} label={`Slot ${i+1}: ${itemName(id)}${id?`, ${creative?'unlimited':inv[id]??0}`:''}`} onClick={()=>setActive(i)}/>)}</div></div>{touch&&(creative?<button type="button" className="bw-round bw-stance" aria-label={p.flying?'Land':'Fly'} aria-pressed={p.flying} onClick={()=>changeInput({fly:!p.flying})}>{p.flying?'Land':'Fly'}</button>:<button type="button" className="bw-round bw-stance" aria-label="Sneak" aria-pressed={sneak} onClick={()=>stance(!sneak)}>Sneak</button>)}<button type="button" className="bw-round bw-menu" aria-label="Items: inventory and menu" onClick={()=>open('bench')}>Items</button></div>
 {modal==='bench'&&<Workbench v={v} pv={privateView} inv={inv} hotbar={hotbar} setActive={setActive} pick={pick} pending={!!pending} status={notice||privateView?.message||''} act={action} onClose={close} tab={tab} setTab={setTab} initialFilter={filter} onHelp={()=>swap('help')} onMap={()=>swap('map')} onQuality={toggleQuality} quality={quality}/>}
 {modal==='map'&&<Modal title="Island map" onClose={close} wide><IslandMap view={v}/><p>Forests, hills, rivers and caves. Ore is scattered through the island; dig your own mine or settle anywhere.</p>{privateView?.recovery&&<p className="bw-recovery-note">Your recovery crate: {Math.floor(privateView.recovery.x)} east · {Math.floor(privateView.recovery.z)} south · {Math.floor(privateView.recovery.y)} high. Gold squares mark recovery crates.</p>}{privateView?.home&&<p>Home: {Math.floor(privateView.home.x)} east · {Math.floor(privateView.home.z)} south</p>}<p>Position: {Math.floor(p.x)} east · {Math.floor(p.z)} south · {Math.floor(p.y)} high</p></Modal>}
 {modal==='help'&&<Modal title="How Blockwild works" onClose={close}>
  <p>Blockwild is an original small survival sandbox with familiar block-game controls. It covers a focused subset: mining and placing blocks, a 9-slot hotbar, pocket 2×2 and crafting-table 3×3 recipes, furnace smelting, chests, beds, wheat farming, oak saplings, hearts and food, day and night, and hostile mobs after dark. There is no redstone, armor, enchanting, trading, or other dimensions; the world is this one island.</p>
  <h3>Touch controls</h3><ul className="bw-legend"><li><b>Mine</b>Hold to mine blocks or attack</li><li><b>Place</b>Hold to place the selected block</li><li><b>Use</b>Replaces Place when you aim at a chest, crafting table, furnace, bed or crop; reads Open for chests and tables. Tap it</li><li><b>Jump</b>Hold to jump{creative?'; reads Up while flying':''}</li>{creative?<><li><b>Fly</b>Beside Items: toggle flight; reads Land while flying</li><li><b>Down</b>Appears beside Up while flying: hold to descend</li></>:<li><b>Sneak</b>Beside Items: toggle sneaking; it switches off when you open a menu or leave the page</li>}<li><b>Items</b>Inventory, crafting, map and settings</li></ul><p>Move with the left stick; push it to the rim while heading forward to sprint. Drag anywhere in the world to look. Hearts and food sit above the hotbar. The hotbar is a carousel: about five of its nine slots show at once. Swipe it sideways, or scroll with a mouse wheel or trackpad, to reach the rest; faded edges mark hidden slots, the selected slot always scrolls into view, and keys 1–9 still pick any slot.</p>
  <h3>Keyboard and mouse</h3><p>Click the world, WASD moves, Space jumps, Ctrl sprints, Shift sneaks, left mouse mines, right mouse places. 1–9 selects a hotbar slot, E uses an aimed station or opens Inventory, C opens Craft, M opens Map, R eats, Escape releases the mouse.{creative?' F toggles flight and Q descends.':''}</p>
  <h3>Hotbar, inventory and crafting</h3><p>Choose a hotbar slot, then tap any inventory item to put it there, including tools or an empty hand. {version<4?'This older world keeps its original stack size of 999.':'Stacks hold 64; tools hold 1. The selected pickaxe decides what you can mine and a selected sword hits harder.'} The recipe book has Construction, Equipment, Items and Nature tabs, search and a Craftable filter; red cells are missing. Pocket crafting is 2×2. Stand within reach of a placed crafting table for 3×3 recipes. Smelting needs a nearby furnace. {version<4?'Each batch burns one coal or log.':'Fuel keeps burning between batches: coal or charcoal for 80 seconds, a log or plank for 15; each smelt takes 10 seconds.'} Aim at the furnace and Use to collect.</p>
  {creative?<p>Creative gives unlimited materials and flight.</p>:<p>Survival starts empty-handed: punch logs, dirt and leaves. Eat to refill food; a full food bar slowly heals. Beds set your respawn and, when every explorer rests at night, bring morning. Torches and campfires stop mobs spawning nearby. Underwater, surface before your air runs out. If you die, your items wait in a recovery crate.</p>}
  <p>The host can save, load or finish the world. The island is 128 × 128 blocks and allows 16,384 changed blocks.</p></Modal>}
 </div>;}
function Display({publicView:v}:Props){const [follow,setFollow]=useState(-1);return <div className="bw-display"><header><div><span className="bw-eyebrow">A WORLD YOU BUILD TOGETHER</span><h1>Blockwild<span>YOUR WORLD, YOUR WAY</span></h1></div><div className="bw-day"><b>{isNight(v.time,v.terrainVersion)?'☾ NIGHTFALL':'☀ DAYLIGHT'}</b><span>Seed {v.seed}</span><span>Day {Math.floor(v.time/dayLength(v.terrainVersion))+1} · {v.mode==='creative'?'Creative':'Survival'}</span>{v.sleeping>0&&<span>{v.sleeping}/{v.players.filter(p=>p.connected).length} resting</span>}</div></header><div className="bw-tv-bottom"><div className="bw-roster">{v.players.map((p,i)=><button key={p.id} aria-pressed={follow===i} onClick={()=>{setFollow(i);const c=document.querySelector<HTMLCanvasElement>('.bw-canvas');if(c)c.dataset.follow=String(i);}}><span style={{background:p.color}}>{i+1}</span><b>{p.name}</b><small>♥ {p.health} · {p.connected?'Exploring':'Away'}</small></button>)}</div><ArcadeButton size="sm" tone="ghost" onClick={()=>{setFollow(-1);const c=document.querySelector<HTMLCanvasElement>('.bw-canvas');if(c)c.dataset.follow='-1';}}>Island overview</ArcadeButton></div></div>;}
export const client:GameClientModule<Input,Action,Settings,View,PrivateView>={sceneRoles:['display','controller'],SceneView:p=><Suspense fallback={null}><World {...p}/></Suspense>,DisplayView:Display,ControllerView:Controller,SettingsView:({settings,onChange,disabled})=><div className="bw-settings"><label>World mode<select value={settings.mode??'survival'} disabled={disabled} onChange={e=>onChange({...settings,mode:e.target.value as Settings['mode']})}><option value="survival">Survival sandbox · gather, build, live</option><option value="creative">Creative sandbox · unlimited materials</option></select></label><label>Island seed<input type="number" min={0} max={999999} value={settings.seed??38471} disabled={disabled} onChange={e=>onChange({...settings,seed:Number(e.target.value)})}/></label><ArcadeButton size="sm" disabled={disabled} onClick={()=>onChange({...settings,seed:((settings.seed??38471)+1+crypto.getRandomValues(new Uint32Array(1))[0]!%999999)%1000000})}>Surprise me</ArcadeButton><p>Each player explores in first person. New worlds have natural forests, rivers, hills and caves. Survival has a 20-minute day/night cycle and no session time limit. The host saves or finishes when you're ready.</p></div>,InstructionsView:()=> <><h2>Make this island your own.</h2><p>Survival is a world to live in, with no quests, required steps or finish line. Mine, build a home, craft tools at a crafting table, smelt in a furnace, farm wheat and survive the night together. Creative is also available with unlimited blocks and flight.</p><p>Touch: left stick moves (push to the rim to sprint), drag the world to look, hold Mine or Place. The Items button opens inventory, crafting and the map. Desktop: click the world, WASD, Space, Ctrl sprint, Shift sneak, left/right mouse, 1–9 hotbar, E inventory, C craft. Escape releases your mouse.</p></>,ResultsView:({publicView:v})=><Panel className="bw-results"><p className="bw-eyebrow">WORLD JOURNAL</p><h1>Your world, your way.</h1><p>Seed {v.seed} · {v.mode==='survival'?'Survival':'Creative'}</p><p>{v.mined} resources gathered · {v.built} blocks built · {Math.floor(v.time/60)} minutes exploring</p><div className="bw-results-roster">{v.players.map(p=><div key={p.id}><b>{p.name}</b><span>{p.mined} gathered · {p.built} built</span></div>)}</div><p>Play again creates a fresh island. Load a saved world from the host controls to return to your build.</p></Panel>,prepare(){},dispose(){resetInput();}};
export default client;
