import { useEffect, useRef, useState } from 'react';
import { BoxGeometry, Color, DirectionalLight, EdgesGeometry, Fog, Group, HemisphereLight, LineBasicMaterial, LineSegments, InstancedMesh, Object3D, Mesh, MeshBasicMaterial, MeshLambertMaterial, PerspectiveCamera, PointLight, PlaneGeometry, Scene, Sprite, SpriteMaterial, CanvasTexture, Vector3 } from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { miningTier } from './bedrock';
import { BlockwildAudio } from './audio';
import { HostMusic } from './host-music';
import { mountThreeScene, type SceneMetrics } from '../../../party-3d/src/index';
import { ResourceScope } from '../../../party-runtime/src/index';
import type { SceneViewProps } from '../../../party-ui/src/index';
import { BLOCKS, isWorldBlock, TORCH, SWORD, WOOD_SWORD, STONE_SWORD, CAMPFIRE, CHUNK, W, coords, neutral, dayLength, type PrivateView, type Settings, type View } from './model';
import { terrain, ray } from './terrain';
import { ATLAS_TILES, atlas, chunkGeometry, makeChunks, waterGeometry } from './meshes';
import { readQuality } from './quality';
import { changeInput, controls, resetInput } from './controls';
export default function World(props:SceneViewProps<Settings,View,PrivateView>) {
 const canvas=useRef<HTMLCanvasElement>(null),latest=useRef(props);latest.current=props;const [metrics,setMetrics]=useState<SceneMetrics|null>(null),[locked,setLocked]=useState(false),[targetName,setTargetName]=useState(''),[touch]=useState(()=>matchMedia('(pointer: coarse)').matches);
 useEffect(()=>{
  const scope=new ResourceScope(props.signal),scene=new Scene(),first=props.viewRole==='controller',camera=new PerspectiveCamera(first?76:45,1,.05,300),quality=readQuality();scene.background=new Color('#abcfd0');scene.fog=new Fog('#abcfd0',first?(quality==='low'?45:65):130,first?180:300);
  const audio=first?new BlockwildAudio(scope):null,music=props.isHost?new HostMusic(scope):null;
  const ambient=new HemisphereLight('#fff0dc','#607658',2),sun=new DirectionalLight('#fff1ce',2.2);sun.position.set(-20,45,10);scene.add(ambient,sun);
  const root=new Group();scene.add(root);let grid=terrain(props.settings.seed??38471,props.settings.terrainVersion??4),seed=props.settings.seed??38471,revision=-1,previousEdits=new Map<number,number>();const tex=scope.own(atlas()),mat=scope.own(new MeshLambertMaterial({map:tex,vertexColors:true,alphaTest:.5}));const chunks=makeChunks(root,grid,mat);scope.defer(()=>chunks.forEach(m=>m.geometry.dispose()));
  const box=scope.own(new BoxGeometry(1,1,1));const material=(color:string)=>scope.own(new MeshLambertMaterial({color}));
  const waterMat=scope.own(new MeshLambertMaterial({color:'#43a4b8',transparent:true,opacity:.86})),water=new Mesh(waterGeometry(grid),waterMat);scope.defer(()=>water.geometry.dispose());scene.add(water);for(const [x,z,w,d]of [[-40,W/2,80,W+160],[W+40,W/2,80,W+160],[W/2,-40,W,80],[W/2,W+40,W,80]]){const sea=new Mesh(scope.own(new PlaneGeometry(w,d)),waterMat);sea.rotation.x=-Math.PI/2;sea.position.set(x,6.82,z);scene.add(sea);}
  const sunMat=scope.own(new MeshBasicMaterial({color:'#ffe9a3',transparent:true})),sunDisc=new Mesh(box,sunMat),moonMat=scope.own(new MeshBasicMaterial({color:'#dfeaf8',transparent:true,opacity:0})),moon=new Mesh(box,moonMat);moon.scale.setScalar(3);moon.position.set(105,65,35);scene.add(moon);sunDisc.scale.set(5,5,5);sunDisc.position.set(-20,48,-35);scene.add(sunDisc);
  const clouds:Mesh[]=[];for(let i=0;i<12;i++){const cloud=new Mesh(box,material('#dce5df'));cloud.scale.set(10+(i%3)*4,.7,7);cloud.position.set((i*29)%180-25,55+(i%4)*3,(i*47)%170-20);scene.add(cloud);clouds.push(cloud);}
  const outline=new LineSegments(scope.own(new EdgesGeometry(box)),scope.own(new LineBasicMaterial({color:'#fff6dc',transparent:true,opacity:.95,depthTest:true})));outline.scale.setScalar(1.005);scene.add(outline);outline.visible=false;
  const actors=new Map<string,Group>();for(const [i,p]of props.players.entries()){const g=new Group(),body=new Mesh(box,material(p.color));body.scale.set(.52,.7,.3);body.position.y=.88;const head=new Mesh(box,material('#e4bb8d'));head.scale.set(.42,.42,.42);head.position.y=1.48;g.add(body,head);for(const x of [-.15,.15]){const leg=new Mesh(box,material('#364958'));leg.scale.set(.2,.52,.25);leg.position.set(x,.27,0);g.add(leg);}const label=document.createElement('canvas');label.width=256;label.height=64;const c=label.getContext('2d')!;c.fillStyle='#163b3d';c.fillRect(0,4,256,56);c.fillStyle='#fff6e5';c.font='bold 26px sans-serif';c.textAlign='center';c.fillText(`${i+1} · ${p.name}`,128,43);const badge=new Sprite(scope.own(new SpriteMaterial({map:scope.own(new CanvasTexture(label)),depthTest:false})));badge.position.y=2;badge.scale.set(2,.5,1);g.add(badge);scene.add(g);actors.set(p.id,g);}
  let gpuReady=false,assetsReady=false;const ready=()=>{if(gpuReady&&assetsReady&&!scope.signal.aborted)latest.current.onReady();};
  const mobModels=new Map<string,Group>(),loader=new GLTFLoader();
  void Promise.all(['zombie','skeleton','spider','creeper'].map(async kind=>{const asset=await loader.loadAsync(`/games/blockwild/models/${kind}.glb`);asset.scene.traverse(node=>{if(node instanceof Mesh){scope.own(node.geometry);for(const m of Array.isArray(node.material)?node.material:[node.material])scope.own(m);}});if(!scope.signal.aborted)mobModels.set(kind,asset.scene);})).then(()=>{assetsReady=true;ready();}).catch(error=>{if(!scope.signal.aborted)latest.current.onError(error);});
  const enemies=new Map<number,Group>(),crates=new Map<string,Mesh>(),enemyMat=material('#76528e'),eyeMat=scope.own(new MeshBasicMaterial({color:'#ffbc68'})),cacheMat=material('#ebbd64'),fuseMat=scope.own(new MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.35,depthWrite:false}));
  const texturedBox=(tile:number)=>{const geometry=scope.own(box.clone()),uv=geometry.getAttribute('uv');for(let i=0;i<uv.count;i++)uv.setX(i,(tile+.005+uv.getX(i)*.99)/ATLAS_TILES);return geometry;},toolMat=scope.own(new MeshLambertMaterial({map:tex}));
  const tool=new Group(),hand=new Mesh(box,material('#e4bb8d')),handle=new Mesh(texturedBox(4),toolMat),head=new Mesh(texturedBox(4),toolMat),tip=new Mesh(texturedBox(4),toolMat),heads=[4,4,3,34,9].map(texturedBox);handle.scale.set(.075,.6,.075);head.scale.set(.42,.09,.09);head.position.y=.27;tip.scale.set(.08,.16,.09);tip.position.set(-.19,.22,0);hand.scale.set(.14,.2,.18);hand.position.set(.02,-.07,0);const heldBlock=new Mesh(box,toolMat),blockHeads=BLOCKS.map((_,id)=>texturedBox(id));heldBlock.scale.setScalar(.36);heldBlock.position.set(0,.12,0);tool.add(handle,head,tip,hand,heldBlock);camera.add(tool);tool.scale.setScalar(.72);tool.position.set(.48,-.53,-1.2);tool.rotation.z=-.3;tool.visible=first;scene.add(camera);
  const lights=quality==='low'?[]:Array.from({length:4},()=>{const light=new PointLight('#ffbb66',0,10,1.5);scene.add(light);return light;});let emitters:{x:number;y:number;z:number;kind:number}[]=[],lightAt=-1,beacon:{x:number;y:number;z:number}|null=null,label='',swing=0;

  const chips=new InstancedMesh(box,material('#ffffff'),24),chipDummy=new Object3D(),particles=Array.from({length:24},()=>({x:0,y:-100,z:0,vx:0,vy:0,vz:0,life:0,color:'#ffffff'}));scope.own(chips);chips.frustumCulled=false;scene.add(chips);let chipNext=0;const beam=new Mesh(box,scope.own(new MeshBasicMaterial({color:'#a5ffe3',transparent:true,opacity:.25,depthWrite:false})));beam.visible=false;beam.scale.set(1,22,1);scene.add(beam);
  const marker=(text:string,x:number,y:number,z:number)=>{const label=document.createElement('canvas');label.width=512;label.height=96;const c=label.getContext('2d')!;c.fillStyle='#173e3ee8';c.fillRect(0,4,512,88);c.fillStyle='#ffe0a0';c.font='bold 36px sans-serif';c.textAlign='center';c.fillText(text,256,60);const sprite=new Sprite(scope.own(new SpriteMaterial({map:scope.own(new CanvasTexture(label)),depthTest:true})));sprite.position.set(x,y,z);sprite.scale.set(5,.94,1);scene.add(sprite);};if((props.settings.terrainVersion??4)<3){marker('COPPER MINE ↓',64,12,57);marker('SUNWELL CAMP',67,12,66);marker('CRYSTAL GROTTO',64,7,42);marker('FROSTWATCH',64,25,15);marker('DUNE TEMPLE',112,25,64);marker('PINE SANCTUARY',15,25,64);marker('SOUTHERN RUINS',64,25,112);}
  const crops=new InstancedMesh(box,material('#b8be54'),384),cropDummy=new Object3D(),cropColor=new Color();crops.frustumCulled=false;scene.add(crops);scope.own(crops);
  const furnaceGlow=new InstancedMesh(box,scope.own(new MeshBasicMaterial({color:'#ffac43'})),32);furnaceGlow.frustumCulled=false;scene.add(furnaceGlow);scope.own(furnaceGlow);
  const arrows=new InstancedMesh(box,material('#bfa988'),40),arrowDummy=new Object3D(),explosions=new InstancedMesh(box,scope.own(new MeshBasicMaterial({color:'#ffdba6',wireframe:true,transparent:true,opacity:.6})),20);scope.own(arrows);scope.own(explosions);arrows.frustumCulled=explosions.frustumCulled=false;scene.add(arrows,explosions);
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const position=new Vector3(64.5,10.55,66.5),keys=new Set<string>();let initialized=false,lookPointer:number|null=null,lastX=0,lastY=0;
  if(first){controls.input=neutral();controls.publish=input=>latest.current.setInput(input);controls.release=()=>latest.current.releaseInput();const update=()=>changeInput({x:Number(keys.has('d'))-Number(keys.has('a')),z:Number(keys.has('s'))-Number(keys.has('w')),jump:keys.has(' '),down:keys.has('q'),sprint:keys.has('control'),sneak:keys.has('shift')});scope.listen(window,'keydown',e=>{const event=e as KeyboardEvent;if((event.target as HTMLElement)?.closest('input,select,textarea,button,[role=dialog]'))return;const k=event.key.toLowerCase();if(k==='f'&&!event.repeat){changeInput({fly:!controls.input.fly});return;}if(['w','a','s','d',' ','q','shift','control'].includes(k)){event.preventDefault();keys.add(k);update();}});scope.listen(window,'keyup',e=>{if(keys.delete((e as KeyboardEvent).key.toLowerCase()))update();});scope.listen(document,'focusin',()=>{if(document.activeElement!==canvas.current&&keys.size){keys.clear();update();}});const reset=()=>{keys.clear();lookPointer=null;resetInput();};scope.listen(window,'blur',reset);scope.listen(window,'resize',reset);scope.listen(document,'visibilitychange',reset);scope.listen(document,'pointerlockchange',()=>{setLocked(document.pointerLockElement===canvas.current);reset();});scope.listen(document,'mousemove',e=>{if(document.pointerLockElement===canvas.current){const event=e as MouseEvent;changeInput({yaw:wrap(controls.input.yaw-event.movementX*.0025),pitch:clamp(controls.input.pitch-event.movementY*.0025)});}});scope.listen(canvas.current!,'pointerdown',e=>{const event=e as PointerEvent;canvas.current!.focus();if(event.pointerType==='mouse'){if(document.pointerLockElement!==canvas.current){void canvas.current?.requestPointerLock();return;}changeInput(event.button===2?{place:true}:{mine:true});}else{lookPointer=event.pointerId;lastX=event.clientX;lastY=event.clientY;canvas.current!.setPointerCapture(event.pointerId);}});scope.listen(canvas.current!,'pointermove',e=>{const event=e as PointerEvent;if(event.pointerId===lookPointer){changeInput({yaw:wrap(controls.input.yaw-(event.clientX-lastX)*.006),pitch:clamp(controls.input.pitch-(event.clientY-lastY)*.006)});lastX=event.clientX;lastY=event.clientY;}});const release=(e:Event)=>{const event=e as PointerEvent;if(event.pointerId===lookPointer)lookPointer=null;if(event.pointerType==='mouse'&&document.pointerLockElement===canvas.current)changeInput(event.button===2?{place:false}:{mine:false});};scope.listen(window,'pointerup',release);scope.listen(canvas.current!,'pointercancel',release);scope.listen(canvas.current!,'lostpointercapture',release);scope.listen(canvas.current!,'contextmenu',e=>e.preventDefault());scope.defer(()=>{reset();controls.publish=()=>{};controls.release=()=>{};if(document.pointerLockElement===canvas.current)document.exitPointerLock();});}
  scope.defer(()=>{scene.clear();});
  mountThreeScene(canvas.current!,{signal:scope.signal,scene,camera,quality,resize(aspect){camera.aspect=aspect;camera.updateProjectionMatrix();},frame(now,dt){
    const v=latest.current.publicView;
    if(v&&(v.revision!==revision||v.seed!==seed)){const dirty=new Set<string>();let waterDirty=false;if(v.seed!==seed||v.revision<revision){grid=terrain(v.seed,v.terrainVersion);seed=v.seed;waterDirty=true;chunks.forEach((_,k)=>dirty.add(k));}const currentEdits=new Map(v.edits),changes=[...v.edits];if([...previousEdits.keys()].some(i=>!currentEdits.has(i))){const base=terrain(v.seed,v.terrainVersion);for(const i of previousEdits.keys())if(!currentEdits.has(i))changes.push([i,base[i]!]);}previousEdits=currentEdits;for(const [i,b]of changes){if(grid[i]===b)continue;if(b===6||grid[i]===6||grid[i-W*W]===6)waterDirty=true;if(b===0&&!reduced){const p=coords(i);for(let n=0;n<4;n++){const chip=particles[chipNext++%particles.length]!;Object.assign(chip,{x:p.x+.5,y:p.y+.5,z:p.z+.5,vx:(n%2?1:-1)*1.3,vy:2+n*.2,vz:(n<2?1:-1)*1.3,life:.65,color:BLOCKS[grid[i]!]!.color});}}grid[i]=b;const p=coords(i);for(const [x,z]of [[p.x,p.z],[p.x-1,p.z],[p.x+1,p.z],[p.x,p.z-1],[p.x,p.z+1]])if(x>=0&&z>=0&&x<W&&z<W)dirty.add(`${Math.floor(x/CHUNK)},${Math.floor(z/CHUNK)}`);}for(const key of dirty){const mesh=chunks.get(key);if(mesh){const [x,z]=key.split(',').map(Number);mesh.geometry.dispose();mesh.geometry=chunkGeometry(grid,x!,z!);}}if(waterDirty){water.geometry.dispose();water.geometry=waterGeometry(grid);}revision=v.revision;const b=v.edits.find(([,kind])=>kind===13);beacon=b?coords(b[0]):null;emitters=v.edits.filter(([,kind])=>[12,13,TORCH,CAMPFIRE].includes(kind)).map(([i,kind])=>({...coords(i),kind}));}
    audio?.update(v,grid,props.playerId,latest.current.connected,controls.input.yaw);
    music?.update(v?.time,latest.current.connected);
    particles.forEach((p,i)=>{p.life=Math.max(0,p.life-dt);p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=8*dt;chipDummy.position.set(p.x,p.y,p.z);chipDummy.scale.setScalar(p.life>0?.09:0);chipDummy.updateMatrix();chips.setMatrixAt(i,chipDummy.matrix);chips.setColorAt(i,cropColor.set(p.color));});chips.instanceMatrix.needsUpdate=true;if(chips.instanceColor)chips.instanceColor.needsUpdate=true;
    crops.count=(v?.farms.length??0)*3;for(const [i,f]of (v?.farms??[]).entries()){const c=coords(f.i),growth=Math.max(.15,Math.min(1,1-(f.readyAt-(v?.time??0))/180));for(let stem=0;stem<3;stem++){cropDummy.position.set(c.x+.25+stem*.23,c.y+1+growth*.35,c.z+.3+(stem%2)*.35);cropDummy.scale.set(.12,growth*.7,.12);cropDummy.updateMatrix();crops.setMatrixAt(i*3+stem,cropDummy.matrix);crops.setColorAt(i*3+stem,cropColor.set(growth>=1?'#dfbd56':'#77a54a'));}}crops.instanceMatrix.needsUpdate=true;if(crops.instanceColor)crops.instanceColor.needsUpdate=true;
    furnaceGlow.count=0;for(const f of v?.furnaces??[])if(f.readyAt>v!.time){const c=coords(f.i);cropDummy.position.set(c.x+.5,c.y+.4,c.z+1.005);cropDummy.scale.set(.42,.25,.015);cropDummy.updateMatrix();furnaceGlow.setMatrixAt(furnaceGlow.count++,cropDummy.matrix);}furnaceGlow.instanceMatrix.needsUpdate=true;
    beam.visible=!!beacon;if(beacon)beam.position.set(beacon.x+.5,beacon.y+11,beacon.z+.5);
    const t=v?.time??0,night=Math.max(0,Math.sin((t/dayLength(v?.terrainVersion??4)-.45)*Math.PI*2));const sky=new Color('#abcfd0').lerp(new Color('#172942'),night*.9);scene.background=sky;(scene.fog as Fog).color.copy(sky);ambient.intensity=2-night*1.3;sun.intensity=2.2-night*1.9;sunMat.opacity=1-night;moonMat.opacity=night;for(const cloud of clouds){cloud.visible=first;if(!reduced)cloud.position.x=(cloud.position.x+dt*.18+40)%210-40;}
    if(now-lightAt>500){lightAt=now;const active=[...emitters,...(v?.furnaces??[]).filter(f=>f.readyAt>(v?.time??0)).map(f=>({...coords(f.i),kind:29}))].sort((a,b)=>camera.position.distanceToSquared(new Vector3(a.x,a.y,a.z))-camera.position.distanceToSquared(new Vector3(b.x,b.y,b.z)));lights.forEach((light,i)=>{const at=active[i];light.userData.active=!!at;if(at){light.position.set(at.x+.5,at.y+1.2,at.z+.5);light.color.set(at.kind===13?'#83eee0':'#ffbb66');}});}for(const light of lights)light.intensity=light.userData.active?1+night*7:0;
    if(first){const p=v?.players.find(a=>a.id===props.playerId);if(p){if(!initialized){position.set(p.x,p.y+1.55,p.z);controls.input.yaw=p.yaw;controls.input.pitch=p.pitch;initialized=true;}const next=new Vector3(p.x,p.y+(p.sneaking?1.35:1.55),p.z);if(position.distanceTo(next)>8)position.copy(next);else position.lerp(next,Math.min(1,dt*18));}camera.position.copy(position);camera.rotation.order='YXZ';camera.rotation.y=controls.input.yaw;camera.rotation.x=controls.input.pitch;const hit=ray(grid,position.x,position.y,position.z,controls.input.yaw,controls.input.pitch);outline.visible=!!hit;if(hit)outline.position.set(hit.x+.5,hit.y+.5,hit.z+.5);const name=hit?`${BLOCKS[grid[hit.i]!]!.name}${p&&v?.mode==='survival'&&(v.terrainVersion===4?miningTier(grid[hit.i]!):BLOCKS[grid[hit.i]!]!.tier)>p.tier?' · stronger pick needed':''}`:'';if(name!==label){label=name;setTargetName(name);}outline.material.opacity=.65+(p?.progress??0)*.35;outline.material.color.set(p?.progress?'#ffd184':'#fff6dc');if(controls.input.mine&&!reduced)swing=(swing+dt*3)%1;else swing=0;const arc=Math.sin(Math.PI*swing);tool.rotation.z=-.3-arc*.45;tool.rotation.x=-arc*.35;tool.position.y=-.53+(!reduced&&(controls.input.x||controls.input.z)?Math.sin(now*.009)*.012:0);heldBlock.visible=!!p&&p.selected>0&&isWorldBlock(p.selected)&&(latest.current.privateView?.inventory[p.selected]??0)>0;if(heldBlock.visible)heldBlock.geometry=blockHeads[p!.selected]!;const sword=!!p&&[SWORD,WOOD_SWORD,STONE_SWORD].includes(p.selected);handle.visible=head.visible=!!p?.tier||sword;tip.visible=!!p?.tier&&!sword;hand.visible=!p?.tier&&!sword;head.scale.set(sword?.09:.42,sword?.55:.09,.09);head.geometry=tip.geometry=heads[sword?(p?.selected===SWORD?3:p?.selected===STONE_SWORD?2:1):p?.tier??0]!;}

    else{const follow=Number(canvas.current?.dataset.follow??-1),p=v?.players[follow];if(p){camera.position.lerp(new Vector3(p.x,p.y+1.55,p.z),Math.min(1,dt*18));camera.lookAt(p.x-Math.sin(p.yaw)*Math.cos(p.pitch),p.y+1.55+Math.sin(p.pitch),p.z-Math.cos(p.yaw)*Math.cos(p.pitch));}else{const angle=reduced?.72:t*.007+.72;camera.position.lerp(new Vector3(64+Math.sin(angle)*140,135,64+Math.cos(angle)*140),Math.min(1,dt*2));camera.lookAt(64,10,64);} }
    actors.forEach((g,id)=>{const p=v?.players.find(a=>a.id===id);const watched=v?.players[Number(canvas.current?.dataset.follow??-1)]?.id;g.visible=!!p&&(first?id!==props.playerId:id!==watched);if(p){g.position.lerp(new Vector3(p.x,p.y,p.z),Math.min(1,dt*18));g.rotation.y=p.yaw;g.children[g.children.length-1]!.visible=camera.position.distanceTo(g.position)>3;}});
    for(const c of v?.creatures??[]){let g=enemies.get(c.id);if(!g){
      if(c.kind){const template=mobModels.get(c.kind);if(!template)continue;g=template.clone(true);g.traverse(node=>{if(node.name.startsWith('leg')||node.name.startsWith('arm'))node.userData.rest=node.rotation.clone();});}
      else{g=new Group();const body=new Mesh(box,enemyMat);body.scale.set(.8,.65,.7);body.position.y=.4;g.add(body);for(const x of [-.22,.22]){const eye=new Mesh(box,eyeMat);eye.scale.set(.13,.13,.08);eye.position.set(x,.55,-.36);g.add(eye);}}
      if(c.kind==='creeper'){const glow=new Mesh(box,fuseMat);glow.position.y=.87;glow.scale.set(.65,1.76,.6);glow.visible=false;g.add(glow);g.userData.fuseGlow=glow;}scene.add(g);enemies.set(c.id,g);g.position.set(c.x,c.y,c.z);}
      const walking=g.position.distanceToSquared(new Vector3(c.x,c.y,c.z))>.0005;g.position.lerp(new Vector3(c.x,c.y,c.z),Math.min(1,dt*18));g.rotation.y=c.yaw??0;
      if(!reduced)g.traverse(node=>{const rest=node.userData.rest;if(rest){const phase=node.name.includes('left')||node.name.includes('_0')||node.name.includes('_2')?0:Math.PI;node.rotation.x=rest.x+(walking?Math.sin(now*.008+phase)*.35:0);}});
      g.scale.setScalar((!reduced&&c.hitAt>0&&v!.time-c.hitAt<.18?1.08:1)+(c.fuse??0)*.06);
      if(g.userData.fuseGlow)g.userData.fuseGlow.visible=(c.fuse??0)>.15&&(reduced||Math.sin(now*.02+(c.fuse??0)*8)>0);g.visible=true;
    }enemies.forEach((g,id)=>{if(!v?.creatures.some(c=>c.id===id)){scene.remove(g);enemies.delete(id);}});
    arrows.count=v?.projectiles?.length??0;for(const [i,a]of (v?.projectiles??[]).entries()){arrowDummy.position.set(a.x,a.y,a.z);arrowDummy.quaternion.setFromUnitVectors(new Vector3(0,1,0),new Vector3(a.vx,a.vy,a.vz).normalize());arrowDummy.scale.set(.035,.65,.035);arrowDummy.updateMatrix();arrows.setMatrixAt(i,arrowDummy.matrix);}arrows.instanceMatrix.needsUpdate=true;
    explosions.count=v?.blasts?.length??0;for(const [i,b]of (v?.blasts??[]).entries()){arrowDummy.position.set(b.x,b.y,b.z);arrowDummy.rotation.set(0,0,0);arrowDummy.scale.setScalar(Math.max(.01,(v!.time-b.at)*5));arrowDummy.updateMatrix();explosions.setMatrixAt(i,arrowDummy.matrix);}explosions.instanceMatrix.needsUpdate=true;
    for(const c of v?.caches??[]){let mesh=crates.get(c.id);if(!mesh){mesh=new Mesh(box,cacheMat);mesh.scale.setScalar(.65);scene.add(mesh);crates.set(c.id,mesh);}mesh.position.set(c.x,c.y+.4,c.z);}crates.forEach((g,id)=>{if(!v?.caches.some(c=>c.id===id)){scene.remove(g);crates.delete(id);}});
  },onReady:()=>{gpuReady=true;ready();},onError:e=>latest.current.onError(e),onMetrics:setMetrics});
  return scope.dispose;
 },[props.roundId,props.signal]);
 return <><canvas ref={canvas} className="bw-canvas" tabIndex={0} aria-label={props.viewRole==='controller'?'Blockwild first-person world: drag to look':'Blockwild island overview'} data-follow={-1}/>{props.viewRole==='controller'&&targetName&&<div className="bw-aim-label">{targetName}</div>}{props.viewRole==='controller'&&<div className="bw-lock-hint">{touch?'Drag the world to look · left thumb to move':locked?'WASD · Space jump · 1–9 hotbar · Ctrl sprint · Shift sneak · E inventory · C craft · R eat · Esc release':'Click world to look around · WASD to move'}</div>}<details className="bw-metrics" hidden={!new URLSearchParams(location.search).has('metrics')}><summary>Performance</summary><pre data-testid="blockwild-metrics">{metrics?JSON.stringify(metrics,null,2):'Warming world…'}</pre></details></>;
}
const wrap=(n:number)=>((n+Math.PI*3)%(Math.PI*2))-Math.PI;
const clamp=(n:number)=>Math.max(-1.45,Math.min(1.45,n));
