import { emitSound, SOUND_AGE, type SoundState } from './sound-events';
import type { GameRules } from '../../../party-contract/src/index';
import { BLOCKS, SAPLING, TORCH, recipesFor, paletteFor, stackLimit, selectable, type Projectile, type Blast, BERRIES, TOOL, BENCH, FURNACE, FARMLAND, CAMPFIRE, SEEDS, IRON_PICK, SWORD, isTool, isWorldBlock, isNight, parseCommand, type Homestead, type TerrainVersion, EDIT_LIMIT, PLAYER_RADIUS, CACHE_ITEM_LIMIT, H, ITEMS, PALETTE, W, coords, index, neutral, solid, type Action, type Cache, type Creature, type Input, type Player, type PrivateView, type Settings, type View } from './model';
import { addDrops, attackDamage, drops, growSaplings, miningTier, selectedTier } from './bedrock';
import { tickMobs, mobLoot } from './mobs';
import { block, fits, hash, ray, terrain } from './terrain';
import { bedSpawn, canRemove, homesteadAction, nearby, readHomestead, sleepTick, startSmelting, stationView } from './survival';
export type Actor = Player & { home:{x:number;y:number;z:number;bed:number}|null;air:number;regen:number;sleeping:boolean; inventory: Record<number,number>; vy:number; grounded:boolean; cooldown:number; targetBlock:number; lastJump:boolean; hunger:number; hurtUntil:number; commandAck:number; commandResult:string; };
export type State = Homestead & SoundState & { seed:number; terrainVersion:TerrainVersion; mode:Settings['mode']; grid:Uint8Array; base:Uint8Array; edits:Map<number,number>; revision:number; players:Actor[]; creatures:Creature[]; projectiles:Projectile[]; blasts:Blast[]; caches:Cache[]; time:number; beacon:boolean; complete:boolean; spawnClock:number; nextCreature:number; };
const initialInventory = (mode:Settings['mode'],version:TerrainVersion=2):Record<number,number> => mode==='survival'?(version>=3?{}:{[BERRIES]:5}):Object.fromEntries((version<4?[...PALETTE,TOOL,TOOL+1,TOOL+2,BERRIES,IRON_PICK,SWORD,SEEDS]:ITEMS.map((_,id)=>id).filter(id=>selectable(id)&&![0,13,26,42].includes(id))).map(id=>[id,stackLimit(version,id)]));
function spawn(s:State,p:Actor,i:number) { p.x=64.5+[0,-1,1,-2,2][i%5]!*1.1;p.z=66.5+Math.floor(i/5)*1.25;p.y=9;
  if(s.terrainVersion>=3){p.y=H-2;while(p.y>1&&[0,6].includes(block(s.grid,p.x,p.y-1,p.z)))p.y--;const home=p.home?bedSpawn(s,p.home.bed):null;if(home)Object.assign(p,home);}
  if(!fits(s.grid,p.x,p.y,p.z)||!solid(block(s.grid,p.x,p.y-1,p.z))) {let found=false;for(let r=0;r<=10&&!found;r++)for(let dx=-r;dx<=r&&!found;dx++)for(let dz=-r;dz<=r&&!found;dz++)for(let y=H;y>=1;y--){const x=64.5+dx,z=64.5+dz;if(fits(s.grid,x,y,z)&&solid(block(s.grid,x,y-1,z))&&block(s.grid,x,y,z)!==6){p.x=x;p.y=y;p.z=z;found=true;break;}}}
  p.vy=0;p.grounded=false;p.yaw=0;p.pitch=0;p.target=null;p.progress=0; }
function setBlock(s:State,i:number,value:number) { if(value!==s.base[i]&&!s.edits.has(i)&&s.edits.size>=EDIT_LIMIT) return false; s.grid[i]=value;if(value===s.base[i])s.edits.delete(i);else s.edits.set(i,value);s.revision++;return true; }
function tier(s:State,p:Actor) { if(s.terrainVersion===4)return selectedTier(p);return p.inventory[IRON_PICK]?4:p.inventory[TOOL+2]?3:p.inventory[TOOL+1]?2:p.inventory[TOOL]?1:0; }
function say(p:Actor,text:string) { p.message=text; }
function hurt(s:State,p:Actor,damage:number) {
  if(s.mode==='creative'||s.time<p.hurtUntil)return;p.health=Math.max(0,p.health-damage);p.hurtUntil=s.time+1;emitSound(s,p.health?'hurt':'death',p,{playerId:p.id});if(p.health)return;
  const items:Record<number,number>={};for(const cache of s.caches)if(cache.owner===p.id)Object.assign(items,cache.items);
  for(const [key,n]of Object.entries(p.inventory))if((s.terrainVersion>=3||(!isTool(Number(key))&&Number(key)!==BERRIES))&&n){const item=Number(key),moved=Math.min(n,CACHE_ITEM_LIMIT-(items[item]??0));items[item]=(items[item]??0)+moved;p.inventory[item]=n-moved;}
  if(Object.keys(items).length){s.caches=s.caches.filter(c=>c.owner!==p.id);s.caches.push({id:`${p.id}-${s.time}`,owner:p.id,x:p.x,y:p.y,z:p.z,items});}
  p.tier=tier(s,p);spawn(s,p,s.players.indexOf(p));p.health=8;p.food=Math.max(5,p.food);p.air=12;p.sleeping=false;say(p,p.home&&bedSpawn(s,p.home.bed)?'Back home. Your dropped supplies wait in your recovery crate.':'Respawned. Your dropped supplies wait in your recovery crate.');
}
export function craft(s:State,p:Actor,id:string) {
  const recipe=recipesFor(s.terrainVersion).find(r=>r.id===id);if(!recipe)throw new Error('Unknown recipe.');
  if(s.mode!=='creative'){
    if(isTool(recipe.item)&&p.inventory[recipe.item])throw new Error('You already have this tool.');
    if(s.terrainVersion>=3&&recipe.station===FURNACE){startSmelting(s,p,recipe);return;}
    if(s.terrainVersion>=3&&recipe.station===BENCH&&nearby(s,p,BENCH)===null)throw new Error('Place a crafting table nearby for this recipe.');
    if((p.inventory[recipe.item]??0)+recipe.count>stackLimit(s.terrainVersion,recipe.item))throw new Error(`Make room for ${recipe.count} ${ITEMS[recipe.item]} before crafting.`);
    for(const [key,n]of Object.entries(recipe.costs))if((p.inventory[Number(key)]??0)<n)throw new Error(`Need ${n} ${ITEMS[Number(key)]}.`);
    for(const [key,n]of Object.entries(recipe.costs))p.inventory[Number(key)]-=n;
  }
  p.inventory[recipe.item]=Math.min(stackLimit(s.terrainVersion,recipe.item),(p.inventory[recipe.item]??0)+recipe.count);p.tier=tier(s,p);say(p,`Crafted ${recipe.name}.`);emitSound(s,'craft',p);
}
export function growTree(s:State,p:Actor){
  if(s.terrainVersion===4){const hit=ray(s.grid,p.x,p.y+1.55,p.z,p.yaw,p.pitch);if(!hit||![1,2].includes(s.grid[hit.i]!)||hit.previous.y!==hit.y+1||block(s.grid,hit.x,hit.y+1,hit.z)!==0)throw new Error('Aim at clear grass or dirt to plant an oak sapling.');if(s.mode!=='creative'&&!(p.inventory[SAPLING]>0))throw new Error('Gather a sapling from oak leaves first.');if(!setBlock(s,index(hit.x,hit.y+1,hit.z),SAPLING))throw new Error('World edit limit reached.');if(s.mode!=='creative')p.inventory[SAPLING]--;p.built++;emitSound(s,'plant',p);say(p,'Sapling planted. Leave space for its canopy; it will grow over time.');return;}
  const hit=ray(s.grid,p.x,p.y+1.55,p.z,p.yaw,p.pitch);
  if(!hit||![1,2].includes(block(s.grid,hit.x,hit.y,hit.z))||hit.previous.y!==hit.y+1)throw new Error('Aim at the top of grass or earth within reach, then Grow tree.');
  if(s.mode!=='creative'&&(!(p.inventory[BERRIES]>0)||!(p.inventory[2]>0)))throw new Error('Growing a tree needs 1 berry and 1 earth.');
  const cells:{x:number;y:number;z:number;b:number}[]=[];
  for(let dy=1;dy<=5;dy++)cells.push({x:hit.x,y:hit.y+dy,z:hit.z,b:4});
  for(let dy=3;dy<=5;dy++)for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)if((dx||dz)&&Math.abs(dx)+Math.abs(dz)<(dy===5?3:4))cells.push({x:hit.x+dx,y:hit.y+dy,z:hit.z+dz,b:5});
  let size=s.edits.size;
  for(const c of cells){if(c.x<0||c.z<0||c.x>=W||c.z>=W||c.y<1||c.y>=H)throw new Error('The whole tree needs room inside the island bounds.');if(block(s.grid,c.x,c.y,c.z)!==0||s.players.some(a=>a.connected&&Math.abs(a.x-c.x-.5)<.8&&Math.abs(a.z-c.z-.5)<.8&&a.y<c.y+1&&a.y+1.75>c.y))throw new Error('Give the tree clear space, including its canopy and nearby explorers.');const i=index(c.x,c.y,c.z);if(c.b===s.base[i]){if(s.edits.has(i))size--;}else if(!s.edits.has(i))size++;}
  if(size>EDIT_LIMIT)throw new Error('This tree would exceed the world edit limit.');
  if(s.mode!=='creative'){p.inventory[BERRIES]--;p.inventory[2]--;}
  for(const c of cells){const i=index(c.x,c.y,c.z);s.grid[i]=c.b;if(c.b===s.base[i])s.edits.delete(i);else s.edits.set(i,c.b);}s.revision++;p.built+=cells.length;emitSound(s,'plant',p);say(p,'A new tree! Harvest its timber and leaves, or grow your own forest.');
}

function move(s:State,p:Actor,input:Input,dt:number) {
  if(input.x||input.z||input.jump||input.mine||input.place)p.sleeping=false;
  if(input.looking){p.yaw=input.yaw;p.pitch=input.pitch;p.flying=s.mode==='creative'&&input.fly;}
  p.sneaking=s.terrainVersion===4&&!!input.sneak;
  const speed=s.terrainVersion<4?(input.sprint&&(s.mode==='creative'||p.food>2)?8:4.5):p.sneaking?1.3:input.sprint&&(s.mode==='creative'||p.food>2)?5.6:4.3;
  const len=Math.max(1,Math.hypot(input.x,input.z)),dx=(Math.cos(input.yaw)*input.x+Math.sin(input.yaw)*input.z)/len*speed*dt,dz=(-Math.sin(input.yaw)*input.x+Math.cos(input.yaw)*input.z)/len*speed*dt;
  if(p.flying){const y=p.y+(Number(input.jump)-Number(input.down))*8*dt;if(y>=1&&y<H+12&&fits(s.grid,p.x,y,p.z))p.y=y;p.vy=0;}
  if(!p.flying&&input.jump&&!p.lastJump&&p.grounded) { p.vy=7;p.grounded=false; }p.lastJump=input.jump;
  for(const [axis,delta] of [['x',dx],['z',dz]] as const) {
    const x=p.x+(axis==='x'?delta:0),z=p.z+(axis==='z'?delta:0);
    if(p.sneaking&&p.grounded&&!solid(block(s.grid,x,p.y-.2,z)))continue;
    if(fits(s.grid,x,p.y,z)) p[axis]+=delta;
    else if(!p.sneaking&&p.grounded&&fits(s.grid,x,p.y+1.01,z)&&fits(s.grid,p.x,p.y+1.01,p.z)) { p[axis]+=delta;p.y+=1.01; }
  }
  if(p.flying)return;
  const inWater=block(s.grid,p.x,p.y+.4,p.z)===6;p.vy=Math.max(inWater?-2:-25,p.vy-(inWater?5:20)*dt);if(inWater&&input.jump)p.vy=4;
  let remaining=p.vy*dt;p.grounded=false;while(Math.abs(remaining)>.00001) { const step=Math.sign(remaining)*Math.min(.1,Math.abs(remaining));if(fits(s.grid,p.x,p.y+step,p.z)) {p.y+=step;remaining-=step;}else {if(p.vy<0){p.grounded=true;if(p.vy<-12)hurt(s,p,Math.floor((-p.vy-10)/2));}p.vy=0;break;} }
  if(p.y<1||!Number.isFinite(p.y)) {spawn(s,p,s.players.indexOf(p));say(p,'Returned safely to camp.');}
}
function interact(s:State,p:Actor,input:Input,dt:number) {
  const target=ray(s.grid,p.x,p.y+1.55,p.z,p.yaw,p.pitch), b=target?block(s.grid,target.x,target.y,target.z):0;
  if(!target||target.i!==p.target||b!==p.targetBlock||!input.mine) {p.progress=0;p.target=target?.i??null;p.targetBlock=b;}
  p.cooldown=Math.max(0,p.cooldown-dt);
  if(input.mine&&!p.cooldown) {
    const direction={x:-Math.sin(p.yaw)*Math.cos(p.pitch),y:Math.sin(p.pitch),z:-Math.cos(p.yaw)*Math.cos(p.pitch)};
    const enemy=s.creatures.find(c=>{const dx=c.x-p.x,dy=c.y+(c.kind==='spider'?.45:c.kind?1.1:.5)-(p.y+1.55),dz=c.z-p.z,dist=Math.hypot(dx,dy,dz);return dist<3.2&&(!target||dist<target.distance)&&((dx*direction.x+dy*direction.y+dz*direction.z)/dist)>.85;});
    if(enemy) {enemy.health-=s.terrainVersion===4?attackDamage(p):p.inventory[SWORD]?5:p.tier?3:1;enemy.hitAt=s.time;emitSound(s,enemy.health<=0?'death':'hit',enemy,enemy.kind?{mob:enemy.kind}:{});p.cooldown=.4;if(enemy.health<=0) {s.creatures=s.creatures.filter(c=>c!==enemy);if(s.terrainVersion===4){addDrops(s,p,mobLoot(enemy));say(p,`${enemy.kind} defeated.`);}else{p.inventory[BERRIES]=Math.min(999,(p.inventory[BERRIES]??0)+2);say(p,'Bramble defeated. +2 berries.');}}return;}
    if(target&&b!==14) { if(s.mode!=='creative'&&(s.terrainVersion===4?miningTier(b):BLOCKS[b]!.tier)>p.tier) {say(p,`${BLOCKS[b]!.name} needs a ${ (s.terrainVersion===4?miningTier(b):BLOCKS[b]!.tier)===1?'wooden':(s.terrainVersion===4?miningTier(b):BLOCKS[b]!.tier)===2?'stone':'iron'} pickaxe selected.`);return;}p.progress+=dt/(s.mode==='creative'?.12:BLOCKS[b]!.hard/(1+p.tier*.6));if(p.progress>=1) {try{canRemove(s,target.i);}catch(error){say(p,(error as Error).message);p.progress=0;return;}if(s.terrainVersion===4){const items=drops(b,target.i,s.seed);if(s.mode==='survival'&&Object.entries(items).some(([id,n])=>(p.inventory[Number(id)]??0)+n>stackLimit(4,Number(id)))){say(p,'Make inventory space before mining this block.');p.progress=0;return;}if(setBlock(s,target.i,0)){if(s.mode==='survival')addDrops(s,p,items);p.mined++;emitSound(s,'break',target,{block:b});delete s.chests[target.i];if(s.fuelUntil)delete s.fuelUntil[target.i];say(p,Object.entries(items).map(([id,n])=>`+${n} ${ITEMS[Number(id)]}`).join(' · ')||`Broke ${ITEMS[b]}.`);}else say(p,'World edit limit reached.');p.progress=0;p.target=null;p.cooldown=.08;return;}const item=b===1||b===FARMLAND?2:b===5&&s.terrainVersion<3?BERRIES:b;
      if(s.terrainVersion>=3&&[5,20].includes(b)&&[BERRIES,SEEDS].some(id=>(p.inventory[id]??0)>=999)){say(p,'Make room for berries and seeds before gathering leaves.');p.progress=0;return;}if(s.mode==='survival'&&(p.inventory[item]??0)>=999){say(p,`${ITEMS[item]} storage is full. Use some before mining more.`);p.progress=0;p.cooldown=.3;return;}if(setBlock(s,target.i,0)) {p.inventory[item]=Math.min(999,(p.inventory[item]??0)+1);p.mined++;emitSound(s,'break',target,{block:b});if(s.terrainVersion>=3&&[5,20].includes(b)){p.inventory[BERRIES]=(p.inventory[BERRIES]??0)+1;p.inventory[SEEDS]=(p.inventory[SEEDS]??0)+1;}delete s.chests[target.i];if(s.fuelUntil)delete s.fuelUntil[target.i];say(p,`+1 ${ITEMS[item]}${s.terrainVersion>=3&&[5,20].includes(b)?' · berries · seeds':''}`);}else say(p,'World edit limit reached. Save this world and start another.');p.progress=0;p.target=null;p.cooldown=.08;} }
  }
  if(input.place&&!p.cooldown&&target&&isWorldBlock(input.slot)&&input.slot!==0&&paletteFor(s.terrainVersion).includes(input.slot)) {const q=target.previous,i=index(q.x,q.y,q.z);p.cooldown=.25;if(q.y<1||q.y>=H||q.x<0||q.z<0||q.x>=W||q.z>=W||solid(block(s.grid,q.x,q.y,q.z)))return;if(s.players.some(a=>a.connected&&Math.abs(a.x-(q.x+.5))<.8&&Math.abs(a.z-(q.z+.5))<.8&&a.y<q.y+1&&a.y+1.75>q.y)){say(p,'Give everyone a little building room.');return;}if(s.mode!=='creative'&&!(p.inventory[input.slot]>0)){say(p,`No ${ITEMS[input.slot]} left. Gather or craft more.`);return;}if(input.slot===SAPLING&&![1,2].includes(block(s.grid,q.x,q.y-1,q.z))){say(p,'Plant saplings on grass or dirt.');return;}if(input.slot===TORCH&&!solid(block(s.grid,q.x,q.y-1,q.z))){say(p,'Place a torch on top of a solid block.');return;}if(setBlock(s,i,input.slot)){if(s.mode!=='creative')p.inventory[input.slot]--;p.built++;emitSound(s,'place',q,{block:input.slot});if(input.slot===13){s.beacon=true;s.players.forEach(a=>say(a,'Sunwell placed.'));}else say(p,`Placed ${ITEMS[input.slot]}.`);} }
}
function recoverSupplies(s:State,p:Actor){
  let recovered=0,pendingNear=false;
  for(const c of s.caches)if(c.owner===p.id&&Math.hypot(c.x-p.x,c.y-p.y,c.z-p.z)<2){for(const [key,n]of Object.entries(c.items)){const item=Number(key),count=Math.min(n,Math.max(0,stackLimit(s.terrainVersion,item)-(p.inventory[item]??0)));if(count){p.inventory[item]=(p.inventory[item]??0)+count;recovered+=count;if(count===n)delete c.items[item];else c.items[item]=n-count;}}if(Object.keys(c.items).length)pendingNear=true;else s.caches=s.caches.filter(a=>a!==c);}
  if(recovered){p.tier=tier(s,p);emitSound(s,'pickup',p);}
  if(recovered)say(p,s.caches.some(c=>c.owner===p.id)?'Recovered what fits. More supplies remain in your crate.':'Recovered your supplies.');else if(pendingNear)say(p,'Inventory full. Build or craft to make room for your supplies.');
}

function creatures(s:State,dt:number) {
  const night=isNight(s.time,s.terrainVersion);
  s.spawnClock+=dt;if(night&&s.spawnClock>8&&s.creatures.length<8&&s.mode==='survival') {s.spawnClock=0;const id=s.nextCreature++,angle=hash(id,3,s.seed)*Math.PI*2,players=s.players.filter(p=>p.connected),anchor=players[id%Math.max(1,players.length)],x=Math.max(1,Math.min(W-2,(s.terrainVersion>=3?anchor?.x??64:64)+Math.cos(angle)*15)),z=Math.max(1,Math.min(W-2,(s.terrainVersion>=3?anchor?.z??64:64)+Math.sin(angle)*15));let y=H-2;while(y>1&&!solid(block(s.grid,x,y-1,z)))y--;if(fits(s.grid,x,y,z)&&block(s.grid,x,y,z)!==6)s.creatures.push({id,x,y,z,health:6,hitAt:0});}
  for(const c of s.creatures) {const target=s.players.filter(p=>p.connected).sort((a,b)=>Math.hypot(a.x-c.x,a.z-c.z)-Math.hypot(b.x-c.x,b.z-c.z))[0];if(!target)continue;const d=Math.hypot(target.x-c.x,target.z-c.z);let safe=false;for(const [i,b]of s.edits)if((b===12||b===13||b===CAMPFIRE)&&Math.hypot(coords(i).x-c.x,coords(i).z-c.z)<5){safe=true;break;}const speed=safe?-1:night?1.35:.45;for(const axis of ['x','z']as const){const delta=(target[axis]-c[axis])/Math.max(1,d)*dt*speed,x=c.x+(axis==='x'?delta:0),z=c.z+(axis==='z'?delta:0);if(fits(s.grid,x,c.y,z))c[axis]+=delta;else if(fits(s.grid,x,c.y+1,z)){c[axis]+=delta;c.y+=1;}}if(fits(s.grid,c.x,c.y-.1,c.z))c.y-=Math.min(.1,dt*4);if(d<1.2&&!safe&&Math.abs(target.y-c.y)<1.5){const dx=target.x-c.x,dz=target.z-c.z,dy=target.y+.8-(c.y+.6),distance=Math.hypot(dx,dy,dz),wall=ray(s.grid,c.x,c.y+.6,c.z,Math.atan2(-dx,-dz),Math.atan2(dy,Math.hypot(dx,dz)),distance);if(!wall||wall.distance>=distance-.05)hurt(s,target,1);} }
  if(!night)s.creatures=s.creatures.filter(c=>s.time-c.hitAt<12);
}
export const rules:GameRules<State,Input,Action,Settings,View,PrivateView> = {
  validateSettings(raw) {const v=raw as Partial<Settings>;if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!['mode','seed','terrainVersion'].includes(k)))throw new Error('Invalid world settings.');const mode=v.mode??'survival',seed=v.seed??38471;if(!['survival','creative'].includes(mode)||!Number.isInteger(seed)||seed<0||seed>999999)throw new Error('Choose a mode and a seed from 0 to 999999.');const terrainVersion=v.terrainVersion??4;if(![1,2,3,4].includes(terrainVersion))throw new Error('Unknown terrain version.');return{mode,seed,terrainVersion};},
  parseInput(raw){const v=raw as Input;if(!v||typeof v!=='object'||Object.keys(v).some(k=>!Object.keys(neutral()).includes(k))||!['x','z','yaw','pitch','slot'].every(k=>Number.isFinite(v[k as keyof Input]))||Math.abs(v.x)>1||Math.abs(v.z)>1||Math.abs(v.yaw)>Math.PI*2||Math.abs(v.pitch)>1.45||!selectable(v.slot)||!['looking','fly','sprint','down','jump','mine','place'].every(k=>typeof v[k as keyof Input]==='boolean'))throw new Error('Invalid controls.');if(v.sneak!==undefined&&typeof v.sneak!=='boolean')throw new Error('Invalid sneak control.');return{...v,sneak:v.sneak??false,command:parseCommand(v.command)};},neutralInput:neutral,
  parseAction(raw){const v=raw as Action;if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!['type','recipe','item'].includes(k)))throw new Error('Invalid action.');if(v?.type==='finish'&&Object.keys(v).length===1)return{type:'finish'};const c=parseCommand({...v,seq:1});if(!c)throw new Error('Invalid action.');const {seq:_seq,...action}=c;return action as Action;},
  create(ctx,settings){const s:State={seed:settings.seed,terrainVersion:settings.terrainVersion??4,mode:settings.mode,grid:terrain(settings.seed,settings.terrainVersion??4),base:terrain(settings.seed,settings.terrainVersion??4),edits:new Map(),revision:0,players:[],creatures:[],projectiles:[],blasts:[],caches:[],time:0,beacon:false,complete:false,spawnClock:0,nextCreature:1,chests:{},furnaces:{},farms:[]};s.players=ctx.players.map((p,i)=>{const a:Actor={...p,selected:0,sneaking:false,home:null,air:12,regen:0,sleeping:false,x:0,y:9,z:0,yaw:0,pitch:0,health:10,food:10,connected:true,mined:0,built:0,flying:false,tier:settings.mode==='creative'?4:0,progress:0,target:null,message:settings.mode==='creative'?'Unlimited materials. Open Craft to choose blocks, or Fly to explore.':'Explore, gather and build at your own pace. Craft and Map are there whenever you need them.',inventory:initialInventory(settings.mode,settings.terrainVersion??4),vy:0,grounded:false,cooldown:0,targetBlock:0,lastJump:false,hunger:0,hurtUntil:0,commandAck:0,commandResult:''};spawn(s,a,i);return a;});return s;},
  applyAction(s,id,a){const p=s.players.find(p=>p.id===id);if(!p||!p.connected||s.complete)throw new Error('Join the active world first.');if(a.type==='craft')craft(s,p,a.recipe);else if(a.type==='grow')growTree(s,p);else if(a.type!=='finish'){homesteadAction(s,p,a,setBlock);p.tier=tier(s,p);}else throw new Error('Only the host can finish through world controls.');},
  tick(s,inputs,dt){if(s.complete)return;s.time+=dt;s.sounds=(s.sounds??[]).filter(e=>s.time-e.at<=SOUND_AGE);for(const p of s.players){if(!p.connected)continue;const input=inputs.get(p.id);if(input){p.selected=input.slot;if(s.terrainVersion===4)p.tier=selectedTier(p);if(input.looking){p.yaw=input.yaw;p.pitch=input.pitch;}if(input.command&&input.command.seq===p.commandAck+1){try{rules.applyAction(s,p.id,rules.parseAction(Object.fromEntries(Object.entries(input.command).filter(([k])=>k!=='seq'))),s.time*1000);p.commandResult=p.message;}catch(error){p.commandResult=error instanceof Error?error.message:'Command unavailable.';}p.commandAck=input.command.seq;}move(s,p,input,dt);interact(s,p,input,dt);}else{move(s,p,{...neutral(),yaw:p.yaw,pitch:p.pitch},dt);p.progress=0;p.lastJump=false;}if(s.terrainVersion>=3){
      if(s.mode==='survival'){
        p.hunger+=dt*(input?.sprint&&(input.x||input.z)?2:input&&(input.x||input.z||input.mine)?1:.35);
        if(p.hunger>=90){p.hunger-=90;p.food=Math.max(0,p.food-1);}
        p.regen+=dt;if(p.regen>=10){p.regen=0;if(p.food>=8&&p.health<10){p.health++;p.hunger+=15;}else if(!p.food&&p.health>1)hurt(s,p,1);}
        p.air=block(s.grid,p.x,p.y+1.55,p.z)===6?Math.max(0,p.air-dt):12;if(!p.air)hurt(s,p,1);
      }
    }else{p.hunger+=dt;if(s.mode==='survival'&&p.hunger>=35){p.hunger=0;p.food=Math.max(0,p.food-1);if(!p.food)hurt(s,p,1);else if(p.food>6)p.health=Math.min(10,p.health+1);}}
    recoverSupplies(s,p);if(s.terrainVersion===4)p.tier=selectedTier(p);}sleepTick(s);if(s.terrainVersion===4){for(const [i,t]of Object.entries(s.fuelUntil??{}))if(t<=s.time)delete s.fuelUntil![Number(i)];growSaplings(s,dt);tickMobs(s,dt,hurt,setBlock);}else creatures(s,dt);},
  onPresenceChange(s,id,connected){const p=s.players.find(p=>p.id===id);if(p){p.connected=connected;p.sleeping=false;p.progress=0;p.lastJump=false;}},
  publicView(s){return{sounds:(s.sounds??[]).map(e=>({...e})),burningFurnaces:s.terrainVersion===4?Object.entries(s.fuelUntil??{}).filter(([,until])=>until>s.time).map(([i])=>Number(i)):Object.entries(s.furnaces).filter(([,j])=>j.readyAt>s.time).map(([i])=>Number(i)),projectiles:s.projectiles.map(p=>({...p})),blasts:s.blasts.map(b=>({...b})),seed:s.seed,terrainVersion:s.terrainVersion,revision:s.revision,edits:[...s.edits],players:s.players.map(({home:_home,air:_air,regen:_regen,sleeping:_sleeping,inventory:_i,vy:_v,grounded:_g,cooldown:_c,targetBlock:_t,lastJump:_j,hunger:_h,hurtUntil:_u,commandAck:_a,commandResult:_r,...p})=>({...p})),creatures:s.creatures.map(c=>({...c})),caches:s.caches.map(({items:_i,owner,...c})=>({...c,ownerId:owner})),farms:s.farms.map(f=>({...f})),furnaces:Object.entries(s.furnaces).map(([i,j])=>({i:Number(i),readyAt:j.readyAt})),sleeping:s.players.filter(p=>p.connected&&p.sleeping).length,time:s.time,mode:s.mode,beacon:s.beacon,complete:s.complete,mined:s.players.reduce((n,p)=>n+p.mined,0),built:s.players.reduce((n,p)=>n+p.built,0)};},
  playerView(s,id){const p=s.players.find(p=>p.id===id),cache=s.caches.find(c=>c.owner===id);return{craftingSize:p&&nearby(s,p,BENCH)!==null?3:2,nearFurnace:!!p&&nearby(s,p,FURNACE)!==null,station:p?stationView(s,p):null,home:p?.home?{x:p.home.x,y:p.home.y,z:p.home.z}:null,air:p?.air??12,inventory:{...p?.inventory},message:p?.message??'Watching this world.',commandAck:p?.commandAck??0,commandResult:p?.commandResult??'',recovery:cache?{x:cache.x,y:cache.y,z:cache.z}:null};},
  exportSave:serializeWorld,loadSave(ctx,raw,settings){const state=rules.create(ctx,settings);restoreWorld(state,raw);return{state,settings:{seed:state.seed,mode:state.mode,terrainVersion:state.terrainVersion}};},finish:finishWorld,
  outcome(s){return{complete:s.complete,winners:[],rows:s.players.map(p=>({playerId:p.id,score:p.mined+p.built,label:`${p.mined} gathered · ${p.built} built`}))};},dispose(){},
};
export function serializeWorld(s:State){return{format:'blockwild',version:2,width:W,height:H,terrainVersion:s.terrainVersion,seed:s.seed,mode:s.mode,time:s.time,edits:[...s.edits],beacon:s.beacon,homestead:{fuelUntil:s.fuelUntil??{},chests:s.chests,furnaces:s.furnaces,farms:s.farms},caches:s.caches.map(c=>({ownerName:s.players.find(p=>p.id===c.owner)?.name??'',...(s.players.some(p=>p.id===c.owner)?{ownerIndex:s.players.findIndex(p=>p.id===c.owner)}:{}),x:c.x,y:c.y,z:c.z,items:{...c.items}})),players:s.players.map(p=>({name:p.name,inventory:p.inventory,...(p.home?{home:p.home}:{}),x:p.x,y:p.y,z:p.z,health:p.health,food:p.food,mined:p.mined,built:p.built}))};}
export function restoreWorld(s:State,raw:unknown){
  let v=raw as ReturnType<typeof serializeWorld>;
  if(v&&v.version===1){const old=v;v={...old,version:2,width:W,height:H,terrainVersion:1,caches:[],edits:Array.isArray(old.edits)?old.edits.map(pair=>{if(!Array.isArray(pair)||!Number.isInteger(pair[0])||pair[0]<4096||pair[0]>=131072||!Number.isInteger(pair[1])||pair[1]<0||pair[1]>15||pair[1]===14)throw new Error('Invalid legacy edit.');return[index(pair[0]%64+32,Math.floor(pair[0]/4096),Math.floor(pair[0]/64)%64+32),pair[1]];}):old.edits,players:Array.isArray(old.players)?old.players.map(p=>({...p,x:p.x+32,z:p.z+32,inventory:p.inventory&&Object.fromEntries(Object.entries(p.inventory).map(([k,n])=>[Number(k)>=16?Number(k)+8:k,n]))})):old.players};}
  if(!v||v.format!=='blockwild'||v.version!==2||v.width!==W||v.height!==H||![1,2,3,4].includes(v.terrainVersion)||!Number.isInteger(v.seed)||v.seed<0||v.seed>999999||!['survival','creative'].includes(v.mode)||!Number.isFinite(v.time)||v.time<0||v.time>1e9||typeof v.beacon!=='boolean'||!Array.isArray(v.edits)||v.edits.length>EDIT_LIMIT||!Array.isArray(v.players)||v.players.length>10)throw new Error('Invalid Blockwild save.');
  const edits=new Map<number,number>();for(const pair of v.edits){if(!Array.isArray(pair)||pair.length!==2||!Number.isInteger(pair[0])||pair[0]<W*W||pair[0]>=W*W*H||!Number.isInteger(pair[1])||!isWorldBlock(pair[1])||pair[1]===14||edits.has(pair[0]))throw new Error('Invalid world edit.');edits.set(pair[0],pair[1]);}
  for(const p of v.players){if(!p||Object.keys(p).some(k=>!['name','inventory','x','y','z','health','food','mined','built','home'].includes(k))||typeof p.name!=='string'||p.name.length>16||!p.inventory||typeof p.inventory!=='object'||Array.isArray(p.inventory)||Object.entries(p.inventory).some(([k,n])=>!/^(0|[1-9]\d*)$/.test(k)||Number(k)>=ITEMS.length||!Number.isInteger(n)||n<0||n>stackLimit(v.terrainVersion,Number(k)))||!['x','y','z','health','food','mined','built'].every(k=>Number.isFinite(p[k as keyof typeof p]))||p.x<PLAYER_RADIUS||p.x>W-PLAYER_RADIUS||p.z<PLAYER_RADIUS||p.z>W-PLAYER_RADIUS||p.y<1||p.y>H+12||p.health<1||p.health>10||p.food<0||p.food>10||(!Number.isInteger(p.mined)||p.mined<0||p.mined>1e9)||(!Number.isInteger(p.built)||p.built<0||p.built>1e9))throw new Error('Invalid saved player.');}
  const caches=v.caches??[];if(!Array.isArray(caches)||caches.length>10||caches.some(c=>!c||typeof c.ownerName!=='string'||c.ownerName.length>16||(c.ownerIndex!==undefined&&(!Number.isInteger(c.ownerIndex)||c.ownerIndex<0||c.ownerIndex>=v.players.length||v.players[c.ownerIndex]?.name!==c.ownerName))||!['x','y','z'].every(k=>Number.isFinite(c[k as 'x'|'y'|'z']))||c.x<0||c.x>=W||c.z<0||c.z>=W||c.y<0||c.y>H+12||!c.items||typeof c.items!=='object'||Array.isArray(c.items)||Object.entries(c.items).some(([k,n])=>!/^(0|[1-9]\d*)$/.test(k)||Number(k)>=ITEMS.length||(v.terrainVersion<3&&isTool(Number(k)))||!Number.isSafeInteger(n)||n<1||n>CACHE_ITEM_LIMIT)))throw new Error('Invalid recovery cache.');
  const owners=new Set<number|string>();for(const cache of caches){const key=cache.ownerIndex??(v.players.filter(p=>p.name===cache.ownerName).length===1?v.players.findIndex(p=>p.name===cache.ownerName):cache.ownerName);if(owners.has(key))throw new Error('Duplicate recovery cache owner.');owners.add(key);}
  const grid=terrain(v.seed,v.terrainVersion);for(const [i,b]of edits)grid[i]=b;
  const homestead=readHomestead(v.homestead,grid,v.terrainVersion);
  for(const p of v.players)if(p.home&&(!Number.isInteger(p.home.bed)||p.home.bed<W*W||p.home.bed>=W*W*H||!['x','y','z'].every(k=>Number.isFinite(p.home![k as 'x'|'y'|'z']))||p.home.x<PLAYER_RADIUS||p.home.x>W-PLAYER_RADIUS||p.home.z<PLAYER_RADIUS||p.home.z>W-PLAYER_RADIUS||p.home.y<1||p.home.y>H))throw new Error('Invalid saved home.');
  Object.assign(s,homestead);s.base=terrain(v.seed,v.terrainVersion);s.terrainVersion=v.terrainVersion;s.seed=v.seed;s.mode=v.mode;s.time=v.time;s.edits=edits;s.grid=grid;s.revision++;s.beacon=v.beacon;s.sounds=[];s.creatures=[];s.projectiles=[];s.blasts=[];s.caches=caches.flatMap((c,i)=>{const savedIndex=c.ownerIndex??(v.players.filter(p=>p.name===c.ownerName).length===1?v.players.findIndex(p=>p.name===c.ownerName):-1),occurrence=v.players.slice(0,savedIndex).filter(p=>p.name===c.ownerName).length,owner=savedIndex>=0?s.players.filter(p=>p.name===c.ownerName)[occurrence]:undefined;return owner?[{id:`restored-${i}`,owner:owner.id,x:c.x,y:c.y,z:c.z,items:{...c.items}}]:[];});s.complete=false;
  s.players.forEach((p,i)=>{const occurrence=s.players.slice(0,i).filter(a=>a.name===p.name).length,saved=v.players.filter(a=>a.name===p.name)[occurrence];if(saved){Object.assign(p,{home:saved.home?{...saved.home}:null,x:saved.x,y:saved.y,z:saved.z,health:saved.health,food:saved.food,mined:saved.mined,built:saved.built,inventory:{...saved.inventory}});p.tier=tier(s,p);if(!fits(grid,p.x,p.y,p.z))spawn(s,p,i);}else{p.home=null;p.inventory=initialInventory(s.mode,s.terrainVersion);p.health=p.food=10;p.mined=p.built=0;p.tier=tier(s,p);spawn(s,p,i);}p.air=12;p.regen=0;p.sleeping=false;p.vy=0;p.progress=0;p.target=null;p.cooldown=0;p.hurtUntil=s.time+3;say(p,'World loaded. Make yourself at home.');});
}
export function finishWorld(s:State){s.complete=true;}
export default rules;
