import type { LevelSource } from '../model';
import { MISSIONS } from '../model';

/** Customs house on the night docks. The quay is long and exposed; the warehouse, back lane and crew wing go around it to the records vault. */
export const ferry: LevelSource = {
  id: 'ferry', ...MISSIONS.ferry, objectiveKind: 'manifest', parTimes: [900, 460, 350], outdoor: 'deck',
  briefing: 'The harbour boss files his real cargo manifest in the customs records vault. Two beams guard it: one covers the hall door, one covers the harbourmaster’s door. Come through the warehouse and the back lane, or walk the quay in plain sight. The last ferry leaves from the far end of the quay.',
  objective: 'Steal the cargo manifest',
  grid: [
    '##########################################~~~~',
    '#+,,,$,$,$,$,$,$,$,$,$,$t$,$,$,$,$,$,$,$,,~~~~',
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,~~~~',
    '#########d#####,,,##w#####c###b##k##w#####~~~~',
    '#....S#......+#,,,#S....#.......#.......S#~~~~',
    '#n....=...$...#,$,#.....%...O...L.......q#~~~~',
    '#.$$$.=...$...#,,,#.$$$.#$$$...$#........#~~~~',
    '#v....#...$...#,$,#.....#......$#.$$$$$$.#~~~~',
    '###d###.......#,,,#.$$$.a.......#........#~~~~',
    '#......$$$$$$$#,$,#....u#$$$....#H......x#~~~~',
    '#.............#,,,#g#d######L#######d#####~~~~',
    '#..########...#,$,#.............#.......H#~~~~',
    '#...........$t#,,,j.$.$.$.$.$.$.#........#~~~~',
    '#.$$$$$$$...$.d,$,#.............d.$$$$$$.#~~~~',
    '#.$.........$.#,,,#......$......#........#~~~~',
    '#.$.........$.#,$,#......$......####d#####~~~~',
    '#.$.###########,,,d......$......i........#~~~~',
    '#.$...........#,$,#......$......#........#~~~~',
    '#....$$$$$$$$.#,,,#.............%.$.$.$..#~~~~',
    '#.............#,$,#..$..$..$..$.#........#~~~~',
    '#t$$$$........#,,,#H............#.......+#~~~~',
    '####d#####d####,,,m###d#####d#########d##o~~~~',
    '#,,,,,,,,,,,,,,,,,,,,,,,,,z,,,,,,#S$r#,,,,~~~~',
    '#,PP,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#y..#,,,,~~~~',
    '#,PP,,,,,,,,,,,,,,,,,,,,,,,,,,,,,##d##,,,,~~~~',
    '#,,,,,$,$,$,$,$,$,$,$,$,$,$,$,$,$,,,,,,,,,~~~~',
    '#,,,,,,,,,,,z,,,,,,,,,,,,,,,,,,z,,,,,,,E,,~~~~',
    '~~~~~~$$$~~~~~~~~~~~~~~~~~~~~~~~~~~~~~,,,,~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$,,,~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
  ],
  rooms: [
    { name: 'BACK LANE', x: 1, y: 1, w: 41, h: 2, floor: 'asphalt', light: '#ffb070' },
    { name: 'FOREMAN’S OFFICE', x: 1, y: 4, w: 5, h: 4, floor: 'wood', light: '#ffd28a' },
    { name: 'PALLET STORE', x: 7, y: 4, w: 7, h: 5, floor: 'concrete', light: '#ffd9a0' },
    { name: 'FREIGHT WAREHOUSE', x: 1, y: 9, w: 13, h: 12, floor: 'concrete', light: '#ffe0a8' },
    { name: 'LOADING ALLEY', x: 15, y: 3, w: 3, h: 19, floor: 'asphalt', light: '#9fb4d0' },
    { name: 'EVIDENCE ROOM', x: 19, y: 4, w: 5, h: 6, floor: 'tile', light: '#e8f4ff' },
    { name: 'RECORDS VAULT', x: 25, y: 4, w: 7, h: 6, floor: 'marble', light: '#ffe6a8', tint: '#5b4a2f' },
    { name: 'HARBOUR OFFICE', x: 33, y: 4, w: 8, h: 6, floor: 'carpet', light: '#ffc98a', tint: '#2f4a5b' },
    { name: 'CUSTOMS HALL', x: 19, y: 11, w: 13, h: 10, floor: 'tile', light: '#dfefff' },
    { name: 'CREW BUNKS', x: 33, y: 11, w: 8, h: 4, floor: 'wood', light: '#ffb88a' },
    { name: 'CREW MESS', x: 33, y: 16, w: 8, h: 5, floor: 'checker', light: '#fff0cc' },
    { name: 'NIGHT QUAY', x: 1, y: 22, w: 41, h: 5, floor: 'deck', light: '#8fb8ff' },
    { name: 'TICKET BOOTH', x: 34, y: 22, w: 3, h: 2, floor: 'wood', light: '#ffe08a' },
    { name: 'FERRY PIER', x: 38, y: 27, w: 4, h: 2, floor: 'deck', light: '#b8d8ff' },
  ],
  props: [
    ['tree', 3, 2], ['car', 12, 2, 2, 1], ['barrel', 22, 1], ['barrel', 25, 2], ['car', 27, 2, 2, 1], ['crate', 30, 2], ['crate', 31, 2], ['lamp', 19, 2], ['crate', 40, 2], ['barrel', 41, 1],
    ['desk', 2, 4, 2, 1], ['chair', 3, 5], ['lamp', 1, 4], ['painting', 4, 4], ['locker', 4, 7, 2, 1],
    ['crate', 7, 4], ['crate', 8, 5], ['barrel', 7, 7], ['barrel', 8, 7], ['container', 12, 5, 1, 3, 1], ['shelf', 3, 10, 8, 1],
    ['shelf', 5, 12, 4, 1], ['container', 4, 14, 3, 1], ['container', 8, 14, 3, 1], ['crate', 11, 12],
    ['shelf', 4, 17, 9, 1], ['van', 6, 19, 2, 2], ['crate', 12, 19], ['crate', 12, 20], ['crate', 13, 20], ['barrel', 1, 17], ['barrel', 9, 19],
    ['barrel', 15, 6], ['crate', 17, 9], ['barrel', 15, 19],
    ['shelf', 21, 4, 3, 1], ['crate', 19, 7], ['crate', 19, 8], ['table', 21, 7], ['barrel', 23, 7],
    ['bookcase', 25, 4, 3, 1], ['bookcase', 31, 4], ['lamp', 29, 4], ['rug', 27, 4, 3, 3], ['table', 26, 7],
    ['bookcase', 33, 4, 2, 1], ['painting', 35, 4], ['desk', 37, 5, 2, 1], ['chair', 38, 6], ['rug', 35, 5, 4, 3], ['sofa', 34, 8, 2, 1], ['table', 37, 8], ['plant', 38, 9], ['statue', 40, 7],
    ['counter', 20, 14, 3, 1], ['server', 23, 14], ['server', 26, 14], ['counter', 27, 14, 3, 1], ['desk', 24, 11, 3, 1], ['bench', 20, 17, 2, 1], ['bench', 28, 17, 2, 1],
    ['plant', 19, 13], ['plant', 31, 11], ['plant', 31, 20], ['lamp', 23, 20], ['lamp', 27, 20], ['rug', 23, 15, 5, 5], ['locker', 31, 14],
    ['bed', 33, 11, 1, 2], ['bed', 34, 11, 1, 2], ['bed', 38, 11, 1, 2], ['bed', 39, 11, 1, 2], ['locker', 37, 14, 3, 1], ['lamp', 40, 14],
    ['bar', 39, 16, 2, 1], ['cards', 35, 19, 2, 1], ['table', 37, 19], ['chair', 35, 20], ['chair', 37, 20], ['barrel', 33, 20], ['locker', 33, 16],
    ['counter', 36, 23],
    ['container', 6, 22, 3, 1], ['container', 11, 22, 3, 1], ['crate', 14, 22], ['crate', 20, 22], ['crate', 20, 23], ['container', 24, 23, 3, 1], ['crate', 30, 22], ['crate', 31, 22], ['crate', 31, 23],
    ['barrel', 9, 26], ['barrel', 19, 26], ['barrel', 24, 26], ['barrel', 29, 26], ['lamp', 5, 26], ['lamp', 17, 26], ['lamp', 34, 26], ['bench', 39, 22, 2, 1], ['crate', 41, 23],
    ['boat', 39, 27, 3, 2],
  ],
  legend: {
    a: { kind: 'laser', label: 'Hall-side beam', circuit: 'vault', facing: 'E' },
    b: { kind: 'laser', label: 'Office-side beam', circuit: 'vault', facing: 'S' },
    c: { kind: 'camera', label: 'Vault camera', circuit: 'vault', facing: 'S' },
    g: { kind: 'camera', label: 'Hall camera', circuit: 'hall', facing: 'S' },
    i: { kind: 'camera', label: 'Hall camera', circuit: 'hall', facing: 'W' },
    j: { kind: 'camera', label: 'Alley camera', circuit: 'dock', facing: 'W' },
    k: { kind: 'camera', label: 'Lane camera', circuit: 'dock', facing: 'N' },
    m: { kind: 'camera', label: 'Quay camera', circuit: 'dock', facing: 'S' },
    o: { kind: 'camera', label: 'Pier camera', circuit: 'dock', facing: 'S' },
    n: { kind: 'terminal', label: 'Vault security', circuit: 'vault' },
    q: { kind: 'terminal', label: 'Hall cameras', circuit: 'hall' },
    r: { kind: 'terminal', label: 'Dock cameras', circuit: 'dock' },
    v: { kind: 'vent', label: 'Freight duct', pair: 'u' }, u: { kind: 'vent', label: 'Freight duct', pair: 'v' },
    x: { kind: 'vent', label: 'Office duct', pair: 'y' }, y: { kind: 'vent', label: 'Office duct', pair: 'x' },
    z: { kind: 'hide', label: 'Fishing nets' },
    t: { kind: 'hide', label: 'Tarpaulin' },
  },
};
