import type { LevelSource } from '../model';
import { MISSIONS } from '../model';

/** Auction conservatory. Glass walls expose the palm court from every side; the staff wing, the rose gardens and the ducts go around it. */
export const glasshouse: LevelSource = {
  id: 'glasshouse', ...MISSIONS.glasshouse, objectiveKind: 'jewel', parTimes: [900, 440, 320], outdoor: 'asphalt',
  briefing: 'Tomorrow the Glasshouse auctions the prism jewel. Tonight it sits behind a double laser line in the gallery. Kill the beams from security, crawl the heating duct from the curator’s office, or break in through the restoration archive. Everyone in the palm court can see through glass.',
  objective: 'Lift the prism jewel',
  grid: [
    '#####################c########################',
    '#........#.......H#u..$$$...#S.....q.#,,,,,,+#',
    '#..$$$$$.#........#....O....%........#,,,,,,,#',
    '#......$.L...$$$..#.........#.$$$$...w,$$$,,,#',
    '#S.....$.#........a.........#........#,,,$,,,#',
    '#......$.#.$$$$$$.#.$$$$$$$.f........#,,,$,,,#',
    '#........#........#.........b........L,,,,,,,#',
    '#v.......#........d.........#.$.$.$..#,,,$,,,#',
    '####d#####====d===#=#==L===g####d#####H,,,,,,#',
    '#H......r#..................=.......S#,,,$,,,#',
    '#..$$$$$.#.H$.$.$.$.$.$.$.$.=.$$$$$$.=,,,,,,,#',
    '#........d......===d===.....=........=,,,$,,,#',
    '#+....$..#.$....=.....=...$.=........=,,,,,,H#',
    '#.....$..#.$....=.$...=...$.d........#,,,$,,,#',
    '####d#####.$....=H$...=...$.=.....$..#,,,,,,,#',
    '#.$......=.$....=.$$$$=...$.=.....$..w,,,$,,,#',
    '#.$......=.$....===d===...$.=.....$..#,,,,,,,#',
    '#..$$$$$.=.$...H..........H.#..$$$$..#,,,$,,,#',
    '#y.......=..................#H.......m,,,,,,,#',
    '###d###w##i##=====#d#=====#######L##k#,,,$,,,#',
    '#,,,,,,,,,,#...............#x........#,,,,,,,#',
    '#,,,,$,$,$H#....$.....$....#........n#H,,$,,,#',
    '#,,,,,,,,,,#....$.....$....d.........#,,,,,,,#',
    '#,,,,,,,,$,#....$.....$....#.........d,,,$,,,#',
    '#,,,,,,,,,,%....$.....$....#.$$$$$$..#,,,,,,,#',
    '#,,,E,,,,$,#H..............#+.......S#,,,$,,,#',
    '#,,,,,,,,,,##j#####d############w#####,,,,,,,#',
    '#,,,,,,,,,,d$,$,$,,,,,,,,,,,,,,,,,,,,,,,PPPP,#',
    '#,,,,,,,,,,#,,,,,,,,,,$,$,$,$,$,$,$,$,,,,,,,,#',
    '##############################################',
  ],
  rooms: [
    { name: 'CURATOR’S OFFICE', x: 1, y: 1, w: 8, h: 7, floor: 'wood', light: '#ffcf8f', tint: '#4a3222' },
    { name: 'STATUE GALLERY', x: 10, y: 1, w: 8, h: 7, floor: 'marble', light: '#dfe8ff' },
    { name: 'PRISM GALLERY', x: 19, y: 1, w: 9, h: 7, floor: 'checker', light: '#d9b8ff', tint: '#3a2a5c' },
    { name: 'RESTORATION ARCHIVE', x: 29, y: 1, w: 8, h: 7, floor: 'wood', light: '#ffd9a0' },
    { name: 'STAFF ROOM', x: 1, y: 9, w: 8, h: 5, floor: 'tile', light: '#e8f4ff' },
    { name: 'POTTING HOUSE', x: 1, y: 15, w: 8, h: 4, floor: 'concrete', light: '#c8f0b0' },
    { name: 'PALM COURT', x: 10, y: 9, w: 18, h: 10, floor: 'grass', light: '#b8f5d0', tint: '#1f4a3a' },
    { name: 'ORCHID HOUSE', x: 17, y: 12, w: 5, h: 4, floor: 'tile', light: '#f5b8ff' },
    { name: 'AUCTION SALON', x: 29, y: 9, w: 8, h: 10, floor: 'carpet', light: '#ffc080', tint: '#5a1f2a' },
    { name: 'GRAND FOYER', x: 12, y: 20, w: 15, h: 6, floor: 'marble', light: '#fff0cc' },
    { name: 'SECURITY', x: 28, y: 20, w: 9, h: 6, floor: 'concrete', light: '#9fc7ff' },
    { name: 'DELIVERY YARD', x: 1, y: 20, w: 10, h: 9, floor: 'asphalt', light: '#ffb870' },
    { name: 'FRONT DRIVE', x: 11, y: 27, w: 27, h: 2, floor: 'asphalt', light: '#9fb4d0' },
    { name: 'ROSE GARDENS', x: 38, y: 1, w: 7, h: 28, floor: 'grass', light: '#b0e8c0' },
  ],
  props: [
    ['bookcase', 1, 1, 4, 1], ['lamp', 5, 1], ['painting', 6, 1], ['plant', 8, 1], ['desk', 3, 4, 3, 1], ['chair', 4, 5], ['rug', 2, 5, 3, 2], ['sofa', 5, 6, 2, 1], ['table', 8, 6], ['shelf', 2, 7, 2, 1],
    ['plant', 10, 1], ['painting', 13, 1], ['painting', 14, 1], ['painting', 15, 1], ['statue', 11, 2], ['statue', 16, 2], ['statue', 11, 7], ['statue', 16, 7], ['bench', 13, 6, 2, 1], ['rug', 12, 3, 4, 3],
    ['rug', 21, 1, 5, 3], ['statue', 20, 3], ['statue', 26, 3], ['painting', 26, 1], ['painting', 20, 1], ['plant', 21, 7], ['bench', 24, 7, 2, 1], ['lamp', 27, 7],
    ['shelf', 30, 1, 4, 1], ['crate', 36, 1], ['desk', 30, 4, 2, 1], ['crate', 35, 4], ['crate', 36, 4], ['bookcase', 29, 6, 1, 2, 1], ['statue', 34, 6], ['barrel', 36, 7],
    ['locker', 2, 9, 2, 1], ['sofa', 6, 9, 2, 1], ['cards', 2, 11, 2, 1], ['chair', 2, 10], ['chair', 3, 12], ['shelf', 8, 12, 1, 2],
    ['flowerbed', 5, 15, 4, 1], ['plant', 8, 16], ['table', 5, 18, 2, 1], ['barrel', 8, 18], ['crate', 1, 16],
    ['tree', 10, 9], ['tree', 27, 9], ['tree', 10, 18], ['tree', 27, 18], ['fountain', 13, 13, 2, 2], ['flowerbed', 15, 12, 1, 4], ['flowerbed', 24, 12, 1, 4],
    ['bench', 16, 9, 2, 1], ['bench', 21, 9, 2, 1], ['bench', 16, 18, 2, 1], ['bench', 21, 18, 2, 1], ['plant', 12, 17], ['plant', 24, 17], ['statue', 13, 11],
    ['flowerbed', 20, 12, 2, 1], ['plant', 17, 12], ['plant', 21, 13], ['statue', 20, 14],
    ['desk', 31, 12, 2, 1], ['piano', 35, 12, 2, 1], ['rug', 30, 13, 4, 4], ['chair', 30, 14], ['chair', 31, 14], ['chair', 32, 14], ['chair', 30, 16], ['chair', 31, 16], ['chair', 32, 16],
    ['plant', 29, 9], ['painting', 30, 9], ['painting', 34, 9], ['statue', 36, 17], ['plant', 29, 12], ['bar', 29, 15, 1, 2, 1],
    ['counter', 18, 22, 3, 1], ['rug', 17, 24, 5, 2], ['statue', 14, 21], ['statue', 24, 21], ['plant', 12, 20], ['plant', 26, 20], ['plant', 26, 25], ['lamp', 17, 20], ['lamp', 21, 20], ['bench', 23, 24, 2, 1], ['locker', 12, 21], ['locker', 12, 22],
    ['server', 30, 20], ['server', 31, 20], ['desk', 30, 22, 3, 1], ['chair', 31, 23], ['desk', 34, 22, 2, 1], ['locker', 33, 25], ['locker', 34, 25], ['locker', 35, 25],
    ['van', 1, 26, 2, 2], ['container', 1, 21, 1, 3, 1], ['crate', 5, 23], ['crate', 6, 23], ['crate', 6, 24], ['barrel', 8, 27], ['barrel', 9, 28], ['container', 3, 28, 3, 1], ['lamp', 5, 20],
    ['tree', 43, 3], ['tree', 39, 11], ['tree', 43, 16], ['tree', 39, 25], ['flowerbed', 43, 5, 1, 3], ['flowerbed', 43, 20, 1, 3], ['flowerbed', 39, 17, 1, 3], ['fountain', 42, 9, 2, 2],
    ['bench', 44, 8, 1, 2, 1], ['statue', 39, 6], ['statue', 43, 13], ['lamp', 38, 1], ['lamp', 40, 23],
    ['car', 24, 27, 2, 1], ['car', 29, 27, 2, 1], ['lamp', 18, 28], ['tree', 13, 28], ['tree', 35, 27],
  ],
  legend: {
    a: { kind: 'laser', label: 'Prism beam', circuit: 'prism', facing: 'E' },
    b: { kind: 'laser', label: 'Prism beam', circuit: 'prism', facing: 'W' },
    c: { kind: 'camera', label: 'Gallery camera', circuit: 'prism', facing: 'S' },
    f: { kind: 'laser', label: 'Archive beam', circuit: 'archive', facing: 'E' },
    g: { kind: 'camera', label: 'Court camera', circuit: 'court', facing: 'S' },
    i: { kind: 'camera', label: 'Court camera', circuit: 'court', facing: 'N' },
    j: { kind: 'camera', label: 'Foyer camera', circuit: 'court', facing: 'N' },
    k: { kind: 'camera', label: 'Salon camera', circuit: 'archive', facing: 'N' },
    m: { kind: 'camera', label: 'Garden camera', circuit: 'archive', facing: 'E' },
    n: { kind: 'terminal', label: 'Gallery security', circuit: 'prism' },
    q: { kind: 'terminal', label: 'Court cameras', circuit: 'court' },
    r: { kind: 'terminal', label: 'Archive and salon security', circuit: 'archive' },
    v: { kind: 'vent', label: 'Heating duct', pair: 'u' }, u: { kind: 'vent', label: 'Heating duct', pair: 'v' },
    x: { kind: 'vent', label: 'Service duct', pair: 'y' }, y: { kind: 'vent', label: 'Service duct', pair: 'x' },
  },
};
