import type { LevelSource } from '../model';
import { MISSIONS } from '../model';

/** Casino annex. Front doors are watched; the kitchen dock, courtyard gate, vents and cracked walls give quieter routes. */
export const velvet: LevelSource = {
  id: 'velvet', ...MISSIONS.velvet, objectiveKind: 'ledger', parTimes: [900, 420, 300], outdoor: 'asphalt',
  briefing: 'The Velvet keeps two sets of books. The real ledger sits in the manager’s office behind a laser. Hack security to kill the beam, or find the window it doesn’t cover.',
  objective: 'Steal the crooked ledger',
  grid: [
    '######################f###############z#####',
    '#....a....#.S......S.#........S.#..........#',
    '#.$.......#..$$$$$$..#.........+#.$$$$..O..#',
    '#..$...$$.#..........d.$$$$$$...L..........#',
    '#...$.....#..........#..........#..........#',
    '#.v.......#x.........#$$$$$$$$$.#..........g',
    '#####L###%#####L#####c#####L#####......$$$.#',
    '#.........#.....................#..........#',
    '#...$$$$$b#...................$.#y........S#',
    '#.$.......d.$.................$.=#%#w###w###',
    '#.$.......#.$.................$.=,,,,,,,,,,#',
    '#.$.......#.$.................$.d,$$$$$$$$,#',
    '#H........#.$...$$$$$$$$$$$...$.=,,,,,,,,,,#',
    '#.........#.....................=,,,,,,,,,,#',
    '##w##d#############....########e#,H,,,,,,,,#',
    '#.........#H...#................#,,,,,,,,,,#',
    '#.+....$..#....#................#,,,,,,,,,,#',
    '#..$...$..#H...#....$...........#,,,,,,,,H,#',
    '#..$...$..#....#....$...........#,,,,,,,,,,#',
    'i..$...$..###d##....$...........d,,$$$$$$,,#',
    '#..$...$..d.........$...........#,,,,,,,,,,#',
    '#..$.....H#.$$$$$$$.$...$$$$$$$.#,,,H,,,,,+#',
    '#u........#.........$...........#,,,,,,,,,,#',
    '#####d##w#####w#####d#d####w##########L#####',
    '#,,,,,,,,,,$$$$$$$$,,,,$$$$$$$$$,$$$$$,,,,,#',
    '#,,E,,PPPP,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#',
    '#,,,,,,,,,,,,,,,,,,,,,H,,,,,,,,,,,,,,,,,,,,#',
    '############################################',
  ],
  rooms: [
    { name: 'SECURITY', x: 1, y: 1, w: 9, h: 5, floor: 'concrete', light: '#9fc7ff' },
    { name: 'CASHIER', x: 11, y: 1, w: 10, h: 5, floor: 'marble', light: '#ffe6a8' },
    { name: 'COUNTING ROOM', x: 22, y: 1, w: 10, h: 5, floor: 'wood', light: '#ffd28a' },
    { name: 'MANAGER’S OFFICE', x: 33, y: 1, w: 10, h: 8, floor: 'carpet', light: '#ffc98a', tint: '#2f5b4a' },
    { name: 'VELVET BAR', x: 1, y: 7, w: 9, h: 7, floor: 'wood', light: '#ff9fb0' },
    { name: 'CASINO FLOOR', x: 11, y: 7, w: 21, h: 7, floor: 'carpet', light: '#ffb36b', tint: '#7a1f35' },
    { name: 'KITCHEN', x: 1, y: 15, w: 9, h: 8, floor: 'tile', light: '#e8f4ff' },
    { name: 'LOBBY', x: 11, y: 15, w: 21, h: 8, floor: 'marble', light: '#fff0cc' },
    { name: 'CLOAKROOM', x: 11, y: 15, w: 4, h: 4, floor: 'wood', light: '#ffd9a8' },
    { name: 'COURTYARD', x: 33, y: 10, w: 10, h: 13, floor: 'grass', light: '#b8f0c0' },
    { name: 'VALET LOT', x: 1, y: 24, w: 42, h: 3, floor: 'asphalt', light: '#9fb4d0' },
  ],
  props: [
    ['van', 1, 24, 2, 2], ['car', 24, 26, 2, 1], ['car', 34, 26, 2, 1], ['tree', 13, 26], ['tree', 30, 26], ['tree', 41, 26], ['lamp', 10, 24], ['lamp', 32, 24], ['bench', 17, 26, 2, 1],
    ['desk', 6, 1, 3, 1], ['server', 1, 1], ['server', 1, 2], ['locker', 9, 1], ['locker', 9, 2], ['chair', 7, 2],
    ['bar', 1, 7, 4, 1], ['piano', 7, 7, 2, 1], ['table', 4, 10], ['table', 7, 10], ['table', 4, 12], ['table', 7, 12], ['sofa', 6, 13, 3, 1],
    ['counter', 4, 17, 1, 4], ['counter', 6, 17, 1, 4], ['crate', 8, 21], ['barrel', 7, 22], ['shelf', 6, 15, 3, 1],
    ['locker', 14, 15], ['locker', 14, 16], ['rug', 12, 16, 2, 2],
    ['counter', 24, 16, 4, 1], ['fountain', 25, 18, 2, 2], ['statue', 16, 16], ['plant', 31, 15], ['plant', 16, 22], ['plant', 31, 22], ['rug', 18, 16, 5, 4],
    ['slot', 12, 7], ['slot', 13, 7], ['slot', 14, 7], ['slot', 17, 7], ['slot', 18, 7], ['slot', 19, 7], ['slot', 23, 7], ['slot', 24, 7], ['slot', 25, 7], ['slot', 29, 7], ['slot', 30, 7], ['slot', 31, 7],
    ['roulette', 14, 9, 2, 2], ['roulette', 26, 9, 2, 2], ['cards', 18, 10, 2, 1], ['cards', 23, 10, 2, 1], ['plant', 11, 13], ['plant', 31, 13], ['sofa', 28, 13, 2, 1],
    ['counter', 12, 4, 3, 1], ['counter', 16, 4, 4, 1], ['shelf', 14, 1, 4, 1],
    ['table', 24, 1, 4, 1], ['shelf', 22, 1], ['crate', 29, 4],
    ['bookcase', 33, 1, 3, 1], ['desk', 39, 3, 3, 1], ['rug', 37, 5, 4, 2], ['sofa', 34, 5, 1, 2, 1], ['plant', 42, 1], ['lamp', 36, 4],
    ['fountain', 37, 15, 2, 2], ['tree', 35, 12], ['tree', 40, 13], ['tree', 34, 17], ['tree', 42, 12], ['flowerbed', 39, 21, 2, 1], ['bench', 40, 15, 1, 2, 1],
  ],
  legend: {
    a: { kind: 'terminal', label: 'Vault security', circuit: 'vault' },
    b: { kind: 'terminal', label: 'Floor cameras', circuit: 'floor' },
    c: { kind: 'camera', label: 'Casino camera', circuit: 'floor', facing: 'S' },
    e: { kind: 'camera', label: 'Lobby camera', circuit: 'floor', facing: 'S' },
    i: { kind: 'camera', label: 'Kitchen camera', circuit: 'floor', facing: 'E' },
    f: { kind: 'camera', label: 'Counting camera', circuit: 'vault', facing: 'S' },
    g: { kind: 'camera', label: 'Office camera', circuit: 'vault', facing: 'W' },
    z: { kind: 'laser', label: 'Ledger beam', circuit: 'vault', facing: 'S' },
    v: { kind: 'vent', label: 'Air duct', pair: 'u' }, u: { kind: 'vent', label: 'Air duct', pair: 'v' },
    x: { kind: 'vent', label: 'Cash duct', pair: 'y' }, y: { kind: 'vent', label: 'Cash duct', pair: 'x' },
  },
};
