/* Bracket Brawl content banks (server only; never imported by client code). Every prompt and house answer is original. */

/** A Standard prompt with two house answers written for it (generic house answers fill any other empty slots). */
export type Standard = { text: string; house: readonly string[]; adult?: true };
export type Blind = { cat: string; prompt: string; adult?: true };
/** Smackdown: everyone answers `ask` (part one); each bracket round is judged by a new question (part two, the last is the final's). */
export type Smack = { cat: string; ask: string; judges: readonly [string, string, string, string]; adult?: true };

type Row = readonly [text: string, house1: string, house2: string];
const standard = (rows: readonly Row[], adult = false): Standard[] => rows.map(([text, ...house]) => ({ text, house, ...(adult ? { adult: true as const } : {}) }));

export const STANDARD: readonly Standard[] = [
  ...standard([
    ['The worst thing to hear from your pilot', 'Anyone know where the brakes are?', 'Fun fact: this is my first time'],
    ['A rejected name for a breakfast cereal', 'Soggy Regret Flakes', 'Crunchy Mystery Bits'],
    ['What your dog writes in its diary', 'Postman spotted. Again. Furious.', 'Ate a sock. Zero regrets.'],
    ['The worst thing to say in a job interview', 'I mostly came for the free biscuits', 'My biggest weakness is Mondays'],
    ['A terrible name for a superhero', 'Captain Mild Inconvenience', 'The Damp Avenger'],
    ['The worst flavour for a birthday cake', 'Lukewarm tuna surprise', 'Toothpaste and regret'],
    ['What a ghost does on its day off', 'Rattles its chains at the gym', 'Haunts the self-checkout'],
    ['A terrible thing to engrave on a trophy', 'Participation, technically', 'Best of the rest, I suppose'],
    ['The worst place for a first date', 'A dentist’s waiting room', 'The queue at the tax office'],
    ['Something you should never shout in a library', 'FIRE SALE ON BOOKMARKS!', 'Who wants to hear me yodel?'],
    ['A rejected theme for a kid’s birthday party', 'Tax Season Fun Day', 'Beige: A Celebration'],
    ['The worst thing to find in your shoe', 'A tiny, furious crab', 'Somebody else’s foot'],
    ['A sure sign your house is haunted', 'The kettle boils itself at 3 a.m.', 'Your cat salutes the wall'],
    ['The real reason the chicken crossed the road', 'Witness protection', 'It owed the duck money'],
    ['What a robot dreams about', 'Becoming a toaster', 'A whole day with no updates'],
    ['The least helpful thing a sat-nav could say', 'Good luck out there.', 'You’re on your own now, pal'],
    ['A terrible slogan for a funeral home', 'See you soon!', 'Dying to meet you'],
    ['The worst name for a pet goldfish', 'Dinner', 'Mr Flushy'],
    ['What your fridge really thinks of you', 'Close the door, you animal', 'Again? It’s 2 a.m.'],
    ['A bad excuse for missing school', 'My shadow ran away', 'The goat ate my bus pass'],
    ['The worst prize on a game show', 'A lifetime supply of gravel', 'A long hug from the host'],
    ['An event that should be added to sports day', 'Competitive napping', 'The egg-and-spoon marathon'],
    ['The worst thing a magician could pull out of a hat', 'Your mortgage statement', 'A very cross badger'],
    ['Something you never want to hear from your barber', 'Oops.', 'Have you considered a hat?'],
    ['A terrible name for a boat', 'The Leaky Lady', 'Probably Fine II'],
    ['What the pigeons are secretly planning', 'A takeover of the bread shop', 'Total statue domination'],
    ['A bad name for a perfume', 'Eau de Wet Dog', 'Essence of Bus Seat'],
    ['The worst thing to bring to a picnic', 'A loose swarm of bees', 'A bucket of live eels'],
    ['A useless prediction from a fortune teller', 'You will eat soup', 'Something will happen. Eventually.'],
    ['A secret your teddy bear is keeping', 'It’s been to prison', 'It can talk. It chooses not to.'],
    ['The worst thing to say at a birthday party', 'Wow, you look so much older', 'I brought my own, better cake'],
    ['The most useless superpower', 'Turning slightly damp at will', 'Talking to pigeons, who ignore you'],
    ['What aliens would find most confusing about Earth', 'Cats', 'Paying for water in bottles'],
    ['A terrible name for a hotel', 'The Bedbug Inn', 'Hotel Probably Not Haunted'],
    ['The worst thing to hear from your surgeon', 'Has anyone seen my watch?', 'Right, which side was it again?'],
    ['The worst ice-cream flavour', 'Pickled Onion Swirl', 'Garlic Fudge Ripple'],
    ['A rejected name for a dinosaur', 'Tinyarmsasaurus', 'Gary'],
    ['The worst thing to find under your bed', 'A second, smaller bed', 'A note saying “nice room”'],
    ['Something a pirate would put on their CV', 'Excellent with parrots', 'Fluent in Arr'],
    ['The worst way to wake someone up', 'An air horn and a trombone', 'A goose, inside the duvet'],
    ['A sign you’ve been at the zoo too long', 'The penguins know your name', 'A gorilla is grooming you'],
    ['The worst name for a gym', 'Sweaty Regrets', 'The Pain Palace'],
    ['What the moon gets up to when nobody’s looking', 'Practises its moonwalk', 'Naps behind a cloud'],
    ['The worst thing to hear at a theme park', 'This ride runs on hope', 'Last one off has to clean up'],
    ['Something you should never microwave', 'Your phone', 'A whole watermelon'],
    ['An honest slogan for a fast-food chain', 'Food-adjacent since 1987', 'You’ll be hungry again in an hour'],
    ['The worst name for a rock band', 'The Polite Disagreements', 'Mild Salsa'],
    ['Something you never want your grandma to see', 'You, dancing alone in the kitchen', 'Your bedroom floor'],
    ['The worst thing to find in a hotel room', 'The previous guest, still checked in', 'A sign-up sheet for the sauna'],
    ['What your cat says about you behind your back', 'Adequate food servant', 'Keeps sitting in my chair'],
    ['A bad name for a fire-breathing dragon', 'Sparky McSneeze', 'Heartburn'],
    ['The worst thing to wear to a wedding', 'A full suit of armour', 'A T-shirt that says “I object”'],
    ['A terrible thing to pipe on a cake', 'Congrats on the parole', 'It’s mostly cardboard'],
    ['The real reason the bus is late', 'The driver stopped for a nap', 'It took a wrong turn into 1998'],
    ['What the scarecrow is actually scared of', 'Crows with confidence', 'Bonfire night'],
    ['The worst thing to say to a police officer', 'Catch me if you can!', 'You look exactly like my nan'],
    ['A terrible name for a holiday resort', 'Damp Sands Retreat', 'Mosquito Bay'],
    ['The worst thing to win in a raffle', 'A slightly used plaster', 'Someone else’s tax return'],
    ['Something a snowman worries about', 'Spring', 'Dogs'],
    ['A terrible job for a vampire', 'Sunscreen salesperson', 'Garlic farmer'],
    ['The worst thing to hear on a baby monitor', '“Hello? Is this thing on?”', 'Heavy breathing and a kazoo'],
    ['The worst sandwich filling', 'Wet cardboard and jam', 'Cold spaghetti and custard'],
    ['A bad name for a detective', 'Inspector Clueless', 'Detective Maybe'],
    ['What penguins get up to at parties', 'A conga line, but sliding', 'Fish-based karaoke'],
    ['The worst thing a teacher could say on day one', 'I failed this subject twice', 'Who wants to see my rash?'],
    ['The worst thing to hear from a waiter', 'The chef is crying again', 'The fish is still deciding'],
    ['Something you’d find in a wizard’s bin', 'A half-eaten toad', 'A wand with flat batteries'],
    ['The worst time to get the giggles', 'In a lift with your boss', 'At a mime’s funeral'],
    ['A terrible name for a football team', 'The Mild Ambitions', 'FC Nil-Nil'],
    ['The worst thing to bring to show-and-tell', 'Grandad’s false teeth', 'A jar of live wasps'],
    ['What giraffes complain about', 'Turtleneck shopping', 'Being asked about the weather up there'],
    ['A gadget nobody needs', 'A toaster for one crumb', 'An umbrella for your sandwich'],
    ['Something you should never say on a rollercoaster', 'I think my belt is loose', 'Wait, I left the oven on'],
    ['A terrible name for a spa treatment', 'The Gravel Scrub', 'Mud, but angrier'],
    ['The secret ingredient in Grandma’s cookies', 'Pure spite', 'A pinch of gravel'],
    ['The worst thing to say when you meet a celebrity', 'I thought you’d be taller', 'Do you know my cousin Gary?'],
    ['A bad name for a bakery', 'The Stale Loaf', 'Crumbs & Regrets'],
    ['The worst way to start a speech', 'Sorry in advance', 'I’ve never met any of you'],
    ['The worst thing to step on barefoot', 'A plug', 'A sleeping hedgehog'],
    ['A terrible name for a rescue dog', 'Trouble', 'Mr Chews-Everything'],
    ['Something a T. rex finds really hard', 'Clapping', 'Making the bed'],
    ['The worst thing to find in a time capsule', 'A phone bill from 1992', 'An angry note from your past self'],
    ['A terrible name for a cruise ship', 'The Seasick Queen', 'SS Iceberg Magnet'],
    ['The worst thing to hear from your new neighbour', 'I play the drums at dawn', 'I’ve got forty cats and a dream'],
    ['A strange thing to collect', 'Belly-button fluff', 'Other people’s receipts'],
    ['What the Loch Ness Monster does all day', 'Avoids cameras', 'Waits for a decent sandwich'],
    ['The worst thing a smart speaker could say', 'I heard that.', 'Ordering 400 rubber ducks now'],
    ['The worst lunchbox surprise', 'A single raw onion', 'A note that just says “why?”'],
    ['A bad name for a hair salon', 'The Mullet Mill', 'Bald Ambitions'],
    ['Something you’d hear at a very bad circus', 'The lion has a cold', 'Please don’t feed the clown'],
    ['The worst thing to forget on holiday', 'Your passport and your dignity', 'The children'],
    ['What a hamster thinks about on its wheel', 'Where am I even going?', 'Cardio is a lie'],
    ['The worst first line of a love letter', 'To whom it may concern', 'You’ll do.'],
    ['A terrible thing to say in a museum', 'Can I touch the mummy?', 'I’ve got one of these at home'],
    ['A rejected name for a planet', 'Steve', 'Big Wet Rock'],
    ['The worst way to end a phone call', '“Love you!” (to your boss)', 'Okay, bye, see you, bye, bye'],
    ['What the tooth fairy does with all the teeth', 'Builds a tiny castle', 'Sells them to sharks'],
    ['The worst thing to find in a swimming pool', 'A lifeguard who can’t swim', 'Bubbles. Just bubbles.'],
    ['The worst thing to say on your first day at school', 'I’m the new head teacher', 'Who’s in charge of snacks?'],
    ['A terrible name for a video game', 'Grand Theft Bicycle', 'Call of Laundry'],
    ['The least scary thing in a haunted house', 'A slightly cross librarian', 'A box of kittens'],
    ['Something you should never say to a genie', 'Just surprise me', 'I wish you’d stop granting wishes'],
    ['What a pigeon orders at a café', 'A crumb, to go', 'One of everything off the floor'],
    ['The worst name for a restaurant', 'Food Poisoning Palace', 'Eat at Your Own Risk'],
    ['The worst thing to discover halfway up a mountain', 'You’re wearing slippers', 'The path is a roundabout'],
    ['The worst thing to hear at the vet', 'He’s actually a raccoon', 'You’ll need a bigger lead'],
    ['An unusual thing to keep in your pocket', 'A spare sausage', 'A tiny portrait of your rival'],
    ['The worst motto for a school', 'Try, or don’t.', 'We have a roof'],
    ['Something you shouldn’t put on a pizza', 'Toothpaste', 'Gummy worms and regret'],
    ['What a snail would brag about', 'I’ve been to the end of the garden', 'Shell’s fully paid off'],
    ['A rejected name for a new country', 'Mostly Puddles', 'The United States of Hmm'],
    ['The worst thing to say at a wedding', 'Are you sure about this?', 'I’ve already eaten the cake'],
    ['A terrible tagline for a dating show', 'Love is blind. So are we.', 'Find love, or at least a lift home'],
    ['The worst noise to hear on an aeroplane', 'A goat', 'Clapping from the cockpit'],
    ['Something you’d never want to share', 'Your toothbrush', 'The last chip'],
    ['The worst place to propose', 'At a funeral', 'Halfway through a bank robbery'],
    ['A terrible name for an energy drink', 'Sleepy Juice', 'Mild Buzz'],
    ['Where the missing socks actually go', 'A beach resort for one', 'The washing machine eats them'],
    ['What your shadow does at night', 'Goes clubbing', 'Writes poems about you'],
    ['The worst thing to say at a sleepover', 'I snore like a chainsaw', 'I brought my ventriloquist dummy'],
    ['A bad name for a lifeboat', 'Not Today', 'The Sinker'],
    ['The worst thing to get in the post', 'A brick with your name on it', 'A bill from a wizard'],
    ['An honest job title for your office job', 'Senior Email Ignorer', 'Head of Pretending to Type'],
    ['The worst thing to shout at a quiet golf course', 'FORE! And five! And six!', 'Who wants a sing-song?'],
    ['A bad thing to name a pet tortoise', 'Speedy', 'Lightning Bolt'],
  ]),
  ...standard([
    ['The worst thing to hear from your date', 'I brought my mum', 'So, about my parole officer…'],
    ['A cocktail that guarantees a bad night', 'The Regret Spritzer', 'Tequila Mistakes'],
    ['What you really do at the office party', 'Steal the good sausage rolls', 'Cry in the stationery cupboard'],
    ['The worst thing to text your ex at 2 a.m.', '“U up? Asking for a goose”', '“I still have your blender”'],
    ['The worst excuse for being hungover at work', 'It was a food-related accident', 'I’m allergic to Thursdays'],
    ['The worst thing to say in your wedding vows', 'I suppose you’ll do', 'Until someone better comes along'],
    ['An honest name for a nightclub', 'The Sticky Floor', 'The Bad Decisions Lounge'],
    ['What you whisper to your phone after midnight', 'Please don’t let me order pizza', 'Don’t let me text anyone'],
    ['The worst chat-up line', 'Nice shoes. Want to split a pension?', 'Do you like soup? Me too.'],
    ['An honest dating profile bio', 'Owns three spoons', 'Will cancel plans for a nap'],
    ['The worst thing to wake up next to', 'A full English breakfast', 'Your landlord'],
    ['What the bouncer really thinks of you', 'Nice try, Gary', 'Not in those shoes'],
    ['A terrible name for a wine', 'Château Headache', 'Cheap and Cheerful Red'],
    ['The worst thing to hear through the hotel wall', 'A tuba lesson', 'Someone shouting “Again!”'],
    ['The worst thing to say at a hen party', 'Who invited my mum?', 'I’ve booked us a museum tour'],
    ['The worst thing to discover after a night out', 'A new tattoo of a ferret', 'You bought a boat'],
    ['A rejected name for a hangover cure', 'Hair of the Goose', 'Liquid Regret'],
    ['The worst thing to say on a second date', 'I’ve told my mum all about you', 'Shall we get matching tattoos?'],
    ['Something you’d find in a bachelor’s fridge', 'One lemon, alone', 'A sock (why?)'],
    ['The real reason the party ended early', 'Someone found the karaoke', 'The neighbours called the army'],
    ['What your liver is thinking right now', 'Not again', 'I quit'],
  ], true),
];

/** House answers for any Standard prompt once its own two are used. */
export const GENERIC: readonly string[] = [
  'A goose in a business suit', 'Three raccoons and a dream', 'My nan’s secret lasagne', 'A mysteriously warm sock', 'An interpretive dance about tax',
  'A haunted hairdryer', 'Glitter. Everywhere. Forever.', 'The 3 a.m. fridge raid', 'A passive-aggressive sticky note', 'An emotional support cabbage',
  'A sorcerer called Brenda', 'A gift voucher for gravel', 'A furious little ukulele', 'Lukewarm beans', 'A volcano with manners',
  'Lord Wigglebottom of Leeds', 'Nine hundred rubber ducks', 'A llama with a lawyer', 'Dad’s karaoke playlist', 'A trampoline with trust issues',
  'The noise a dial-up modem makes', 'A box of angry bees', 'Light-up trainers for grown-ups', 'A seasick sea captain', 'A moustache with ambition',
  'Gravy. Gallons of gravy.', 'A goat with a credit card', 'The pigeon who runs the town', 'A doorbell that knows too much', 'Competitive yodelling',
  'A toaster with feelings', 'A mild sense of dread', 'A bucket of spaghetti', 'Crocs at a wedding', 'A life-size cut-out of the vicar',
  'Grandad’s hidden biscuit tin', 'A confused flamingo', 'Seventeen tiny hats', 'An inflatable T. rex', 'A deflating bagpipe',
  'A squirrel life coach', 'The remote, down the sofa', 'A cursed garden gnome', 'Hot custard', 'A disco ball the size of a car',
  'Ham. So much ham.', 'A kazoo solo', 'An awkward high five', 'A haunted Wi-Fi router', 'A snail on a skateboard',
  'Wet cardboard', 'An overconfident toddler', 'A tuba full of soup', 'The neighbour’s leaf blower', 'A badger in a bow tie',
  'Nachos at a funeral', 'Someone else’s grandma', 'A suspicious pie', 'A jellyfish in a tutu', 'A mime with a megaphone',
  'Vintage yoghurt', 'A lifetime supply of paper clips', 'A llama at a job interview', 'A giant novelty cheque', 'Two ferrets in a coat',
  'A cheese that whispers', 'The ghost of a sandwich', 'A dance-off with a heron', 'A banana with a grudge', 'Bagpipes at breakfast',
];

/** Category pools: Blind brackets answer the hint; Smackdown asks fit the category. House answers fill empty slots from here. */
export const CATEGORIES: Readonly<Record<string, { hint: string; house: readonly string[] }>> = {
  food: { hint: 'Name a food', house: ['Spaghetti hoops', 'A pickled egg', 'Cold pizza', 'Fish fingers', 'A lonely sprout', 'Mushy peas', 'Cheesy chips', 'A jacket potato', 'Banana bread', 'Spicy meatballs', 'Prawn cocktail', 'A soggy croissant', 'Blue cheese', 'Gravy'] },
  animal: { hint: 'Name an animal', house: ['A grumpy camel', 'A sloth', 'A goose', 'A wombat', 'An octopus', 'A hedgehog', 'A llama', 'A walrus', 'A pigeon', 'A badger', 'A flamingo', 'A hamster', 'A narwhal'] },
  job: { hint: 'Name a job', house: ['A dentist', 'A lollipop lady', 'A plumber', 'A lifeguard', 'A tax inspector', 'A clown', 'A dinner lady', 'A traffic warden', 'A zookeeper', 'A wedding planner', 'A dog groomer', 'A bin collector', 'A tour guide'] },
  object: { hint: 'Name a household object', house: ['A toaster', 'A spatula', 'The kettle', 'A sofa cushion', 'A rubber glove', 'A lava lamp', 'A doormat', 'The hoover', 'A tea towel', 'A colander', 'A rolling pin', 'An ironing board', 'The loo brush'] },
  history: { hint: 'Name a famous historical figure', house: ['Napoleon', 'Cleopatra', 'Julius Caesar', 'Genghis Khan', 'William Shakespeare', 'Queen Victoria', 'Leonardo da Vinci', 'Isaac Newton', 'Marie Curie', 'Henry VIII', 'Joan of Arc', 'Charles Darwin', 'Abraham Lincoln'] },
  place: { hint: 'Name a holiday destination', house: ['Blackpool', 'Paris', 'A caravan park', 'The Moon', 'A theme park', 'Majorca', 'Grandma’s spare room', 'A Scottish island', 'Las Vegas', 'A campsite in the rain', 'Iceland', 'The seaside', 'Venice'] },
  sport: { hint: 'Name a sport or game', house: ['Synchronised swimming', 'Darts', 'Lawn bowls', 'Chess', 'Ice hockey', 'Curling', 'Snooker', 'Wrestling', 'Hopscotch', 'Tug of war', 'Dodgeball', 'Ping-pong', 'Rugby'] },
  vehicle: { hint: 'Name a vehicle', house: ['A tractor', 'A double-decker bus', 'A unicycle', 'A submarine', 'A hot-air balloon', 'A milk float', 'A monster truck', 'A rowing boat', 'A shopping trolley', 'A tandem bicycle', 'An ice-cream van', 'A hovercraft', 'A golf buggy'] },
  clothing: { hint: 'Name an item of clothing', house: ['A onesie', 'Flip-flops', 'A bow tie', 'A bobble hat', 'Leg warmers', 'A kilt', 'Dungarees', 'A cardigan', 'A wetsuit', 'A sombrero', 'A cape', 'Wellies', 'A tutu'] },
  hobby: { hint: 'Name a hobby', house: ['Knitting', 'Birdwatching', 'Stamp collecting', 'Ballroom dancing', 'Fishing', 'Karaoke', 'Pottery', 'Bonsai trees', 'Juggling', 'Trainspotting', 'Baking', 'Metal detecting', 'Yoga'] },
  sound: { hint: 'Name a sound', house: ['A long, sad trombone', 'Squeaky floorboards', 'A car alarm', 'Dial-up internet', 'A goose honk', 'Whale song', 'Nails on a chalkboard', 'A cat sneeze', 'A whistling kettle', 'A drum solo', 'Fireworks', 'A dripping tap', 'A foghorn'] },
  monster: { hint: 'Name a mythical creature', house: ['A dragon', 'A unicorn', 'A troll', 'Bigfoot', 'A mermaid', 'A werewolf', 'A goblin', 'A yeti', 'The Loch Ness Monster', 'A vampire', 'A phoenix', 'A kraken', 'A zombie'] },
  fridge: { hint: 'Name something in your fridge', house: ['Half a lemon', 'Ancient ketchup', 'Mystery leftovers', 'Butter', 'A sad lettuce', 'Yoghurt', 'Orange juice', 'Pickles', 'Sausages', 'Cheddar', 'One egg', 'Hummus', 'Cold custard'] },
  body: { hint: 'Name a body part', house: ['An elbow', 'A big toe', 'Kneecaps', 'Earlobes', 'An eyebrow', 'The belly button', 'Nostrils', 'The funny bone', 'Knuckles', 'An armpit', 'The chin', 'Ankles', 'Eyelashes'] },
  feeling: { hint: 'Name a feeling', house: ['Mild panic', 'Pure joy', 'Jealousy', 'Embarrassment', 'Nostalgia', 'Hunger', 'Smugness', 'Boredom', 'Awkwardness', 'Excitement', 'Regret', 'Confusion', 'Sheer terror'] },
  power: { hint: 'Name a superpower', house: ['Invisibility', 'Flying', 'Super strength', 'Mind reading', 'Time travel', 'Talking to animals', 'Teleporting', 'Shape-shifting', 'X-ray vision', 'Super speed', 'Freezing time', 'Breathing underwater', 'Laser eyes'] },
  instrument: { hint: 'Name a musical instrument', house: ['The bagpipes', 'A triangle', 'The tuba', 'A kazoo', 'The violin', 'Bongo drums', 'A harp', 'The recorder', 'An accordion', 'A banjo', 'The trombone', 'Maracas', 'A grand piano'] },
  saying: { hint: 'Name something your parents always say', house: ['Money doesn’t grow on trees', 'Were you born in a barn?', 'Because I said so', 'Ask your father', 'Put a coat on', 'We’ll see', 'Turn that racket down', 'Is that what you’re wearing?', 'I’m not a taxi service', 'Who left the lights on?', 'Back in my day…', 'Don’t make me come up there', 'Mind your language'] },
  tool: { hint: 'Name a tool', house: ['A hammer', 'A spirit level', 'A chainsaw', 'A screwdriver', 'Duct tape', 'A wheelbarrow', 'A spanner', 'A leaf blower', 'Pliers', 'A tape measure', 'A ladder', 'A sledgehammer', 'A glue gun'] },
  toy: { hint: 'Name a toy', house: ['A yo-yo', 'A rubber duck', 'A teddy bear', 'Building blocks', 'A jack-in-the-box', 'A skipping rope', 'A slinky', 'A spinning top', 'A kite', 'Marbles', 'A rocking horse', 'A water pistol', 'A toy robot'] },
};

const blind = (cat: string, prompts: readonly string[], adult = false): Blind[] => prompts.map(prompt => ({ cat, prompt, ...(adult ? { adult: true as const } : {}) }));
/** Blind: everyone answers the category, then the real prompt lands. */
export const BLIND: readonly Blind[] = [
  ...blind('food', ['Something you’d yell at a seagull', 'The name of your future band', 'What you’d whisper during a wedding', 'A terrible name for a baby', 'The password to a villain’s secret lair']),
  ...blind('animal', ['What you’d call your boss by accident', 'Your next tattoo', 'The thing hiding under your bed', 'What you’d bring to a job interview', 'A brand-new flavour of ice cream']),
  ...blind('job', ['The worst thing to find in your soup', 'What you shout when you stub your toe', 'The title of your autobiography']),
  ...blind('object', ['Your wrestling name', 'Your new best friend', 'What you’d name your firstborn', 'The surprise guest at your birthday', 'The perfect thing to bring on a first date']),
  ...blind('history', ['Something you’d find in a cereal box', 'The worst thing to hear from your dentist', 'A new flavour of crisps', 'A good name for a pet goldfish']),
  ...blind('place', ['Your middle name', 'A new dance move', 'What you’d chant at a football match']),
  ...blind('sport', ['A good name for a perfume', 'The secret to a happy marriage', 'What you do when nobody’s watching']),
  ...blind('vehicle', ['Your spirit animal', 'What you’d bring to a sleepover', 'Your pet name for your other half']),
  ...blind('clothing', ['The name of a newly discovered planet', 'Your superhero sidekick', 'The worst thing to say at a funeral']),
  ...blind('hobby', ['A good name for a dog', 'The real reason the dinosaurs died out', 'The cure for hiccups']),
  ...blind('sound', ['Your first dance at your wedding', 'The name of your gym', 'What you’d say to a king']),
  ...blind('monster', ['Your ideal flatmate', 'The new school mascot', 'The best way to relax after work']),
  ...blind('fridge', ['What you’d take to a desert island', 'The answer to life’s biggest question', 'Your lucky charm']),
  ...blind('body', ['A bad name for a restaurant', 'A rejected name for a theme park', 'Your rapper name']),
  ...blind('feeling', ['A new flavour of toothpaste', 'The name of your yacht', 'Your football team’s name']),
  ...blind('power', ['The worst gift for a grandparent', 'What’s for dinner tonight', 'The chore you hate most']),
  ...blind('instrument', ['Your nickname at school', 'What you’d hide in a time capsule', 'A new type of yoga']),
  ...blind('saying', ['The motto on your family crest', 'What the dog is thinking right now', 'The slogan of a brand-new airline']),
  ...blind('tool', ['Your dream holiday', 'The first line of a love poem', 'A new breakfast cereal']),
  ...blind('toy', ['What’s inside your boss’s briefcase', 'Your next career move', 'The ingredient that makes a cake great']),
  ...blind('food', ['What you’d whisper to someone in bed'], true),
  ...blind('vehicle', ['Your nickname in the bedroom'], true),
  ...blind('feeling', ['How you feel the morning after the office party'], true),
  ...blind('tool', ['What your ex was like as a partner'], true),
];

type Judges = readonly [string, string, string, string];
const smack = (cat: string, ask: string, judges: Judges, adult = false): Smack => ({ cat, ask, judges, ...(adult ? { adult: true as const } : {}) });
/** Smackdown: part one is the ask; part two is a new judging question each bracket round (the last one decides the final). */
export const SMACKDOWN: readonly Smack[] = [
  smack('animal', 'Name an animal', ['Which would make the better flatmate?', 'Which would you trust to babysit?', 'Which would win a dance-off?', 'Which would be the worst wedding guest?']),
  smack('history', 'Name a famous historical figure', ['Who would win a pie-eating contest?', 'Who would be the worst flatmate?', 'Who would survive longest in a zombie film?', 'Who would give the best hug?']),
  smack('object', 'Name a household object', ['Which would be the worst pillow?', 'Which would be the best weapon in a food fight?', 'Which would you least want to sit on?', 'Which would make the best pet?']),
  smack('food', 'Name a food', ['Which would be the worst to throw at a wedding?', 'Which would make the best hat?', 'Which would be scariest to find in your bed?', 'Which would you marry?']),
  smack('job', 'Name a job', ['Which would be worst at karaoke?', 'Which would you want on your quiz team?', 'Which would last longest on a desert island?', 'Which would make the best supervillain?']),
  smack('monster', 'Name a mythical creature', ['Which would be best at tidying up?', 'Which would be the worst dentist?', 'Which would win a bake-off?', 'Which would you take home to meet your parents?']),
  smack('vehicle', 'Name a vehicle', ['Which would be worst for a first date?', 'Which would win a staring contest?', 'Which would make the best bedroom?', 'Which would you ride into battle?']),
  smack('clothing', 'Name an item of clothing', ['Which would be worst to wear to a job interview?', 'Which would be the best hiding place?', 'Which would make the worst sleeping bag?', 'Which would you wear to meet a king?']),
  smack('sport', 'Name a sport', ['Which would be best played underwater?', 'Which would be funniest in slow motion?', 'Which would be worst to play in a lift?', 'Which should replace school exams?']),
  smack('hobby', 'Name a hobby', ['Which would be worst to do on a plane?', 'Which would impress a cat?', 'Which is the best way to settle an argument?', 'Which would make the best TV show?']),
  smack('power', 'Name a superpower', ['Which would be most useful at the supermarket?', 'Which would be worst for a toddler to have?', 'Which would get you fired fastest?', 'Which would win a talent show?']),
  smack('instrument', 'Name a musical instrument', ['Which would be the worst alarm clock?', 'Which would make the best weapon?', 'Which would be hardest to play on a rollercoaster?', 'Which would you want played at your funeral?']),
  smack('place', 'Name a holiday destination', ['Which would be worst for a honeymoon?', 'Which would a pirate like best?', 'Which would be best for a school trip?', 'Which would you send your worst enemy to?']),
  smack('fridge', 'Name something in your fridge', ['Which would be the worst face mask?', 'Which would survive the apocalypse?', 'Which would win a beauty contest?', 'Which would you hand to a burglar?']),
  smack('body', 'Name a body part', ['Which would make the worst doorbell?', 'Which would be funniest to lose?', 'Which deserves its own holiday?', 'Which would win an arm wrestle?']),
  smack('feeling', 'Name a feeling', ['Which would be the worst flavour of crisps?', 'Which would make the best perfume?', 'Which would be the scariest pet?', 'Which belongs on a birthday card?']),
  smack('sound', 'Name a sound', ['Which would be the worst ringtone?', 'Which would make the best lullaby?', 'Which would scare off a burglar?', 'Which should play at your wedding?']),
  smack('toy', 'Name a toy', ['Which would be the worst bodyguard?', 'Which would make the best politician?', 'Which would survive a week in the jungle?', 'Which would you trust with a secret?']),
  smack('tool', 'Name a tool', ['Which would make the worst cutlery?', 'Which would be the best dance partner?', 'Which would be most useful on a date?', 'Which would you bring to a pillow fight?']),
  smack('saying', 'Name something your parents always say', ['Which would make the best tattoo?', 'Which would be the worst wedding vow?', 'Which would make the best band name?', 'Which should be carved on a monument?']),
  smack('animal', 'Name an animal you could beat in a fight', ['Which would be best at poker?', 'Which would make the best lawyer?', 'Which would hold the longest grudge?', 'Which would you crown ruler of the world?']),
  smack('job', 'Name a job you could never do', ['Which would be worst to do while sneezing?', 'Which is best done in pyjamas?', 'Which would make the best reality show?', 'Which would make your nan proudest?']),
  smack('food', 'Name a food you’d take to space', ['Which would float away first?', 'Which would aliens love most?', 'Which would be worst to eat in a spacesuit?', 'Which deserves a planet named after it?']),
  smack('object', 'Name something in a junk drawer', ['Which would be the worst key to the city?', 'Which would make the best phone?', 'Which would survive a dragon attack?', 'Which deserves its own museum?']),
  smack('history', 'Name someone famous from history', ['Who would be the worst at a sleepover?', 'Who would make the best football manager?', 'Who would cheat at board games?', 'Who would you want as a fairy godparent?']),
  smack('monster', 'Name a monster', ['Which would be best at hide-and-seek?', 'Which would make the worst lollipop lady?', 'Which would cry at sad films?', 'Which would win a beauty pageant?']),
  smack('clothing', 'Name something you wear', ['Which would be the worst parachute?', 'Which would be best at keeping secrets?', 'Which would win a fashion show on Mars?', 'Which would you want to be buried in?']),
  smack('vehicle', 'Name a way to get around', ['Which would be worst in a funeral procession?', 'Which would make the best bath?', 'Which would you take on a getaway?', 'Which would win a race to the shops?']),
  smack('hobby', 'Name a hobby your nan might have', ['Which would be the worst Olympic sport?', 'Which would you take up in prison?', 'Which would scare a ghost?', 'Which would make you famous?']),
  smack('sound', 'Name a noise you’d hear at the zoo', ['Which would be the worst doorbell?', 'Which would win a singing contest?', 'Which would make the best national anthem?', 'Which should announce your arrival?']),
  smack('toy', 'Name a toy from your childhood', ['Which would make the worst getaway driver?', 'Which would win a game of chess?', 'Which would be the best boss?', 'Which deserves a statue?']),
  smack('fridge', 'Name a late-night snack', ['Which would be worst to find in your bed?', 'Which is the most romantic?', 'Which would ruin a first kiss?', 'Which would you take home after the pub?'], true),
  smack('job', 'Name a job you could do hungover', ['Which has the wildest office party?', 'Which would be the worst one-night stand?', 'Which would be the best wingman?', 'Which would you drunk-text at 3 a.m.?'], true),
  smack('place', 'Name a place for a stag or hen do', ['Which has the sketchiest nightclub?', 'Which would be the best for a dirty weekend?', 'Which would you least want to wake up in?', 'Where would you get the worst tattoo?'], true),
  smack('saying', 'Name a classic telling-off', ['Which would be the worst thing to say in bed?', 'Which would make the best drunk tattoo?', 'Which would ruin a wedding speech?', 'Which would you shout at last orders?'], true),
];

export const standardPool = (family: boolean) => family ? STANDARD.filter(p => !p.adult) : STANDARD;
export const blindPool = (family: boolean) => family ? BLIND.filter(p => !p.adult) : BLIND;
export const smackPool = (family: boolean) => family ? SMACKDOWN.filter(p => !p.adult) : SMACKDOWN;
