/* Comment Section content banks (server only; never imported by client code). Every question, format, twist and reply is original. */
import type { Format, Kind, Reply } from './types';

/** Innocent personal questions: honest answers make the best raw material for a twist. */
export const QUESTIONS: readonly string[] = [
  'How do you feel about your morning routine?', 'What’s the best way to spend a rainy Sunday?', 'Describe your ideal sandwich.',
  'What’s something you’re secretly proud of?', 'How do you feel about your hair right now?', 'What did you have for breakfast today?',
  'What’s your favourite thing about your home?', 'How would your friends describe your cooking?', 'What’s the last thing you bought online?',
  'What do you do when you can’t sleep?', 'Describe your perfect holiday.', 'What’s your go-to karaoke song, and why?',
  'How do you feel about Mondays?', 'What’s your favourite smell?', 'What’s a skill you wish you had?',
  'How do you relax after a long day?', 'What’s the best gift you’ve ever received?', 'Describe your first bike or car.',
  'What’s your favourite way to eat potatoes?', 'What always makes you laugh?', 'How do you feel about camping?',
  'What do you think about breakfast for dinner?', 'What’s the most useful thing in your kitchen?', 'Describe your dream house.',
  'What’s your favourite board game, and why?', 'What did you want to be when you grew up?', 'How do you feel about your neighbours?',
  'What’s your favourite season, and why?', 'What are you doing this weekend?', 'What’s the nicest thing a stranger has done for you?',
  'Describe your desk or workspace.', 'What’s your favourite childhood memory?', 'What do you sing in the shower?',
  'How do you feel about exercise?', 'What’s your hidden talent?', 'How do you take your tea or coffee?',
  'What’s your favourite animal, and why?', 'What would you do with a free afternoon?', 'What’s the best advice you’ve ever been given?',
  'How do you feel about gardening?', 'What do you always carry with you?', 'How would you describe your dance moves?',
  'What’s your favourite family tradition?', 'What’s the last thing that made you really happy?', 'Describe your perfect Saturday morning.',
  'How do you feel about long car journeys?', 'What’s the best meal you’ve ever had?', 'What’s your favourite thing to do at the beach?',
  'How tidy is your bedroom right now?', 'What’s your favourite word?', 'What hobby would you love to try?',
  'How do you feel about surprises?', 'What do you like most about your best friend?', 'What’s the last show you binge-watched?',
  'How would you describe your fashion sense?', 'What’s your favourite snack?', 'How do you like to celebrate your birthday?',
  'What’s your favourite thing about winter?', 'What food could you never give up?', 'How do you feel about public speaking?',
  'What’s your favourite room in your house?', 'What’s your proudest cooking moment?', 'How do you feel about your phone?',
  'What are you really good at?', 'What’s the first thing you do when you get home?', 'What’s your favourite holiday tradition?',
  'How do you feel about spiders?', 'What do you love about where you live?', 'Describe your perfect pizza.',
  'How do you organise your fridge?', 'What’s the best part of your day?', 'How do you feel about getting up early?',
  'What small thing makes your day better?', 'What’s your favourite thing to bake?', 'What’s the strangest thing in your bag right now?',
  'How do you feel about going to the dentist?', 'Describe your ideal pet.', 'What’s your favourite way to stay active?',
  'What song always cheers you up?', 'What do you do on a lazy day?', 'How do you feel about your handwriting?',
  'What’s your favourite sound?', 'What’s the best thing you’ve ever made with your hands?', 'How would you spend a surprise lottery win?',
  'What’s your favourite time of day, and why?', 'How do you feel about cold showers?', 'What do you think about while washing up?',
  'What do you wear on a day off?', 'How do you get along with your alarm clock?', 'Describe your best friend in a few words.',
  'What would your dream birthday cake look like?', 'What’s the most relaxing place you’ve ever been?', 'How do you feel about rollercoasters?',
  'What habit are you trying to build?', 'How do you get ready for a big day?', 'What’s your favourite thing about weekends?',
  'What’s your secret to a good night’s sleep?', 'What’s something you learned recently?', 'How do you feel about your daily commute?',
  'What’s the best thing about your family?', 'How do you rate your own cooking?', 'What’s your favourite ice cream flavour?',
  'What’s the nicest compliment you’ve ever had?', 'How do you feel about the colour of your walls?', 'What do you love doing with friends?',
  'What do you usually order at a café?', 'How would you describe your laugh?', 'Where’s your favourite place to go on holiday?',
  'What’s your go-to comfort food?', 'How do you keep your houseplants alive?', 'What’s your strategy at an all-you-can-eat buffet?',
  'How do you feel about group photos?', 'What do you love about your neighbourhood?', 'How do you feel about your feet?',
  'What’s the most impressive thing you can cook?', 'What’s your favourite way to say hello?', 'How do you feel when it snows?',
  'What do you do to cheer someone up?', 'Describe your perfect picnic.', 'What would you name a pet goldfish?',
  'What’s your favourite thing about summer?', 'How do you feel about mirrors first thing in the morning?', 'What’s the best outfit you own?',
  'What do you collect, or wish you collected?', 'What sport do you love to watch?', 'What do you usually do on a Friday night?',
  'How do you feel about cats?', 'How do you feel about dogs?', 'What’s your favourite thing to do on holiday?',
  'What do you honestly think of your singing voice?', 'How do you feel about your last haircut?', 'What would you pack first if you moved house tomorrow?',
  'How do you feel about doing laundry?', 'What’s your favourite part of a wedding?', 'Describe your ideal neighbour.',
  'What did you get up to last weekend?', 'Describe your favourite pair of shoes.', 'How would you describe your family group chat?',
  'What’s the best thing about your bed?', 'What do you think about when you’re stuck in traffic?', 'How do you feel about meeting new people?',
  'What’s your favourite fruit, and why?', 'What do you always forget to buy at the shops?', 'What’s your bedtime routine?',
  'What makes a perfect hot chocolate?', 'How do you feel about cleaning the bathroom?', 'What compliment would you love to hear more often?',
  'What do you like doing when it rains?', 'Describe your ideal day off.', 'How do you feel about your family’s cooking?',
  'What do you love about your grandparents?', 'How do you feel about museums?', 'What’s your most-used emoji, and why?',
  'How do you feel about swimming in the sea?', 'How do you pass the time on a long train ride?', 'What do you think of your neighbour’s garden?',
  'How good are you at keeping secrets?', 'What’s your favourite thing about being you?', 'How do you feel about your teeth?',
  'What’s your favourite kind of weather?', 'How do you like your eggs?', 'What’s your trick for staying warm in winter?',
  'How do you feel about clowns?', 'What’s the best thing you ate this week?', 'How do you feel about your car, or your bike?',
  'What’s the last thing you laughed at?', 'What’s your favourite way to spend a bank holiday?', 'How do you feel about bubble baths?',
  'What’s your proudest school memory?', 'How would you describe your sense of direction?', 'What’s your favourite thing to do in the garden?',
];
/** Cheekier questions: filtered when the host keeps family mode on. */
export const ADULT_QUESTIONS: readonly string[] = [
  'How did your last date go?', 'What do you wear to bed?', 'Describe your ideal date night.', 'How do you feel about your ex?',
  'What’s your hangover cure?', 'What do you do at a party where you know nobody?', 'How do you feel about skinny dipping?',
  'What’s your signature move on the dance floor at 2 a.m.?', 'How do you feel about your body hair?', 'What’s your favourite cocktail, and why?',
  'What happened at the last office party?', 'How do you feel about massages?', 'What do you read on the toilet?',
  'What’s the longest you’ve gone without a shower?', 'How do you feel about really tight trousers?',
];
export const questionPool = (family: boolean): string[] => family ? [...QUESTIONS] : [...QUESTIONS, ...ADULT_QUESTIONS];

export type FormatItem = Format & { id: string; adult?: true };
type Row = [ask: string, label: string, meta: string, adult?: 'adult'];
/** Format variants per fake app: [what the phone asks for, the label on the post, a decoration line]. */
const ROWS: Record<Kind, Row[]> = {
  review: [
    ['Name the product they reviewed', 'Product', '★☆☆☆☆ · Verified purchase'],
    ['Name the product they gave five stars', 'Product', '★★★★★ · Top reviewer'],
    ['Name the product they sent back', 'Returned item', '★★☆☆☆ · Refund pending'],
    ['Name the gift they bought their boss', 'Gift for my boss', '★★★☆☆ · Gift wrapped'],
    ['Name the product they ordered at 4 a.m.', 'Ordered at 4:02 a.m.', '★★★★☆ · Verified purchase'],
    ['Name the present they bought their grandma', 'Bought for Grandma', '★★☆☆☆ · Gift receipt'],
    ['Name the product they bought 500 of', 'Bulk order ×500', '★★★★★ · Subscribe & save'],
    ['Name the product that arrived broken', 'Arrived damaged', '★☆☆☆☆ · Complaint filed'],
    ['Name the product they bought for their pet', 'For my pet', '★★★★☆ · Pet supplies'],
    ['Name the product they bought for the hen party', 'Hen party supplies', '★★★★★ · Discreet packaging', 'adult'],
  ],
  photo: [
    ['Describe the photo they posted', 'Photo', 'Holiday album · 1 of 48'],
    ['Describe their new profile picture', 'New profile picture', 'Updated just now'],
    ['Describe their wedding photo', 'Wedding album', 'Tagged: the whole family'],
    ['Describe the photo they took at the zoo', 'At the zoo', 'Day out · 31 photos'],
    ['Describe the selfie they posted at 3 a.m.', 'Late-night selfie', 'Posted at 3:07 a.m.'],
    ['Describe their family reunion photo', 'Family reunion', 'Grandma shared this'],
    ['Describe their gym photo', 'Gym progress', 'Day 1 of 365'],
    ['Describe their throwback baby photo', 'Throwback Thursday', 'Shared from Mum’s album'],
    ['Describe the photo of their dinner', 'Tonight’s dinner', 'Home cooking · 2 hrs ago'],
    ['Describe the photo from the stag do', 'Stag do album', 'Uploaded by the best man', 'adult'],
  ],
  news: [
    ['Write the breaking news headline they commented on', 'Headline', 'BREAKING NEWS'],
    ['Write a local news headline', 'Headline', 'LOCAL NEWS'],
    ['Write a science news headline', 'Headline', 'SCIENCE'],
    ['Write a celebrity gossip headline', 'Headline', 'CELEBRITY'],
    ['Write a severe weather headline', 'Headline', 'WEATHER WARNING'],
    ['Write a sports headline', 'Headline', 'SPORT'],
    ['Write a health scare headline', 'Headline', 'HEALTH'],
    ['Write a police report headline', 'Headline', 'POLICE REPORT'],
  ],
  search: [
    ['Write what they searched right before this', 'Searched before', 'Search history · Today'],
    ['Write what they searched in a private window', 'Private window', 'Private browsing · 3:12 a.m.'],
    ['Write what they searched on the work laptop', 'Work laptop', 'Work account · 9:41 a.m.'],
    ['Write what they searched on Grandma’s computer', 'Grandma’s computer', 'Shared family computer'],
    ['Write what they searched from the hospital', 'Hospital Wi-Fi', 'Waiting room · Guest Wi-Fi'],
    ['Write what they searched during a wedding', 'During the vows', 'Silent mode · 2:15 p.m.'],
    ['Write what they searched on a first date', 'Under the table', 'Date night · 8:47 p.m.'],
    ['Write what they searched at the airport', 'Airport security', 'Gate 12 · Boarding now'],
    ['Write what they searched after the office party', 'The morning after', 'Search history · 6:03 a.m.', 'adult'],
  ],
  job: [
    ['Write the job title they applied for', 'Job title', 'Full time · Immediate start'],
    ['Write the volunteer role they applied for', 'Volunteer role', 'Unpaid · Bring your own snacks'],
    ['Write the zoo job they applied for', 'Zoo vacancy', 'Part time · Uniform provided'],
    ['Write the hospital night-shift job they applied for', 'Night shift', 'Nights · Must be calm'],
    ['Write the palace job they applied for', 'Royal household', 'Live-in · Discretion required'],
    ['Write the space agency job they applied for', 'Space agency', 'Off-planet · Relocation required'],
    ['Write the kids’ party job they applied for', 'Kids’ parties', 'Weekends · Own costume'],
    ['Write the internship they applied for', 'Internship', 'Unpaid · Great exposure'],
    ['Write the secret government job they applied for', 'Classified', 'Top secret · Shred after reading'],
  ],
  dating: [
    ['Finish their dating profile: “Looking for…”', 'Looking for', '29 · 2 km away'],
    ['Finish their dating profile: “My dealbreaker is…”', 'Dealbreaker', '33 · Online now'],
    ['Finish their dating profile: “Ideal first date…”', 'Ideal first date', '27 · 5 km away'],
    ['Finish their dating profile: “My mum says I’m…”', 'My mum says I’m', '31 · Verified'],
    ['Finish their dating profile: “Green flag…”', 'Green flag', '38 · 1 km away'],
    ['Finish their dating profile: “I’m weirdly into…”', 'Weirdly into', '26 · Active today'],
    ['Finish their dating profile: “Swipe right if you…”', 'Swipe right if you', '35 · 12 km away'],
    ['Finish their dating profile: “My hot take…”', 'Hot take', '30 · New here'],
  ],
  forum: [
    ['Write their thread title on the Home Repair board', 'Home Repair', '412 replies · Solved'],
    ['Write their thread title on the Pet Advice board', 'Pet Advice', '87 replies · Solved'],
    ['Write their thread title on the Legal Questions board', 'Legal Questions', '1.2K replies · Locked'],
    ['Write their thread title on the Medical Mysteries board', 'Medical Mysteries', '233 replies · Solved'],
    ['Write their thread title on the Parenting board', 'Parenting', '96 replies · Solved'],
    ['Write their thread title on the Car Trouble board', 'Car Trouble', '58 replies · Solved'],
    ['Write their thread title on the Paranormal board', 'Paranormal', '666 replies · Unsolved'],
    ['Write their thread title on the Neighbour Disputes board', 'Neighbour Disputes', '301 replies · Escalated'],
    ['Write their thread title on the Things I Can’t Tell My Doctor board', 'Can’t Tell My Doctor', '2.4K replies · Pinned', 'adult'],
  ],
  recipe: [
    ['Name the recipe they reviewed', 'Recipe', '★☆☆☆☆ · Prep 5 min'],
    ['Name the recipe they made for a funeral', 'Made for a funeral', '★★★★☆ · Serves 40'],
    ['Name the recipe they made for a kids’ party', 'Kids’ party recipe', '★★☆☆☆ · Serves 12'],
    ['Name the recipe they cooked for a festive dinner', 'Festive dinner', '★★★★★ · Serves 9'],
    ['Name the recipe they cooked on a first date', 'Date night recipe', '★★★☆☆ · Serves 2'],
    ['Name Grandma’s secret recipe they tried', 'Grandma’s secret', '★★★★★ · Family favourite'],
    ['Name the recipe they made in a microwave', 'Microwave special', '★★☆☆☆ · Ready in 90 sec'],
    ['Name the recipe they made for their in-laws', 'For the in-laws', '★☆☆☆☆ · Serves 6'],
  ],
  video: [
    ['Write the title of the video they commented on', 'Video', '1.2M views · 3 days ago'],
    ['Write the title of the live stream they commented on', 'Live stream', 'LIVE · 14K watching'],
    ['Write the title of the tutorial they commented on', 'Tutorial', 'Tutorial · 12:04'],
    ['Write the title of the unboxing video they commented on', 'Unboxing', '48K views · 1 week ago'],
    ['Write the title of the nature documentary they commented on', 'Nature documentary', '3.1M views · Wildlife'],
    ['Write the title of the kids’ cartoon they commented on', 'Kids’ cartoon', 'Made for kids · 9M views'],
    ['Write the title of the music video they commented on', 'Music video', 'Official video · 22M views'],
    ['Write the title of the cooking show they commented on', 'Cooking show', 'Episode 4 · 260K views'],
  ],
  chat: [
    ['Write what Mum just said in the family chat', 'Mum', 'Family ♥ · 7 members'],
    ['Write what their boss just said in the team chat', 'The boss', 'Team chat · 14 members'],
    ['Write what the bride just said in the wedding chat', 'The bride', 'Wedding planning · 9 members'],
    ['Write what Dave just said in the neighbourhood chat', 'Dave from No. 4', 'Neighbourhood Watch · 31 members'],
    ['Write what the host just said in the book club chat', 'Book club host', 'Book club · 8 members'],
    ['Write what the head teacher said in the parents’ chat', 'Head teacher', 'Class parents · 28 members'],
    ['Write what the coach said in the football chat', 'Coach', 'Sunday football · 16 members'],
    ['Write what Grandad said in the birthday chat', 'Grandad', 'Nan’s 90th · 22 members'],
    ['Write what their ex just texted them', 'Ex (do not reply)', 'Direct message · 1:58 a.m.', 'adult'],
  ],
  status: [
    ['Where did they check in?', 'Checked in at', 'Public · Just now'],
    ['What are they feeling, and why?', 'Feeling', 'Public · 2 min ago'],
    ['Name the life event they announced', 'Life event', 'Public · 5 min ago'],
    ['Who or what are they now in a relationship with?', 'In a relationship with', 'Public · 1 hr ago'],
    ['Name the group they just joined', 'Joined the group', 'Public · 12 min ago'],
    ['What are they watching right now?', 'Watching', 'Public · Just now'],
    ['What are they celebrating?', 'Celebrating', 'Public · 3 hrs ago'],
    ['Who did they tag in this post?', 'With', 'Public · 20 min ago'],
    ['Name the event they’re going to', 'Going to', 'Public · Yesterday'],
    ['What did they wake up next to?', 'Woke up next to', 'Public · 7:02 a.m.', 'adult'],
  ],
};
export const FORMATS: readonly FormatItem[] = (Object.keys(ROWS) as Kind[]).flatMap(kind => ROWS[kind].map(([ask, label, meta, adult], i) => ({ id: `${kind}-${i}`, kind, ask, label, meta, ...(adult ? { adult: true as const } : {}) })));
export const formatPool = (family: boolean, kind: Kind) => FORMATS.filter(f => f.kind === kind && !(family && f.adult));

/** House twists per app, for players who run out of time or tap “Write it for me” (half points). */
export const HOUSE_TWISTS: Record<Kind, readonly string[]> = {
  review: ['Industrial tub of glitter', 'Haunted porcelain doll', 'Self-heating underpants', 'Second-hand dentures', 'Inflatable church',
    'Clown shoes, size 19', 'Mystery meat sampler', 'Toddler-sized bagpipes', 'Talking bathroom scales', 'Extra-strong nose hair wax'],
  photo: ['Me hugging a very confused police horse', 'A goat wearing my wedding dress', 'My head stuck in the park railings', 'Twelve pigeons eating my lunch',
    'Me crying in a ball pit', 'My boss asleep in a hot tub', 'A swan chasing me across a car park', 'Nan holding a chainsaw, smiling',
    'Me in a wheelie bin, giving a thumbs up', 'A stranger’s baby wearing my glasses'],
  news: ['Local man stuck in vending machine for 3 days', 'Escaped llama elected town mayor', 'Scientists confirm the moon is slightly sticky',
    'Zoo apologises after penguin “goes rogue”', 'Council bans laughing after 9 p.m.', 'Man marries his own reflection',
    'Giant cheese wheel flattens village fete', 'Heatwave melts town’s entire jelly supply', 'Woman licked every apple in the shop, police say',
    'Mystery smell over town finally explained'],
  search: ['how to get a ring off a swollen toe', 'is it illegal to own a swan', 'how long can a person live in a cupboard', 'can dogs smell lies',
    'how to get a goat out of a car', 'why does my neighbour wave at 3am', 'how to unsend an email to everyone', 'what if you swallow a whole lemon',
    'how to tell family you joined a circus', 'is glitter edible asking for a friend'],
  job: ['Professional bed tester', 'Live-in clown for a lonely duke', 'Snake massage therapist', 'Senior pigeon wrangler', 'Human scarecrow (nights)',
    'Mattress stain consultant', 'Royal seat warmer', 'Haunted house screamer', 'Chief sock matcher', 'Night-time sewer tour guide'],
  dating: ['Someone who can lift a fridge', 'A partner in crime (literally)', 'Anyone with a boat', 'Someone my mum will hate',
    'A man who smells like soup', 'Somebody to hold my snakes', 'Anyone. Please. Anyone.', 'Someone who owns a hot tub', 'A tall goblin',
    'A partner for my clog-dancing duo'],
  forum: ['Help! A raccoon has moved into my car', 'Husband glued himself to the fridge', 'Is it normal for soup to hum?',
    'Neighbour keeps stealing my bins (pics)', 'Accidentally adopted a goose. Now what?', 'Dog ate my wedding ring. Again.',
    'Can I sue my own shadow?', 'Toddler locked me in the shed', 'Strange noises from Grandma’s wardrobe', 'Haunted toaster: please advise'],
  recipe: ['Grandma’s Mystery Jelly Surprise', 'Microwave Lasagne for One', 'Five-Day Cabbage Soup', 'Beans on a Bigger Bean',
    'Deep-Fried Birthday Cake', 'Fish Custard Pie', 'Hot Dog Smoothie', 'Toenail-Shaped Biscuits', 'Raw Onion Brownies', 'Mayonnaise Ice Lollies'],
  video: ['Man Fights Goose for 40 Minutes (NOT CLICKBAIT)', 'Grandma Tries Rollerblades for the First Time', 'Unboxing 500 Rubber Ducks',
    'Can I Survive a Week in a Wheelie Bin?', 'Dog Plays Bagpipes at Funeral', '10 Hours of a Fridge Humming', 'Toddler Rates Every Sandwich',
    'My Neighbour’s Secret Basement Tour', 'Learn to Yodel in 5 Minutes', 'Teaching My Cat to Drive'],
  chat: ['Who left a fish in the airing cupboard?', 'Has anyone seen Grandad’s teeth?', 'Why is there a horse in the garden',
    'Reminder: the police are coming at 3', 'Who changed the Wi-Fi name to THAT', 'Did someone shave the dog??', 'I can see you from the window. Stop.',
    'Please return the ferret. No questions asked.', 'Whoever ate the birthday cake: confess', 'The vicar saw everything.'],
  status: ['my ex’s wedding (uninvited)', 'the bottom of a well', 'court, again', 'the world’s saddest petting zoo', 'a goat yoga retreat',
    'the back of a police car', 'Nan’s séance', 'a clown funeral', 'the hospital (it’s fine)', 'the job centre in a ball gown'],
};
/** Cheekier house twists, one per app: filtered in family mode. */
export const ADULT_TWISTS: Record<Kind, string> = {
  review: 'Edible underwear, family size', photo: 'Me, very drunk, hugging a lamp post', news: 'Couple caught “misbehaving” in showroom bed',
  search: 'how to explain a love bite to my boss', job: 'Hen party butler (no shirt)', dating: 'Someone to split my bail money',
  forum: 'Woke up at a stranger’s hen party', recipe: 'Hangover Kebab Lasagne', video: 'Stag Do Gone Wrong: Part 7',
  chat: 'Who left their handcuffs at Nan’s?', status: 'the walk of shame (day 3)',
};
export const twistPool = (family: boolean, kind: Kind): string[] => family ? [...HOUSE_TWISTS[kind]] : [...HOUSE_TWISTS[kind], ADULT_TWISTS[kind]];

/** House answers for players who never answered. Vague on purpose: they twist beautifully. */
export const HOUSE_ANSWERS: readonly string[] = [
  'Honestly? It’s the best part of my day.', 'I try not to think about it too much.', 'Better than last year, worse than I’d hoped.',
  'My family says I’m getting better at it.', 'It’s complicated, but I’m working on it.', 'Every single morning, without fail.',
  'I could do it for hours if nobody stopped me.', 'Only on special occasions.', 'I learned it from my grandad.', 'It makes me really happy, to be honest.',
  'I’d give it a solid seven out of ten.', 'Slowly, carefully, and with a lot of snacks.', 'Whenever nobody else is home.', 'I can do it with my eyes closed now.',
  'Usually it ends with me having a little nap.', 'My neighbours have definitely heard me doing it.', 'I take it very seriously.',
  'It’s not for everyone, but it works for me.', 'I need a lot more practice.', 'I’d do it every day if I could.', 'It reminds me of my childhood.',
  'I’m not proud of it, but I’m not ashamed either.', 'Always with a nice cup of tea.', 'Twice a week, more in the summer.', 'It’s my favourite way to unwind.',
  'My cat usually joins in.', 'It takes longer than it should.', 'People tell me I’m a natural.', 'Mostly in the kitchen, sometimes in the garden.',
  'Loudly. Very loudly.', 'I always feel better afterwards.', 'With my whole family watching.', 'I keep it a secret from my friends.',
  'It’s a lot messier than you’d think.', 'I’ve got it down to under five minutes.', 'First thing in the morning, before breakfast.', 'Badly, but with enthusiasm.',
  'I practise in front of the mirror.', 'It was a gift from my mum.', 'Gently, and with plenty of patience.',
];

/** The reply chain: strangers, relatives and institutions chiming in under every post. */
export const REPLIES: readonly Reply[] = ([
  ['@mum_official', 'I am calling you RIGHT NOW'], ['@grandma.joan', 'how do i make the writing bigger'], ['@your_boss', 'Let’s chat Monday.'],
  ['@cousin_dazza', 'screenshotted 📸'], ['@the_vicar', 'I will pray for you.'], ['@hr_department', 'Please see me.'],
  ['@neighbour_trev', 'So THAT was the noise'], ['@local_news', 'Can we use this tonight?'], ['@auntie_bev', '?? who is this for'],
  ['@lawyer.dan', 'Don’t say anything else.'], ['@bestie4eva', 'deleting my account'], ['@the_dog', 'woof (concerned)'],
  ['@school_mums', 'Adding this to the agenda.'], ['@factcheck_bot', '⚠ Missing context'], ['@dad', 'Is this why you never call'],
  ['@gym_steve', 'Respect 💪'], ['@mystery_acct', '👀👀👀'], ['@landlord', 'This explains the deposit.'], ['@your_therapist', 'Bring this up Thursday.'],
  ['@little_sis', 'telling mum'], ['@brand_account', 'DM us! 😊'], ['@nan_typing', 'LOVE YOU SWEETHEART ❤ NAN'], ['@future_employer', 'Hmm.'],
  ['@influencer.kay', 'so relatable omg'], ['@police_dept', 'We would like a word.'], ['@book_club', 'Not what we meant by “spicy”.'],
  ['@primary_teacher', 'I always knew.'], ['@the_council', 'Noted.'], ['@weather_guy', 'unrelated but rain tomorrow'], ['@reply_guy', 'Well, actually…'],
  ['@bot_4421', 'Great post! Check my profile'], ['@group_admin', 'Pinned 📌'], ['@troll_patrol', 'ratio'], ['@podcast_bro', 'We need to talk about this on the pod'],
  ['@future_you', 'I still think about this'], ['@wedding_planner', 'Seating plan updated.'], ['@lollipop_lady', 'I SAW THAT'], ['@alien_watcher', 'Typical earthling'],
  ['@ex_files', 'explains a lot tbh'], ['@the_algorithm', 'Showing this to everyone you know'],
] as const).map(([who, text]) => ({ who, text }));
