/* Odd One In task banks (server only; never imported by client code). Every task is original. Adult extras are filtered in family mode. */
import type { Category } from './types';

const HANDS = [
  'Raise your hand if you’ve ever fallen asleep in a cinema.',
  'Raise your hand if you’ve ever waved back at someone who was waving at somebody else.',
  'Raise your hand if you’ve ever pretended to know the words to a song.',
  'Raise your hand if you’ve ever eaten food that fell on the floor.',
  'Raise your hand if you’ve ever sent a message to the wrong person.',
  'Raise your hand if you’ve ever laughed so hard you snorted.',
  'Raise your hand if you’ve ever walked into a glass door.',
  'Raise your hand if you’ve ever broken a bone.',
  'Raise your hand if you’ve ever been on TV.',
  'Raise your hand if you’ve ever forgotten someone’s name right after hearing it.',
  'Raise your hand if you’ve ever cried at a cartoon.',
  'Raise your hand if you’ve ever got lost in a supermarket.',
  'Raise your hand if you’ve ever tripped over absolutely nothing.',
  'Raise your hand if you’ve ever pretended to be on the phone to avoid someone.',
  'Raise your hand if you’ve ever eaten breakfast for dinner.',
  'Raise your hand if you’ve ever been stung by a bee.',
  'Raise your hand if you’ve ever won a raffle.',
  'Raise your hand if you’ve ever ridden a horse.',
  'Raise your hand if you’ve ever blamed a strange noise on the pet.',
  'Raise your hand if you’ve ever stayed up all night.',
  'Raise your hand if you’ve ever dyed your hair a wild colour.',
  'Raise your hand if you’ve ever been stuck in a lift.',
  'Raise your hand if you’ve ever locked yourself out of your home.',
  'Raise your hand if you’ve ever pushed a door that clearly said pull.',
  'Raise your hand if you’ve ever eaten a whole pizza by yourself.',
  'Raise your hand if you’ve ever been shushed by a librarian.',
  'Raise your hand if you’ve ever said “you too” when a waiter said “enjoy your meal”.',
  'Raise your hand if you’ve ever hidden vegetables to avoid eating them.',
  'Raise your hand if you’ve ever watched a whole series in one weekend.',
  'Raise your hand if you’ve ever sleepwalked.',
  'Raise your hand if you’ve ever given a houseplant a name.',
  'Raise your hand if you’ve ever passed on a present you were given.',
  'Raise your hand if you’ve ever laughed at a joke you didn’t get.',
  'Raise your hand if you’ve ever practised an argument in the shower.',
  'Raise your hand if you’ve ever screamed on a rollercoaster.',
  'Raise your hand if you’ve ever caught a fish.',
  'Raise your hand if you’ve ever been in a school play.',
  'Raise your hand if you’ve ever eaten something so spicy you cried.',
  'Raise your hand if you’ve ever fallen asleep on a bus and missed your stop.',
  'Raise your hand if you’ve ever talked your way out of trouble.',
  'Raise your hand if you’ve ever had a song stuck in your head all day.',
  'Raise your hand if you’ve ever dropped your phone in water.',
  'Raise your hand if you’ve ever forgotten a friend’s birthday.',
  'Raise your hand if you’ve ever searched for your own name online.',
  'Raise your hand if you’ve ever said you read a book you never finished.',
  'Raise your hand if you’ve ever eaten cereal without milk.',
  'Raise your hand if you’ve ever owned a goldfish.',
  'Raise your hand if you’ve ever built a snowman.',
  'Raise your hand if you’ve ever slept in a tent.',
  'Raise your hand if you’ve ever met somebody famous.',
  'Raise your hand if you’ve ever cheated at a board game.',
  'Raise your hand if you’ve ever accidentally called a teacher “Mum” or “Dad”.',
  'Raise your hand if you’ve ever ripped your trousers in public.',
  'Raise your hand if you’ve ever been chased by an animal.',
  'Raise your hand if you’ve ever run for a bus and still missed it.',
  'Raise your hand if you’ve ever eaten a whole bag of sweets in one go.',
  'Raise your hand if you’ve ever made a snow angel.',
  'Raise your hand if you’ve ever cut your own hair.',
  'Raise your hand if you’ve ever been to a concert.',
  'Raise your hand if you’ve ever sung karaoke.',
  'Raise your hand if you’ve ever eaten a bug, on purpose or not.',
  'Raise your hand if you’ve ever written a letter to someone famous.',
  'Raise your hand if you’ve ever climbed a tree and got stuck.',
  'Raise your hand if you’ve ever burnt toast so badly the alarm went off.',
  'Raise your hand if you’ve ever talked to a pet in a silly voice.',
  'Raise your hand if you’ve ever worn odd socks on purpose.',
  'Raise your hand if you’ve ever fallen off a chair.',
  'Raise your hand if you’ve ever ridden a camel.',
  'Raise your hand if you’ve ever been sick on a boat.',
  'Raise your hand if you’ve ever won a trophy.',
];
const HANDS_ADULT = [
  'Raise your hand if you’ve ever called in sick when you were fine.',
  'Raise your hand if you’ve ever sent a text you instantly regretted.',
  'Raise your hand if you’ve ever been on a truly disastrous date.',
  'Raise your hand if you’ve ever fallen asleep at a party.',
  'Raise your hand if you’ve ever been asked to leave a bar.',
  'Raise your hand if you’ve ever checked an ex’s profile at midnight.',
  'Raise your hand if you’ve ever lied about your age.',
  'Raise your hand if you’ve ever woken up with no idea how you got home.',
  'Raise your hand if you’ve ever had a crush on a friend’s sibling.',
  'Raise your hand if you’ve ever got a tattoo you regret.',
  'Raise your hand if you’ve ever ghosted someone.',
  'Raise your hand if you’ve ever kissed someone on a first date.',
  'Raise your hand if you’ve ever sneaked into a party you weren’t invited to.',
];

const NUMBER = [
  'How many hours of sleep did you get last night?',
  'From 0 to 10, how much do you love pineapple on pizza?',
  'How many times have you moved house?',
  'From 0 to 10, how good are you at dancing?',
  'How many pets have you had in your life?',
  'From 0 to 10, how scared are you of spiders?',
  'How many cups of tea or coffee have you had today?',
  'From 0 to 10, how messy is your bedroom right now?',
  'How many countries have you visited?',
  'From 0 to 10, how good is your singing voice?',
  'How many soft toys do you still own?',
  'From 0 to 10, how competitive are you?',
  'How many times did you hit snooze this morning?',
  'From 0 to 10, how much do you like surprises?',
  'How many brothers and sisters do you have?',
  'From 0 to 10, how good a cook are you?',
  'How many pairs of shoes do you own?',
  'From 0 to 10, how likely are you to survive a zombie outbreak?',
  'How many unread messages are on your phone right now?',
  'From 0 to 10, how much do you enjoy camping?',
  'How many hours a day are you on your phone?',
  'From 0 to 10, how afraid are you of heights?',
  'How many hats do you own?',
  'From 0 to 10, how much do you like broccoli?',
  'How many languages can you say “hello” in?',
  'From 0 to 10, how good are you at keeping secrets?',
  'How many books did you read last year?',
  'From 0 to 10, how much of a morning person are you?',
  'How many times have you watched your favourite film?',
  'From 0 to 10, how ticklish are you?',
  'How many plants do you look after?',
  'From 0 to 10, how loud is your sneeze?',
  'How many times a week do you eat chocolate?',
  'From 0 to 10, how much do you love rollercoasters?',
  'How many bones have you broken?',
  'From 0 to 10, how much do you trust pigeons?',
  'How many alarms do you set to wake up?',
  'From 0 to 10, how neat is your handwriting?',
  'How many times have you been on a plane?',
  'From 0 to 10, how stinky are your feet after a long day?',
  'How many cousins do you have?',
  'From 0 to 10, how much do you love Mondays?',
  'How many sweets could you eat in one minute?',
  'From 0 to 10, how well would you do on a reality TV show?',
  'How many times a day do you open the fridge just to look?',
  'From 0 to 10, how brave are you in the dark?',
  'How many umbrellas have you lost?',
  'From 0 to 10, how good are you at whistling?',
  'How many photos did you take yesterday?',
  'From 0 to 10, how much do you love the smell of rain?',
  'How many glasses of water have you drunk today?',
  'From 0 to 10, how good is your sense of direction?',
  'How many musical instruments can you play, badly included?',
  'From 0 to 10, how dramatic are you when you have a cold?',
  'How many times have you said sorry today?',
  'From 0 to 10, how much do you enjoy doing the washing-up?',
  'How many sandwiches could you eat in one sitting?',
  'From 0 to 10, how good are you at hide-and-seek?',
  'How many keys are on your keyring?',
  'From 0 to 10, how spicy do you like your food?',
  'How many pillows do you sleep with?',
  'From 0 to 10, how likely are you to cry at a sad film?',
  'How many fillings do you have?',
  'From 0 to 10, how often do you talk to yourself?',
  'How many days could you last without your phone?',
  'From 0 to 10, how fast can you run?',
  'How many spoons of sugar would you put in a cup of tea?',
  'From 0 to 10, how good are you at board games?',
  'How many times have you been to a wedding?',
  'From 0 to 10, how much do you like being the centre of attention?',
];
const NUMBER_ADULT = [
  'From 0 to 10, how bad was your worst hangover?',
  'How many dates have you been on this year?',
  'From 0 to 10, how embarrassing is your search history?',
  'How many drinks before you hit the dance floor?',
  'From 0 to 10, how awkward was your first kiss?',
  'How many exes do you still follow online?',
  'From 0 to 10, how much do you flirt to get out of trouble?',
  'How many times this month have you pretended to be busy to dodge plans?',
  'From 0 to 10, how wild were your teenage years?',
  'How many dating apps have you tried?',
  'From 0 to 10, how much have you exaggerated on a job application?',
  'From 0 to 10, how wild was your last birthday?',
];

const POINT = [
  'Point at the player most likely to become famous by accident.',
  'Point at the player most likely to survive a week on a desert island.',
  'Point at the player most likely to get lost in their own street.',
  'Point at the player most likely to win a staring contest with a cat.',
  'Point at the player most likely to eat the last slice without asking.',
  'Point at the player most likely to cry at an advert.',
  'Point at the player most likely to be a secret agent.',
  'Point at the player most likely to forget their own birthday.',
  'Point at the player most likely to laugh at the worst possible moment.',
  'Point at the player most likely to adopt twenty cats.',
  'Point at the player most likely to start a band.',
  'Point at the player most likely to talk their way out of a parking ticket.',
  'Point at the player most likely to win a dance-off.',
  'Point at the player most likely to be late to their own wedding.',
  'Point at the player most likely to become a millionaire.',
  'Point at the player most likely to set off a smoke alarm cooking toast.',
  'Point at the player most likely to befriend a pigeon.',
  'Point at the player most likely to fall asleep first at a sleepover.',
  'Point at the player most likely to win a TV quiz show.',
  'Point at the player most likely to read the instructions first.',
  'Point at the player most likely to rule a small country.',
  'Point at the player most likely to get the giggles in a serious moment.',
  'Point at the player most likely to invent something brilliant.',
  'Point at the player most likely to buy a haunted house.',
  'Point at the player most likely to go viral online.',
  'Point at the player most likely to spend all their money on snacks.',
  'Point at the player most likely to be chased by geese.',
  'Point at the player most likely to lose an argument with a toddler.',
  'Point at the player most likely to climb a mountain.',
  'Point at the player most likely to have a secret talent.',
  'Point at the player most likely to sing loudest at karaoke.',
  'Point at the player most likely to cheat at a board game.',
  'Point at the player most likely to believe in ghosts.',
  'Point at the player most likely to get stuck in a revolving door.',
  'Point at the player most likely to become a pirate.',
  'Point at the player most likely to give their car a name.',
  'Point at the player most likely to win a pie-eating contest.',
  'Point at the player most likely to survive a horror film.',
  'Point at the player most likely to keep a secret diary.',
  'Point at the player most likely to panic first in an emergency.',
  'Point at the player most likely to steal the show at a wedding.',
  'Point at the player most likely to try to pet a wild animal.',
  'Point at the player most likely to become an astronaut.',
  'Point at the player most likely to forget where they parked.',
  'Point at the player most likely to win the lottery and lose the ticket.',
  'Point at the player most likely to wear socks with sandals.',
  'Point at the player most likely to chat to a stranger for an hour.',
  'Point at the player most likely to join a club for something very odd.',
  'Point at the player most likely to befriend a dragon.',
  'Point at the player most likely to build a robot butler.',
  'Point at the player most likely to plan everyone’s birthday party.',
  'Point at the player most likely to take a selfie at the worst moment.',
  'Point at the player most likely to rescue a kitten from a tree.',
  'Point at the player most likely to eat dessert first.',
  'Point at the player most likely to sleep through a thunderstorm.',
  'Point at the player most likely to bake a cake that explodes.',
  'Point at the player most likely to still have an imaginary friend.',
  'Point at the player most likely to lead a rebellion.',
  'Point at the player most likely to get a song stuck in everyone’s head.',
  'Point at the player most likely to win gold in napping.',
  'Point at the player most likely to talk to their plants.',
  'Point at the player most likely to be secretly royal.',
  'Point at the player most likely to solve a mystery.',
  'Point at the player most likely to hide in the bathroom at a party.',
  'Point at the player most likely to win a hot-sauce challenge.',
  'Point at the player most likely to trip on stage.',
  'Point at the player most likely to own a llama one day.',
  'Point at the player most likely to tell the same story twice.',
];
const POINT_ADULT = [
  'Point at the player most likely to text an ex at 2 a.m.',
  'Point at the player most likely to be thrown out of a bar.',
  'Point at the player most likely to marry someone they met on holiday.',
  'Point at the player most likely to have a secret dating profile.',
  'Point at the player most likely to lie about their age.',
  'Point at the player most likely to start drama at a wedding.',
  'Point at the player most likely to fall asleep at their own party.',
  'Point at the player most likely to be banned from an all-you-can-eat buffet.',
  'Point at the player most likely to have the wildest dating history.',
  'Point at the player most likely to reply-all with office gossip.',
  'Point at the player most likely to blow their savings on a whim.',
  'Point at the player most likely to dance on a table.',
];

const FACE = [
  'Make the face you’d make if you found a hair in your soup.',
  'Make the face you’d make if you won the lottery.',
  'Make the face you’d make if a spider landed on your arm.',
  'Make the face you’d make if your crush waved at you.',
  'Make the face you’d make if someone ate your leftovers.',
  'Make the face you’d make if you heard a noise in the attic at midnight.',
  'Make the face you’d make if someone explained a sport you don’t care about.',
  'Make the face you’d make if you beat your best friend at a board game.',
  'Make the face you’d make if you stepped in something squishy barefoot.',
  'Make the face you’d make if you saw a puppy in a tiny hat.',
  'Make the face you’d make if your phone fell in the toilet.',
  'Make the face you’d make if you smelled fresh cookies.',
  'Make the face you’d make if your teacher announced a surprise test.',
  'Make the face you’d make if you turned out to be right all along.',
  'Make the face you’d make if someone put the empty biscuit packet back in the cupboard.',
  'Make the face you’d make if you unwrapped a present full of socks.',
  'Make the face you’d make if you tasted milk that had gone off.',
  'Make the face you’d make if the lights went out in a haunted house.',
  'Make the face you’d make if you just won an argument.',
  'Make the face you’d make if someone sneezed on your sandwich.',
  'Make the face you’d make if you found money in an old coat.',
  'Make the face you’d make if your favourite celebrity said hello.',
  'Make the face you’d make if your ice cream fell on the floor.',
  'Make the face you’d make if a clown jumped out of a cupboard.',
  'Make the face you’d make if someone said they don’t like pizza.',
  'Make the face you’d make if you opened the instructions for flat-pack furniture.',
  'Make the face you’d make if you found out you were on the big screen.',
  'Make the face you’d make if someone pushed in front of you in a queue.',
  'Make the face you’d make if you saw a baby panda sneeze.',
  'Make the face you’d make if you got a text saying “we need to talk”.',
  'Make the face you’d make if your friend told a terrible pun.',
  'Make the face you’d make if the doctor said “this won’t hurt a bit”.',
  'Make the face you’d make if you smelled your own gym bag.',
  'Make the face you’d make if someone guessed your password.',
  'Make the face you’d make if you saw a cake with your name on it.',
  'Make the face you’d make if you heard a recording of your own voice.',
  'Make the face you’d make if your cat brought you a “present”.',
  'Make the face you’d make if a seagull stole your chips.',
  'Make the face you’d make if the waiter brought the wrong order.',
  'Make the face you’d make if you were the only one in fancy dress.',
  'Make the face you’d make if you won a dance-off.',
  'Make the face you’d make if you realised you’d been on mute the whole time.',
  'Make the face you’d make if your dentist said “hmm”.',
  'Make the face you’d make if you saw a ghost brushing its teeth.',
  'Make the face you’d make if someone stole your seat on the sofa.',
  'Make the face you’d make if someone handed you a crying baby.',
  'Make the face you’d make if you bit into a lemon by surprise.',
  'Make the face you’d make if you finally found the TV remote.',
  'Make the face you’d make if a stranger complimented your outfit.',
  'Make the face you’d make if your favourite song came on the radio.',
  'Make the face you’d make if you got a surprise day off.',
  'Make the face you’d make if a magician pulled a rabbit out of your hood.',
  'Make the face you’d make if you had to sing in front of everyone.',
  'Make the face you’d make if you won a goldfish at the fair.',
  'Make the face you’d make if the wifi died mid-game.',
  'Make the face you’d make if your toast landed butter side down.',
  'Make the face you’d make if a friend spoiled the ending of a film.',
  'Make the face you’d make if you found a frog in your shoe.',
  'Make the face you’d make if you watched the sun set over the sea.',
  'Make the face you’d make if you sat on a whoopee cushion.',
  'Make the face you’d make if you got picked first for the team.',
  'Make the face you’d make if a dog walked past on its back legs.',
  'Make the face you’d make if you got the last slice of cake.',
  'Make the face you’d make if you heard the ice-cream van coming.',
  'Make the face you’d make if your sock got wet.',
  'Make the face you’d make if you saw your exam results.',
  'Make the face you’d make if a bird pooped on your shoulder.',
  'Make the face you’d make if your best friend got you the perfect gift.',
];
const FACE_ADULT = [
  'Make the face you’d make if you bumped into your boss at a nightclub.',
  'Make the face you’d make if your date turned up with their mum.',
  'Make the face you’d make if you checked your bank balance after a holiday.',
  'Make the face you’d make if you remembered what you said last night.',
  'Make the face you’d make if your ex announced their engagement.',
  'Make the face you’d make if the bartender called last orders.',
  'Make the face you’d make if your date ordered for you.',
  'Make the face you’d make if you got a 3 a.m. text from your ex.',
  'Make the face you’d make if you saw the price of your round of drinks.',
  'Make the face you’d make if your in-laws turned up unannounced.',
  'Make the face you’d make if your date chewed with their mouth open.',
  'Make the face you’d make if you found your parents’ old love letters.',
];

export const TASKS: Record<Category, { family: readonly string[]; adult: readonly string[] }> = {
  hands: { family: HANDS, adult: HANDS_ADULT },
  number: { family: NUMBER, adult: NUMBER_ADULT },
  point: { family: POINT, adult: POINT_ADULT },
  face: { family: FACE, adult: FACE_ADULT },
};
export const taskPool = (category: Category, family: boolean) => family ? TASKS[category].family : [...TASKS[category].family, ...TASKS[category].adult];
