import { lazy, Suspense, useState, type CSSProperties } from 'react';
import { StatusNotice, ToggleRow, type GameClientModule, type InstructionsViewProps, type ResultsViewProps, type SettingsViewProps } from '../../../party-ui/src/index';
import type { Action, PrivateView, PublicView, Settings } from './model';
import { MISSIONS, SCENARIOS, VARIANTS, type Mission, type Scenario, type Variant } from './expansion-model';
import { DEFAULT_SETTINGS, SCENARIO_NAMES, VARIANT_NAMES, expansionRestrictions, maximumTargetPoints, suggestedPoints } from './expansion-settings';
import { Display } from './display';
import { Controller } from './controller';
import { MISSION_META, describeSettings, expansionPlayer, playerOf, withDefaults } from './presentation';
import './style.css';

const IslandScene = lazy(() => import('./scene'));
const SCENARIO_BLURB: Record<Scenario, string> = { fishing: 'Fishing grounds and a lake give fish tokens to spend on small favours.', rivers: 'Rivers cross the island; bridges cost extra and gold rewards the wealthiest builder.', caravans: 'Vote on where camel trains travel; roads and settlements beside them pay more.', 'barbarian-attack': 'Barbarians land on the coast; guards and knights defend or lose your cities.', traders: 'Haul marble, glass and sand between depots with your wagon while road barbarians block the way.' };
const VARIANT_BLURB: Record<Variant, string> = { 'friendly-robber': 'The robber avoids players with two points or fewer.', harbormaster: 'An extra award for whoever owns the most harbour points.' };
function IslandSettings({ settings: raw, onChange, disabled }: SettingsViewProps<Settings>) {
  const settings = withDefaults(raw), reasons = expansionRestrictions(settings), suggested = suggestedPoints(settings), maximum = maximumTargetPoints(settings), [dropped, setDropped] = useState<string | null>(null);
  // Switching systems can invalidate earlier picks; turn them off visibly with the shared reason instead of failing at start.
  // Switching systems can invalidate earlier picks or exceed the scoring ceiling; adjust visibly with the shared reason rather than failing at start.
  const set = (part: Partial<Settings>) => { const next = { ...settings, ...part }, blocked = expansionRestrictions(next), gone = [...(next.scenarios ?? []), ...(next.variants ?? [])].filter(key => blocked[key]), cleaned = { ...next, scenarios: (next.scenarios ?? []).filter(key => !blocked[key]), variants: (next.variants ?? []).filter(key => !blocked[key]) }, cap = maximumTargetPoints(cleaned), notes = gone.map(key => `${(SCENARIO_NAMES as Record<string, string>)[key] ?? (VARIANT_NAMES as Record<string, string>)[key]} turned off: ${blocked[key]}`); if (cleaned.targetPoints > cap) { notes.push(`Victory target lowered to ${cap}, the maximum for this setup.`); cleaned.targetPoints = cap; } setDropped(notes.length ? notes.join(' ') : null); onChange(cleaned); };
  const toggle = <T extends string>(list: T[] | undefined, key: T, on: boolean) => on ? [...(list ?? []).filter(item => item !== key), key] : (list ?? []).filter(item => item !== key);
  return <div className="is-settings">
    {dropped && <div className="is-settings-dropped"><StatusNotice tone="info">{dropped}</StatusNotice></div>}
    <div className="is-setting"><label htmlFor="is-mode">Turn structure</label><select id="is-mode" value={settings.mode} disabled={disabled} onChange={event => set({ mode: event.target.value as Settings['mode'] })}><option value="standard">Standard · one player at a time</option><option value="connect">Connect-style · simultaneous rounds</option></select><p>{settings.mode === 'standard' ? 'Classic turns: roll, collect, trade, build. With five or more players, turns run in pairs; the second player builds and bank-trades without player trades.' : 'Our adaptation of large-group play: one shared roll, then everyone trades and builds at once against a round timer. Confirmed placements win contested spots; victory is checked at the end of each round.'}</p></div>
    <fieldset className="is-setting is-radio-set"><legend>Map and sea system</legend>{([['base', 'Base island', 'One island, classic trading ports. Above four players the board grows into a larger custom layout.'], ['seafarers', 'Seafarers', 'Islands linked by sea lanes. Ships form routes, gold fields pay any resource, a pirate roams. Our archipelago scenario.'], ['explorers', 'Explorers & Pirates', 'Expedition ships carry settlers, crews, fish and spices into unexplored fog. Harbour settlements replace ports. Cannot combine with Seafarers routes.']] as const).map(([value, label, blurb]) => <label key={value} className="is-radio" data-on={settings.expansion === value || undefined}><input type="radio" name="is-expansion" value={value} checked={settings.expansion === value} disabled={disabled} onChange={() => set({ expansion: value })}/><span><strong>{label}</strong><small>{blurb}</small></span></label>)}</fieldset>
    <div className="is-setting is-toggle-set"><ToggleRow label="Cities & Knights · commodities, knights, barbarians, metropolises" checked={!!settings.citiesKnights} disabled={disabled} onChange={citiesKnights => set({ citiesKnights })}/><p>Additive to any map. With Explorers & Pirates it follows the official combination notes: knights stay on their island and harbours differ from cities.</p></div>
    <fieldset className="is-setting is-toggle-set"><legend>Traders &amp; Barbarians scenarios</legend>{SCENARIOS.map(key => { const blocked = reasons[key]; return <div key={key} className="is-toggle-line" data-blocked={blocked ? true : undefined}><ToggleRow label={SCENARIO_NAMES[key]} checked={!!settings.scenarios?.includes(key) && !blocked} disabled={disabled || !!blocked} onChange={on => set({ scenarios: toggle(settings.scenarios, key, on) })}/><p>{blocked ?? SCENARIO_BLURB[key]}</p></div>; })}</fieldset>
    {settings.expansion === 'explorers' && <fieldset className="is-setting is-toggle-set"><legend>Explorers &amp; Pirates missions</legend>{MISSIONS.map(key => <div key={key} className="is-toggle-line"><ToggleRow label={MISSION_META[key].label} checked={(settings.missions ?? []).includes(key)} disabled={disabled || ((settings.missions ?? []).length <= 1 && (settings.missions ?? []).includes(key))} onChange={on => set({ missions: toggle<Mission>(settings.missions, key, on) })}/><p>{MISSION_META[key].blurb}</p></div>)}<p className="is-settings-note">At least one mission stays on. Fewer missions shorten the game and lower the suggested target.</p></fieldset>}
    <fieldset className="is-setting is-toggle-set"><legend>Variants</legend>{VARIANTS.map(key => { const blocked = reasons[key]; return <div key={key} className="is-toggle-line" data-blocked={blocked ? true : undefined}><ToggleRow label={VARIANT_NAMES[key]} checked={!!settings.variants?.includes(key) && !blocked} disabled={disabled || !!blocked} onChange={on => set({ variants: toggle(settings.variants, key, on) })}/><p>{blocked ?? VARIANT_BLURB[key]}</p></div>; })}</fieldset>
    <div className="is-setting-row">
      <div className="is-setting"><label htmlFor="is-points">Victory points to win</label><input id="is-points" className="kp-input" type="number" inputMode="numeric" min={10} max={maximum} value={settings.targetPoints} disabled={disabled} onChange={event => set({ targetPoints: Number(event.target.value) })}/><p>Suggested for this setup: <b>{suggested}</b>{settings.targetPoints !== suggested && <> · <button type="button" className="is-back" disabled={disabled} onClick={() => set({ targetPoints: suggested })}>use it</button></>}. Allowed 10 to <b>{maximum}</b>{maximum < 30 ? ` · this setup cannot score higher than ${maximum}` : ''}.</p></div>
      <div className="is-setting"><label htmlFor="is-seconds">Connect round timer</label><select id="is-seconds" value={settings.roundSeconds} disabled={disabled || settings.mode !== 'connect'} onChange={event => set({ roundSeconds: Number(event.target.value) as Settings['roundSeconds'] })}><option value={60}>60 seconds</option><option value={90}>90 seconds</option><option value={120}>120 seconds</option></select>{settings.mode !== 'connect' && <p>Used only in Connect-style rounds.</p>}</div>
    </div>
    <p className="is-settings-note">Selected: {describeSettings(settings)}. 3 to 10 players on every setup; larger rosters and Connect-style rounds are PartyPlay adaptations. Defaults: {DEFAULT_SETTINGS.mode}, {describeSettings(DEFAULT_SETTINGS)}, {DEFAULT_SETTINGS.targetPoints} points.</p>
  </div>;
}
function Instructions({ role }: InstructionsViewProps) {
  return <div className="is-instructions">
    <h2>Settle the island.</h2>
    <p>Settlements on hex corners collect resources when the dice match a number. Spend wood, brick, wool, grain and ore on roads, ships, settlements, cities and development cards. First to the target score wins.</p>
    {role === 'display' ? <p>The shared screen shows the island, the dice, open offers and everyone’s public totals. Card counts are public; the cards themselves stay on phones.</p> : <p>Your phone holds your hand. When it is your move, the map lights up the legal spots: tap one, check the details, then confirm. Trade by talking, then post the offer; the other side accepts on their phone and you pick who to trade with. Expansion actions appear under More as labelled choices supplied by the game.</p>}
    <p><strong>Standard</strong> plays classic turns. With five or more players, turns run in pairs and the second player skips player trades.</p>
    <p><strong>Connect-style rounds</strong> are our adaptation for big groups, not the official Connect rules: one shared roll, then everyone trades and builds at the same time until the timer or everyone is ready. Confirmed placements win contested spots and victory is checked at each round boundary.</p>
    <p><strong>Seafarers</strong> adds ships along sea lanes, gold fields that pay any resource, and a pirate that blocks ships. <strong>Explorers &amp; Pirates</strong> replaces that with expedition ships that carry settlers, crews, fish and spices into unexplored fog, harbour settlements instead of trading ports, and missions worth points. The two sea systems never combine.</p>
    <p><strong>Cities &amp; Knights</strong> adds paper, cloth and coin commodities, city improvements on three tracks, progress cards, knights, metropolises and a barbarian fleet that everyone must defend against. It works with any map. <strong>Traders &amp; Barbarians</strong> scenarios are individual toggles: fishing, rivers, merchant trains, barbarian attack and deliveries. Incompatible picks are greyed with the reason.</p>
    <p>Above six players every map is a larger custom layout and pacing is an adaptation, not an official variant.</p>
  </div>;
}
function Results({ outcome, publicView: view, playerId }: ResultsViewProps<PublicView>) {
  const rows = [...outcome.rows].sort((a, b) => (a.rank ?? 99) - (b.rank ?? 99) || (b.score ?? 0) - (a.score ?? 0)), settings = withDefaults(view.settings), exp = view.expansions;
  return <div className="is-results">
    <p className="kp-eyebrow">Island Settlers · {describeSettings(settings)} · {settings.mode === 'connect' ? `${view.turn} rounds` : `${view.turn} turns`} · {settings.targetPoints} points to win</p>
    <h1 className="kp-display">{outcome.winners.length ? `${outcome.winners.map(id => playerOf(view, id)?.name ?? 'Someone').join(' & ')} ${outcome.winners.length > 1 ? 'share' : 'takes'} the island` : 'The island rests'}</h1>
    <ol className="is-standings">{rows.map(row => { const player = playerOf(view, row.playerId), extra = expansionPlayer(view, row.playerId), missions = extra ? Object.values(extra.missions).reduce((sum, value) => sum + value, 0) : 0; return <li key={row.playerId} data-winner={outcome.winners.includes(row.playerId) || undefined} data-you={row.playerId === playerId || undefined} style={{ '--seat': player?.color } as CSSProperties}><span className="is-rank kp-numeral">{row.rank ?? '–'}</span><b className="is-swatch"/><span className="is-standing-name">{player?.name ?? 'Player'}{row.playerId === playerId && <small> · you</small>}</span><span className="is-standing-flags">{view.longestOwner === row.playerId && <em>Longest route</em>}{view.armyOwner === row.playerId && <em>Largest army</em>}{exp?.harborOwner === row.playerId && <em>Harbormaster</em>}{exp?.metropolises.filter(m => m.playerId === row.playerId).map(m => <em key={m.vertex}>{m.track} metropolis</em>)}{player && player.knights > 0 && <em>{player.knights} knights</em>}{extra && extra.defenderPoints > 0 && <em>{extra.defenderPoints} defender</em>}{missions > 0 && <em>{missions} mission pts</em>}</span><strong className="kp-numeral">{row.score ?? player?.score ?? 0}<small>VP</small></strong></li>; })}</ol>
  </div>;
}
export const client: GameClientModule<null, Action, Settings, PublicView, PrivateView> = {
  settingsWide: true,
  SceneView: props => <Suspense fallback={null}><IslandScene {...props}/></Suspense>,
  DisplayView: Display, ControllerView: Controller,
  SettingsView: IslandSettings, InstructionsView: Instructions, ResultsView: Results,
  prepare() {}, dispose() {},
};
export default client;
