import { useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ArcadeButton, Countdown, Eyebrow, Panel, StatusNotice, type GameViewProps } from '../../../party-ui/src/index';
import { COSTS, RESOURCES, emptyHand, type Action, type Hand, type Offer, type PrivateView, type PublicView, type Resource } from './model';
import { TRACKS, type ExpansionCommand, type Good } from './expansion-model';
import { BoardMap, type Hotspot } from './map';
import { HandChips, TerrainIcon } from './icons';
import { ChoiceList, GoodPick, HandPicker } from './pickers';
import { CommandList, CommandRunner, freshCommandDraft, type CommandDraft } from './commands';
import { DEV_META, GOOD_META, PIECE_LABEL, PROGRESS_LABEL, RESOURCE_META, TRACK_META, canAfford, count, describeStep, edgeLabel, handTotal, indexBoard, isConnect, nameOf, names, pickableGoods, pips, playerOf, readDraft, resourceTotal, saveDraft, tileLabel, vertexTiles, withDefaults, withinLimit } from './presentation';

type Props = GameViewProps<null, Action, PublicView, PrivateView>;
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;
type Move = DistributiveOmit<Action, 'turnId'>;
type Tab = 'build' | 'trade' | 'cards' | 'more';
type Pick = 'settlement' | 'city' | 'road' | 'ship' | 'route' | 'ship-move';
type Draft = { tab: Tab; pick: Pick | null; selected: string | null; from: string | null; victim: string | null; cards: Hand; give: Hand; get: Hand; bankGive: Good | null; bankGet: Good | null; card: string | null; command: string | null; commands: Record<string, CommandDraft> };
type Task = 'ended' | 'choice' | 'discard' | 'gold' | 'robber' | 'setup' | 'free-routes' | 'roll' | 'movement' | 'action' | 'wait';
type Act = (move: Move, done?: Partial<Draft>, success?: string) => Promise<void>;
const MAX_ASK = 48;
type Notice = { tone: 'error' | 'success' | 'info'; text: string };
const fresh = (): Draft => ({ tab: 'build', pick: null, selected: null, from: null, victim: null, cards: emptyHand(), give: emptyHand(), get: emptyHand(), bankGive: null, bankGet: null, card: null, command: null, commands: {} });
const CLEAR: Partial<Draft> = { pick: null, selected: null, from: null, victim: null, cards: emptyHand(), card: null, command: null };

function taskFor(view: PublicView, me: PrivateView, active: boolean): Task {
  if (view.phase === 'ended') return 'ended';
  if (view.phase === 'choice') return me.expansion?.task ? 'choice' : 'wait';
  if (me.discardDue > 0) return 'discard';
  if (me.goldDue > 0) return 'gold';
  if (me.legal.robber.length || me.legal.pirate.length) return 'robber';
  if (view.phase === 'setup') return active ? 'setup' : 'wait';
  if (view.phase === 'roll' && me.freeRoutes > 0 && me.canAct && !me.canRoll) return 'free-routes';
  if (me.canRoll) return 'roll';
  // Movement follows building and trading. Standard flips the public phase; Connect keeps `action` while each phone enters movement alone.
  if (me.canAct && (me.expansion?.movement || view.phase === 'movement')) return 'movement';
  return me.canAct ? 'action' : 'wait';
}
function hotspotsFor(task: Task, draft: Draft, me: PrivateView, setupTone: Hotspot['tone'] = 'settlement'): Hotspot[] {
  const vertices = (ids: string[], tone: Hotspot['tone']) => ids.map(id => ({ id, shape: 'vertex' as const, tone })), edges = (ids: string[], tone: Hotspot['tone']) => ids.map(id => ({ id, shape: 'edge' as const, tone }));
  const routes = () => [...edges(me.legal.roads, 'road'), ...edges(me.legal.ships.filter(id => !me.legal.roads.includes(id)), 'ship')];
  if (task === 'setup') return me.legal.settlements.length ? vertices(me.legal.settlements, setupTone) : routes();
  if (task === 'free-routes') return routes();
  if (task === 'robber') return [...me.legal.robber.map(id => ({ id, shape: 'tile' as const, tone: 'robber' as const })), ...me.legal.pirate.map(id => ({ id, shape: 'tile' as const, tone: 'pirate' as const }))];
  if (task !== 'action') return [];
  switch (draft.pick) {
    case 'settlement': return vertices(me.legal.settlements, 'settlement'); case 'city': return vertices(me.legal.cities, 'city');
    case 'road': return edges(me.legal.roads, 'road'); case 'ship': return edges(me.legal.ships, 'ship'); case 'route': return routes();
    case 'ship-move': { if (!draft.from) return edges(me.legal.shipMoves.map(move => move.from), 'ship'); const move = me.legal.shipMoves.find(item => item.from === draft.from); return move ? edges(move.to, 'ship') : []; }
    default: return [];
  }
}
function CostChips({ cost, free }: { cost: Hand; free?: boolean }) { return free ? <span className="is-cost is-cost-free">free</span> : <span className="is-cost"><HandChips hand={cost}/></span>; }

/** Mirrors the server: trades need canTrade, a proposer who has not ended, and in Standard the active player on one side. */
function canRespond(view: PublicView, me: PrivateView, playerId: string, offer: Offer) { return me.canTrade && !view.readyIds.includes(offer.playerId) && (isConnect(view) || offer.playerId === view.actorId || playerId === view.actorId); }
function OfferComposer({ view, me, draft, update, busy, act, goods }: { view: PublicView; me: PrivateView; draft: Draft; update(part: Partial<Draft>): void; busy: boolean; act: Act; goods: readonly Good[] }) {
  const overlap = goods.some(good => count(draft.give, good) > 0 && count(draft.get, good) > 0);
  return <div className="is-offer-builder"><Eyebrow>Offer the table</Eyebrow>{!me.canTrade ? <p className="is-task-note">Player trades are not available right now{view.secondary ? ' on a paired turn' : ''}.</p> : !isConnect(view) && <p className="is-task-note">Trades always involve {nameOf(view, view.actorId)}, whose turn it is.</p>}<HandPicker title="You give" value={draft.give} limit={me.hand} goods={goods} onChange={give => update({ give })}/><HandPicker title="You want" value={draft.get} limit={MAX_ASK} goods={goods} onChange={get => update({ get })}/>{overlap && <p className="is-task-note">Offer different goods on each side.</p>}<ArcadeButton tone="grape" disabled={busy || !me.canTrade || overlap || !handTotal(draft.give) || !handTotal(draft.get) || !withinLimit(draft.give, me.hand, goods)} onClick={() => act({ type: 'offer', give: draft.give, get: draft.get }, { give: emptyHand(), get: emptyHand() }, 'Offer posted. Everyone sees it on the shared screen.')}>Post offer</ArcadeButton></div>;
}
function Offers({ view, me, playerId, busy, act }: { view: PublicView; me: PrivateView; playerId: string; busy: boolean; act: Act }) {
  if (!view.offers.length) return null;
  return <section className="is-offers" aria-label="Open offers">{view.offers.map((offer: Offer) => { const mine = offer.playerId === playerId, proposer = playerOf(view, offer.playerId), accepted = offer.accepts.includes(playerId), affordable = canAfford(me.hand, offer.get), allowed = canRespond(view, me, playerId, offer); return <Panel key={offer.id} className="is-offer is-offer-phone" style={{ '--seat': proposer?.color } as CSSProperties}>
    <header><b className="is-swatch"/><strong>{mine ? 'Your offer' : proposer?.name ?? 'Someone'}</strong>{!mine && <span>offers</span>}</header>
    <div className="is-offer-hands"><HandChips hand={offer.give}/><span className="is-offer-for">for</span><HandChips hand={offer.get}/></div>
    {mine ? <div className="is-offer-actions">{offer.accepts.length ? offer.accepts.map(id => <ArcadeButton key={id} tone="lime" size="sm" disabled={busy} onClick={() => act({ type: 'complete-offer', offerId: offer.id, partner: id }, undefined, `Traded with ${nameOf(view, id)}.`)}>Trade with {nameOf(view, id)}</ArcadeButton>) : <span className="is-offer-wait">Waiting for someone to accept…</span>}<ArcadeButton tone="ghost" size="sm" disabled={busy} onClick={() => act({ type: 'cancel-offer', offerId: offer.id })}>Withdraw</ArcadeButton></div>
      : <div className="is-offer-actions">{accepted ? <span className="is-offer-wait">You accepted. {proposer?.name ?? 'They'} picks a partner.</span> : <ArcadeButton tone="lime" size="sm" disabled={busy || !allowed || !affordable} onClick={() => act({ type: 'accept-offer', offerId: offer.id }, undefined, 'Accepted. Waiting for the proposer to confirm.')}>Accept</ArcadeButton>}{!affordable && !accepted && <small>You cannot cover what they want.</small>}{affordable && !allowed && !accepted && <small>{view.readyIds.includes(offer.playerId) ? 'The proposer has finished their turn.' : !me.canTrade ? 'Player trades are closed for you right now.' : `Trades must involve ${nameOf(view, view.actorId)}.`}</small>}</div>}
  </Panel>; })}</section>;
}
/** Development cards plus Cities & Knights progress cards. Progress plays are server commands; the phone never infers card effects. */
function CardPanel({ me, draft, update, busy, act, title, onOpen }: { me: PrivateView; draft: Draft; update(part: Partial<Draft>): void; busy: boolean; act: Act; title?: string; onOpen(command: ExpansionCommand): void }) {
  const plentyCount = Math.min(2, resourceTotal(me.bank)), progress = me.expansion?.progress ?? [], plays = (me.expansion?.commands ?? []).filter(command => command.group === 'Progress');
  return <section className="is-task is-cards">{title && <Eyebrow>{title}</Eyebrow>}{me.development.length ? <ul className="is-devlist">{me.development.map(card => <li key={card.id} data-open={draft.card === card.id || undefined}><div className="is-dev-row"><div><strong>{DEV_META[card.kind].label}</strong><small>{DEV_META[card.kind].blurb}</small></div>{card.kind !== 'victory' && <ArcadeButton size="sm" tone={card.playable ? 'grape' : 'ghost'} disabled={busy || !card.playable} onClick={() => card.kind === 'plenty' || card.kind === 'monopoly' ? update({ card: draft.card === card.id ? null : card.id, cards: emptyHand(), bankGive: null }) : act({ type: 'play-development', cardId: card.id }, CLEAR, card.kind === 'knight' ? 'Knight played. Move the robber.' : 'Two free routes ready to place.')}>{card.playable ? 'Play' : 'Not now'}</ArcadeButton>}</div>
    {draft.card === card.id && card.kind === 'plenty' && <><HandPicker title={`Take ${plentyCount} from the bank`} hint={`${handTotal(draft.cards)} of ${plentyCount}`} value={draft.cards} limit={me.bank} goods={RESOURCES} onChange={cards => update({ cards })}/><ArcadeButton tone="grape" disabled={busy || plentyCount === 0 || handTotal(draft.cards) !== plentyCount || !withinLimit(draft.cards, me.bank, RESOURCES)} onClick={() => act({ type: 'play-development', cardId: card.id, cards: draft.cards }, CLEAR, 'Year of Plenty played.')}>{plentyCount ? `Take ${plentyCount === 1 ? 'this one' : 'these two'}` : 'Bank is empty'}</ArcadeButton></>}
    {draft.card === card.id && card.kind === 'monopoly' && <><GoodPick label="Resource to monopolise" goods={RESOURCES} value={draft.bankGive} onChange={bankGive => update({ bankGive })}/><ArcadeButton tone="grape" disabled={busy || !draft.bankGive} onClick={() => act({ type: 'play-development', cardId: card.id, resource: draft.bankGive as Resource }, CLEAR, 'Monopoly played.')}>Take everyone’s {draft.bankGive ? GOOD_META[draft.bankGive].label : '…'}</ArcadeButton></>}
  </li>)}</ul> : !progress.length && <p className="is-task-note">No development cards yet. Buy one under Build for one ore, one wool and one grain.</p>}
    {progress.length > 0 && <><Eyebrow>Progress cards</Eyebrow><ul className="is-devlist is-progress">{progress.map(card => <li key={card.id} style={{ '--track': TRACK_META[card.track].color } as CSSProperties}><div className="is-dev-row"><div><strong>{PROGRESS_LABEL[card.kind]}</strong><small>{TRACK_META[card.track].label} progress</small></div></div></li>)}</ul></>}
    {plays.length > 0 && <CommandList title="Play a progress card" commands={plays} hand={me.hand} busy={busy} onOpen={onOpen}/>}
  </section>;
}
function SelectionDetail({ view, spot, victims, victim, onVictim }: { view: PublicView; spot: Hotspot; victims?: string[]; victim?: string | null; onVictim?(id: string): void }) {
  const index = useMemo(() => indexBoard(view.board), [view.board]);
  if (spot.shape === 'vertex') { const tiles = vertexTiles(index, spot.id).filter(tile => tile.terrain !== 'sea'), port = view.board.ports.find(item => item.vertices.includes(spot.id)); return <div className="is-detail"><Eyebrow>Selected corner</Eyebrow><ul className="is-detail-tiles">{tiles.map(tile => <li key={tile.id} style={{ '--chip': RESOURCE_META[tile.terrain as Resource]?.color ?? '#e9d5a4' } as CSSProperties}><TerrainIcon terrain={tile.terrain} size={18}/><span>{tileLabel(tile)}</span>{tile.number > 0 && <small aria-label={`${pips(tile.number)} of 5 likelihood`}>{'●'.repeat(pips(tile.number))}{'○'.repeat(5 - pips(tile.number))}</small>}</li>)}{!tiles.length && <li>Open water</li>}</ul>{port && <p className="is-detail-port">Harbour · {port.resource === 'any' ? '3 : 1 any resource' : `2 : 1 ${RESOURCE_META[port.resource].label}`}</p>}</div>; }
  if (spot.shape === 'edge') return <div className="is-detail"><Eyebrow>Selected {spot.tone === 'ship' ? 'sea lane' : 'path'}</Eyebrow><p>{edgeLabel(index, spot.id)}</p></div>;
  const tile = index.tiles.get(spot.id);
  return <div className="is-detail"><Eyebrow>{spot.tone === 'pirate' ? 'Pirate destination' : 'Robber destination'}</Eyebrow><p>{tile ? tileLabel(tile) : spot.id}{spot.tone === 'pirate' ? ' · blocks ships on this sea' : ' · stops producing'}</p>
    {victims && (victims.length ? <ChoiceList label="Steal from" options={victims.map(id => ({ value: id, label: `${nameOf(view, id)} · ${playerOf(view, id)?.handCount ?? 0} cards` }))} value={victim ?? null} onChange={id => onVictim?.(id)} colorOf={id => playerOf(view, id)?.color}/> : <p className="is-detail-note">No one to rob here.</p>)}</div>;
}
function Improvements({ me }: { me: PrivateView }) {
  const levels = me.expansion?.improvements; if (!levels) return null;
  return <div className="is-improvements"><Eyebrow>City improvements</Eyebrow>{TRACKS.map(track => <div key={track} className="is-track" style={{ '--track': TRACK_META[track].color } as CSSProperties}><span>{TRACK_META[track].label}</span><span className="is-track-dots" aria-label={`${TRACK_META[track].label} level ${levels[track]} of 5`}>{Array.from({ length: 5 }, (_, i) => <i key={i} data-on={i < levels[track] || undefined}/>)}</span><b className="kp-numeral">{levels[track]}</b></div>)}</div>;
}

export function Controller({ publicView: view, privateView: me, playerId, sendAction, serverNowMs, roomId, roundId }: Props) {
  const key = `island-settlers:${roomId}:${roundId}:${playerId}`;
  const [draft, setDraft] = useState<Draft>(() => ({ ...fresh(), ...readDraft<Partial<Draft>>(sessionStorage, key, view.turnId) }));
  const turn = useRef(view.turnId);
  useEffect(() => { if (turn.current !== view.turnId) { turn.current = view.turnId; setDraft({ ...fresh(), ...readDraft<Partial<Draft>>(sessionStorage, key, view.turnId) }); } }, [view.turnId, key]);
  const update = (part: Partial<Draft>) => setDraft(previous => { const next = { ...previous, ...part }; saveDraft(sessionStorage, key, view.turnId, next); return next; });
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState<Notice | null>(null);
  const act: Act = async (move, done, success) => {
    if (busy) return; setBusy(true); setNotice(null);
    try { const result = await sendAction({ ...move, turnId: view.turnId } as Action); if (!result.accepted) setNotice({ tone: 'error', text: result.reason ?? 'That move was not accepted.' }); else { if (done) update(done); if (success) setNotice({ tone: 'success', text: success }); } }
    catch { setNotice({ tone: 'error', text: 'Connection interrupted. Try again once reconnected.' }); }
    finally { setBusy(false); }
  };
  if (!me || !playerId) return <StatusNotice>Your private hand is not available yet. Stay connected.</StatusNotice>;
  const seat = playerOf(view, playerId), color = seat?.color ?? '#fff6e5', connect = isConnect(view), settings = withDefaults(view.settings), active = view.activeIds.includes(playerId), goods = pickableGoods(settings);
  const setupPiece = view.setupPiece ?? 'settlement', task = taskFor(view, me, active), step = describeStep(view), hotspots = hotspotsFor(task, draft, me, setupPiece), selected = hotspots.find(spot => spot.id === draft.selected) ?? null;
  const commands = me.expansion?.commands ?? [], choiceCommands = commands.filter(command => command.group === 'Choice'), otherCommands = commands.filter(command => command.group !== 'Choice' && command.group !== 'Progress');
  const openCommand = commands.find(command => command.id === draft.command) ?? null;
  // Command drafts live under the turn draft so reloads restore the half-answered command but a new turn starts clean.
  const commandDraft = (id: string) => draft.commands[id] ?? freshCommandDraft();
  const updateCommand = (id: string, part: Partial<CommandDraft>) => update({ commands: { ...draft.commands, [id]: { ...commandDraft(id), ...part } } });
  const openCmd = (command: ExpansionCommand) => update({ command: command.id, pick: null, selected: null });
  const sendCommand = (command: ExpansionCommand, choices: Record<string, string>, cards?: Hand) => { const rest = { ...draft.commands }; delete rest[command.id]; void act({ type: 'expansion', command: command.id, choices, ...(cards ? { cards } : {}) }, { ...CLEAR, commands: rest }, `${command.label} confirmed.`); };
  const runner = openCommand && <CommandRunner view={view} command={openCommand} draft={commandDraft(openCommand.id)} update={part => updateCommand(openCommand.id, part)} busy={busy} send={sendCommand} onBack={() => update({ command: null })} ghostColor={color}/>;
  const select = (spot: Hotspot) => { if (task === 'action' && draft.pick === 'ship-move' && !draft.from) update({ from: spot.id, selected: null }); else update({ selected: spot.id, victim: null }); };
  const buildButtons = (spot: Hotspot) => { const both = spot.shape === 'edge' && me.legal.roads.includes(spot.id) && me.legal.ships.includes(spot.id), setup = task === 'setup' && spot.shape === 'vertex', kind = spot.shape === 'vertex' ? (spot.tone === 'city' && !setup ? 'city' : 'settlement') : spot.tone === 'ship' ? 'ship' : 'road', shown = setup ? setupPiece : kind; const send = (k: 'road' | 'ship' | 'settlement' | 'city') => act({ type: 'build', kind: k, target: spot.id }, CLEAR, `${PIECE_LABEL[setup && k === 'settlement' ? setupPiece : k]} placed.`); return both ? <><ArcadeButton tone="lime" disabled={busy} onClick={() => send('road')}>Build road here</ArcadeButton><ArcadeButton tone="sky" disabled={busy} onClick={() => send('ship')}>Build ship here</ArcadeButton></> : <ArcadeButton tone="lime" size="lg" disabled={busy} onClick={() => send(kind)}>Confirm {PIECE_LABEL[shown].toLowerCase()}</ArcadeButton>; };
  const back = task === 'action' ? () => update({ pick: null, selected: null, from: null, victim: null }) : null;
  const mapBlock = (title: string, hint: string, confirm: ReactNode, extra?: ReactNode) => <section className="is-task"><div className="is-task-head"><div className="is-task-title"><Eyebrow>{title}</Eyebrow>{back && <button type="button" className="is-back" onClick={back}>‹ Back</button>}</div><p>{hint}</p></div><BoardMap view={view} hotspots={hotspots} selected={selected?.id ?? null} onSelect={select} ghostColor={color}/>{selected ? <>{extra}<div className="is-actionbar">{confirm}<ArcadeButton tone="ghost" disabled={busy} onClick={() => update({ selected: null, victim: null })}>Clear</ArcadeButton></div></> : <p className="is-task-note">{hotspots.length ? `Tap a highlighted spot (${hotspots.length} available). Drag to pan, pinch to zoom.` : draft.pick === 'ship-move' && draft.from ? 'That ship has nowhere to go.' : 'No legal spot right now.'}{draft.pick === 'ship-move' && draft.from && <button type="button" className="is-back" onClick={() => update({ from: null, selected: null })}>Choose another ship</button>}</p>}</section>;
  const victims = selected?.shape === 'tile' ? me.legal.victims[selected.id] ?? [] : [];
  const affordable = (cost: Hand) => canAfford(me.hand, cost), freeRoute = me.freeRoutes > 0, rate = (good: Good) => count(me.rates, good) || 4;
  const hasMovement = !!me.expansion?.hasMovement, endLabel = connect ? view.readyIds.includes(playerId) ? 'Ready · waiting for others' : 'Ready for next round' : task === 'movement' ? 'Finish turn' : hasMovement ? 'Finish building & move' : 'End turn';
  const endButton = <div className="is-actionbar is-endbar"><ArcadeButton tone="coral" size="lg" disabled={busy || !me.canEnd} onClick={() => act({ type: 'end' }, CLEAR)}>{endLabel}</ArcadeButton>{task === 'action' && hasMovement && <small className="is-task-note">Movement comes after this. Once you move, building and trading are closed for the turn.</small>}</div>;
  const tokens = me.expansion && (me.expansion.fish.length > 0 || me.expansion.coins > 0 || settings.expansion === 'explorers' || settings.scenarios?.includes('fishing'));
  return <div className="is-phone" style={{ '--seat': color } as CSSProperties} data-task={task}>
    <header className="is-phone-head"><b className="is-swatch">{view.players.findIndex(player => player.id === playerId) + 1}</b><div className="is-phone-identity"><strong>{seat?.name ?? 'You'}</strong><small>{me.score} VP{seat && me.score !== seat.score ? ' incl. hidden' : ''} · {handTotal(me.hand)} goods · {me.development.length + (me.expansion?.progress.length ?? 0)} card{me.development.length + (me.expansion?.progress.length ?? 0) === 1 ? '' : 's'}</small></div><div className="is-phone-turn">{connect ? <><span>Round {view.turn}</span>{view.deadline !== null && <Countdown deadline={view.deadline} serverNowMs={serverNowMs}/>}</> : <span>{task === 'wait' ? `${nameOf(view, view.actorId)}’s turn` : task === 'ended' ? 'Game over' : task === 'choice' ? 'Your decision' : 'Your turn'}</span>}</div></header>
    {task !== 'ended' && <HandChips hand={me.hand} zeros goods={goods} className="is-hand"/>}
    {task !== 'ended' && tokens && me.expansion && <div className="is-tokens" aria-label="Tokens">{(settings.expansion === 'explorers' || settings.scenarios?.includes('fishing') || me.expansion.fish.length > 0) && <span className="is-token" data-kind="fish"><TerrainIcon terrain="lake" size={16}/><b className="kp-numeral">{me.expansion.fish.length}</b> fish{me.expansion.fish.length > 0 && <small> · worth {me.expansion.fish.reduce((sum, token) => sum + token.value, 0)}</small>}</span>}{(settings.expansion === 'explorers' || me.expansion.coins > 0) && <span className="is-token" data-kind="coins"><TerrainIcon terrain="gold" size={16}/><b className="kp-numeral">{me.expansion.coins}</b> gold coins</span>}</div>}
    {notice && <StatusNotice tone={notice.tone}>{notice.text}</StatusNotice>}
    {view.pausedPlayers.length > 0 && <StatusNotice>Timers paused while {view.pausedPlayers.map(id => nameOf(view, id)).join(', ')} reconnect.</StatusNotice>}
    {task === 'ended' && <Panel className="is-task"><Eyebrow>Final</Eyebrow><h2 className="kp-display">{step.title}</h2><p>{view.winners.includes(playerId) ? 'You reached the target. Well settled!' : 'Results are on the shared screen.'}</p></Panel>}
    {task === 'choice' && (runner ?? <><section className="is-task is-choice"><Eyebrow>Decision needed</Eyebrow><h2>{me.expansion?.task}</h2><p>Everyone waits for this. Pick an option below and confirm.</p></section><CommandList commands={choiceCommands} hand={me.hand} busy={busy} onOpen={openCmd} empty="No option has arrived for this decision yet. Stay connected; it appears here as soon as the game lists it."/></>)}
    {task === 'wait' && <><Panel className="is-task is-wait"><Eyebrow>{view.phase === 'choice' ? 'Waiting for a decision' : connect ? 'Waiting' : `${nameOf(view, view.actorId)}’s move`}</Eyebrow><h2>{step.title}</h2><p>{view.phase === 'choice' ? `${names(view, view.activeIds)} ${view.activeIds.length === 1 ? 'has' : 'have'} a required choice open on their phone. Play resumes when it is confirmed.` : step.detail}</p>{view.phase === 'action' && !connect && me.canTrade && <p className="is-task-note">Accept their offers or post a counteroffer below. Every trade involves {nameOf(view, view.actorId)}.</p>}</Panel><Offers view={view} me={me} playerId={playerId} busy={busy} act={act}/>{me.canTrade && <OfferComposer view={view} me={me} draft={draft} update={update} busy={busy} act={act} goods={goods}/>}{(me.development.length > 0 || (me.expansion?.progress.length ?? 0) > 0) && <details className="is-more"><summary>Your cards ({me.development.length + (me.expansion?.progress.length ?? 0)})</summary><ul className="is-devlist">{me.development.map(card => <li key={card.id}><strong>{DEV_META[card.kind].label}</strong><small>{DEV_META[card.kind].blurb}</small></li>)}{me.expansion?.progress.map(card => <li key={card.id}><strong>{PROGRESS_LABEL[card.kind]}</strong><small>{TRACK_META[card.track].label} progress</small></li>)}</ul></details>}<Improvements me={me}/><details className="is-more"><summary>Show the island</summary><BoardMap view={view}/></details></>}
    {task === 'roll' && (runner ?? <><section className="is-task is-roll"><Eyebrow>Your turn</Eyebrow><h2>Roll the dice</h2><p>{settings.citiesKnights ? 'Two dice produce; the event die moves the barbarians or deals progress cards.' : 'Everyone collects from matching numbers. A 7 lets you move the robber.'}</p><ArcadeButton size="xl" tone="sun" disabled={busy} onClick={() => act({ type: 'roll' }, CLEAR)}>Roll</ArcadeButton></section>{(me.development.some(card => card.playable) || commands.some(command => command.group === 'Progress')) && <CardPanel title="Play a card before rolling" me={me} draft={draft} update={update} busy={busy} act={act} onOpen={openCmd}/>}<CommandList title="Before rolling" commands={otherCommands} hand={me.hand} busy={busy} onOpen={openCmd}/></>)}
    {task === 'free-routes' && <>{mapBlock(`Road Building · ${me.freeRoutes} free route${me.freeRoutes === 1 ? '' : 's'} left`, 'Place your free roads or ships before rolling. Other building and trading waits until after the roll.', selected ? buildButtons(selected) : null, selected ? <SelectionDetail view={view} spot={selected}/> : null)}<div className="is-actionbar is-endbar"><ArcadeButton tone="ghost" disabled={busy || !me.canEnd} onClick={() => act({ type: 'end' }, CLEAR, 'Remaining free routes skipped. Roll when ready.')}>Skip remaining routes</ArcadeButton></div></>}
    {task === 'discard' && <section className="is-task"><Eyebrow>Robber!</Eyebrow><h2>Discard {me.discardDue} card{me.discardDue === 1 ? '' : 's'}</h2><p>You are over your hand limit{settings.citiesKnights ? ' (seven, or more with city walls)' : ' of seven'}. Choose exactly {me.discardDue} to return to the bank{settings.citiesKnights ? '; commodities count too' : ''}.</p><HandPicker title="Discard" hint={`${handTotal(draft.cards)} of ${me.discardDue} chosen`} value={draft.cards} limit={me.hand} goods={goods} onChange={cards => update({ cards })}/><div className="is-actionbar"><ArcadeButton tone="coral" size="lg" disabled={busy || handTotal(draft.cards) !== me.discardDue || !withinLimit(draft.cards, me.hand, goods)} onClick={() => act({ type: 'discard', cards: draft.cards }, CLEAR, 'Cards discarded.')}>Discard {handTotal(draft.cards)} / {me.discardDue}</ArcadeButton></div></section>}
    {task === 'gold' && (() => { const due = Math.min(me.goldDue, resourceTotal(me.bank)); return <section className="is-task"><Eyebrow>Gold field</Eyebrow><h2>Take {due} resource{due === 1 ? '' : 's'}</h2><p>Gold pays in any resource you like{due < me.goldDue ? `. The bank only has ${due} left` : ''}.</p><HandPicker title="Take from the bank" hint={`${handTotal(draft.cards)} of ${due} chosen`} value={draft.cards} limit={me.bank} goods={RESOURCES} onChange={cards => update({ cards })}/><div className="is-actionbar"><ArcadeButton tone="sun" size="lg" disabled={busy || handTotal(draft.cards) !== due || !withinLimit(draft.cards, me.bank, RESOURCES)} onClick={() => act({ type: 'gold', cards: draft.cards }, CLEAR, 'Gold collected.')}>Take {handTotal(draft.cards)} / {due}</ArcadeButton></div></section>; })()}
    {task === 'setup' && mapBlock(me.legal.settlements.length ? `Setup · place a ${PIECE_LABEL[setupPiece].toLowerCase()}` : `Setup · add a road${me.legal.ships.length ? ' or ship' : ''}`, me.legal.settlements.length ? `Pick a corner${setupPiece === 'city' ? '. A city produces double' : setupPiece === 'harbor' ? '. A harbor settlement produces one resource and lets ships load' : ''}. Numbers with more dots roll more often; spread your resources.` : `Routes must touch your new ${PIECE_LABEL[setupPiece].toLowerCase()}.${me.legal.ships.length ? ' Ships sail on sea lanes.' : ''}`, selected ? buildButtons(selected) : null, selected ? <SelectionDetail view={view} spot={selected}/> : null)}
    {task === 'robber' && mapBlock(me.legal.pirate.length ? 'Move the robber or pirate' : 'Move the robber', 'Choose a hex to block. If neighbours live there, pick one to rob.', selected && (victims.length === 0 || draft.victim) ? <ArcadeButton tone="coral" size="lg" disabled={busy} onClick={() => act({ type: 'robber', target: selected.id, victim: draft.victim ?? null, pirate: selected.tone === 'pirate' }, CLEAR, draft.victim ? `Robbed ${nameOf(view, draft.victim)}.` : 'Robber moved.')}>Confirm {selected.tone === 'pirate' ? 'pirate' : 'robber'}</ArcadeButton> : <span className="is-task-note">Choose who to rob.</span>, selected ? <SelectionDetail view={view} spot={selected} victims={victims} victim={draft.victim} onVictim={id => update({ victim: id })}/> : null)}
    {task === 'movement' && (runner ?? <><div className="is-turnline"><Eyebrow>{connect ? `Round ${view.turn} · movement` : 'Your turn · movement'}</Eyebrow><small>Building and trading are finished for this turn. Move ships, wagons or knights, then finish.</small></div><CommandList commands={otherCommands} hand={me.hand} busy={busy} onOpen={openCmd} empty="Nothing can move right now. Finish your turn to continue."/>{endButton}</>)}
    {task === 'action' && (runner ?? <>
      <div className="is-turnline"><Eyebrow>{connect ? `Round ${view.turn} · build and trade` : view.secondary ? 'Paired turn' : 'Your turn'}</Eyebrow>{view.secondary && <small>Bank trades, building and cards only. No player trades this turn.</small>}{freeRoute && <small className="is-free">{me.freeRoutes} free route{me.freeRoutes === 1 ? '' : 's'} from Road Building — place {me.freeRoutes === 1 ? 'it' : 'them'} now.</small>}</div>
      <div className="is-tabs" role="tablist" aria-label="Actions" data-count={otherCommands.length || me.expansion ? 4 : 3}>{(['build', 'trade', 'cards', 'more'] as Tab[]).filter(tab => tab !== 'more' || otherCommands.length > 0 || !!me.expansion).map(tab => <button key={tab} type="button" role="tab" aria-selected={draft.tab === tab} onClick={() => update({ tab, ...(draft.pick ? { pick: null, selected: null, from: null } : {}) })}>{tab === 'build' ? 'Build' : tab === 'trade' ? 'Trade' : tab === 'cards' ? `Cards${me.development.length + (me.expansion?.progress.length ?? 0) ? ` · ${me.development.length + (me.expansion?.progress.length ?? 0)}` : ''}` : `More${otherCommands.length ? ` · ${otherCommands.length}` : ''}`}</button>)}</div>
      {draft.tab === 'build' && (draft.pick ? mapBlock(draft.pick === 'ship-move' ? (draft.from ? 'Move ship · choose destination' : 'Move ship · choose a ship') : `Build ${draft.pick === 'route' ? 'a road or ship' : `a ${draft.pick}`}`, draft.pick === 'ship-move' ? 'Only ships at the open end of a line can move.' : draft.pick === 'city' ? 'Cities replace one of your settlements and produce double.' : 'Tap a highlighted spot, then confirm.', selected ? draft.pick === 'ship-move' ? <ArcadeButton tone="sky" size="lg" disabled={busy || !draft.from} onClick={() => act({ type: 'move-ship', from: draft.from!, to: selected.id }, CLEAR, 'Ship moved.')}>Confirm move</ArcadeButton> : buildButtons(selected) : null, selected ? <SelectionDetail view={view} spot={selected}/> : null) : <section className="is-task is-build">
        {([['road', me.legal.roads], ['ship', me.legal.ships], ['settlement', me.legal.settlements], ['city', me.legal.cities]] as const).filter(([kind]) => kind !== 'ship' || settings.expansion === 'seafarers').map(([kind, legal]) => { const free = freeRoute && (kind === 'road' || kind === 'ship'), ok = legal.length > 0; return <button key={kind} type="button" className="is-build-option" disabled={!ok || busy} onClick={() => update({ pick: kind, selected: null })}><span className="is-build-name"><strong>{PIECE_LABEL[kind]}</strong><small>{ok ? `${legal.length} spot${legal.length === 1 ? '' : 's'}` : !free && !affordable(COSTS[kind]) ? 'Need more resources' : 'No legal spot'}</small></span><CostChips cost={COSTS[kind]} free={free}/></button>; })}
        {me.legal.shipMoves.length > 0 && <button type="button" className="is-build-option" disabled={busy} onClick={() => update({ pick: 'ship-move', selected: null, from: null })}><span className="is-build-name"><strong>Move a ship</strong><small>{me.legal.shipMoves.length} can sail</small></span><span className="is-cost is-cost-free">free</span></button>}
        {!settings.citiesKnights && settings.expansion !== 'explorers' && <button type="button" className="is-build-option" disabled={busy || view.deckCount === 0 || !affordable(COSTS.development)} onClick={() => act({ type: 'buy-development' }, undefined, 'Development card bought. Find it under Cards.')}><span className="is-build-name"><strong>Development card</strong><small>{view.deckCount ? `${view.deckCount} left in the deck` : 'Deck is empty'}</small></span><CostChips cost={COSTS.development}/></button>}
        <CommandList commands={otherCommands.filter(command => command.group === 'Cities' || command.group === 'Knights' || command.group === 'Expeditions')} hand={me.hand} busy={busy} onOpen={openCmd}/>
      </section>)}
      {draft.tab === 'trade' && <section className="is-task is-trade">
        <div className="is-bank-trade"><Eyebrow>Bank &amp; harbours</Eyebrow><p className="is-task-note">Your rates: {goods.map(good => `${GOOD_META[good].label} ${rate(good)}:1`).join(' · ')}</p>
          <strong className="is-label">Give</strong><GoodPick label="Good to give" goods={goods} value={draft.bankGive} onChange={bankGive => update({ bankGive })} disabledFor={good => count(me.hand, good) < rate(good)}/>
          <strong className="is-label">Get{handTotal(me.bank) === 0 && <small> · bank is empty</small>}</strong><GoodPick label="Good to receive" goods={goods} value={draft.bankGet} onChange={bankGet => update({ bankGet })} disabledFor={good => good === draft.bankGive || count(me.bank, good) < 1}/>
          <ArcadeButton tone="sky" disabled={busy || !draft.bankGive || !draft.bankGet || draft.bankGive === draft.bankGet} onClick={() => act({ type: 'bank', give: draft.bankGive!, get: draft.bankGet! }, { bankGive: null, bankGet: null }, 'Bank trade done.')}>{draft.bankGive && draft.bankGet ? `Trade ${rate(draft.bankGive)} ${GOOD_META[draft.bankGive].label} for 1 ${GOOD_META[draft.bankGet].label}` : 'Choose give and get'}</ArcadeButton></div>
        <Offers view={view} me={me} playerId={playerId} busy={busy} act={act}/>
        <OfferComposer view={view} me={me} draft={draft} update={update} busy={busy} act={act} goods={goods}/>
      </section>}
      {draft.tab === 'cards' && <CardPanel me={me} draft={draft} update={update} busy={busy} act={act} onOpen={openCmd}/>}
      {draft.tab === 'more' && <section className="is-task is-more-tab"><Improvements me={me}/>{(['Knights', 'Cities', 'Fishing', 'Rivers', 'Caravans', 'Barbarians', 'Deliveries', 'Expeditions'] as const).map(group => { const items = otherCommands.filter(command => command.group === group); return items.length ? <CommandList key={group} title={group} commands={items} hand={me.hand} busy={busy} onOpen={openCmd}/> : null; })}{!otherCommands.length && <p className="is-task-note">No expansion actions are available right now.</p>}</section>}
      {!draft.pick && endButton}
    </>)}
  </div>;
}
