import type { PublicView } from './model';
import { CARGO_META, TRACK_META, WAGON_CARGO, edgeGeometry, type BoardIndex } from './presentation';

const R = (n: number) => Math.round(n * 1000) / 1000;
type Ctx = { view: PublicView; index: BoardIndex; colorOf(id: string): string };
const INK = '#05071a', CREAM = '#fff6e5';

function Shield({ x, y, color, strength, active }: { x: number; y: number; color: string; strength: number; active: boolean }) {
  return <g transform={`translate(${R(x)} ${R(y)})`} className="is-piece"><path d="M-.2-.28h.4v.3q0 .26-.2.4-.2-.14-.2-.4Z" fill={color} stroke={INK} strokeWidth=".05"/>{Array.from({ length: strength }, (_, i) => <circle key={i} cx={(i - (strength - 1) / 2) * .11} cy="-.08" r=".045" fill={active ? '#ffd24a' : INK}/>)}{!active && <line x1="-.16" y1=".2" x2=".16" y2="-.2" stroke={CREAM} strokeWidth=".04"/>}</g>;
}
function Cargo({ x, y, kinds }: { x: number; y: number; kinds: string[] }) {
  return <g transform={`translate(${R(x)} ${R(y)})`}>{kinds.map((kind, i) => <rect key={i} x={-.06 + (i - (kinds.length - 1) / 2) * .13} y="-.06" width=".12" height=".12" rx=".02" fill={(CARGO_META as Record<string, { color: string }>)[kind]?.color ?? CREAM} stroke={INK} strokeWidth=".03"/>)}</g>;
}
/** Expansion layers drawn over the base board; every marker keys off public IDs only. */
export function MapLayers({ view, index, colorOf }: Ctx) {
  const exp = view.expansions; if (!exp) return null;
  const vertex = (id: string) => index.vertices.get(id), tile = (id: string) => index.tiles.get(id), edge = (id: string) => edgeGeometry(index, id);
  return <g className="is-layers">
    {exp.rivers?.edges.map(id => { const g = edge(id); return g && <line key={`river-${id}`} x1={R(g.a.x)} y1={R(g.a.y)} x2={R(g.b.x)} y2={R(g.b.y)} stroke="#3aa6e8" strokeWidth=".22" strokeLinecap="round" opacity=".9"/>; })}
    {exp.rivers?.bridgeSites.map(id => { const g = edge(id); return g && <circle key={`site-${id}`} cx={R(g.x)} cy={R(g.y)} r=".1" fill="none" stroke={CREAM} strokeWidth=".04" strokeDasharray=".05 .04"/>; })}
    {exp.rivers?.bridges.map(id => { const g = edge(id); return g && <rect key={`bridge-${id}`} x="-.22" y="-.08" width=".44" height=".16" rx=".04" fill="#8a6136" stroke={INK} strokeWidth=".03" transform={`translate(${R(g.x)} ${R(g.y)}) rotate(${R(g.angle * 180 / Math.PI)})`}/>; })}
    {exp.caravans?.segments.map(seg => { const g = edge(seg.edge); return g && <g key={`caravan-${seg.edge}`} transform={`translate(${R(g.x)} ${R(g.y)}) rotate(${R(g.angle * 180 / Math.PI)})`}><line x1="-.34" x2=".34" stroke="#d9b27a" strokeWidth=".14" strokeLinecap="round" strokeDasharray=".1 .08"/><circle cx="-.08" cy="-.05" r=".07" fill="#8a6136" stroke={INK} strokeWidth=".025"/><circle cx=".08" cy="-.05" r=".07" fill="#8a6136" stroke={INK} strokeWidth=".025"/></g>; })}
    {exp.attack?.barbarians.map(item => { const t = tile(item.tile); return t && <g key={`barb-${item.tile}`} transform={`translate(${R(t.x - .45)} ${R(t.y + .35)})`}>{Array.from({ length: Math.min(item.count, 4) }, (_, i) => <path key={i} d={`M${i * .16 - .1} .1l.08-.22.08.22Z`} fill="#2b2540" stroke={CREAM} strokeWidth=".025"/>)}{item.count > 4 && <text x=".7" y=".12" fontSize=".22" fontWeight="900" fill={CREAM}>×{item.count}</text>}</g>; })}
    {exp.attack?.guards.map(guard => { const g = edge(guard.edge); return g && <g key={guard.id} transform={`translate(${R(g.x)} ${R(g.y)})`} className="is-piece"><circle r=".13" fill={colorOf(guard.playerId)} stroke={INK} strokeWidth=".04"/><line x1="0" y1="-.28" x2="0" y2=".05" stroke={guard.active ? '#ffd24a' : INK} strokeWidth=".04"/><text y=".06" textAnchor="middle" fontSize=".16" fontWeight="900" fill={INK}>{guard.strength}</text></g>; })}
    {exp.deliveries?.barbarians.map(id => { const g = edge(id); return g && <g key={`roadbarb-${id}`} transform={`translate(${R(g.x)} ${R(g.y)})`}><path d="M-.12.1l.12-.3.12.3Z" fill="#2b2540" stroke={CREAM} strokeWidth=".03"/></g>; })}
    {exp.deliveries?.wagons.map(wagon => { const v = vertex(wagon.vertex); return v && <g key={`wagon-${wagon.playerId}`} transform={`translate(${R(v.x)} ${R(v.y - .3)})`} className="is-piece"><rect x="-.2" y="-.12" width=".4" height=".2" rx=".04" fill={colorOf(wagon.playerId)} stroke={INK} strokeWidth=".04"/><circle cx="-.12" cy=".12" r=".06" fill={INK}/><circle cx=".12" cy=".12" r=".06" fill={INK}/>{wagon.cargo && <rect x="-.07" y="-.24" width=".14" height=".14" fill={WAGON_CARGO[wagon.cargo].color} stroke={INK} strokeWidth=".03"/>}</g>; })}
    {exp.explorers?.ships.map(ship => { const g = edge(ship.edge); return g && <g key={ship.id} className="is-piece"><g transform={`translate(${R(g.x)} ${R(g.y)}) rotate(${R(g.angle * 180 / Math.PI)})`}><path d="M-.4 .02q.4 .26 .8 0l-.12 .2h-.56Z" fill={colorOf(ship.playerId)} stroke={INK} strokeWidth=".05"/><path d="M-.05 .02V-.36M-.05 -.36l.3 .26h-.3Z" fill={CREAM} stroke={INK} strokeWidth=".04"/></g><Cargo x={g.x} y={g.y + .34} kinds={ship.cargo.map(c => c.kind)}/></g>; })}
    {exp.explorers?.harbors.map(h => { const v = vertex(h.vertex); return v && h.cargo.length > 0 && <Cargo key={`hcargo-${h.vertex}`} x={v.x} y={v.y + .34} kinds={h.cargo.map(c => c.kind)}/>; })}
    {exp.explorers?.lairs.map(lair => { const t = tile(lair.tile); return t && <g key={`lair-${lair.tile}`} transform={`translate(${R(t.x)} ${R(t.y + .25)})`}><path d="M-.3.15l.3-.5.3.5Z" fill={lair.captured ? '#6b7385' : '#2b2540'} stroke={CREAM} strokeWidth=".035"/>{lair.captured ? <path d="M0-.35v-.3l.22.08-.22.1" fill={CREAM} stroke={CREAM} strokeWidth=".03"/> : lair.crews.slice(0, 3).map((id, i) => <circle key={id} cx={(i - 1) * .14} cy=".28" r=".06" fill={colorOf(id)} stroke={INK} strokeWidth=".025"/>)}</g>; })}
    {exp.explorers?.shoals.map(shoal => { const t = tile(shoal.tile); return t && shoal.fish && <g key={`fish-${shoal.tile}`} transform={`translate(${R(t.x + .45)} ${R(t.y - .4)})`}><path d="M-.14 0q.14-.14.28 0-.14.14-.28 0Zm-.06 0-.1-.1v.2Z" fill="#6cc3e8" stroke={INK} strokeWidth=".025"/></g>; })}
    {exp.explorers?.spices.map(spice => { const t = tile(spice.tile); return t && <g key={`spice-${spice.tile}`} transform={`translate(${R(t.x + .42)} ${R(t.y + .38)})`}><rect x="-.1" y="-.14" width=".2" height=".28" rx=".05" fill={spice.benefit === 'gold' ? '#ffd24a' : spice.benefit === 'pirate' ? '#2b2540' : '#28c6e7'} stroke={INK} strokeWidth=".03"/>{spice.visitors.slice(0, 3).map((id, i) => <circle key={id} cx={(i - 1) * .12} cy=".22" r=".05" fill={colorOf(id)} stroke={INK} strokeWidth=".02"/>)}</g>; })}
    {exp.fishing?.grounds.map(ground => { const points = ground.vertices.map(vertex).filter((v): v is NonNullable<typeof v> => !!v); if (!points.length) return null; const cx = points.reduce((s, p) => s + p.x, 0) / points.length, cy = points.reduce((s, p) => s + p.y, 0) / points.length; return <g key={`ground-${ground.id}`} transform={`translate(${R(cx)} ${R(cy)})`}><ellipse rx=".42" ry=".28" fill="#3b9ad8" fillOpacity=".5" stroke="#6cc3e8" strokeWidth=".04" strokeDasharray=".08 .06"/><text y=".06" textAnchor="middle" fontSize=".2" fontWeight="900" fill={CREAM}>{ground.numbers.join(' ')}</text></g>; })}
    {exp.merchant && (() => { const t = tile(exp.merchant.tile); return t && <g transform={`translate(${R(t.x - .45)} ${R(t.y - .3)})`}><path d="M-.22.12l.22-.4.22.4Z" fill={colorOf(exp.merchant.playerId)} stroke={INK} strokeWidth=".035"/><path d="M-.08.12l.08-.16.08.16Z" fill={CREAM}/></g>; })()}
    {exp.walls.map(id => { const v = vertex(id); return v && <circle key={`wall-${id}`} cx={R(v.x)} cy={R(v.y)} r=".34" fill="none" stroke="#7d6b52" strokeWidth=".07" strokeDasharray=".12 .05"/>; })}
    {exp.metropolises.map(m => { const v = vertex(m.vertex); return v && <g key={`metro-${m.vertex}`} transform={`translate(${R(v.x)} ${R(v.y - .42)})`}><path d="M-.18.08v-.14l.09.08.09-.16.09.16.09-.08v.14Z" fill={TRACK_META[m.track].color} stroke={INK} strokeWidth=".03"/></g>; })}
    {exp.knights.map(knight => { const v = vertex(knight.vertex); return v && <Shield key={knight.id} x={v.x} y={v.y} color={colorOf(knight.playerId)} strength={knight.strength} active={knight.active}/>; })}
  </g>;
}
