import { useId, useState } from 'react';
import { Modal } from '../../../party-ui/src/index';
import { COSTS, type Settings } from './model';
import { GOOD_META, MISSION_META, PIECE_LABEL, withDefaults } from './presentation';
import { SCENARIO_NAMES, VARIANT_NAMES } from './expansion-settings';
import type { Scenario } from './expansion-model';

type Topic = { id: string; title: string; lines: string[] };
const SCENARIO_HELP: Record<Scenario, string[]> = {
  fishing: ['Build beside numbered fishing grounds or the lake to collect fish tokens when they produce. Cities draw twice; token values vary.', 'Open More → Fishing to spend fish on the available benefits. Prices are shown on each action, and overpayment gives no change. Fish tokens are different from expedition fish hauls.', 'The old boot makes its owner need one extra victory point. Its owner may pass it to someone with at least their public score.'],
  rivers: ['Marked river crossings need bridges instead of ordinary roads. Build bridges through More → Rivers; each costs two brick and one wood.', 'River-side roads and settlements earn gold; a bridge earns three gold. Gold coins are separate from coin commodity cards.', 'The sole wealthiest player gains one point. The poorest players lose two points unless Barbarian Attack or deliveries is also enabled. Spending gold can change these awards.'],
  caravans: ['Building a settlement or upgrading a building can trigger a caravan decision. Follow the private bidding and voting prompts after negotiating with the table.', 'Wool and grain bids give votes for the next caravan edge. A tie is resolved by the prompted player.', 'A route edge with a caravan counts twice toward Longest Route. A building touched by at least two caravan segments earns one extra point.'],
  'barbarian-attack': ['Barbarians land on coastal hexes. Three on a hex stop its production; a building surrounded entirely by conquered land also loses its building points until freed.', 'Use More → Barbarians to position castle knights on edges beside threatened hexes. Combined with Cities & Knights, recruit, activate and promote them through the knight actions.', 'At battle, nearby defending strength must exceed the barbarian count. Captured prisoners earn points: one per two prisoners, or per three with Cities & Knights. Knights can suffer losses.', 'This replaces the land robber and Largest Army. A seven still requires discards, then the active player chooses an opponent to steal from.'],
  traders: ['Your wagon carries goods between the castle, quarry and glassworks. Open More → Deliveries for its destination, movement and upgrade choices.', 'Build and trade before starting movement. Routes help travel, other players may collect tolls, and barbarians interfere with the journey.', 'Deliver the cargo to its matching destination for one point and the displayed reward, then take the next cargo. The final wagon upgrade adds one point.', 'Deliveries replaces Longest Route and the land robber. After discards on a seven, follow the barbarian-movement prompt.'],
};
export function rulesTopics(raw: Settings, playerCount: number): Topic[] {
  const s = withDefaults(raw), sea = s.expansion === 'seafarers', ep = s.expansion === 'explorers', ck = !!s.citiesKnights, scenarios = s.scenarios ?? [], attack = scenarios.includes('barbarian-attack'), deliveries = scenarios.includes('traders');
  const topics: Topic[] = [], add = (id: string, title: string, ...lines: string[]) => topics.push({ id, title, lines });
  add('start', 'Start here', `Reach ${s.targetPoints} victory points. Settlements are worth one point; cities${ep ? ' and harbor settlements' : ''} are worth two. Your phone includes your hidden points.`, 'The shared screen shows the board and public totals. Your phone holds your private cards and available actions.', 'When a map appears, tap a highlighted spot, review it, then confirm. Drag to pan; pinch or use + / − to zoom. The whole-board button resets the view.', 'Build and trade on their tabs. Expansion actions are under More; private decisions appear automatically. An unavailable action may need more cards, a legal location or a later phase.');
  add('turns', s.mode === 'connect' ? 'Connect-style rounds' : 'Standard turns', ...(s.mode === 'connect' ? [
    `One shared roll produces for everyone, then everyone may trade and build at once for up to ${s.roundSeconds} seconds.`, 'Confirm promptly: the first confirmed placement claims a contested location. Ready ends your actions for this round; the next round starts when everyone is ready or time expires.', 'Victory is checked at the round boundary. If several people qualify, the highest score wins; equal highest scores share victory.',
  ] : ['The main player rolls, resolves production and required choices, then trades and builds in any order before ending their turn.', ...(playerCount >= 5 ? ['With five or more players, a paired player then gets a building turn without rolling or trading with other players. Bank trades are allowed.'] : []), 'Reach the target during your own active turn to win.']), 'Required decisions and disconnected players can pause play. Opening this guide does not pause the game or the Connect timer.');
  add('setup', 'Starting placements', 'Setup goes once around the table and then back in reverse order. Each placement is followed by an adjoining route.', ep ? (ck ? 'Place a city and road first, then a harbor settlement and expedition ship.' : 'Place a harbor settlement and expedition ship first, then a settlement and road.') : `Place a settlement and route first, then ${ck || attack || deliveries ? 'a city' : 'a second settlement'} and route.`, 'Leave at least one empty corner between buildings. Choose a mix of resources and numbers; more dots mean a more likely roll. The game grants your starting resources automatically.');
  add('production', 'Dice, resources & building', 'Everyone collects from their buildings beside hexes matching the dice total. A settlement produces one resource; a city normally produces two. The bank is finite, so a shortage can prevent a payout.', 'New roads extend your connected network. New settlements must touch your route and leave one empty corner between buildings. Upgrade your own settlement to a city.', ...(['road', 'settlement', ...(ep && !ck ? [] : ['city']), ...(sea ? ['ship'] : []), ...(!ck && !ep ? ['development'] : [])] as (keyof typeof COSTS)[]).map(kind => `${kind === 'development' ? 'Development card' : PIECE_LABEL[kind]}: ${Object.entries(COSTS[kind]).filter(([, n]) => n).map(([r, n]) => `${n} ${GOOD_META[r as keyof typeof GOOD_META].label.toLowerCase()}`).join(', ')}.`));
  add('trading', 'Trading', 'Agree a deal aloud, then post what you give and what you want on Trade. The other player accepts; the proposer confirms the partner to exchange the cards.', 'Accepting alone does not transfer anything. If someone spends the offered cards, the deal may no longer be available. No gifts or promises of future cards.', s.mode === 'standard' ? 'Player trades must involve the main active player. The paired building turn has no player trades.' : 'Anyone still acting in the round may negotiate and trade.', ep ? 'Harbor settlements replace trading ports. Check the rates shown on your phone; gold purchases are separate actions.' : 'Bank trading normally costs four matching resources for one. Your ports reduce this to three of any one resource, or two of the named resource. Your phone shows the rates you can use.');
  add('seven', 'A seven & blocked hexes', `A seven gives no normal resource production. Over the hand limit of seven${ck ? ' plus two per city wall' : ''}, discard half your resource${ck ? ' and commodity' : ''} cards, rounded down. Follow the exact count on your phone.`, attack ? SCENARIO_HELP['barbarian-attack'][3] : deliveries ? SCENARIO_HELP.traders[3] : ep ? 'There is no land robber. Move the pirate as prompted; opponent ships passing its waters may owe gold tribute.' : 'Move the robber to another legal land hex, then choose an adjacent opponent to steal one random card from. The blocked hex stops producing until the robber leaves.', ...(ck && !ep && !attack && !deliveries ? ['The robber stays out of play until the first barbarian fleet attack; discards still happen.'] : []));
  if (!ep && !deliveries) add('route', 'Longest Route', 'The longest continuous route of at least five edges earns two points. Branches cannot reuse an edge, and an opponent building can interrupt your route.', 'A tied challenger does not take the award from its current holder. If it becomes unowned, a sole leader must claim it.', ...(sea ? ['Roads and ships join into one route only through your own building.'] : []));
  if (!ck && !ep) {
    if (attack) add('cards', 'Barbarian Attack: defense cards', 'Open More → Barbarians and choose Draw a defense card. Pay one ore, one wool and one grain, then resolve the drawn effect immediately.', 'Follow its placement or resource prompts. These cards replace the ordinary development deck; there is no Largest Army award.');
    else add('cards', 'Development cards', 'Buy on Build and play from Cards. A new card normally waits until a later turn. Play at most one development card per turn; hidden victory cards count automatically.', ...(deliveries ? ['Knight moves a road barbarian; Road Building gives two free routes; Swift Journey helps your wagon travel. This scenario deck replaces Year of Plenty and Monopoly.'] : ['Knight moves the robber; Road Building gives two free routes; Year of Plenty takes two available resources; Monopoly takes all opponents’ cards of one resource.']), 'Playing three Knights can earn Largest Army for two points. A challenger needs more played Knights to take it.');
  }
  if (sea) add('seafarers', 'Seafarers', 'Ships cost one wood and one wool and occupy sea lanes. They extend from your ships or buildings; switch between roads and ships at your own building.', 'Once per turn, move an older ship at the open end of a shipping route. Newly built ships and pirate-blocked ships cannot move.', 'Your first settlement on each new island earns two extra points. Gold fields let you choose resources from the bank when they produce.', 'On a seven or a Knight move, choose the robber or pirate. The pirate blocks nearby ship building and movement.');
  if (ck) {
    add('cities', 'Cities & Knights: cities', 'Cities beside wood, wool and ore produce one resource plus paper, cloth or coin respectively. Grain and brick cities still produce two resources. Harbor settlements produce only one resource.', 'Spend paper on Science, cloth on Trade and coin on Politics through More → Cities. Each next improvement costs its new level in that commodity. Level three unlocks the track’s special ability.', 'Reach level four first in a track to claim its metropolis on a city. It adds two points; a rival must exceed your level to take it. Level five secures that track.', 'A wall costs two brick and raises your discard limit by two. You may have up to three walls.');
    add('knights', 'Cities & Knights: defense', 'Recruit a basic knight for one wool and one ore. Activate it for one grain. Activation defends immediately; its other actions wait until your next turn.', 'Promote a knight for one wool and one ore. Moving, displacing a weaker knight or chasing a robber uses an eligible active knight and deactivates it.', 'The event die advances the barbarian fleet. When it attacks, total active knight strength must match or exceed the number of cities. Help defend before it arrives.', 'A successful defense rewards the strongest contributors. If defense fails, the weakest eligible defenders lose a vulnerable city; metropolises are protected. Knights deactivate after the attack.', ...(ep ? ['Knights remain on their own island; they do not travel as ship cargo. Harbors are distinct from cities.'] : []));
    add('progress', 'Cities & Knights: progress cards', 'Progress cards replace ordinary development-card purchases and Largest Army. The event die and your improvement levels determine which tracks deal cards.', 'Open Cards to read and play your available progress actions. Each action explains its effect and any targets or resources you must choose.', 'Progress cards have their own timing and hand-limit prompts. Resolve any discard or mandatory choice on your phone before play can continue.');
  }
  for (const scenario of scenarios) add(scenario, SCENARIO_NAMES[scenario], ...SCENARIO_HELP[scenario]);
  if (ep) {
    add('explorers', 'Explorers & Pirates: sailing', 'Build a harbor settlement by upgrading a coastal settlement for two grain and two ore. It is worth two points, produces one resource and holds two cargo spaces.', 'Build up to three expedition ships beside your harbors for one wood and one wool each. A ship holds one settler or fish haul, or two small crew/spice pieces.', 'Build settlers for the ordinary settlement cost; crews cost one wool and one ore. Load and transfer cargo through the displayed harbor/ship actions.', 'Finish building and trading before moving ships. Sail using the highlighted sea edges; discovering a fog hex ends that ship’s movement. One wool can buy two extra moves once per ship per turn.', 'Land a settler on an eligible coast to replace the ship and settler with a settlement. Build only beside explored land; uncleared lairs and unvisited spice farms can block settlement sites.');
    for (const mission of s.missions ?? []) add(`mission-${mission}`, `Mission: ${MISSION_META[mission].label}`, ...(mission === 'lairs' ? ['Sail crews to discovered pirate lairs. A lair is captured once three crews have landed there; contributors earn mission progress and the strongest contributor can earn a bonus.', 'Recover crews from captured lairs using an adjacent ship with space.'] : mission === 'fish' ? ['Use Find a fish haul during movement. A matching discovered shoal can gain a haul.', 'Load a haul onto an empty ship, sail to the Council coast and deliver it for mission progress. The haul uses both cargo spaces.'] : ['Land a crew at a spice farm you have not visited. It gives spices and the farm’s ongoing benefit.', 'Return spices to the Council coast and deliver them for mission progress. Spices use one cargo space each.']), 'Your mission track awards points at its milestones. The leading mission player can also hold a one-point bonus.');
  }
  for (const variant of s.variants ?? []) add(variant, VARIANT_NAMES[variant], variant === 'friendly-robber' ? 'The robber cannot be placed beside a player with two or fewer points. Discards on a seven still apply.' : 'Buildings on ports contribute harbor points: one per settlement and two per city. A leading total of at least three can earn the two-point Harbormaster award.');
  add('about', 'About this version', 'This guide describes Island Settlers as played here. Maps are generated, combined scenarios have adaptations, and 7–10-player layouts and Connect-style rounds are custom rules.', 'The phone’s action prompts show exact available targets and costs. Reading rules does not submit an action, end your turn or pause other players.');
  return topics;
}
export function RulesHelp({ settings, playerCount }: { settings: Settings; playerCount: number }) {
  const [open, setOpen] = useState(false), [topic, setTopic] = useState('start'), id = useId(), topics = rulesTopics(settings, playerCount), selected = topics.find(t => t.id === topic) ?? topics[0];
  return <div className="is-rules-access"><button type="button" className="is-rules-open" aria-haspopup="dialog" onClick={() => setOpen(true)}>Rules</button>{open && <Modal title="Island Settlers rules" onClose={() => setOpen(false)}><div className="is-rulebook"><div className="is-rulebook-nav"><button type="button" className="is-back" onClick={() => setOpen(false)}>Back to game</button><label htmlFor={id}>Rule topic</label><select id={id} value={selected.id} onChange={event => { setTopic(event.target.value); event.currentTarget.closest('dialog')?.scrollTo({ top: 0 }); }}>{topics.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></div><p className="is-rulebook-note">For this room · {settings.targetPoints} points to win. Play continues while you read.</p><section key={selected.id}><h3>{selected.title}</h3><ul>{selected.lines.map(line => <li key={line}>{line}</li>)}</ul></section>{selected.id === 'about' && <a href="https://www.catan.com/understand-catan/game-rules" target="_blank" rel="noreferrer">Official tabletop rulebooks (rules may differ)</a>}</div></Modal>}</div>;
}
