/* Quip Clash content banks (server only; never imported by client code). All prompts and quips are original. */

/** Head-to-head prompts for everyone. */
export const FAMILY: readonly string[] = [
  'The worst thing to find in your sandwich',
  'A rejected flavour of toothpaste',
  'What the cat is actually plotting',
  'A terrible name for a pirate ship',
  'The real reason the dinosaurs disappeared',
  'Something you should never say to a lifeguard',
  'A surprising thing to find in Grandma’s handbag',
  'The worst possible theme for a wedding',
  'What aliens think our socks are for',
  'A new Olympic sport nobody asked for',
  'The least comforting thing a pilot could announce',
  'A fortune cookie message that goes way too far',
  'A bad slogan for a dentist',
  'The secret ingredient in the school canteen’s mystery stew',
  'What your houseplant complains about behind your back',
  'An unhelpful tip for your first day at a new job',
  'A terrible superpower to get stuck with',
  'The catchphrase of the world’s most boring superhero',
  'A rejected name for a theme park ride',
  'What the moon gossips about',
  'The worst thing to yell during a magic show',
  'A bedtime story guaranteed to keep kids awake',
  'The worst gift to bring to a housewarming',
  'A board game that would end friendships in minutes',
  'A new name for Wednesday',
  'Something a robot would brag about at a party',
  'The title of a cookbook written by a raccoon',
  'A warning label every trampoline should have',
  'The worst thing to hear from your hairdresser',
  'A conspiracy theory about pigeons',
  'A very specific fear',
  'What knights did on their day off',
  'The worst mascot for a sports team',
  'A bad name for a racehorse',
  'The worst flavour of crisps',
  'What sloths get up to when nobody is watching',
  'A rule that would make school way more fun',
  'A brand-new holiday and how people celebrate it',
  'The most disappointing prize ever found in a cereal box',
  'The worst advice a fairy godmother could give',
  'What penguins argue about',
  'A rejected title for a holiday song',
  'The worst thing to name your Wi-Fi network',
  'A sign you have been in the bath too long',
  'What a snail would do with a jet pack',
  'Something you never want your sat-nav to say',
  'A suspicious thing to find in your new house’s attic',
  'The worst toy to give a toddler',
  'A dramatic name for a very small hamster',
  'The worst thing to say when meeting royalty',
  'The opening line of the world’s most boring novel',
  'A brand-new emoji the world desperately needs',
  'The one thing a goldfish remembers',
  'The tagline for a horror movie set in a library',
  'A terrible place to hide a birthday present',
  'A failed invention from the year 3000',
  'A rejected fairy tale title',
  'The worst possible name for a cruise ship',
  'What vampires order at a restaurant',
  'Something you’d hate to hear from your dentist mid-drill',
  'The worst ice cream topping',
  'A totally useless kitchen gadget',
  'The real reason the chicken crossed the road',
  'A weird thing to collect',
  'A slogan for a gym run by sloths',
  'The worst job at the North Pole',
  'What dogs are saying when they bark at nothing',
  'An unusual thing to bring to a picnic',
  'A hobby that sounds completely made up',
  'How a ghost stays in shape',
  'The worst name for a newly discovered planet',
  'A thing you should never microwave',
  'The worst reason to call the fire brigade',
  'A rejected flavour of birthday cake',
  'A new law that would make traffic jams more fun',
  'The worst first sentence for a love letter',
  'What is really inside a piñata',
  'A side effect of drinking way too much lemonade',
  'The worst thing to forget on a camping trip',
  'A celebrity endorsement for broccoli',
  'The world’s most pointless trophy',
  'The worst board game piece',
  'An awkward thing to say at a family reunion',
  'What the tooth fairy does with all those teeth',
  'A brand-new extreme sport for grandparents',
  'A rejected name for a crayon colour',
  'The worst animal to have as your pilot',
  'What really happens at a snowman’s birthday party',
  'A secret only your fridge knows',
  'A terrible thing to engrave inside a wedding ring',
  'The worst restaurant review ever written',
  'A better name for Monday',
  'The worst thing to find at the bottom of a swimming pool',
  'A useless superhero sidekick',
  'The worst name for a hair salon',
  'What your phone does while you sleep',
  'A sign your teacher is secretly a wizard',
  'Something you’d hate to read in your horoscope',
  'The worst thing to shout in a library',
  'A suspicious name for a bakery',
  'A thing you should never say to a giraffe',
  'An unexpected thing to see at the zoo',
  'The worst thing to bring to show-and-tell',
  'A rejected name for a breakfast cereal',
  'A new rule for musical chairs',
  'Why the scarecrow quit his job',
  'The worst song to wake up to',
  'What astronauts really miss about Earth',
  'A clue that your neighbour is a superhero',
  'A new chewing gum flavour nobody wants',
  'The worst nickname for a firefighter',
  'What squirrels do with all those nuts',
  'The motto of the laziest knight in the kingdom',
  'A terrible name for a lemonade stand',
  'Something pirates bury besides treasure',
  'A souvenir from a very disappointing holiday',
  'The most dramatic way to announce you’re out of milk',
  'A secret talent of the monster in the lake',
  'What cows think about all day',
  'The worst message to pipe on a birthday cake',
  'A shocking twist ending for a nursery rhyme',
  'A bad name for a lion',
  'Something that should never be shaped like a duck',
  'Something in a wizard’s junk drawer',
  'A rejected superhero name',
  'What is actually at the end of the rainbow',
  'An odd thing for a museum to put on display',
  'The worst way to wake someone up',
  'A strange thing to teach a parrot to say',
  'What the Easter bunny does the rest of the year',
  'A terrible flavour for a smoothie',
  'Something that would make a goat famous',
  'A new word for being slightly hungry',
  'The worst thing to say in a job interview',
  'A sequel nobody needed: Revenge of the ___',
  'A terrible ending to a fairy tale',
  'What the dinosaurs would think of us',
  'A thing that would make any road trip worse',
  'The worst thing to find in your shoe',
  'What mermaids use as money',
  'The world’s least scary monster',
  'A bad slogan for an umbrella company',
  'Something you should not do in a hot-air balloon',
  'A dragon’s biggest pet peeve',
  'The worst prize on a game show',
  'A rejected name for the colour blue',
  'A terrible theme for a children’s party',
  'The weirdest thing to use your last genie wish on',
  'What hedgehogs whisper to each other',
  'The worst name for a talk show',
  'A new thing to put on pizza',
  'The strangest thing to see on the motorway',
  'An invention that would make bedtime better',
  'What really goes on in the teachers’ lounge',
  'Something you should never say to a ghost',
  'Something you’d find in a giant’s pocket',
  'The worst thing to put in a time capsule',
  'A rejected Olympic mascot',
  'A terrible way to start a toast',
  'A new chore invented by a robot',
  'What the ocean would say if it could talk',
  'An unexpected item on a pirate’s shopping list',
  'A dangerous hobby for a jellyfish',
  'A conspiracy theory about the moon',
  'A rejected name for a golf course',
  'Something you can’t say on the first day of school',
  'The worst thing to sneeze on',
  'The least helpful sign in a hospital',
  'What clouds dream about',
  'A strange thing to see at the car wash',
  'The worst name for a soup',
  'A new emergency phone number and what it’s for',
  'What a bear packs in its picnic basket',
  'A brand-new playground ride',
  'A slogan for a shop that only sells left shoes',
  'The name of the worst haircut ever',
  'The suspicious ingredient in Grandpa’s famous chilli',
  'What owls actually stay up all night doing',
  'A really bad name for a band',
  'The worst thing to find on your doorstep',
  'A totally new kind of weather',
  'The worst thing to bring to a sleepover',
  'Something you never want your car to say',
  'A strange way to win an argument',
  'The worst advice from a fortune teller',
  'A rejected name for a constellation',
  'What a T. rex would do with longer arms',
  'Something that should never be inflatable',
  'The worst first thing to say on a video call',
  'The secret to a perfect sandwich, according to a toddler',
  'What the waiter is really writing in that notepad',
  'A sign your cat is planning to run for mayor',
  'The worst name for a spaceship',
  'A gift that says “I forgot your birthday”',
  'The worst moment to start a dance-off',
  'An extreme new version of hide-and-seek',
  'A truly terrible pizza delivery promise',
  'What your shadow does when you’re not looking',
  'A rejected design for a new banknote',
  'What the snowman whispered before melting',
  'A fake fact about kangaroos',
  'A dish on the menu at a dragon’s café',
  'Something nobody should wear to a wedding',
  'The world’s least relaxing spa treatment',
  'A terrible stage name for a magician',
  'An excuse for being late that involves a llama',
  'The first rule of the Secret Sock Society',
  'A new reality show set in a bakery',
  'The last word in the dictionary',
  'The worst thing for a mime to suddenly say out loud',
  'A brand-new animal made by mixing two animals',
  'A noise your car should never make',
  'The worst sticker to put on your laptop',
  'What a superhero does on laundry day',
  'The worst thing to say to a nervous parachutist',
  'A new flavour of ice lolly for grumpy people',
  'Something a sandcastle would put on its CV',
  'The real reason teachers drink so much coffee',
  'The world’s worst bedtime snack',
  'A ridiculous rule for a library',
  'What the vacuum cleaner is afraid of',
  'A rejected name for a new dog breed',
  'The worst thing a lighthouse could do',
  'A secret level in the game of life',
  'An unusual pet for a queen',
];

/** Head-to-head prompts with grown-up or edgy humour. Only used when family mode is off. */
export const ADULT: readonly string[] = [
  'The worst thing to say on a first date',
  'A terrible chat-up line for a librarian',
  'What your ex is probably doing right now',
  'The real reason the office party was cancelled',
  'A song that should never play at a funeral',
  'The worst thing to hear from a tattoo artist',
  'Something you shouldn’t say in a work meeting with your camera on',
  'A dating app bio that guarantees zero matches',
  'The worst thing to find in your search history',
  'What your hangover is trying to tell you',
  'The worst excuse for missing your own wedding',
  'A cocktail name that should be illegal',
  'The least romantic thing to whisper',
  'What happens at a bachelor party for robots',
  'A terrible name for a perfume',
  'The worst thing to say to your in-laws',
  'A reason to get kicked out of a karaoke bar',
  'The worst place to have a midlife crisis',
  'A text you should never send after midnight',
  'What the boss really does in that office all day',
  'An honest wine label',
  'The worst thing to say at a divorce party',
  'A cringe-worthy anniversary post',
  'The real reason the neighbours are moving out',
  'An honest name for your group chat',
  'The most awkward thing to overhear in a public toilet',
  'A new excuse for calling in sick',
  'The worst thing to say in a wedding speech',
  'What your bank really thinks of your spending',
  'A terrible slogan for a dating agency',
  'Something you never want to hear from the next cubicle',
  'A terrible name for a nightclub',
  'The worst thing to bring to an office potluck',
  'The worst line in a breakup letter',
  'What really happens in the gym sauna',
  'A disturbing thing to find in your hotel room',
  'The real reason you’re still single',
  'The worst way to tell your parents you’re moving back in',
  'A sign you had too much to drink at the wedding',
  'The worst message to accidentally send to your boss',
  'A terrible honeymoon destination',
  'Something you shouldn’t say while being arrested',
  'A new rule for awkward family dinners',
  'An embarrassing tattoo you got on holiday',
  'The worst thing your mum could find in your room',
  'A sign your date is a vampire',
  'The worst thing to say during a candlelit dinner',
  'What is really in the hot dog',
  'A terrible name for a hangover cure',
  'The worst thing to yell at a kids’ football match',
  'A confession you would only make at 3 a.m.',
  'The honest title of every office meeting',
  'A terrible way to quit your job',
  'The worst thing to say to a police officer',
  'What your snoring is really trying to say',
  'A bad thing to discover the morning after a night out',
  'The real reason for the noise from the honeymoon suite',
  'An honest caption for your dating profile photo',
  'A rejected name for an energy drink',
  'Something you should never search for at work',
  'The worst thing about being a grown-up',
  'A suspicious reason for a 2 a.m. phone call',
  'The worst thing to say on a nude beach',
  'What the lifeguard is really looking at',
  'The worst thing to whisper at a funeral',
];

/** Last Laugh prompts: open-ended, one for the whole room. */
export const FINAL_FAMILY: readonly string[] = [
  'Write a new law that everyone must obey from tomorrow',
  'Invent a new holiday. What is it called?',
  'The title of the autobiography of the person on your left',
  'Name the next big dance craze',
  'A motivational poster slogan for a sloth',
  'The tagline for the movie about tonight',
  'What should be carved into the moon?',
  'Pitch a brand-new breakfast cereal',
  'Give the universe one piece of feedback',
  'Rename the room you are sitting in',
  'Invent a new sport and its only rule',
  'Tomorrow’s front-page headline',
  'The world’s shortest horror story',
  'Write a one-star review of Earth',
  'A new mascot for this group of friends',
  'The best excuse ever invented',
  'The next thing humans will invent',
  'A brand-new word and what it means',
  'The last text message sent before the robots took over',
  'Name a perfume that smells like a school bus',
  'A slogan for a planet that is up for sale',
  'A dog’s first post on social media',
  'Your secret villain name',
  'The worst possible baby name, according to a cat',
  'A new superhero and their one weakness',
  'A one-sentence sequel to Little Red Riding Hood',
  'What is printed on the welcome mat of a haunted house?',
  'The motto of a truly terrible airline',
  'Describe your dream sandwich in three words',
  'The opening line of the next big pop hit',
  'Pitch a reality show you would actually watch',
  'The name of this group’s first album',
];
export const FINAL_ADULT: readonly string[] = [
  'The worst thing to write in a wedding card',
  'Your honest dating app headline',
  'A new name for a hangover',
  'A one-line breakup text from a pirate',
  'The motto of a very bad bar',
  'The worst toast at your own retirement party',
  'What the office printer mutters under its breath',
  'An honest name for a cocktail',
  'A slogan for a very honest gym',
  'The worst thing to put on a dating profile',
];

/** House answers for the Safety quip button and for anyone who runs out of time. Fit almost any prompt. */
export const SAFETY: readonly string[] = [
  'A suspiciously damp sock', 'My uncle’s third toupee', 'Seventeen raccoons in a trench coat', 'Whatever is at the back of the fridge',
  'A strongly worded letter', 'Grandma’s secret soup', 'Interpretive dance', 'Three ducks and a dream', 'An emotional support potato',
  'A haunted spatula', 'The mayor of Pigeon Town', 'A wizard named Kevin', 'Way too much glitter', 'A tiny, furious tuba',
  'Sir Reginald Fluffington III', 'A goose with a grudge', 'A banana with commitment issues', 'A cardboard cut-out of a dentist',
  'An extremely confident toddler', 'The 4 a.m. snack', 'A sad trombone noise', 'Socks with sandals', 'A llama in sunglasses',
  'Mild disappointment', 'Soup. Just soup.', 'A fridge magnet that knows too much', 'Aggressive yodelling', 'Free samples of gravel',
  'A slightly haunted lamp', 'The world’s sweatiest mime', 'A spoon, but bigger', 'Yoghurt that expired in 2009', 'A box of bees (sealed, probably)',
  'One million rubber chickens', 'Nana’s karaoke playlist', 'An unsupervised goat', 'A motivational squirrel', 'The lost TV remote',
  'An inflatable dinosaur', 'My neighbour’s leaf blower', 'A pirate who gets seasick', 'A bowl of lukewarm beans', 'Cat videos at 3 a.m.',
  'Too many tiny hats', 'A soggy cardboard castle', 'Dad jokes, weaponised', 'A toaster with ambitions', 'The noise a fax machine makes',
  'Moustache wax', 'A high five that missed', 'A disappointed seagull', 'Velcro shoes for grown-ups', 'A slightly used trampoline',
  'A very polite volcano', 'Ham. Lots of ham.', 'Bubble wrap, unpopped',
];

export const promptPool = (family: boolean) => family ? FAMILY : [...FAMILY, ...ADULT];
export const finalPool = (family: boolean) => family ? FINAL_FAMILY : [...FINAL_FAMILY, ...FINAL_ADULT];
