import type { AugmentDefinition, DroneDefinition, HullDefinition, RoomDefinition, SystemDefinition, SystemId, WeaponDefinition, WeaponFamily } from '../../contracts';

import { ROOM_LAYOUTS } from './layouts';

function layout(hullId: string, optional: SystemId): RoomDefinition[] {
  const roomSystems: (SystemId | null)[] = ['piloting', 'engines', 'shields', 'weaponry', 'life-support', 'doors', 'medical', optional, null, null];
  const rooms = roomSystems.map((system, i) => { const [x, y, w, h] = ROOM_LAYOUTS[hullId]![i]!; return { id: `r${i}`, name: system?.replaceAll('-', ' ') ?? 'Equipment bay', x, y, w, h, capacity: 4, system, adjacent: [] as string[] }; });
  for (const a of rooms) a.adjacent = rooms.filter(b => a !== b && (((a.x + a.w === b.x || b.x + b.w === a.x) && Math.min(a.y + a.h, b.y + b.h) >= Math.max(a.y, b.y) + 1) || ((a.y + a.h === b.y || b.y + b.h === a.y) && Math.min(a.x + a.w, b.x + b.w) >= Math.max(a.x, b.x) + 1))).map(b => b.id);
  return rooms;
}
const hullRows = [
  ['wayfarer', 'Wayfarer', 'Balanced explorer with room to grow.', '#4fc6c0', 110, 4, 'laser-needle', 'scanner', 'exploration'],
  ['bulwark', 'Bulwark', 'Armored escort built to hold the line.', '#71a8e8', 150, 3, 'laser-twin', 'shield-projector', 'defense'],
  ['longbow', 'Longbow', 'Heavy artillery mounts reward careful targeting.', '#dc8b74', 100, 5, 'missile-lance', 'point-defense', 'artillery'],
  ['moth', 'Moth', 'Boarding vessel with a hardened assault crew.', '#b79bdc', 115, 3, 'ion-tap', 'teleporter', 'boarding'],
  ['hearth', 'Hearth', 'Support carrier with generous medical facilities.', '#e3ae65', 125, 4, 'laser-twin', 'repair-relay', 'support'],
  ['kite', 'Kite', 'A light scout with evasive countermeasures.', '#8fcbb0', 95, 4, 'flak-scatter', 'cloak', 'evasion'],
  ['magpie', 'Magpie', 'Salvage specialist equipped for dangerous recovery.', '#cfbf7d', 120, 4, 'beam-thread', 'tractor', 'salvage'],
  ['cuttlefish', 'Cuttlefish', 'Electronic warfare vessel that opens enemy defenses.', '#d28fb1', 105, 4, 'laser-needle', 'hacking', 'electronic'],
] as const;
export const hulls: HullDefinition[] = hullRows.map(([id, name, description, color, maxHull, maxWeapons, weapon, system, trait], i) => ({ id, name, description, color, maxHull, maxWeapons, rooms: layout(id, system), startingWeapons: [weapon, 'laser-needle'], startingSystems: ['piloting', 'engines', 'shields', 'weaponry', 'life-support', 'doors', 'medical', system], crew: i === 3 ? 5 : 4, traits: [trait] }));

type WeaponRow = [string, string, string, Partial<WeaponDefinition>];
const families: Record<WeaponFamily, { base: Partial<WeaponDefinition>; rows: WeaponRow[] }> = {
  laser: { base: { chargeMs: 4800, damage: 6, shieldDamage: 1 }, rows: [
    ['needle', 'Needle', 'Quick, efficient single pulse.', {}], ['twin', 'Twin Spark', 'Two pulses strip layered shields.', { shots: 2, chargeMs: 6500 }], ['rake', 'Rake', 'Four light pulses punish weak shields.', { shots: 4, damage: 3, chargeMs: 8500 }], ['hammer', 'Hammerlight', 'A slow concentrated hull strike.', { damage: 16, chargeMs: 11000 }], ['suture', 'Suture Laser', 'Precision light damages machinery.', { roomDamage: 2, damage: 3 }], ['mercy', 'Mercy Pattern', 'Hull-safe shots injure exposed boarders.', { damage: 1, crewDamage: 24 }],
  ] },
  beam: { base: { chargeMs: 8500, damage: 12, shieldDamage: 0 }, rows: [
    ['thread', 'Threadbeam', 'A hull cutter stopped by intact shields.', {}], ['prism', 'Prism Fan', 'Three cutting rays spread hull pressure.', { shots: 3, damage: 5, chargeMs: 12000 }], ['needle', 'Bore Beam', 'Pierces the first shield layer.', { pierce: 1, damage: 8 }], ['welder', 'Hot Seam', 'Burns open a compartment.', { fire: 0.7, damage: 6 }], ['surgeon', 'Surgeon', 'Cuts systems while sparing hull.', { roomDamage: 3, damage: 2 }], ['vacuum', 'Vacuum Line', 'Opens seams and drains compartment air.', { breach: 0.8, damage: 7 }],
  ] },
  missile: { base: { chargeMs: 9500, damage: 15, shieldDamage: 0, pierce: 9, ammo: 1 }, rows: [
    ['lance', 'Copper Lance', 'A shield-bypassing rocket vulnerable to interception.', {}], ['cluster', 'Cluster Pips', 'Three small warheads saturate interception.', { shots: 3, damage: 6, ammo: 2 }], ['drill', 'Drillhead', 'A bunker-busting system strike.', { roomDamage: 3, damage: 10 }], ['ember', 'Ember Pod', 'Incendiary payload ignites the target room.', { fire: 1, damage: 7 }], ['anchor', 'Anchor Rocket', 'Disrupts the struck station after impact.', { ionMs: 6500, damage: 8 }], ['needle', 'Needle Dart', 'Fast light missile for finishing damaged targets.', { chargeMs: 4200, damage: 7 }],
  ] },
  flak: { base: { chargeMs: 7500, damage: 4, shieldDamage: 1, shots: 3 }, rows: [
    ['scatter', 'Scatterbox', 'Three scraps of metal overload shields.', {}], ['storm', 'Scrapstorm', 'Six fragments need a long reload.', { shots: 6, chargeMs: 14000 }], ['breach', 'Rivetcaster', 'Heavy fragments open hull leaks.', { breach: 0.3, damage: 5 }], ['flash', 'Flash Can', 'A fast two-fragment screen breaker.', { shots: 2, chargeMs: 3900 }], ['shred', 'Shredder', 'Compartment fragments hurt crew.', { crewDamage: 9 }], ['slug', 'Ballast Gun', 'One heavy slug trades saturation for impact.', { shots: 1, damage: 14, roomDamage: 1 }],
  ] },
  ion: { base: { chargeMs: 6500, damage: 1, shieldDamage: 2, ionMs: 4500 }, rows: [
    ['tap', 'Blue Tap', 'Briefly disrupts a station and strips shields.', {}], ['chain', 'Chain Coil', 'Twin disruptions hold a shield gap.', { shots: 2, chargeMs: 10500 }], ['lock', 'Lock Coil', 'Long disruption with a slow recharge.', { ionMs: 10000, chargeMs: 13000 }], ['needle', 'Phase Needle', 'Bypasses one layer to disrupt a room.', { pierce: 1, shieldDamage: 0 }], ['breaker', 'Wave Breaker', 'Strips four shield layers with little hull harm.', { shieldDamage: 4, ionMs: 1500 }], ['sabot', 'Sabot Pulse', 'Physical system damage outlasts the pulse.', { roomDamage: 2, ionMs: 2500 }],
  ] },
  plasma: { base: { chargeMs: 9000, damage: 8, shieldDamage: 1, fire: 0.6 }, rows: [
    ['cinder', 'Cinder Globe', 'Molten plasma starts room fires.', {}], ['rain', 'Cinder Rain', 'Three small fire-starting globes.', { shots: 3, damage: 3, fire: 0.4, chargeMs: 12500 }], ['sun', 'Pocket Sun', 'A guaranteed fire with heavy hull impact.', { damage: 18, fire: 1, chargeMs: 15000 }], ['ash', 'Ash Lance', 'Pierces light shields at an ammunition cost.', { pierce: 1, ammo: 1 }], ['crucible', 'Crucible', 'Overheats machinery and injures operators.', { roomDamage: 2, crewDamage: 12, damage: 4 }], ['spark', 'Spark Spitter', 'Rapid embers sustain repair pressure.', { chargeMs: 3500, damage: 3, fire: 0.3 }],
  ] },
  boarding: { base: { chargeMs: 10000, damage: 2, pierce: 3, crewDamage: 18, ammo: 1 }, rows: [
    ['spear', 'Breach Spear', 'An unmanned assault payload ruptures a room.', { breach: 1 }], ['gas', 'Sleep Capsule', 'Suppresses crew without major hull damage.', { damage: 0, crewDamage: 35 }], ['charge', 'Doorbreaker', 'Sabotage charge cripples machinery.', { roomDamage: 3 }], ['torch', 'Boarding Torch', 'Incendiary penetrator forces defenders away.', { fire: 1 }], ['jammer', 'Jammer Pod', 'A penetrator locks down enemy equipment.', { ionMs: 9000 }], ['swarm', 'Splinter Pods', 'Three small anti-personnel capsules.', { shots: 3, crewDamage: 9, ammo: 2 }],
  ] },
  support: { base: { chargeMs: 7500, damage: -8, target: 'ally' }, rows: [
    ['patch', 'Patch Emitter', 'Repairs the selected allied hull.', {}], ['surge', 'Shield Stitch', 'Restores shield cover with a light hull repair.', { damage: -3, shieldDamage: -2 }], ['clinic', 'Field Clinic', 'Restores living crew in the target room.', { damage: -1, crewDamage: -20 }], ['relay', 'Repair Lance', 'Repairs damaged machinery remotely.', { damage: -2, roomDamage: -2 }], ['burst', 'Emergency Foam', 'A strong slow repair burst consumes a charge.', { damage: -22, ammo: 1, chargeMs: 12000 }], ['spray', 'Patch Spray', 'Three small repair pulses arrive together.', { damage: -4, shots: 3, chargeMs: 9500 }],
  ] },
};
export const weapons: WeaponDefinition[] = Object.entries(families).flatMap(([family, { base, rows }]) => rows.map(([id, name, description, stats], i) => ({ id: `${family}-${id}`, name, description, family: family as WeaponFamily, price: 35 + i * 9, chargeMs: 6000, damage: 0, shieldDamage: 0, pierce: 0, roomDamage: 0, crewDamage: 0, fire: 0, breach: 0, ionMs: 0, ammo: 0, shots: 1, tier: i > 3 ? 2 : 1, target: 'enemy', tags: [family], ...base, ...stats })));

const systemRows: [SystemId, string, string, number, number, number][] = [
  ['piloting', 'Piloting', 'A staffed helm improves evasion.', 0, 0, 5], ['engines', 'Engines', 'Improves evasion and escape preparation.', 0, 0, 5], ['shields', 'Shields', 'Absorbs attacks and regenerates between hits.', 0, 0, 1], ['weaponry', 'Weaponry', 'Each tier enables another installed weapon.', 0, 0, 1], ['life-support', 'Life support', 'Restores air in sealed compartments.', 0, 0, 1], ['doors', 'Doors', 'Controls compartment access and containment.', 0, 0, 1], ['medical', 'Medical', 'Heals living crew at the medical station.', 0, 0, 2],
  ['teleporter', 'Teleporter', 'Deploy or retrieve owned crew across vessels.', 14000, 0, 2], ['drone-bay', 'Drone bay', 'Launch selected attack or support drones.', 5000, 0, 1], ['hacking', 'Hacking suite', 'Disrupt a targeted system without transferring control.', 22000, 6500, 1], ['cloak', 'Cloaking', 'Evade incoming attacks for a short window.', 24000, 6500, 1], ['point-defense', 'Point defense', 'Intercept incoming projectiles until saturated.', 14000, 6000, 2], ['shield-projector', 'Shield projector', 'Reinforce a selected allied shield.', 19000, 7000, 2], ['repair-relay', 'Repair relay', 'Deliver repair support to an allied room and hull.', 18000, 5000, 9], ['tractor', 'Tractor system', 'Disable hostile drones and secure salvage.', 16000, 6000, 2], ['scanner', 'Advanced scanner', 'Reveal hidden interior threats and survey opportunities.', 12000, 12000, 1], ['decoy', 'Decoy emitter', 'Divert eligible hostile attacks from an ally.', 21000, 7000, 3], ['boarding-defense', 'Boarding defense', 'Suppress hostile boarders in the selected room.', 17000, 4000, 18], ['medical-support', 'Medical support', 'Heal living crew aboard a selected allied vessel.', 16000, 5000, 20],
];
export const systems: SystemDefinition[] = systemRows.map(([id, name, description, cooldownMs, durationMs, strength]) => ({ id, name, description, cooldownMs, durationMs, strength, price: cooldownMs ? 65 : 30, maxTier: id === 'weaponry' ? 5 : 3, tags: [id] }));
const droneRows: [DroneDefinition['behavior'], string, string, number, number][] = [
  ['attack', 'Needle Drone', 'Steady light fire against a selected ship.', 3000, 4], ['intercept', 'Catcher', 'Destroys incoming hostile projectiles.', 2200, 1], ['repair', 'Mender', 'Patches allied hull and machinery.', 3500, 3], ['board', 'Door Mouse', 'Assault drone attacks crew and room machinery.', 4000, 9], ['scan', 'Firefly', 'Reveals interior threats.', 6000, 1], ['shield', 'Umbrella', 'Reinforces an allied shield.', 4000, 1], ['heal', 'Little Doctor', 'Heals living crew in the target room.', 3000, 8], ['fire', 'Ember Beetle', 'Starts fires inside exposed compartments.', 4500, 1], ['ion', 'Blue Moth', 'Disrupts a selected system.', 5000, 3000], ['breach', 'Tin Borer', 'Punctures a compartment seal.', 5500, 1], ['decoy', 'Paper Kite', 'Draws eligible incoming attacks.', 4000, 1], ['salvage', 'Magnet Crab', 'Recovers ammunition from destroyed enemy vessels.', 10000, 1],
];
export const drones: DroneDefinition[] = droneRows.map(([behavior, name, description, intervalMs, strength], i) => ({ id: `drone-${behavior}`, name, description, behavior, intervalMs, strength, price: 38 + i * 3, hp: 16 + (i % 3) * 4, tags: [behavior] }));
const augmentRows: [AugmentDefinition['effect'], string, string][] = [
  ['hull', 'Honeycomb Plating', 'Layered armor increases hull durability.'], ['hull', 'Collision Bladder', 'Sacrificial bulkheads cushion impacts.'], ['evasion', 'Vector Fins', 'Sharper course changes avoid incoming fire.'], ['evasion', 'Ghost Wake', 'False engine trails confuse targeting.'], ['reload', 'Feed Motor', 'Weapon feeds cycle more quickly.'], ['reload', 'Coolant Loop', 'Heat exchange shortens weapon recharge.'], ['shield', 'Lattice Screen', 'A tighter shield lattice improves recovery.'], ['shield', 'Harmonic Lens', 'Tunes the shield envelope against sustained fire.'], ['repair', 'Patch Locker', 'Accessible supplies improve crew repair.'], ['repair', 'Seam Memory', 'Smart hull material supports repair work.'], ['medical', 'Triage Reader', 'Treatment assists preserve living crew.'], ['medical', 'Softbed Array', 'Medical cradles improve recovery.'], ['oxygen', 'Air Fern', 'Cultured filters restore cabin air.'], ['oxygen', 'Reserve Lung', 'A pressure reservoir slows oxygen loss.'], ['boarding', 'Grip Boots', 'Boarding crew gain stable footing.'], ['boarding', 'Breach Armor', 'Protective suits help boarding combat.'], ['scrap', 'Salvage Ledger', 'Finds overlooked recoverable material.'], ['scrap', 'Ore Sorter', 'Separates usable salvage from waste.'], ['ammo', 'Shell Press', 'Recovers useful ammunition components.'], ['ammo', 'Careful Loader', 'Reduces ammunition waste.'], ['sensors', 'Long Ear', 'Sensitive receivers clarify distant signals.'], ['sensors', 'Spectrum Prism', 'Separates concealed signatures.'], ['teleport', 'Phase Anchor', 'Stabilizes crew transfers.'], ['teleport', 'Return Thread', 'Improves transport recovery timing.'],
];
export const augments: AugmentDefinition[] = augmentRows.map(([effect, name, description], i) => ({ id: `augment-${effect}-${i % 2 + 1}`, name, description, effect, strength: i % 2 ? 0.2 : 0.12, price: 40 + i % 6 * 6, tags: [effect] }));
