import type { RefObject } from 'react';
import type { Input, Race, RoomView, SpeedClass, TrackId } from './types';
export type GameView = 'menu' | 'join' | 'lobby' | 'race' | 'results';
export type GameClient = {
  view: GameView; mode: 'solo' | 'party' | 'controller' | 'display';
  race: Race | null; room: RoomView | null; playerId: string;
  name: string; driver: number; track: TrackId; laps: number; speedClass: SpeedClass; difficulty: Race['difficulty'];
  joinCode: string; joinUrl: string; joinUrls: string[];
  error: string; notice: string; connected: boolean; busy: boolean; paused: boolean;
  muted: boolean; audioUnlocked:boolean; enableAudio:()=>void; quality: 'high' | 'performance'; autoAccelerate: boolean; hostPlays:boolean; setHostPlays:(value:boolean)=>void;
  canvasRef: RefObject<HTMLDivElement | null>;
  setName: (value: string) => void; setDriver: (value: number) => void; setTrack: (value: TrackId) => void;
  setLaps: (value: number) => void; setSpeedClass: (value: SpeedClass) => void; setDifficulty: (value: Race['difficulty']) => void;
  setJoinCode: (value: string) => void; setJoinUrl: (value: string) => void;
  setMuted: (value: boolean) => void; setQuality: (value: 'high' | 'performance') => void;
  setAutoAccelerate: (value: boolean) => void;
  solo: () => void; host: () => void; join: () => void; showJoin: () => void; start: () => void;
  watch: () => void; removePlayer: (id: string) => void;
  ready: () => void; leave: () => void; rematch: () => void; lobby: () => void; togglePause: () => void;
  setControlsEnabled: (value: boolean) => void;
  input: (value: Partial<Input>) => void; dismissError: () => void;
};
