import type { EventDefinition } from '../../../contracts';
import { choice, root } from './helpers';

export const distressEvents: EventDefinition[] = [
  root('distress', 'distress-missed-shift', 'The Missed Shift', 'A clinic porter has missed three check-ins after entering a jammed service bay. The clinic can still reach him by radio, and his suit has air, but the bay door controls are trapped beneath fallen equipment. Your fleet could push the outer loading plate inward to free him, damaging its own docking collars. Alternatively, the clinic can keep him comfortable while you transmit the incident to a professional rescue tug nearby.', [
    choice('push', 'Push the loading plate inward', 'Free the porter immediately, accepting hull damage for the clinic emergency payment.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 22 }]),
    choice('tug', 'Call the nearby rescue tug', 'Arrange a slower professional extraction and earn civic trust without forcing the plate.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('distress', 'distress-spinning-cradle', 'The Spinning Cradle', 'A lifeboat cradle has broken loose from a passenger carrier and begun spinning around its remaining cable. Everyone inside is strapped down, but the occupants cannot reach the release lever against the rotation. You could steady the cradle against your hulls while the carrier retrieves it. The carrier also has a powered winch that will work if supplied with compatible magazine charges. Its captain explains both methods before asking anyone to take a risk.', [
    choice('steady', 'Steady the cradle with your hulls', 'Absorb the cradle impacts and let the carrier recover its frightened passengers.', [{ kind: 'damage', amount: 6 }, { kind: 'reputation', faction: 'civic', amount: 2 }]),
    choice('winch', 'Supply charges for the winch', 'Spend one round to power the recovery and receive the carrier reimbursement.', [{ kind: 'ammo', amount: -1 }, { kind: 'scrap', amount: 18 }]),
  ]),
  root('distress', 'distress-pressure-choir', 'The Pressure Choir', 'A traveling choir sings each breath aloud so its conductor can track an oxygen leak through a damaged cabin. The method is working, but several singers are already dizzy. Connecting emergency air lines would stabilize them while reducing oxygen aboard your own ships. A trained medic could instead organize controlled breathing and isolate the failing valve. A rescue station is listening; you may also pass the singers precise location without docking.', [
    choice('air', 'Connect emergency air lines', 'Stabilize the choir at the cost of some oxygen in your own compartments.', [{ kind: 'hazard', hazard: 'oxygen', amount: -12 }, { kind: 'reputation', faction: 'pilgrims', amount: 2 }]),
    choice('relay', 'Guide the rescue station in', 'Keep the choir in radio contact until professional rescuers take over the approach.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('medic', 'Have a medic isolate the leak', 'A living medic guides the singers through a safe valve change without using fleet air.', [{ kind: 'reputation', faction: 'pilgrims', amount: 2 }], { requirement: { kind: 'crew-skill', id: 'medic' } }),
  ]),
  root('distress', 'distress-anchor-tenant', 'The Anchor Tenant', 'A small repair shop has become the final occupied room in a station being dismantled around it. Its owner refused to leave because the last customer never collected a repaired engine. Now the exit corridor is gone. She will happily abandon the engine if your fleet can offer a berth, but cutting a new opening will shower nearby hulls with scrap. A tug operator offers a slower, safer tow of the whole remaining room.', [
    choice('cut', 'Cut a new shop entrance', 'Accept debris damage and invite the grateful engineer to join a consenting captain crew.', [{ kind: 'damage', amount: 7 }, { kind: 'recruit', skill: 'engineer' }]),
    choice('tow', 'Arrange the whole-room tow', 'Guide the tug around the dismantling machinery and help the shop owner relocate safely.', [{ kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('distress', 'distress-empty-alarm', 'An Empty Alarm', 'The distress beacon leads to an empty lifeboat with neatly folded blankets on every seat. Its passengers were rescued several hours ago, but the recovery crew forgot to switch off the transmitter. Their return message confirms that everyone reached a nearby habitat safely. They ask you to silence the alarm so other ships do not waste a dangerous approach. You complete the simple check and recover the spare emergency cartridges they explicitly leave for the next traveler.', [], [{ kind: 'ammo', amount: 2 }]),
  root('distress', 'distress-salt-lungs', 'Salt in the Lungs', 'A brine freighter has sprayed its air scrubbers with crystallized salt. Its crew can breathe in their suits, but the ship cannot support them through the next long crossing. Lending your filtration machinery would clear their ducts while briefly disrupting life support aboard your own fleet. The freighter captain also knows a maintenance tender within reach if someone carries a detailed parts request. She refuses to let another crew suffer simply because hers is frightened.', [
    choice('filter', 'Lend filtration machinery', 'Clear the freighter scrubbers for a salvage payment while your life support recovers.', [{ kind: 'scrap', amount: 26 }, { kind: 'timed-status', system: 'life-support', durationMs: 12000 }]),
    choice('request', 'Carry the precise parts request', 'Help the freighter reach its maintenance tender without exchanging contaminated equipment.', [{ kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('distress', 'distress-unlit-miner', 'The Unlit Miner', 'A miner hangs outside a rock cutter after its work lights failed. She can reach the safety cable, but every movement pulls sharp fragments against her suit. Floodlighting the surface would let her choose a safe path, though the bright sweep will reveal your fleet to distant patrols. A close approach could retrieve her quickly at the cost of scraped plating. Her partner is waiting inside the cutter with the airlock already prepared.', [
    choice('lights', 'Illuminate the safe footholds', 'Guide the miner home while your powerful work lights increase patrol attention.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'guild', amount: 1 }]),
    choice('retrieve', 'Retrieve her at close range', 'Accept hull scrapes and collect the grateful partner equipment donation after the rescue.', [{ kind: 'damage', amount: 6 }, { kind: 'items', count: 1 }]),
  ]),
  root('distress', 'distress-tether-classroom', 'The Tethered Classroom', 'A school module has drifted away from its teaching station, still connected by a cable too thin to support a docking maneuver. The students are calm because their teacher has turned the incident into a mathematics lesson. Cutting and catching the module would strain your hulls. A transporter could move everyone directly into the station reception room. The station also has a slow recovery reel that needs only clear radio guidance to bring the classroom home.', [
    choice('catch', 'Catch the classroom module', 'Take the docking strain and accept the station equipment donation once everyone is safe.', [{ kind: 'damage', amount: 7 }, { kind: 'items', count: 1 }]),
    choice('reel', 'Guide the recovery reel', 'Help the station retrieve its classroom slowly while patrol pressure increases.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('teleport', 'Teleport the class to reception', 'Use an operational transporter for a direct evacuation and receive the station donation.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'teleporter', tier: 1 } }),
  ]),
  root('distress', 'distress-counterfeit-flares', 'Counterfeit Flares', 'A courier stranded with a dead transmitter has spent every emergency flare in her kit. All produced festive blue glitter instead of a distress signal. The manufacturer label is forged. You can donate proper magazine charges for a replacement signaling device, or stay beside her until a service patrol notices both ships. She has enough air and refuses an unnecessary transfer; what she needs is a reliable way to be found.', [
    choice('charges', 'Build a reliable signal charge', 'Spend one round to restore her emergency beacon and accept her reimbursement.', [{ kind: 'ammo', amount: -1 }, { kind: 'scrap', amount: 17 }]),
    choice('stay', 'Stay until service arrives', 'Keep the courier visible to rescuers while your extended stop increases pursuit pressure.', [{ kind: 'reputation', faction: 'civic', amount: 1 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('distress', 'distress-furnace-crossing', 'The Furnace Crossing', 'A smelter crew has reached a refuge compartment, but molten waste has sealed the only corridor to their lifeboat. Their cooling system can open a passage if nearby ships lend radiator capacity. Coupling would carry dangerous heat back into your engine rooms. A rescue barge offers to cut through the opposite wall if your fleet illuminates the worksite. Its approach is slower, but the refuge has enough air to make waiting a real option.', [
    choice('cool', 'Lend radiator capacity', 'Open the corridor immediately, accepting engine room fires in exchange for the smelter salvage payment.', [{ kind: 'hazard', hazard: 'fire', amount: 12 }, { kind: 'scrap', amount: 28 }]),
    choice('light', 'Illuminate the rescue barge approach', 'Support a safe exterior rescue while your work lights attract additional patrol attention.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('distress', 'distress-sealed-greenhouse', 'The Sealed Greenhouse', 'A greenhouse caretaker is locked inside with an irrigation machine that will not stop spraying. The plants enjoy the emergency; she does not. Breaking the outer hatch would free her but send water and metal fragments across your docking approach. Lending pump pressure could drain the compartment through its existing outlet, briefly occupying your engine controls. She offers the same recovery payment either way and asks that you avoid flattening the seedlings if possible.', [
    choice('break', 'Break the outer hatch', 'Free the caretaker quickly and absorb the fragments before collecting her recovery payment.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 24 }]),
    choice('pump', 'Drive the existing drain pump', 'Earn the payment while your engines briefly recover from powering the flooded greenhouse outlet.', [{ kind: 'timed-status', system: 'engines', durationMs: 10000 }, { kind: 'scrap', amount: 24 }]),
  ]),
  root('distress', 'distress-stalled-elevator', 'The Stalled Elevator', 'A maintenance elevator sits between two decks of a habitat, trapping workers beside an overheated drive. They have disengaged the motor, but it will remain dangerously warm until someone moves the car. Your crews could enter through a narrow service crawlway and release the brake by hand. The habitat superintendent instead suggests paying a nearby specialist for an insulated tool. Both methods are available; neither requires the workers to restart the failing motor.', [
    choice('crawl', 'Release the brake by hand', 'Accept minor heat injuries among living crew and earn the habitat repair fee.', [{ kind: 'crew-health', amount: -6 }, { kind: 'scrap', amount: 25 }]),
    choice('tool', 'Fund the insulated tool delivery', 'A consenting captain pays for the specialist equipment and earns civic goodwill.', [{ kind: 'reputation', faction: 'civic', amount: 2 }], { cost: 12 }),
  ]),
  root('distress', 'distress-drifting-infirmary', 'The Drifting Infirmary', 'A mobile infirmary has lost its medical equipment to an electrical fault. Its patients are stable but cannot safely move through the docking collars. Connecting your own medical circuits would support them during repairs while leaving your medical rooms temporarily unavailable. An operational medical support system could cover the load without that interruption. The infirmary also has a protected berth nearby; it needs a careful radio escort if you cannot lend equipment.', [
    choice('connect', 'Connect your medical circuits', 'Stabilize the infirmary and accept a temporary disruption of shipboard medical systems.', [{ kind: 'timed-status', system: 'medical', durationMs: 15000 }, { kind: 'reputation', faction: 'civic', amount: 2 }]),
    choice('escort', 'Guide it to the protected berth', 'Keep the patients on a quiet course while a little travel time is lost.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('support', 'Provide dedicated medical support', 'Use the operational support system; the infirmary medics also tend your living crew.', [{ kind: 'crew-health', amount: 15 }, { kind: 'reputation', faction: 'civic', amount: 2 }], { requirement: { kind: 'system', id: 'medical-support', tier: 1 } }),
  ]),
  root('distress', 'distress-oxygen-debt', 'An Oxygen Debt', 'An independent hauler exhausted its reserve air helping another ship and never reached the promised resupply point. Its crew are conserving breath behind a carefully sealed door. You can share enough oxygen to restart their scrubbers, reducing your own compartment reserves. A nearby vendor will also deliver sealed air canisters for a modest fee. The hauler captain offers a crate of spare machinery, insisting that accepting help does not make earlier generosity a mistake.', [
    choice('share', 'Share air for the scrubbers', 'Give up some fleet oxygen and accept the hauler spare equipment after the restart.', [{ kind: 'hazard', hazard: 'oxygen', amount: -15 }, { kind: 'items', count: 1 }]),
    choice('canisters', 'Buy an emergency air delivery', 'A consenting captain pays the vendor, preserving fleet oxygen and earning freehold goodwill.', [{ kind: 'reputation', faction: 'freeholds', amount: 2 }], { cost: 15 }),
  ]),
  root('distress', 'distress-lifeboat-garden', 'The Lifeboat Garden', 'You reach the lifeboat just as its rescue tug arrives. The passengers spent their wait planting emergency ration seeds in the absorbent packing around their supplies. Tiny shoots now cover the floor. There is no rescue left to perform, but the tug requests a brief lighted escort through loose debris. Your fleet supplies it without incident. Before leaving, the passengers send a warm meal from their intact galley and a promise that someone will keep watering the little garden.', [], [{ kind: 'crew-health', amount: 8 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
  root('distress', 'distress-two-rescue-claims', 'Two Rescue Claims', 'Two salvage crews have attached towing cables to opposite ends of a disabled shuttle. Each claims the right to rescue its occupants, and neither has noticed the strain bending the passenger cabin. You can interpose your hulls to force both tugs to stop, accepting the cable recoil. Broadcasting the shuttle recorded request for help should also settle the dispute, though it will take a conspicuous transmission to override the arguing salvage channels.', [
    choice('interpose', 'Force both towing cables slack', 'Protect the passengers with your hulls and receive their pooled emergency payment.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 25 }]),
    choice('broadcast', 'Broadcast the passengers request', 'Make both crews hear the people they are rescuing and accept the public attention.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('distress', 'distress-pressure-wedding', 'A Wedding Under Pressure', 'A wedding party is trapped behind a decorative arch that has collapsed across the reception airlock. The compartment is safe, but the station pressure computer refuses to open any neighboring door until the obstruction clears. Cutting the arch would consume ammunition and ruin a very expensive ornament. Your crews could dismantle it by hand instead, risking cuts from the brittle frame. The newlyweds agree immediately that the guests matter more than the decoration.', [
    choice('cut', 'Cut through the wedding arch', 'Spend one magazine round to free the guests and receive the hosts equipment gift.', [{ kind: 'ammo', amount: -1 }, { kind: 'items', count: 1 }]),
    choice('dismantle', 'Dismantle the brittle frame', 'Free everyone carefully while living crew accept minor injuries for the hosts payment.', [{ kind: 'crew-health', amount: -4 }, { kind: 'scrap', amount: 21 }]),
  ]),
  root('distress', 'distress-blind-recovery-tug', 'The Blind Recovery Tug', 'A recovery tug has collected three escape pods but lost its navigation array in the same collision. Its pilot can see your lights and asks you to lead it through a rubble cloud. Flying close would expose your hulls to the debris. A working scanner could transmit a precise route that lets both vessels keep their distance. The tug can also hold safely at the cloud edge while a second recovery crew approaches.', [
    choice('lead', 'Lead from inside the rubble', 'Accept debris strikes while guiding the rescued passengers out of the cloud.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 24 }]),
    choice('hold', 'Help the tug hold position', 'Keep it steady for the second crew and allow following patrols some extra time.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('route', 'Transmit a scanned safe route', 'Use an operational scanner to guide both ships safely and collect the recovery fee.', [{ kind: 'scrap', amount: 24 }], { requirement: { kind: 'system', id: 'scanner', tier: 1 } }),
  ]),
  root('distress', 'distress-burned-chartroom', 'The Burned Chartroom', 'A chartmaker escaped a fire by sealing herself in a cabinet designed to protect paper maps. The cabinet worked too well: its heat fuse now refuses to release the door. Flooding the room with your spare atmosphere would cool the fuse enough to open, while leaving less oxygen aboard your fleet. A manual cutting approach avoids that transfer but exposes working crew to hot fragments. She promises her remaining navigation earnings for either rescue.', [
    choice('cool', 'Cool the cabinet with spare air', 'Release the heat fuse at the cost of fleet oxygen and receive the chartmaker payment.', [{ kind: 'hazard', hazard: 'oxygen', amount: -10 }, { kind: 'scrap', amount: 23 }]),
    choice('cut', 'Cut the fused latch manually', 'Free the chartmaker while living crew endure minor burns from the hot cabinet.', [{ kind: 'crew-health', amount: -5 }, { kind: 'scrap', amount: 23 }]),
  ]),
  root('distress', 'distress-flooded-magazine', 'The Flooded Magazine', 'A patrol tender used its fire suppression reservoir to drown a magazine blaze. The crew survived, but two technicians remain on a dry platform surrounded by floating ammunition. Pulling alongside risks knocking unstable rounds against your hulls. A safer route requires sacrificing compatible charges to activate the flooded handling crane remotely. The tender captain authorizes you to keep a sealed equipment case after the technicians are back behind a proper pressure door.', [
    choice('alongside', 'Dock beside the dry platform', 'Recover the technicians and equipment case while accepting accidental magazine impacts.', [{ kind: 'damage', amount: 7 }, { kind: 'items', count: 1 }]),
    choice('crane', 'Activate the handling crane', 'Spend two magazine rounds to power the remote crane and recover the case safely.', [{ kind: 'ammo', amount: -2 }, { kind: 'items', count: 1 }]),
  ]),
  root('distress', 'distress-orphaned-maintenance', 'The Orphaned Maintenance Unit', 'A maintenance robot broadcasts a distress call because its owner fell asleep inside a locked workshop. The owner is healthy and thoroughly irritated by the alarm, but the door has genuinely lost power. Feeding it a small external charge would solve the problem. Staying on the channel while the owner cranks the manual generator costs only time. The robot asks whether worry counts as a successful diagnostic, and nobody aboard has a quick answer.', [
    choice('charge', 'Supply a door actuator charge', 'Spend one round to open the workshop and accept the owner scrap reimbursement.', [{ kind: 'ammo', amount: -1 }, { kind: 'scrap', amount: 16 }]),
    choice('crank', 'Stay through the manual restart', 'Keep the robot calm while the owner restores the door, increasing your time at the beacon.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('distress', 'distress-quarantine-meal', 'The Quarantine Meal', 'A galley steward locked a dining compartment after a spoiled meal made its occupants ill. The quarantine system now insists that only a doctor physically inside can release the door. The patients need assistance, but none faces immediate danger. You could cut a bypass, fund a licensed local medic visit, or guide the steward through a slow manual pressure reset. The steward has stopped defending the recipe and started writing down everyone allergies.', [
    choice('bypass', 'Cut a door bypass', 'Open the compartment while working crew risk minor injuries from the cramped access panel.', [{ kind: 'crew-health', amount: -4 }, { kind: 'scrap', amount: 20 }]),
    choice('doctor', 'Fund the local medic visit', 'A consenting captain pays for professional treatment and earns civic goodwill.', [{ kind: 'reputation', faction: 'civic', amount: 2 }], { cost: 12 }),
    choice('reset', 'Guide the manual pressure reset', 'Use a slower safe procedure while patrols gain distance on your waiting fleet.', [{ kind: 'threat', amount: 1 }]),
  ]),
  root('distress', 'distress-cracked-cupola', 'The Cracked Cupola', 'Visitors are sheltering beneath a cracked observation dome while the habitat closes its inner shutters. The dome must hold only a little longer. Pressing your hulls against its support ring would slow the crack but damage your plating. A shield projector could protect the exposed glass without contact. The visitors can also reach an inner shelter before the glass fails if someone calmly guides them through the unfamiliar maintenance passage.', [
    choice('brace', 'Brace the cupola support ring', 'Hold the damaged dome until the shutters close and accept the visitors recovery payment.', [{ kind: 'damage', amount: 7 }, { kind: 'scrap', amount: 27 }]),
    choice('shelter', 'Guide visitors to the inner shelter', 'Keep the group moving calmly through the maintenance passage and earn civic goodwill.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('project', 'Project a protective shield', 'Use an operational shield projector to hold the dome safely and receive the recovery payment.', [{ kind: 'scrap', amount: 27 }], { requirement: { kind: 'system', id: 'shield-projector', tier: 1 } }),
  ]),
  root('distress', 'distress-radiation-bakery', 'The Radiation Bakery', 'A bakery module used a salvaged reactor shield as an oven liner. The shield has shifted, and the staff are trapped behind a hot service corridor. Their suits can handle a short wait. You could move the liner using external docking pressure, transferring some heat into your own engine compartments. A guild technician offers a remotely operated clamp if a captain pays the rental deposit. The head baker has already promised never to improvise insulation again.', [
    choice('move', 'Move the liner with docking pressure', 'Free the staff and accept a bakery payment alongside new engine room fires.', [{ kind: 'hazard', hazard: 'fire', amount: 10 }, { kind: 'scrap', amount: 26 }]),
    choice('clamp', 'Rent the insulated remote clamp', 'A consenting captain pays for a safe removal and strengthens your standing with the guild.', [{ kind: 'reputation', faction: 'guild', amount: 2 }], { cost: 13 }),
  ]),
  root('distress', 'distress-returned-courier', 'The Returned Courier', 'A search group is packing away its equipment when your fleet answers the beacon. The missing courier has returned under her own power, embarrassed that she plotted the wrong rendezvous and slept through the first calls. Nobody needs rescuing. The search leader nevertheless thanks you for answering and shares surplus emergency rations before they spoil. Your crews enjoy the fresh supplies while the courier helps dismantle every search marker she caused someone else to install.', [], [{ kind: 'crew-health', amount: 10 }]),
  root('distress', 'distress-exhausted-relay', 'The Exhausted Relay Crew', 'A relay crew has worked through repeated power failures to keep the local emergency channel open. Their distress message is not about a trapped passenger; they are too exhausted to finish the final repair safely. Your crews could take a shift, accepting fatigue injuries in exchange for the maintenance budget. You could instead close the relay honestly and direct callers to a quieter backup channel. The operators visibly relax when someone says that stopping is a legitimate option.', [
    choice('shift', 'Take the final repair shift', 'Earn the maintenance payment while living crew absorb the strain of the difficult work.', [{ kind: 'crew-health', amount: -6 }, { kind: 'scrap', amount: 26 }]),
    choice('backup', 'Direct callers to the backup relay', 'Give the exhausted operators relief and use the quieter channel for your own departure.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('distress', 'distress-stranded-picket', 'The Stranded Picket Boat', 'A workers picket boat has lost its engine outside a closed fabrication yard. The workers and yard manager disagree about almost everything except the need to get everyone home alive. The manager offers a repair fee if your fleet supplies compatible drive charges. The workers prefer a slow tow to a neutral dock so nobody can seize their boat as compensation. They ask your captains to choose a rescue method without pretending it resolves their wider dispute.', [
    choice('repair', 'Supply compatible drive charges', 'Spend two magazine rounds to restart the picket boat and collect the manager repair fee.', [{ kind: 'ammo', amount: -2 }, { kind: 'scrap', amount: 24 }]),
    choice('neutral', 'Coordinate a neutral dock tow', 'Help the workers reach neutral shelter while the slower operation increases pursuit pressure.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('distress', 'distress-brake-cable', 'The Last Brake Cable', 'A passenger platform is sliding down an exposed service track toward a rigid stop. Its emergency brake is holding, but each correction sheds another strand of cable. Docking against the platform could slow it enough for station crews to secure the passengers. An engineer could guide a repair through the platform own maintenance controls. The station also has a clear evacuation stair; a calm voice could persuade the passengers to use it before anyone tries a dangerous jump.', [
    choice('dock', 'Slow the platform with your hulls', 'Take the braking strain and accept the station equipment donation after securing the platform.', [{ kind: 'damage', amount: 7 }, { kind: 'items', count: 1 }]),
    choice('stair', 'Guide everyone onto the stair', 'Help the passengers leave the failing platform in order and earn civic trust.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('engineer', 'Guide an engineer through the brake', 'A living engineer stabilizes the mechanism and earns the station equipment donation.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'crew-skill', id: 'engineer' } }),
  ]),
  root('distress', 'distress-forgotten-cycle', 'The Forgotten Decompression Cycle', 'A docking attendant has started two incompatible pressure cycles and left visiting crews waiting in their suits. Everyone is safe for now, but the attendant cannot remember which override preserves the inner seals. Your fleet can lend a clean atmosphere sample to recalibrate the controller. A guild repair desk will also provide a supervised remote reset for a fee. The attendant offers a small machinery crate and asks that you explain the correct sequence afterward.', [
    choice('sample', 'Lend a clean atmosphere sample', 'Give up a little fleet oxygen to reset the controller and collect the machinery crate.', [{ kind: 'hazard', hazard: 'oxygen', amount: -8 }, { kind: 'items', count: 1 }]),
    choice('desk', 'Fund a supervised remote reset', 'A consenting captain pays the repair desk to resolve the mistake and earns guild goodwill.', [{ kind: 'reputation', faction: 'guild', amount: 2 }], { cost: 11 }),
  ]),
  root('distress', 'distress-moving-reservoir', 'The Moving Reservoir', 'An agricultural habitat has detached a leaking water tank, unaware that a cleaner was still on its inspection walkway. The tank is drifting out of local recovery range. A close pass could collect the cleaner, but loose support straps threaten your hulls. The habitat can reel the tank back slowly if someone keeps a strong tracking beam on it. The cleaner jokes steadily over the channel until the jokes begin to repeat.', [
    choice('collect', 'Collect the cleaner at close range', 'Accept support-strap damage and receive the habitat emergency recovery payment.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 24 }]),
    choice('track', 'Keep a strong tracking beam on it', 'Help the habitat recover its worker while the bright beam attracts patrol attention.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('distress', 'distress-utility-hostages', 'The Utility Barge', 'Raiders have boarded a utility barge and are using its emergency channel to demand payment. The barge crew have sealed themselves inside a protected machinery room and quietly signal that their escape engine is almost ready. Drawing the raider escort away would give them a chance to leave, but commits your fleet to a dangerous escape fight. A neutral rescue dispatcher can also negotiate a delayed release while you keep the barge location on record.', [
    choice('draw', 'Draw the armed escort away', 'Fight for an escape opening while the utility crew prepares its own departure.', [{ kind: 'combat', objective: 'escape', threat: 2 }]),
    choice('dispatcher', 'Bring in the neutral dispatcher', 'Keep the barge identity public so negotiators can work, accepting additional signal exposure.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('distress', 'distress-lost-storyteller', 'The Lost Storyteller', 'A storyteller aboard a pilgrim ferry has become disoriented after a long period alone. The ship is functioning, but she no longer trusts her own navigation instructions. She does not need a replacement captain or a forced evacuation. She asks someone to remain on the channel while she checks each departure step against the printed list. Your crews recognize the value of having another person listen, especially when every instrument says there should be no problem.', [
    choice('listen', 'Stay on the channel through departure', 'Help her finish the checklist; the quiet conversation steadies living crew aboard your own fleet too.', [{ kind: 'crew-health', amount: 7 }, { kind: 'reputation', faction: 'pilgrims', amount: 1 }]),
  ]),
  root('distress', 'distress-cinder-pilgrims', 'The Cinder Pilgrims', 'A pilgrim hostel has evacuated everyone except its fire watch, who remain beside a damaged suppression pump. Connecting an external power feed would restore the pump but risks carrying heat back into your engine rooms. A repair relay could stabilize the failing assembly without that direct connection. The fire watch also has a protected exit and will withdraw if you tell the arriving rescue crews that saving the empty hostel is no longer worth the risk.', [
    choice('feed', 'Restore the suppression power feed', 'Save the hostel machinery and receive its spare equipment, accepting engine room fires.', [{ kind: 'hazard', hazard: 'fire', amount: 10 }, { kind: 'items', count: 1 }]),
    choice('withdraw', 'Coordinate a fire-watch withdrawal', 'Help the last watch reach safety and preserve the pilgrims trust without saving the building.', [{ kind: 'reputation', faction: 'pilgrims', amount: 1 }]),
    choice('relay', 'Stabilize it with a repair relay', 'Use an operational repair relay to save the pump and collect the spare equipment safely.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'repair-relay', tier: 1 } }),
  ]),
  root('distress', 'distress-silent-nursery', 'The Silent Nursery', 'A childcare module has lost its outside speaker, leaving its caretaker unable to tell rescuers that the pressure doors are still safe. The children are frightened by silhouettes moving beyond the windows. You can illuminate a simple set of instructions for an orderly transfer, or dock a direct communication cable through a damaged exterior panel. The first method takes longer. The second scrapes your hulls but allows the caretaker to coordinate the rescue immediately.', [
    choice('lights', 'Signal a calm transfer sequence', 'Guide the caretaker patiently while the extended rescue increases pursuit pressure.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('cable', 'Dock a direct communication cable', 'Accept panel damage and receive the module emergency payment after a coordinated transfer.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 22 }]),
  ]),
  root('distress', 'distress-blanket-line', 'The Blanket Line', 'Rescue workers have already evacuated a damaged passenger ship and formed a line to move blankets into the receiving habitat. Your fleet arrives after the dangerous work is over. Spare arms are still useful, and your crews carry folded bedding while tired passengers find their assigned rooms. A field medic insists on checking the helpers as well as the rescued. The resulting treatment benefits living crew aboard your ships, and the workers send you away before fatigue becomes another emergency.', [], [{ kind: 'crew-health', amount: 12 }]),
  root('distress', 'distress-severed-service-collar', 'The Severed Service Collar', 'A docking collar has separated during routine maintenance, leaving two suited inspectors standing on its loose exterior ring. Neither is injured, and a station tug is already moving to collect them. What they lack is a stable reference point in the spinning lights. Your fleet can hold a clear formation outside the debris and let them orient themselves against it. The inspectors ask you to keep talking until the tug has both safety lines attached.', [
    choice('hold', 'Hold a steady reference formation', 'Give the inspectors a reliable horizon until their tug secures them; the station pays a modest assistance fee.', [{ kind: 'scrap', amount: 13 }, { kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('distress', 'distress-signal-monopoly', 'The Signal Monopoly', 'An injured courier cannot reach the public distress network because a commercial repeater is drowning it out with priority advertisements. The repeater operator will lower its signal for a transmission fee. You could instead broadcast the courier coordinates at greater power, making your fleet easier to track. The courier has already authorized the nearest clinic to collect her; she needs a message delivered, not another ship attempting an improvised medical transfer.', [
    choice('fee', 'Pay for a clear emergency channel', 'A consenting captain pays the operator so the clinic receives the courier coordinates.', [{ kind: 'reputation', faction: 'civic', amount: 2 }], { cost: 10 }),
    choice('override', 'Broadcast above the advertisements', 'Get the coordinates to the clinic while your powerful signal increases pursuit pressure.', [{ kind: 'threat', amount: 1 }, { kind: 'reputation', faction: 'freeholds', amount: 1 }]),
  ]),
  root('distress', 'distress-isolated-medics', 'The Isolated Medics', 'Two volunteer medics are trapped beyond a collapsed passage after treating the last patients in a damaged outpost. They have food and a sound pressure shelter, but their rescue team cannot find a stable cutting angle. Your fleet could provide a docking brace, accepting debris on its own hulls. A transporter would bring the medics across directly. They are also willing to wait for the outpost structural crew, provided someone keeps their shelter location clearly marked.', [
    choice('brace', 'Brace the rescue team approach', 'Accept falling debris and invite a grateful medic to join a consenting captain crew.', [{ kind: 'damage', amount: 6 }, { kind: 'recruit', skill: 'medic' }]),
    choice('mark', 'Mark the shelter for structural crews', 'Ensure the medics remain accounted for while professional workers plan a safe opening.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('transfer', 'Teleport the medics to safety', 'Use an operational transporter; one volunteer offers to continue with a consenting captain.', [{ kind: 'recruit', skill: 'medic' }], { requirement: { kind: 'system', id: 'teleporter', tier: 1 } }),
  ]),
  root('distress', 'distress-caustic-freight', 'Caustic Freight', 'A freight pilot has discovered that the supposedly inert cargo behind her cabin is dissolving its storage tank. She can abandon the ship, but doing so without stabilizing its course would send the leaking vessel toward a populated service pier. Steering beside her would let your fleet absorb some caustic spray while she plots a safe departure. A local disposal contractor offers to take control remotely if someone pays the emergency connection fee.', [
    choice('steer', 'Guide the leaking ship clear', 'Accept shallow hull damage and collect the freight company emergency assistance payment.', [{ kind: 'damage', amount: 6 }, { kind: 'scrap', amount: 27 }]),
    choice('contractor', 'Fund the disposal connection', 'A consenting captain pays to clear the populated pier and earns civic goodwill.', [{ kind: 'reputation', faction: 'civic', amount: 2 }], { cost: 14 }),
  ]),
  root('distress', 'distress-rescue-certificates', 'The Rescue Certificates', 'A class of apprentice rescue pilots has completed its final exercise and forgotten to cancel the practice beacon. Their instructor meets your fleet with an apology before you approach the dummy wreck. Nobody was ever in danger, and she offers the training ammunition left over from the demonstration. The apprentices insist on escorting you through the real debris at the edge of the practice zone. Their careful formation is slower than the instructor would like, but they get every ship through safely.', [], [{ kind: 'ammo', amount: 2 }, { kind: 'reputation', faction: 'civic', amount: 1 }]),
  root('distress', 'distress-leaking-museum', 'The Leaking Museum', 'A museum custodian is sheltering inside an exhibit of an early pressure cabin after the surrounding gallery developed a leak. The antique cabin works, but its emergency release is on the outside. You can push a docking collar through a damaged display wall or contribute air to make the gallery briefly breathable. The custodian offers a surplus equipment case from the museum workshop and asks that nobody mistake the rescue for an interactive historical demonstration.', [
    choice('collar', 'Reach the exhibit with a docking collar', 'Take display-wall damage and recover the custodian along with the offered equipment case.', [{ kind: 'damage', amount: 5 }, { kind: 'items', count: 1 }]),
    choice('air', 'Make the gallery briefly breathable', 'Spend some fleet oxygen so the custodian can reach the ordinary exit safely.', [{ kind: 'hazard', hazard: 'oxygen', amount: -12 }, { kind: 'items', count: 1 }]),
  ]),
  root('distress', 'distress-unbolted-home', 'The Unbolted Home', 'A family bought a modular home without realizing that the delivery crew had left its transport bolts engaged. When they opened the living room shutters, the entire module started turning away from its dock. The family can retreat safely into the service section. Your fleet could hold the home against the dock while the bolts are cut, or help a housing cooperative arrange a patient recovery. The owners want their home saved, but they want their family safe first.', [
    choice('hold', 'Hold the home against the dock', 'Accept contact damage and earn the family pooled recovery payment.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 23 }]),
    choice('cooperative', 'Arrange a cooperative recovery', 'Keep the family in shelter and support a careful freehold housing rescue.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }]),
  ]),
  root('distress', 'distress-falling-radiator', 'The Falling Radiator', 'A hospital radiator has detached with an inspection crew still tethered to its edge. The hospital can retrieve the crew once the immense panel stops turning. Docking against it would transfer dangerous heat to your engine compartments. A tractor system could steady it from a safer distance. The inspectors can also cut their tethers and drift toward a waiting lifeboat if someone talks them through the timing. They ask for clear instructions rather than heroic promises.', [
    choice('dock', 'Dock against the hot panel', 'Stop the rotation and accept engine room fires for the hospital recovery payment.', [{ kind: 'hazard', hazard: 'fire', amount: 11 }, { kind: 'scrap', amount: 26 }]),
    choice('lifeboat', 'Time the transfer to the lifeboat', 'Guide the suited inspectors across the short gap and earn the hospital trust.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
    choice('tractor', 'Steady it with a tractor', 'Use an operational tractor to secure the panel and receive the recovery payment safely.', [{ kind: 'scrap', amount: 26 }], { requirement: { kind: 'system', id: 'tractor', tier: 1 } }),
  ]),
  root('distress', 'distress-wrong-clock', 'The Wrong Clock', 'A sleeper transport wakes its crew for an emergency that happened months ago. Its navigation computer has confused a recorded alert with a current one, and frightened passengers are preparing to abandon a perfectly sound ship. A strong public correction would persuade them quickly, though it reveals your fleet position. You can instead work through the captain step by step, comparing the clock to your own beacon records until she can reassure everyone herself.', [
    choice('public', 'Broadcast the corrected date', 'End the panic quickly and accept the grateful captain payment alongside greater signal exposure.', [{ kind: 'scrap', amount: 20 }, { kind: 'threat', amount: 1 }]),
    choice('private', 'Check the records with the captain', 'Help her regain confidence and earn civic goodwill without a dramatic public intervention.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('distress', 'distress-last-responder', 'The Last Responder', 'The final rescue boat at a damaged service station is carrying nobody but its exhausted pilot. She stayed to check every compartment after the evacuation manifest was complete. Your fleet meets her at the clear edge of the beacon, confirms the station is empty, and helps her send the final closure report. There is no remaining passenger to find or reward to claim. A field kitchen invites both crews to eat, and the shared rest restores some health to living crew aboard your ships.', [], [{ kind: 'crew-health', amount: 11 }]),
  root('distress', 'distress-evacuation-guns', 'Guns at the Evacuation Lane', 'An evacuation convoy is leaving a damaged fuel depot when armed looters begin firing across its departure lane. The convoy can keep moving if your fleet holds the attackers attention long enough. Joining the defense means a real battle, not a warning shot. The convoy leader also offers a quieter role: transmit a false departure vector from a distant relay so some pursuers search the wrong lane. Either contribution gives frightened civilian crews a better chance to get clear.', [
    choice('defend', 'Defend the convoy departure', 'Hold against the looter force while the evacuation ships clear the combat zone.', [{ kind: 'combat', objective: 'defend', threat: 3 }]),
    choice('misdirect', 'Transmit a false departure vector', 'Draw attention to your fleet instead and help civic rescuers keep the convoy moving.', [{ kind: 'threat', amount: 2 }, { kind: 'reputation', faction: 'civic', amount: 2 }]),
  ]),
  root('distress', 'distress-cooks-hatch', 'The Cooks Hatch', 'A relief kitchen cook is trapped behind a swollen storage hatch after using all the compartment cold packs to preserve food for evacuees. The chamber is safe, but the swollen seal will not release until someone chills it. Lending your cooling pumps would briefly disrupt your engines. A manual pry is possible through a narrow service gap, with some risk of injured hands. The cook promises to reimburse whichever repair method gets lunch moving again.', [
    choice('cool', 'Chill the swollen hatch seal', 'Receive the kitchen repair payment while your engines recover from the cooling transfer.', [{ kind: 'timed-status', system: 'engines', durationMs: 9000 }, { kind: 'scrap', amount: 20 }]),
    choice('pry', 'Pry through the service gap', 'Accept minor injuries among living crew in exchange for the same repair payment.', [{ kind: 'crew-health', amount: -4 }, { kind: 'scrap', amount: 20 }]),
  ]),
  root('distress', 'distress-survivors-survey', 'The Survivors Survey', 'A rescue surveyor has located an abandoned Wayfarer whose original crew reached safety. The hull is available for a shipless captain, but it needs a paid recommissioning inspection before anyone can claim it. An engineer can verify the worst faults and reduce the required work. Captains who still have ships may simply help mark the wreck for future survivors. The surveyor is explicit: a replacement vessel cannot restore people or equipment already lost elsewhere.', [
    choice('commission', 'Commission the abandoned Wayfarer', 'A shipless captain may pay the stated ninety scrap recommissioning cost for a replacement hull.', [{ kind: 'replacement', hullId: 'wayfarer', cost: 90 }]),
    choice('mark', 'Mark it for another survivor', 'Preserve a useful rescue resource and strengthen your standing with independent freeholds.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }]),
    choice('engineer', 'Have an engineer assess the hull', 'A living engineer enables a shipless captain replacement at the reduced seventy scrap cost.', [{ kind: 'replacement', hullId: 'wayfarer', cost: 70 }], { requirement: { kind: 'crew-skill', id: 'engineer' } }),
  ]),
];
