import type { EventDefinition } from '../../../contracts';
import { choice, root } from './helpers';

export const travelEvents: EventDefinition[] = [
  root('travel', 'travel-lantern-account', 'The Lantern Account', 'A navigation buoy asks your fleet to settle an account. Its previous keeper paid for another century of light, but the replacement bulbs arrived without an installer. Nobody is trapped here; ships simply take a longer approach whenever another lamp fails. The buoy can reimburse material costs from a sealed maintenance fund. Doing the work would leave your own outer plating thinner until the next repair stop.', [
    choice('install', 'Replace the lamps', 'Cut spare hull plates into mounting brackets and collect the maintenance payment.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 24 }]),
    choice('chart', 'Publish the dark approach', 'Warn other travelers and use their corrected charts to avoid the busiest patrol lane.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-unclaimed-weather', 'Unclaimed Weather', 'A weather satellite broadcasts forecasts for a planet that was moved off the trade maps generations ago. Its instruments now track metallic dust around the beacon. A local courier wants those readings kept private because the clear intervals give her a valuable shortcut. She offers ammunition for silence. Publishing the readings would help everyone travel quietly, including people she considers competition. The satellite itself cannot distinguish a paying customer from a passing listener.', [
    choice('share', 'Publish the dust forecast', 'Open the safest intervals to everyone and reduce the trail your fleet leaves.', [{ kind: 'threat', amount: -2 }]),
    choice('license', 'License the readings', 'Accept the courier ammunition shipment and leave her exclusive navigation service intact.', [{ kind: 'ammo', amount: 3 }]),
  ]),
  root('travel', 'travel-stowaway-mural', 'A Mural on the Outside', 'During a routine hull check, a captain finds a painted landscape spreading across the outer plating. Tiny maintenance robots arrived with the last docking seal and have mistaken your fleet for a public promenade. Their paint contains useful ceramic filler. Letting them finish would mend shallow damage, but their glittering floodlights advertise your position. Turning the lights off saves the robots from patrol attention while leaving the unfinished landscape visible in daylight.', [
    choice('finish', 'Let the painters finish', 'Accept ceramic repairs and the extra attention drawn by the illuminated fleet.', [{ kind: 'repair', amount: 12 }, { kind: 'threat', amount: 1 }]),
    choice('dark', 'Ask for a quiet departure', 'The robots pack away their lamps and leave a small tin of reusable filler.', [{ kind: 'scrap', amount: 10 }]),
  ]),
  root('travel', 'travel-folded-bridge', 'The Folded Bridge', 'An abandoned construction ship carries a bridge folded like a concertina. Its destination was a pair of habitats that never reached matching orbits. Most of the metal is worthless in its current shape, but one intact actuator remains beneath the compression frame. Cutting through the frame would release stored tension against nearby hulls. A towing system could restrain it instead. The construction log ends with an invoice politely marked awaiting a suitable distance.', [
    choice('cut', 'Cut out the actuator', 'Recover useful equipment while absorbing the released frame against your hulls.', [{ kind: 'damage', amount: 6 }, { kind: 'items', count: 1 }]),
    choice('leave', 'Record the obstruction', 'Mark the folded structure on public charts and continue outside its spring path.', []),
    choice('brace', 'Brace it with a tractor', 'Hold the compression frame steady while the actuator is removed intact.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'tractor', tier: 1 } }),
  ]),
  root('travel', 'travel-last-postbox', 'The Last Postbox', 'A floating postbox has accepted messages for two hundred years without dispatching a single delivery. The settlement that owned it migrated and forgot to leave an address. Its memory is almost full. You cannot find the recipients from here, but you can transmit the archive to public relays or sell its empty storage hardware. The oldest messages are ordinary things: recipes, condolences, a complaint about a borrowed pressure washer.', [
    choice('broadcast', 'Transmit the archive', 'Give the letters another chance of finding someone, at the cost of a conspicuous transmission.', [{ kind: 'threat', amount: 1 }]),
    choice('preserve', 'Leave the archive sealed', 'Keep the letters sealed; the grateful maintenance unit patches small cracks in your hulls.', [{ kind: 'repair', amount: 3 }]),
  ]),
  root('travel', 'travel-cold-regatta', 'The Cold Regatta', 'Uncrewed racing hulls circle a derelict grandstand, completing a competition whose spectators went home long ago. The timing computer offers an exhibition lap to anything with a transponder. There is no entry fee. Joining the narrow race would strain your engines but earns a portion of the remaining prize fund. Taking the outside lane lets the timing drones inspect your exhaust and suggest a less noticeable cruising pattern.', [
    choice('race', 'Run an exhibition lap', 'Win the modest purse while your engines recover from the sustained acceleration.', [{ kind: 'scrap', amount: 30 }, { kind: 'timed-status', system: 'engines', durationMs: 12000 }]),
    choice('observe', 'Accept an exhaust check', 'Let the timing drones tune your departure profile for quieter travel.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-spare-shadow', 'A Spare Shadow', 'A commercial shade sail crosses your route, dragging a cool wedge through an otherwise exposed debris field. Its owner rents shadow to ships whose radiators are failing. Your fleet can coast beneath the fabric while crews rest, although slower travel gives pursuers a better chance to catch up. The owner also buys surplus ammunition for the sail deployment charges. She shows you her rates before opening either docking clamp.', [
    choice('rest', 'Coast in the shade', 'Give living crew a comfortable recovery interval while patrol pressure increases.', [{ kind: 'crew-health', amount: 12 }, { kind: 'threat', amount: 1 }]),
    choice('continue', 'Keep the exposed course', 'Your radiators can manage the crossing; thank the operator and hold your existing schedule.', []),
  ]),
  root('travel', 'travel-three-permits', 'Three Valid Permits', 'Three harmless inspection drones arrive together, each carrying a different authority to inspect your fleet. Their rules are mutually exclusive: one requires open hatches, another forbids them, and the third insists no vessel stop here at all. Their supervisors disappeared years ago. You can wait for the drones to negotiate, purchase their express inspection certificate, or carefully disable their transmitters. Each drone assures you that its complaints process remains fully operational.', [
    choice('wait', 'Wait for arbitration', 'The drones eventually dismiss the inspection, but your prolonged stop attracts patrol interest.', [{ kind: 'threat', amount: 1 }]),
    choice('pay', 'Buy the express certificate', 'A consenting captain pays to end all three inspections without a lengthy argument.', [{ kind: 'threat', amount: -1 }], { cost: 14 }),
    choice('jam', 'Disable the transmitters', 'End the dispute yourself, accepting a brief disruption of your own scanner systems.', [{ kind: 'timed-status', system: 'scanner', durationMs: 15000 }]),
  ]),
  root('travel', 'travel-thin-morning', 'A Thin Morning', 'A sheet of frozen atmosphere peels away from a wandering ice world. Sunlight warms its leading edge into a stream of breathable gas. Your intakes could replenish depleted compartments, but the flow contains invisible ice needles that pit ordinary hull plating. A life support specialist could separate the needles before opening the valves. The plume will drift clear of the route eventually, leaving a perfectly serviceable passage without any free atmosphere.', [
    choice('scoop', 'Scoop the drifting air', 'Restore compartment oxygen and accept a small amount of ice damage.', [{ kind: 'hazard', hazard: 'oxygen', amount: 30 }, { kind: 'damage', amount: 3 }]),
    choice('coast', 'Pass behind the plume', 'Leave the free atmosphere to ships equipped to collect it and keep your hulls clear.', []),
    choice('filter', 'Use upgraded life support', 'Separate the sharp crystals and replenish your ships without striking the ice.', [{ kind: 'hazard', hazard: 'oxygen', amount: 40 }], { requirement: { kind: 'system', id: 'life-support', tier: 2 } }),
  ]),
  root('travel', 'travel-table-for-nobody', 'A Table for Nobody', 'A restaurant module opens its shutters as your fleet passes. The kitchen has no food left, but its proprietor is proud of the view and invites your crews to bring their own meals. Tables rotate slowly around a window overlooking a blue dwarf. For once there is no distress call, hidden invoice, or salvage claim to settle. Your crews eat together over an open channel, then leave the tables clean. The ordinary pause helps living crew recover before the next beacon.', [], [{ kind: 'crew-health', amount: 10 }]),
  root('travel', 'travel-dogleg-monument', 'A Monument in the Way', 'An immense stone hand occupies the straightest departure lane. Its sculptor wanted travelers to slow down and consider their responsibilities. Judging by the scorched fingertips, most considered only their braking distance. A preservation crew asks you to tow warning lights around the monument. Helping takes time; cutting across the marked exclusion zone saves it, but the drifting stone chips are much harder than your hulls.', [
    choice('lights', 'Place the warning lights', 'Protect the monument and earn civic goodwill while patrols draw a little closer.', [{ kind: 'reputation', faction: 'civic', amount: 1 }, { kind: 'threat', amount: 1 }]),
    choice('cross', 'Cross the chipped fingertips', 'Shorten your visible trail at the expense of scratched hull plating.', [{ kind: 'damage', amount: 4 }, { kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-scrap-dividend', 'The Scrap Dividend', 'A dismantling cooperative is distributing the last assets of a bankrupt shipping company. Every passing transponder receives one claim number; the owners apparently signed a very generous definition of creditor. You can take a small guaranteed allotment or exchange it for an unopened recovery canister. The clerk stresses that a canister may contain valuable machinery or nothing but shredded insulation. Neither selection requires your fleet to pay anything.', [
    choice('allotment', 'Take the guaranteed share', 'Accept a modest stack of clean metal and let the clerk close your claim.', [{ kind: 'scrap', amount: 16 }]),
    choice('canister', 'Choose a recovery canister', 'Trade certainty for whatever survived inside the sealed container.', [], { outcomes: [{ weight: 2, text: 'A complete spare assembly rests inside dry packing foam.', effects: [{ kind: 'items', count: 1 }] }, { weight: 1, text: 'The insulation is ruined, but the canister shell still has scrap value.', effects: [{ kind: 'scrap', amount: 5 }] }] }),
  ]),
  root('travel', 'travel-dress-rehearsal', 'Dress Rehearsal', 'A theater ship rehearses an evacuation scene using authentic pressure suits and alarm bells. Its director lacks performers who actually know how a damaged ship behaves. Your crews could demonstrate proper emergency movement, though the cramped set has several dangerously convincing sharp edges. Alternatively, the company offers a recorded performance for your medical wards. The director promises to remove the surprise explosion from whichever version you choose.', [
    choice('demonstrate', 'Demonstrate real emergency drills', 'Earn a technical consulting fee while living crew endure minor rehearsal injuries.', [{ kind: 'scrap', amount: 25 }, { kind: 'crew-health', amount: -5 }]),
    choice('watch', 'Watch from the medical wards', 'Let recovering crew enjoy the performance without setting foot on the unsafe stage.', [{ kind: 'crew-health', amount: 8 }]),
  ]),
  root('travel', 'travel-memory-braid', 'The Memory Braid', 'Two relay cables have twisted together, passing the same navigation update back and forth with a new service charge each time. Their maintenance accounts are nearly empty. A manual reset will stop the charges but briefly flood your scanners with old position reports. A hacking system could separate the billing loop from the useful data. The operators offer salvage from a retired repeater to anyone who untangles their expensive conversation.', [
    choice('reset', 'Reset both relays', 'Claim the repeater equipment and accept temporary scanner interference from the replayed reports.', [{ kind: 'items', count: 1 }, { kind: 'timed-status', system: 'scanner', durationMs: 10000 }]),
    choice('pass', 'Pass outside transmission range', 'Leave the account holders to arrange maintenance and avoid the repeating signal.', []),
    choice('separate', 'Separate the billing loop', 'Use operational hacking equipment to recover the repeater without flooding your instruments.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'hacking', tier: 1 } }),
  ]),
  root('travel', 'travel-coolant-comet', 'Coolant Comet', 'A tiny comet trails green crystals instead of ordinary ice. An industrial label identifies the material as refrigerant lost during an old transport accident. The crystals can cool hot machinery, but loading them through ordinary cargo locks would frost the adjoining compartments. A recycler offers to buy a sample without opening your intakes. She has already demonstrated the coolant on her tea, which is now a solid block.', [
    choice('cool', 'Use the refrigerant', 'Extinguish shipboard fires while the cold exposure briefly slows living crew recovery.', [{ kind: 'hazard', hazard: 'fire', amount: -20 }, { kind: 'crew-health', amount: -3 }]),
    choice('sample', 'Collect a sealed sample', 'Let the recycler handle the frozen material and accept her small laboratory payment.', [{ kind: 'scrap', amount: 12 }]),
  ]),
  root('travel', 'travel-antenna-whales', 'Antenna Whales', 'Large listening machines glide through the beacon zone, opening fanlike receivers whenever a ship transmits. Their survey crew calls them whales, although they are entirely mechanical and remarkably bad at avoiding traffic. The machines are following a distant distress recording rather than a live signal. Broadcasting a stronger decoy would clear your route but advertise your fleet. Remaining silent lets their maintenance tenders lead you through a quieter channel.', [
    choice('decoy', 'Broadcast a stronger recording', 'Maintenance tenders pay for the cleared route; your stronger broadcast increases patrol attention.', [{ kind: 'threat', amount: 1 }, { kind: 'scrap', amount: 18 }]),
    choice('silent', 'Follow the maintenance tenders', 'Travel beneath the receivers while the tenders show you their discreet service approach.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-airlock-tunnel', 'The Airlock Tunnel', 'A chain of retired cargo locks forms a temporary tunnel between two traffic buoys. A repair guild uses it to check seals as ships pass through. Their test is reliable but vigorous: sound doors emerge better aligned, while any compartment already short of oxygen may lose a little more during pressure cycling. The guild also accepts ships through an open inspection lane where nothing is tested or charged.', [
    choice('test', 'Take the pressure test', 'Seal minor breaches and accept the oxygen drawn away during the test cycle.', [{ kind: 'hazard', hazard: 'breach', amount: -12 }, { kind: 'hazard', hazard: 'oxygen', amount: -8 }]),
    choice('open', 'Use the open inspection lane', 'Show your docking certificates and continue without altering the atmosphere aboard your ships.', []),
  ]),
  root('travel', 'travel-family-frequency', 'The Family Frequency', 'Your emergency channel briefly fills with a family arguing over where to hold a reunion. Their migration convoy has scattered across several routes, and they have mistaken the beacon transmitter for a private connection. You could give them enough bandwidth to finish planning, making your own transponder easier to follow. Or you could compress their messages into a quiet burst. They offer home maintenance advice to anyone patient enough to listen.', [
    choice('relay', 'Relay the whole conversation', 'The family talks you through practical hull repairs while your signal remains conspicuous.', [{ kind: 'repair', amount: 10 }, { kind: 'threat', amount: 1 }]),
    choice('compress', 'Send a quiet message bundle', 'Arrange a useful exchange without broadcasting your fleet continuously across the lane.', [{ kind: 'scrap', amount: 8 }]),
  ]),
  root('travel', 'travel-reverse-tug', 'The Reverse Tug', 'A tug pilot has mounted the drive backward and is stubbornly calling the result a braking demonstration. His delivery barge is moving away from its destination with increasing dignity. Matching its velocity would batter your docking collars, but the customer will pay for a controlled interception. An experienced pilot could match the strange maneuver without making contact. The tug operator says he would appreciate a solution that preserves his professional terminology.', [
    choice('intercept', 'Intercept at the docking collars', 'Stop the delivery barge and accept collision damage in exchange for the customer payment.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 26 }]),
    choice('advise', 'Transmit corrected engine settings', 'Give the embarrassed operator enough information to resolve the demonstration himself.', [{ kind: 'reputation', faction: 'guild', amount: 1 }]),
    choice('pilot', 'Match the backward maneuver', 'A living pilot guides the tug into a controlled approach without stressing your hulls.', [{ kind: 'scrap', amount: 26 }], { requirement: { kind: 'crew-skill', id: 'pilot' } }),
  ]),
  root('travel', 'travel-amber-reading-room', 'The Amber Reading Room', 'A library capsule rotates slowly beside the beacon. Every book has been sealed in amber resin to survive a voyage the librarians knew they would never finish. You cannot borrow the originals, but their catalog offers complete radio copies without registration. Your crews choose repair manuals, poetry, and a surprisingly popular guide to growing onions in small rooms. A maintenance appendix contains a careful method for patching hull seams using materials already aboard. You complete those modest repairs before leaving.', [], [{ kind: 'repair', amount: 7 }]),
  root('travel', 'travel-border-hum', 'The Border Hum', 'The old border exists only as a low humming transmission. No patrol claims it, but every ship that crosses is asked to declare what it hopes to find beyond. Honest answers join a public recording; silence triggers an obsolete identification scan. A freehold historian maintains the beacon because the declarations tell a better story than the missing government records. She asks permission before adding your voices to the archive.', [
    choice('answer', 'Record your hopes', 'Support the freehold archive while accepting that your public message may reach unfriendly listeners.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }, { kind: 'threat', amount: 1 }]),
    choice('silent', 'Submit to the old scan', 'Keep your plans private and tolerate a brief interruption of your scanners.', [{ kind: 'timed-status', system: 'scanner', durationMs: 8000 }]),
  ]),
  root('travel', 'travel-surveyor-wager', 'A Surveyor Wager', 'Two survey crews disagree about the density of a rubble cluster. Their argument has become a wager, and they want an independent ship to collect a sample. The predicted amounts of useful metal differ wildly. Entering the cluster is optional; both crews will pay a modest arbitration fee if you simply record that their instruments disagree. One surveyor has already written a victory speech, which the other keeps correcting over the shared channel.', [
    choice('sample', 'Collect an independent sample', 'Enter the loose rubble and discover which density estimate was closer.', [{ kind: 'damage', amount: 3 }], { outcomes: [{ weight: 2, text: 'The sample holds dense metal nodules; both crews honor the larger sample fee.', effects: [{ kind: 'scrap', amount: 32 }] }, { weight: 1, text: 'The rubble is mostly porous slag, worth only a token payment.', effects: [{ kind: 'scrap', amount: 6 }] }] }),
    choice('arbitrate', 'Record the disagreement', 'Take the smaller guaranteed fee without flying into the disputed rubble.', [{ kind: 'scrap', amount: 12 }]),
  ]),
  root('travel', 'travel-painted-constellation', 'A Painted Constellation', 'A tourism company has arranged bright satellites into a constellation visible from a nearby resort. Unfortunately, it resembles an obsolete naval signal for surrender. Armed traffic keeps arriving to collect prisoners and leaving irritated. The caretaker asks you to shift one satellite so the pattern becomes a fish. Handling the hot positioning thrusters could injure working crew; circulating a correction requires only a public transmission and a little patience.', [
    choice('move', 'Move the misplaced star', 'Restore the intended fish and earn payment, with minor burns among living crew.', [{ kind: 'scrap', amount: 22 }, { kind: 'crew-health', amount: -4 }]),
    choice('correct', 'Broadcast the correct meaning', 'Help civilian traffic understand the display while making your own route more visible.', [{ kind: 'reputation', faction: 'civic', amount: 1 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('travel', 'travel-shield-rain', 'Rain for the Shields', 'Charged droplets from a ruptured fuel refinery sweep across the lane. Their glow makes the cloud look gentle, but the refinery warnings describe an excellent way to burn holes in a hull. Your fleet could skirt the densest rain or catch floating refinery stock along its edge. Reinforced shields would let you reach the stock directly. Nobody is still aboard the refinery; its evacuation manifest has already been signed and transmitted.', [
    choice('edge', 'Recover stock along the edge', 'Bring useful equipment aboard and accept scorch damage from the charged spray.', [{ kind: 'items', count: 1 }, { kind: 'damage', amount: 7 }]),
    choice('detour', 'Take the dry detour', 'Keep your ships clear of the refinery discharge without collecting its abandoned stock.', []),
    choice('shield', 'Cross under reinforced shields', 'An operational tier two shield system opens a safer route to the floating stock.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'shields', tier: 2 } }),
  ]),
  root('travel', 'travel-runaway-conveyor', 'The Runaway Conveyor', 'An endless line of empty shipping pallets moves between two unmanned warehouses. Both warehouses insist the other ordered them. The pallets are blocking small craft from the service lane, and a guild dispatcher offers a clearance payment. You can feed a few ammunition charges into the conveyor cutters to break the loop. Leaving a marked opening for local tugs is slower but does not require anything from your magazines.', [
    choice('cut', 'Charge the conveyor cutters', 'Spend two rounds from shipboard magazines to clear the loop and collect the fee.', [{ kind: 'ammo', amount: -2 }, { kind: 'scrap', amount: 28 }]),
    choice('opening', 'Mark an opening for tugs', 'Give the repair guild a workable approach while their slow clearance delays your departure.', [{ kind: 'reputation', faction: 'guild', amount: 1 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('travel', 'travel-drum-of-names', 'The Drum of Names', 'A supply drum carries hundreds of names scratched into its shell. It belongs to a mutual aid circuit: travelers take emergency goods and leave something useful. The current contents are mostly ammunition and handwritten directions to quiet anchorages. A lock records withdrawals but does not restrict them. Your crews can take the ammunition now or leave it for someone whose weapons depend on it, using only the copied navigation advice.', [
    choice('rounds', 'Take emergency ammunition', 'Add the donated rounds to shipboard magazines and leave your fleet names on the drum.', [{ kind: 'ammo', amount: 2 }]),
    choice('directions', 'Copy the quiet anchorages', 'Preserve the physical supplies and use the contributors advice to reduce your visible trail.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-weather-quilts', 'Weather Quilts', 'Textile workers stretch thermal blankets between small utility boats, testing a shelter for exposed docking platforms. Their patchwork canopy is beautiful and entirely in the way. Passing through would help demonstrate the shelter under real engine wash, but loose fabric might clog your intakes. The workers can fold a narrow corridor instead. They are testing for a community that cannot afford a second failed winter, so either kind of cooperation matters.', [
    choice('test', 'Provide a real engine wash', 'Earn a testing fee while accepting the risk of a temporary life support blockage.', [{ kind: 'scrap', amount: 20 }, { kind: 'timed-status', system: 'life-support', durationMs: 9000 }]),
    choice('corridor', 'Help hold a folded corridor', 'Give the civic shelter project useful measurements without flying through its fabric.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('travel', 'travel-empty-escort', 'The Empty Escort', 'An automated escort contract activates as you enter the beacon. The convoy it was written for has vanished, but its supply tender still waits at the rendezvous. A hostile salvage patrol considers the tender abandoned property. You could honor the escort until it jumps, or send the old cancellation code before the patrol closes. The tender carries no passengers and explicitly releases you from responsibility if you cancel.', [
    choice('escort', 'Honor the escort contract', 'Defend the tender against the approaching salvage patrol until it clears the beacon.', [{ kind: 'combat', objective: 'defend', threat: 2 }]),
    choice('cancel', 'Cancel the obsolete contract', 'The tender burns its sensitive files and sends you its remaining navigation credit.', [{ kind: 'scrap', amount: 10 }]),
  ]),
  root('travel', 'travel-vacuum-honey', 'Vacuum Honey', 'A sticky golden substance coats a broken cargo cage. It is industrial hull sealant, despite a merchant insisting that vacuum honey is a recognized food. Removing it by hand would expose crews to the cage sharp edges. A maintenance drone could scrape the cage from outside and carry the sealed cartridge directly aboard. The merchant will also buy an unopened sample, sparing you any need to test his culinary claims.', [
    choice('scrape', 'Scrape usable sealant by hand', 'Patch small hull defects while working crew suffer cuts from the damaged cage.', [{ kind: 'repair', amount: 13 }, { kind: 'crew-health', amount: -5 }]),
    choice('sample', 'Sell a sealed sample', 'Accept a little scrap and let the merchant decide how to describe his purchase.', [{ kind: 'scrap', amount: 9 }]),
    choice('drone', 'Send a maintenance drone', 'Use an operational drone bay to retrieve the cartridge without sending crew into the cage.', [{ kind: 'repair', amount: 13 }], { requirement: { kind: 'system', id: 'drone-bay', tier: 1 } }),
  ]),
  root('travel', 'travel-forgotten-apology', 'A Forgotten Apology', 'A courier buoy intercepts your transponder with an apology addressed to whoever was inconvenienced. Its owner accidentally blocked this lane with construction equipment thirty years ago and prepaid compensation for the next hundred ships. The construction equipment is long gone. The buoy explains that interest has kept the account open far longer than expected. It credits your fleet a small compensation payment, records the delivery, and returns to practicing a warmer version of the apology for the next visitor.', [], [{ kind: 'scrap', amount: 14 }]),
  root('travel', 'travel-tilted-cylinder', 'The Tilted Cylinder', 'A rotating residential cylinder has tilted into its own supply route. Nobody is in danger, but every delivery now ends with an argument about which end counts as the front door. Residents have pooled scrap for a temporary docking adjustment. The work requires holding your hulls against a rough guide rail. You could instead carry their revised directions onto the next public relay, helping suppliers without touching the spinning structure.', [
    choice('adjust', 'Hold the docking guide steady', 'Let the residents fit new bearings while your hulls scrape against the temporary guide.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 23 }]),
    choice('directions', 'Carry the revised directions', 'Help freehold delivery pilots find the proper entrance without joining the construction work.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }]),
  ]),
  root('travel', 'travel-coolant-hymn', 'The Coolant Hymn', 'Pilgrims aboard a radiator barge sing in time with its circulation pumps. The rhythm lets them hear a failing bearing before any indicator reports trouble. They invite your crews to rest inside their warm observation chamber while the barge draws heat from nearby ships. Their practiced cooling can extinguish lingering fires, but coupling to the slow barge costs travel time. They also offer the pump rhythm as a simple farewell gift.', [
    choice('couple', 'Join the radiator circuit', 'Cool dangerous shipboard fires while your fleet loses ground to following patrols.', [{ kind: 'hazard', hazard: 'fire', amount: -25 }, { kind: 'threat', amount: 1 }]),
    choice('listen', 'Learn the pump rhythm', 'Share a few quiet minutes with the pilgrims and continue on your existing course.', [{ kind: 'reputation', faction: 'pilgrims', amount: 1 }]),
  ]),
  root('travel', 'travel-navigation-auction', 'The Navigation Auction', 'A chart broker auctions the location of a hidden service lane to every ship in range. Winning would make the lane useful only briefly; the runners up will know exactly where the winner went. Your captains notice that her ordinary public charts already show a slower quiet route. She admits this freely when asked. The expensive version includes a cache of obsolete ammunition that the public route does not reach.', [
    choice('bid', 'Buy the service lane package', 'A consenting captain pays for the cached ammunition and the temporary shortcut.', [{ kind: 'ammo', amount: 4 }, { kind: 'threat', amount: -1 }], { cost: 18 }),
    choice('public', 'Use the ordinary public chart', 'Follow the less fashionable quiet passage without entering the auction or buying supplies.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-broken-palindrome', 'The Broken Palindrome', 'A beacon repeats a navigation phrase forward and backward. One digit differs, and departing ships have followed both versions into the same harmless cul de sac. A survey award remains available for correcting the encoding. Trying both routes would expose your fleet to more patrol traffic. A scientist could identify the transmission error from the waveform alone. The beacon patiently congratulates every wrong answer because its courtesy recording has also been reversed.', [
    choice('test', 'Survey both advertised routes', 'Earn the survey award after enough visible maneuvering to attract additional patrol attention.', [{ kind: 'scrap', amount: 24 }, { kind: 'threat', amount: 1 }]),
    choice('ignore', 'Use your existing charts', 'Reject both contradictory instructions and continue through the ordinary mapped departure lane.', []),
    choice('decode', 'Have a scientist decode it', 'A living scientist corrects the waveform and claims the award without the repeated survey.', [{ kind: 'scrap', amount: 24 }], { requirement: { kind: 'crew-skill', id: 'scientist' } }),
  ]),
  root('travel', 'travel-ice-carousel', 'The Ice Carousel', 'Ice blocks rotate around a dismantled freezer station, each still bearing a restaurant delivery address. Their centers contain sealed mechanical fittings used as ballast. Heating a block would release the fittings but send hot vapor against nearby hulls. A food historian wants one whole block preserved instead; the frost pattern records how freight was packed before refrigeration standards changed. He is delighted that anyone else finds the subject worth stopping for.', [
    choice('melt', 'Melt out the ballast fittings', 'Recover a usable equipment assembly while accepting a small thermal shock to your hulls.', [{ kind: 'items', count: 1 }, { kind: 'damage', amount: 4 }]),
    choice('preserve', 'Deliver an intact ice block', 'Let the historian secure his specimen and collect the modest research payment.', [{ kind: 'scrap', amount: 11 }]),
  ]),
  root('travel', 'travel-sealed-witness', 'The Sealed Witness Box', 'A legal archive requests transport verification for a sealed evidence container. The trial ended years ago, but the box must still be counted whenever it changes orbit. You need not open it or decide who was right. Simply broadcasting its location earns the archive fee, while quietly checking its tamper seals helps a pilgrim order that guards records of wrongful imprisonment. The two custodians disagree mainly about how much publicity preserves the truth.', [
    choice('broadcast', 'Publish the verified location', 'Collect the archive fee while the long transmission reveals more of your fleet route.', [{ kind: 'scrap', amount: 20 }, { kind: 'threat', amount: 1 }]),
    choice('seals', 'Verify the seals privately', 'Return the intact seal numbers to the custodians without making a public claim.', [{ kind: 'reputation', faction: 'pilgrims', amount: 1 }]),
  ]),
  root('travel', 'travel-paper-sails', 'Paper Sails', 'A school flotilla launches miniature solar sails covered in student drawings. Their teacher discovers too late that the deployment charges use the same firing frequency as your weapons. A brief weapons shutdown would let the exhibition continue safely. Keeping your equipment active requires the children to collect their models before you pass. The teacher offers spare charges either way, apologizing with the exhausted precision of someone who checked everything except this.', [
    choice('shut', 'Shut down weapons briefly', 'Let the sails deploy and accept spare ammunition while your weapon systems restart.', [{ kind: 'ammo', amount: 3 }, { kind: 'timed-status', system: 'weaponry', durationMs: 9000 }]),
    choice('collect', 'Wait for the models to return', 'Keep your weapons available and help the class recover its little exhibition intact.', [{ kind: 'reputation', faction: 'civic', amount: 1 }]),
  ]),
  root('travel', 'travel-laundry-quarantine', 'Laundry Quarantine', 'A decontamination station has quarantined its own laundry because a red sock triggered the biological scanner. The attendant can prove there is no infection, but the wash cycle will not release its pressure locks. Using your pumps would finish the cycle and refill nearby oxygen reserves, while temporarily occupying your life support controls. You can also provide an outside witness statement so the attendant can authorize a manual release later.', [
    choice('pump', 'Complete the pressure cycle', 'Replenish compartment oxygen while your life support systems recover from the external load.', [{ kind: 'hazard', hazard: 'oxygen', amount: 20 }, { kind: 'timed-status', system: 'life-support', durationMs: 7000 }]),
    choice('witness', 'Sign the witness statement', 'Help the guild attendant resolve the false alarm without connecting your ships to the laundry.', [{ kind: 'reputation', faction: 'guild', amount: 1 }]),
  ]),
  root('travel', 'travel-compressed-grove', 'The Compressed Grove', 'A timber shipment has been compressed into a block dense enough to interfere with local docking magnets. No trees are alive inside; a sawmill manager wants the obstruction broken into manageable slabs. Explosive cutting would consume ammunition but earns a cash payment. A beam weapon could make clean cuts and preserve valuable machine housings trapped along the edge. The manager is equally happy to wait for a properly equipped industrial cutter.', [
    choice('charges', 'Cut with magazine charges', 'Spend two rounds to break the obstruction and receive the sawmill clearance payment.', [{ kind: 'ammo', amount: -2 }, { kind: 'scrap', amount: 26 }]),
    choice('wait', 'Leave it for industrial cutters', 'Send the manager your measurements and continue without disturbing the dense shipment.', []),
    choice('beam', 'Slice it with a beam weapon', 'Use a working beam installation to recover an intact housing during the clean cut.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'weapon-family', id: 'beam' } }),
  ]),
  root('travel', 'travel-veterans-marker', 'The Veterans Marker', 'A modest marker lists the names of repair crews who kept civilian ships moving during a forgotten evacuation. Nobody has polished its surface in years. Your crews clean one panel while waiting for the beacon to finish its normal alignment cycle. Beneath the dust they find instructions for a common emergency patch, written in six languages by someone who knew frightened people might need it. Following the diagram closes several small defects in your own hulls. You leave the diagram uncovered.', [], [{ kind: 'repair', amount: 6 }]),
  root('travel', 'travel-turbine-reef', 'The Turbine Reef', 'Discarded turbine blades have gathered into a sharp, slowly turning reef. Salvagers use the enclosed calm as a workshop, repairing ships with whatever the reef sheds. They offer substantial hull work if your fleet supplies ammunition for their cutting charges. Their sheltered departure lane is free to anyone who observes the workshop speed limit. One apprentice has painted arrows on the blades, though half point somewhere different after each rotation.', [
    choice('repair', 'Supply charges for hull work', 'Spend two magazine rounds and let the salvagers patch your surviving ships.', [{ kind: 'ammo', amount: -2 }, { kind: 'repair', amount: 15 }]),
    choice('lane', 'Follow the sheltered lane', 'Use the workshop shelter to reduce your trail without asking for repairs.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-ring-exchange', 'The Ring Exchange', 'Two married station keepers are swapping the outer rings of their habitats as an anniversary gift. The transaction is romantic, legal, and blocking every marked route. They ask passing ships to brace one ring while the transfer collars align. That work risks scraped hulls but earns a share of the removed fittings. Waiting beyond the ceremony gives your crews a chance to rest while the keepers deliver increasingly elaborate speeches.', [
    choice('brace', 'Brace the turning ring', 'Accept collar damage in exchange for the salvaged fittings payment.', [{ kind: 'damage', amount: 4 }, { kind: 'scrap', amount: 24 }]),
    choice('rest', 'Wait through the speeches', 'Let living crew recover during the ceremony while following patrols gain ground.', [{ kind: 'crew-health', amount: 10 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('travel', 'travel-ticket-to-yesterday', 'A Ticket to Yesterday', 'An automated ferry gate offers tickets dated a day before your arrival. Its clock error has stranded no passengers, but delivery crews have begun flying through the service gap instead of arguing. Buying a ticket contributes to the maintenance fund and opens an inspected passage. Using the unofficial gap costs nothing, though its loose pressure shutters could nick your hulls. The gate repeatedly assures you that advance booking offers excellent value.', [
    choice('ticket', 'Buy the misdated ticket', 'A consenting captain pays for a maintained passage that helps the local civic service.', [{ kind: 'reputation', faction: 'civic', amount: 1 }], { cost: 10 }),
    choice('gap', 'Use the delivery crews gap', 'Pass the unreliable gate through the narrow opening and accept minor shutter scrapes.', [{ kind: 'damage', amount: 2 }]),
  ]),
  root('travel', 'travel-charged-footsteps', 'Charged Footsteps', 'A maintenance robot has left a trail of charged fasteners between the beacon and a tool cache. Every time a ship approaches, the loose screws leap toward its hull. The robot is embarrassed but cannot collect them with its own magnetic feet. You can endure the impacts to reach the cache, or let the robot discharge the trail slowly. Point defense could intercept the fasteners before they touch anything important.', [
    choice('approach', 'Approach through the fasteners', 'Recover equipment from the tool cache while the loose metal chips your plating.', [{ kind: 'damage', amount: 5 }, { kind: 'items', count: 1 }]),
    choice('discharge', 'Let the robot discharge them', 'Wait for a safe ordinary departure while the extended stop increases pursuit pressure.', [{ kind: 'threat', amount: 1 }]),
    choice('intercept', 'Intercept with point defense', 'Clear the fasteners using operational point defense and recover the cache safely.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'point-defense', tier: 1 } }),
  ]),
  root('travel', 'travel-harbor-abacus', 'The Harbor Abacus', 'The harbor accountant tracks docking fees on floating metal beads because the computer has been broken for decades. A recent jolt scattered half the beads into a cooling duct. Recovering them would restore several residents deposits, but hot air from the duct can burn working crew. The accountant can also accept a public declaration that the records were lost accidentally. She wants witnesses more than she wants anyone punished.', [
    choice('recover', 'Recover the scattered beads', 'Return the deposit records and earn a recovery fee despite minor heat injuries.', [{ kind: 'crew-health', amount: -4 }, { kind: 'scrap', amount: 22 }]),
    choice('witness', 'Witness the accidental loss', 'Help the freehold harbor settle the missing accounts without sending crew into the duct.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }]),
  ]),
  root('travel', 'travel-ghost-traffic', 'Ghost Traffic', 'Your radar fills with a disciplined convoy, yet the windows show empty space. A training buoy is projecting practice targets onto the shared navigation band. Its instructor offers to turn the exercise toward your fleet for a gunnery refresher. The exercise spends real ammunition and rewards a small training stipend. Refusing is entirely acceptable; the instructor will instead demonstrate how to recognize false transponder patterns without firing.', [
    choice('practice', 'Join the live gunnery exercise', 'Spend one magazine round for the instructor stipend and the controlled target practice.', [{ kind: 'ammo', amount: -1 }, { kind: 'scrap', amount: 20 }]),
    choice('recognize', 'Study the false transponders', 'Use the instructor quiet navigation advice to leave a less obvious trail.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-ceramic-river', 'The Ceramic River', 'A production accident has released thousands of tiny ceramic tiles into a narrow stream. Their owner cannot sell them as tableware anymore, but their heat resistant glaze remains useful for hull repairs. Catching the tiles involves flying through the stream and accepting a few impacts before the new patches can be fitted. A cautious buyer offers scrap for a small sample collected outside the main flow. Nobody expects you to recover the whole shipment.', [
    choice('collect', 'Collect tiles from the stream', 'Accept the initial impacts, then fit the recovered heat resistant patches.', [{ kind: 'damage', amount: 3 }, { kind: 'repair', amount: 14 }]),
    choice('sample', 'Sell a small outside sample', 'Collect only loose edge tiles and take the buyer guaranteed sample fee.', [{ kind: 'scrap', amount: 9 }]),
  ]),
  root('travel', 'travel-green-flare', 'The Green Flare', 'A bright green flare rises from a shuttered navigation office. The local codebook defines green as safe passage, but the office clerk uses it to mean please visit because the kettle is ready. She apologizes when armed travelers arrive expecting an escort. Staying for tea gives living crew a restorative break. Correcting the public codebook would help future visitors, although the long transmission makes your current position easier to identify.', [
    choice('tea', 'Accept the invitation to tea', 'Let living crew recover with the clerk while patrols make up some distance.', [{ kind: 'crew-health', amount: 12 }, { kind: 'threat', amount: 1 }]),
    choice('codebook', 'Correct the public codebook', 'Help civic navigation services distinguish invitations from safety instructions while exposing your transmission.', [{ kind: 'reputation', faction: 'civic', amount: 1 }, { kind: 'threat', amount: 1 }]),
  ]),
  root('travel', 'travel-folded-warehouse', 'The Folded Warehouse', 'A modular warehouse has folded around its own loading platform, leaving a paid supply shipment behind an inaccessible door. Its owner can authorize demolition of an exterior wall, provided your fleet takes responsibility for the debris. An operational teleporter could retrieve the shipment without opening the structure. The owner also offers a small cancellation payment if you would prefer to leave the supplies where they are until a construction crew arrives.', [
    choice('demolish', 'Open the exterior wall', 'Recover the stranded equipment while demolition fragments strike nearby hulls.', [{ kind: 'items', count: 1 }, { kind: 'damage', amount: 6 }]),
    choice('cancel', 'Take the cancellation payment', 'Release the owner from the delivery promise and wait for no further construction work.', [{ kind: 'scrap', amount: 12 }]),
    choice('transfer', 'Teleport the supply crate', 'Use an operational transporter to recover the sealed equipment without demolishing the wall.', [{ kind: 'items', count: 1 }], { requirement: { kind: 'system', id: 'teleporter', tier: 1 } }),
  ]),
  root('travel', 'travel-sky-burial', 'A Quiet Sky Burial', 'An empty passenger capsule drifts past with its shutters open and its engines carefully removed. A farewell recording explains that the traveler lived a full life and asked for this last view. There are no valuables to recover and no emergency to solve. Your crews lower their work lights while the capsule crosses the sunlit edge of the beacon. A pilgrim watchkeeper thanks your fleet for respecting the passage and records the courtesy in the order guest ledger.', [], [{ kind: 'reputation', faction: 'pilgrims', amount: 1 }]),
  root('travel', 'travel-radiator-bells', 'Radiator Bells', 'A metalworker has turned discarded radiator fins into bells that ring through contact microphones. The instrument is too large to transport, so visitors dock against it to listen. Coupling your ships to the cold fins would also draw heat from any active fires. The metalworker warns that the vibration may unsettle delicate scanners. You can listen to a recorded performance instead, leaving your instruments entirely out of the arrangement.', [
    choice('couple', 'Dock against the instrument', 'Extinguish lingering fires while your scanners briefly recover from the transmitted vibration.', [{ kind: 'hazard', hazard: 'fire', amount: -18 }, { kind: 'timed-status', system: 'scanner', durationMs: 8000 }]),
    choice('recording', 'Listen to the recorded bells', 'Share the metalworker performance with recovering crew without physically coupling the ships.', [{ kind: 'crew-health', amount: 6 }]),
  ]),
  root('travel', 'travel-thermal-contest', 'The Thermal Contest', 'A research club awards prizes for unusual radiator patterns. Your fleet has arrived during judging, and the chair enthusiastically mistakes battle wear for an experimental design. Entering would require a hot demonstration that may scorch outer plating. Correcting the misunderstanding disappoints the judges, but their cooling specialist still offers useful advice. The previous winner appears to have achieved success by forgetting to remove a large decorative cover.', [
    choice('enter', 'Demonstrate the unusual pattern', 'Accept a little heat damage in exchange for the club exhibition prize.', [{ kind: 'damage', amount: 3 }, { kind: 'scrap', amount: 21 }]),
    choice('advice', 'Ask for ordinary cooling advice', 'Apply the specialist practical recommendations to suppress small shipboard fires.', [{ kind: 'hazard', hazard: 'fire', amount: -8 }]),
  ]),
  root('travel', 'travel-exit-signs', 'Every Sign Says Exit', 'A dismantled shopping habitat has released hundreds of illuminated exit signs. Their emergency batteries still work, making the debris field brighter than the official beacon. Collecting the batteries would supply useful scrap but keeps your fleet visible among the lights. A delivery pilot knows an unlit gap behind the former loading docks. He insists he only became lost here once, although his map shows several carefully crossed out routes.', [
    choice('batteries', 'Recover the emergency batteries', 'Take useful electrical scrap while the brilliant signs advertise your position.', [{ kind: 'scrap', amount: 23 }, { kind: 'threat', amount: 1 }]),
    choice('gap', 'Follow the unlit loading gap', 'Use the delivery pilot final corrected route to leave a smaller trail.', [{ kind: 'threat', amount: -1 }]),
  ]),
  root('travel', 'travel-map-under-skin', 'A Map Under the Skin', 'An old survey hull carries its final chart etched beneath a layer of protective plating. The pilot who made it distrusted digital archives but underestimated how difficult the map would be to read. Removing the skin gives access to valuable route data and sharp debris. A powerful scanner could read through the metal instead. The nearest cartography guild offers a recovery payment; nobody needs the chart simply to leave this beacon.', [
    choice('strip', 'Strip the protective plating', 'Recover the chart for the guild while debris scratches your own surviving ships.', [{ kind: 'damage', amount: 5 }, { kind: 'scrap', amount: 28 }]),
    choice('report', 'Report the chart location', 'Leave its recovery to a specialist vessel and retain your existing navigation plans.', [{ kind: 'reputation', faction: 'guild', amount: 1 }]),
    choice('scan', 'Read through the survey skin', 'Use an operational tier two scanner to copy the map without stripping its cover.', [{ kind: 'scrap', amount: 28 }], { requirement: { kind: 'system', id: 'scanner', tier: 2 } }),
  ]),
  root('travel', 'travel-launch-rehearsal', 'Launch Rehearsal', 'A community launch team is testing the countdown for its first independent cargo service. Everything works except the final igniter, which is compatible with ordinary missile primers. They ask your captains for a contribution of magazine ammunition. A successful test would pay a modest supplier fee and encourage the freehold venture. You can also help by transmitting an honest technical report so the team can request the correct part from another ship.', [
    choice('primer', 'Supply the compatible primers', 'Spend one round from shipboard magazines to support the launch and collect the supplier fee.', [{ kind: 'ammo', amount: -1 }, { kind: 'scrap', amount: 18 }, { kind: 'reputation', faction: 'freeholds', amount: 1 }]),
    choice('report', 'Transmit the parts report', 'Help the launch team explain its problem without contributing physical supplies.', [{ kind: 'reputation', faction: 'freeholds', amount: 1 }]),
  ]),
  root('travel', 'travel-soup-transmission', 'The Soup Transmission', 'A galley instructor broadcasts a recipe across the service band. The lesson includes substitutions for nearly every ingredient and assumes the listener owns one dented pot. Your crews recognize most of the substitutes from their emergency rations. While the navigation computer completes its routine checks, they prepare a shared meal in their own quarters. The instructor signs off before anyone can thank her, already explaining how to clean the pot with almost no water. Living crew finish the meal rested and a little healthier.', [], [{ kind: 'crew-health', amount: 9 }]),
  root('travel', 'travel-harbor-credit', 'A Credit from the Harbor', 'An unmanned harbor machine apologizes for damaging a ship with your transponder pattern several decades ago. Your fleet clearly is not that ship, but its claims policy allows a verified successor to accept compensation. The machine offers either spare ammunition or an exterior maintenance pass. It has no method for hearing a long explanation about coincidence. Declining the payment simply leaves the account open for another traveler with equally unfortunate identification numbers.', [
    choice('ammo', 'Accept the magazine credit', 'Take the machine documented ammunition compensation and close the old claim.', [{ kind: 'ammo', amount: 2 }]),
    choice('service', 'Accept exterior maintenance', 'Let the harbor tools patch shallow hull damage as the equivalent compensation.', [{ kind: 'repair', amount: 8 }]),
  ]),
  root('travel', 'travel-lantern-sentry', 'The Lantern Sentry', 'A bright navigation lantern is guarded by an obsolete recognition system. It shines on unfamiliar ships until a human operator approves them, but there has been no operator for years. You can cross the beam openly and allow it to report your route. Shutting down your engines would let its slow scan finish before departure. A working cloak could carry the fleet through the illuminated approach without feeding the sentry another identification record.', [
    choice('open', 'Cross the beam openly', 'Keep all systems available while the sentry broadcasts your passage to distant listeners.', [{ kind: 'threat', amount: 1 }]),
    choice('drift', 'Drift through the scan', 'Avoid the public alarm while your engines complete a brief cold restart.', [{ kind: 'timed-status', system: 'engines', durationMs: 10000 }]),
    choice('cloak', 'Use an operational cloak', 'Pass the obsolete sentry quietly without stopping to satisfy its missing operator.', [{ kind: 'threat', amount: -1 }], { requirement: { kind: 'system', id: 'cloak', tier: 1 } }),
  ]),
];
