import { test } from 'node:test';
import assert from 'node:assert/strict';
import { rules, craft, restoreWorld, serializeWorld, growTree } from '../src/server';
import { tickMobs } from '../src/mobs';
import { growSaplings } from '../src/bedrock';
import { homesteadAction } from '../src/survival';
import { BENCH, FURNACE, COBBLE, RAW_IRON, INGOT, FUEL, IRON_PICK, DIAMOND_PICK, SAPLING, TORCH, RECIPES, ITEMS, paletteFor, index, neutral, type MobKind } from '../src/model';
import { assertSerializable } from '../../../party-contract/src/serializable';
const ctx={roomId:'r',roundId:'g',seed:99,nowMs:0,players:[{id:'p',name:'Builder',color:'#aabbcc'}]};
const make=()=>rules.create(ctx,rules.validateSettings({}));
const set=(s:ReturnType<typeof make>,x:number,y:number,z:number,b:number)=>{const i=index(x,y,z);s.grid[i]=b;s.edits.set(i,b);s.revision++;return i;};
function arena(){const s=make();s.grid.fill(0);for(let x=0;x<128;x++)for(let z=0;z<128;z++)s.grid[index(x,5,z)]=3;Object.assign(s.players[0]!,{x:64.5,y:6,z:66.5,yaw:0,pitch:0});return s;}
const tick=(s:ReturnType<typeof make>,input=neutral(),seconds=1)=>{for(let n=0;n<seconds*30;n++)rules.tick(s,new Map([['p',input]]),1/30,0);};
test('new worlds use familiar recipes and preserve all legacy item IDs',()=>{const s=make();assert.equal(s.terrainVersion,5);assert.deepEqual(s.players[0]!.inventory,{});assert.equal(ITEMS[IRON_PICK],'Iron Pickaxe');assert.ok(!paletteFor(4).includes(13));for(const id of ['sunwell','copper','hedge','rose','ocean','gold','roast'])assert.ok(!RECIPES.some(r=>r.id===id));assert.equal(rules.playerView(s,'p',{nowMs:0,phase:'playing'}).craftingSize,2);});
test('logs to iron progression requires the correct selected tool and local table',()=>{const s=arena(),p=s.players[0]!;p.inventory={4:4};for(let i=0;i<4;i++)craft(s,p,'planks');craft(s,p,'sticks');craft(s,p,'bench');assert.throws(()=>craft(s,p,'twig'),/table/);set(s,63,6,66,BENCH);craft(s,p,'twig');assert.equal(rules.playerView(s,'p',{nowMs:0,phase:'playing'}).craftingSize,3);set(s,64,7,64,3);tick(s,{...neutral(),mine:true,slot:0},2);assert.equal(p.inventory[COBBLE]??0,0);tick(s,{...neutral(),mine:true,slot:24},2);assert.equal(p.inventory[COBBLE],1);p.inventory[COBBLE]=3;craft(s,p,'stone');assert.equal(p.inventory[25],1);set(s,64,7,64,34);tick(s,{...neutral(),mine:true,slot:24},2);assert.equal(p.inventory[RAW_IRON]??0,0);tick(s,{...neutral(),mine:true,slot:25},2);assert.equal(p.inventory[RAW_IRON],1);});
test('capacity and station failures spend nothing; inventory-only tools cannot be placed',()=>{const s=arena(),p=s.players[0]!;p.inventory={4:1,10:63,[IRON_PICK]:1};assert.throws(()=>craft(s,p,'planks'),/room/);assert.equal(p.inventory[4],1);const before=s.edits.size;tick(s,{...neutral(),place:true,pitch:-.5,looking:true,slot:IRON_PICK});assert.equal(s.edits.size,before);assert.throws(()=>rules.parseInput({...neutral(),slot:14}));assert.throws(()=>rules.parseInput({...neutral(),sneak:1}));});
test('one coal fuels repeated iron smelts; finished output and burn time survive save',()=>{const s=make(),p=s.players[0]!,y=Math.floor(p.y);const i=set(s,Math.floor(p.x),y,Math.floor(p.z)-2,FURNACE);p.pitch=-.5;p.inventory={[RAW_IRON]:2,[FUEL]:1};craft(s,p,'iron');const fuel=s.fuelUntil![i];assert.equal(fuel,80);s.time=10;homesteadAction(s,p,{type:'use'},()=>false);assert.equal(p.inventory[INGOT],1);craft(s,p,'iron');assert.equal(p.inventory[FUEL],0);assert.equal(s.fuelUntil![i],80);const save=serializeWorld(s);assertSerializable(save);const restored=make();restoreWorld(restored,JSON.parse(JSON.stringify(save)));assert.equal(restored.furnaces[i]?.item,INGOT);assert.equal(restored.fuelUntil![i],80);});
test('new save limits validate atomically and every modern inventory item roundtrips',()=>{const s=make(),p=s.players[0]!;p.inventory={[DIAMOND_PICK]:1, [RAW_IRON]:64};const save=serializeWorld(s),bad=structuredClone(save);bad.players[0]!.inventory[RAW_IRON]=65;assert.throws(()=>restoreWorld(s,bad));assert.deepEqual(serializeWorld(s),save);const restored=make();restoreWorld(restored,save);assert.deepEqual(restored.players[0]!.inventory,p.inventory);});
test('saplings are delayed, grow only with clearance, and survive saves as blocks',()=>{const s=make(),p=s.players[0]!;p.inventory={[SAPLING]:1};p.pitch=-1.2;const x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z)-1;set(s,x,y-1,z,1);for(let dy=0;dy<6;dy++)set(s,x,y+dy,z,0);growTree(s,p);assert.equal(p.inventory[SAPLING],0);assert.ok([...s.edits.values()].includes(SAPLING));const save=serializeWorld(s),restored=make();restoreWorld(restored,save);assert.ok([...restored.edits.values()].includes(SAPLING));for(let n=1;n<=40;n++){s.time=n*30;growSaplings(s,1/30);}assert.ok(![...s.edits.values()].includes(SAPLING));});
test('sneaking holds the edge while ordinary movement can leave it',()=>{const s=arena(),p=s.players[0]!;for(let z=0;z<128;z++)for(let x=65;x<128;x++)s.grid[index(x,5,z)]=0;tick(s,{...neutral(),x:1,sneak:true},1);assert.ok(p.x<65);tick(s,{...neutral(),x:1},1);assert.ok(p.x>65&&p.y<6);});
function mob(s:ReturnType<typeof make>,kind:MobKind,x:number,z:number){s.creatures=[{id:1,kind,x,y:6,z,health:10,hitAt:0,fuse:0,attackAt:0}];s.time=800;}
const damage=(s:ReturnType<typeof make>,p:ReturnType<typeof make>['players'][number],n:number)=>{p.health-=n;};
const edit=(s:ReturnType<typeof make>,i:number,b:number)=>{s.grid[i]=b;s.edits.set(i,b);return true;};
test('skeleton arrows hit players and stop at walls',()=>{const s=arena(),p=s.players[0]!;mob(s,'skeleton',64.5,58.5);tickMobs(s,1/30,damage,edit);assert.equal(s.projectiles.length,1);for(let i=0;i<30;i++){s.time+=1/30;tickMobs(s,1/30,damage,edit);}assert.ok(p.health<10);p.health=10;s.projectiles=[];for(let y=6;y<10;y++)set(s,64,y,62,3);s.time+=3;tickMobs(s,1/30,damage,edit);assert.equal(s.projectiles.length,0);});
test('creeper fuse cancels behind a wall and blasts damage only within sight',()=>{const s=arena(),p=s.players[0]!;mob(s,'creeper',64.5,64.5);tickMobs(s,.7,damage,edit);assert.ok(s.creatures[0]!.fuse!>0);for(let y=6;y<9;y++)set(s,64,y,65,3);tickMobs(s,.5,damage,edit);assert.equal(s.creatures[0]!.fuse,0);assert.equal(p.health,10);for(let y=6;y<9;y++)set(s,64,y,65,0);tickMobs(s,1.5,damage,edit);assert.equal(s.creatures.length,0);assert.equal(s.blasts.length,1);assert.ok(p.health<10);});
test('spiders climb obstacles; exposed undead burn but sheltered undead survive',()=>{const s=arena();mob(s,'spider',64.5,62);set(s,64,6,63,3);set(s,64,7,63,3);for(let n=0;n<30;n++)tickMobs(s,1/30,damage,edit);assert.ok(s.creatures[0]!.y>6);mob(s,'zombie',64.5,62.5);s.time=100;tickMobs(s,1,damage,edit);assert.ok(s.creatures[0]!.health<10);s.mode='creative';set(s,64,9,Math.floor(s.creatures[0]!.z),3);const hp=s.creatures[0]!.health;tickMobs(s,1,damage,edit);assert.equal(s.creatures[0]!.health,hp);});
test('torch placement is non-solid and cannot become a floating full block',()=>{const s=arena(),p=s.players[0]!;p.inventory={[TORCH]:2};tick(s,{...neutral(),looking:true,pitch:-.7,slot:TORCH,place:true},.1);assert.ok([...s.edits.values()].includes(TORCH));assert.equal(p.inventory[TORCH],1);});
test('a visible zombie can approach from the nighttime spawn distance',()=>{const s=arena();mob(s,'zombie',64.5,42.5);tickMobs(s,1/30,damage,edit);assert.ok(s.creatures[0]!.z>42.5);});
