import { test } from 'node:test';
import assert from 'node:assert/strict';
import { rules, craft, restoreWorld, serializeWorld } from '../src/server';
import { aimedAnimal, animalLoot, feedAnimal, tickAnimals, ANIMAL_LIMIT } from '../src/animals';
import { farmUse, harvestCrop, plantCrop, tickCrops } from '../src/farming';
import { drops } from '../src/bedrock';
import { terrain } from '../src/terrain';
import { BENCH, CARROT, FARMLAND, GRAIN, POTATO, SEEDS, SHORT_GRASS, STICK, WILD_CARROT, WILD_POTATO, WOOD_HOE, index, neutral, type Animal } from '../src/model';
import { assertSerializable } from '../../../party-contract/src/serializable';
const ctx={roomId:'farm',roundId:'f',seed:1,nowMs:0,players:[{id:'p',name:'Farmer',color:'#abcabc'}]};
const make=()=>rules.create(ctx,rules.validateSettings({seed:38471}));
const edit=(s:ReturnType<typeof make>,i:number,b:number)=>{s.grid[i]=b;s.edits.set(i,b);s.revision++;return true;};
function flat(){const s=make();s.grid.fill(0);s.base.fill(0);s.edits.clear();s.animals=[];for(let x=0;x<128;x++)for(let z=0;z<128;z++)s.grid[index(x,5,z)]=1;Object.assign(s.players[0]!,{x:64.5,y:6,z:66.5,yaw:0,pitch:-.9});return s;}
function cow(id=1,x=64.5,z=64.5):Animal{return{id,kind:'cow',x,y:6,z,yaw:0,health:5,adultAt:0,loveUntil:0,breedAt:0,hitAt:0};}
test('new terrain has walk-through short grass and region-specific crop discoveries; old terrain unchanged',()=>{const s=make();assert.equal(s.terrainVersion,5);for(const id of [SHORT_GRASS,WILD_CARROT,WILD_POTATO])assert.ok(s.grid.includes(id));assert.ok(!terrain(38471,4).includes(SHORT_GRASS));assert.equal(s.animals.length,16);assert.deepEqual(new Set(s.animals.map(a=>a.kind)),new Set(['cow','sheep','pig','chicken']));});
test('seeds come from short grass, never leaves or grass blocks in new worlds',()=>{let seeds=0;for(let i=0;i<1000;i++){assert.equal(drops(1,i,42)[SEEDS],undefined);assert.equal(drops(5,i,42)[SEEDS],undefined);assert.equal(drops(20,i,42)[SEEDS],undefined);seeds+=drops(SHORT_GRASS,i,42)[SEEDS]??0;}assert.ok(seeds>80&&seeds<180);assert.deepEqual(drops(WILD_CARROT,0,0),{[CARROT]:1});assert.deepEqual(drops(WILD_POTATO,0,0),{[POTATO]:1});});
test('hoe crafting, tilling, planting, hydration, harvesting and replanting form one loop',()=>{const s=flat(),p=s.players[0]!,i=index(64,5,65);p.inventory={10:2,[STICK]:2,[SEEDS]:2};edit(s,index(63,6,66),BENCH);craft(s,p,'wood-hoe');p.selected=WOOD_HOE;assert.equal(farmUse(s,p,edit),true);assert.equal(s.grid[i],FARMLAND);p.selected=SEEDS;assert.equal(farmUse(s,p,edit),true);assert.equal(p.inventory[SEEDS],1);edit(s,index(60,5,65),6);for(let n=0;n<180;n++){s.time++;tickCrops(s,1);}assert.ok(s.farms[0]!.readyAt<=s.time);harvestCrop(s,p,i);assert.equal(p.inventory[GRAIN],1);assert.equal(p.inventory[SEEDS],3);plantCrop(s,p,i);assert.equal(s.farms.length,1);});
test('plain dirt, blocked soil, missing hoe and empty seed stacks cannot plant for free',()=>{const s=flat(),p=s.players[0]!,i=index(64,5,65);p.inventory={[SEEDS]:2};assert.throws(()=>plantCrop(s,p,i),/hoe/);p.selected=WOOD_HOE;assert.throws(()=>farmUse(s,p,edit),/hoe/);assert.equal(s.grid[i],1);edit(s,i,FARMLAND);p.selected=SEEDS;p.inventory[SEEDS]=0;assert.throws(()=>plantCrop(s,p,i),/Gather/);assert.equal(s.farms.length,0);});
test('dry growth takes six minutes, darkness and cover pause crops, roots replant themselves',()=>{const s=flat(),p=s.players[0]!,i=index(64,5,65);edit(s,i,FARMLAND);p.selected=CARROT;p.inventory={[CARROT]:1};plantCrop(s,p,i);edit(s,index(64,7,65),3);s.time=100;tickCrops(s,100);assert.equal(s.farms[0]!.readyAt,460);edit(s,index(64,7,65),0);s.time=460;harvestCrop(s,p,i);assert.equal(p.inventory[CARROT],3);plantCrop(s,p,i);assert.equal(s.farms[0]!.crop,CARROT);});
test('early harvest returns only its seed; a full inventory leaves a ripe crop untouched',()=>{const s=flat(),p=s.players[0]!,i=index(64,5,65);edit(s,i,FARMLAND);p.inventory={[SEEDS]:1};p.selected=SEEDS;plantCrop(s,p,i);harvestCrop(s,p,i);assert.equal(p.inventory[SEEDS],1);assert.equal(p.inventory[GRAIN],undefined);plantCrop(s,p,i);s.time=400;p.inventory[GRAIN]=64;assert.throws(()=>harvestCrop(s,p,i),/space/);assert.equal(s.farms.length,1);});
test('fed adults seek their own species, produce exactly one baby, and wait five minutes',()=>{const s=flat(),p=s.players[0]!,a=cow(),b=cow(2,65.5);s.animals=[a,b];p.selected=GRAIN;p.inventory={[GRAIN]:4};feedAnimal(s,p,a);feedAnimal(s,p,b);tickAnimals(s,1/30);assert.equal(s.animals.length,3);assert.equal(p.inventory[GRAIN],2);assert.equal(s.animals[2]!.adultAt,300);for(let n=0;n<30;n++)tickAnimals(s,1/30);assert.equal(s.animals.length,3);assert.throws(()=>feedAnimal(s,p,a),/again/);assert.throws(()=>feedAnimal(s,p,s.animals[2]!),/baby/);s.time=301;feedAnimal(s,p,s.animals[2]!);assert.equal(p.inventory[GRAIN],1);});
test('wrong food, duplicate feeding, babies, expired love and different species do not breed',()=>{const s=flat(),p=s.players[0]!,a=cow(),b={...cow(2,65.5),kind:'pig' as Animal['kind']};s.animals=[a,b];p.selected=SEEDS;p.inventory={[SEEDS]:4,[GRAIN]:2,[CARROT]:1};assert.throws(()=>feedAnimal(s,p,a),/wheat/);p.selected=GRAIN;feedAnimal(s,p,a);assert.throws(()=>feedAnimal(s,p,a),/Already/);p.selected=CARROT;feedAnimal(s,p,b);tickAnimals(s,1);assert.equal(s.animals.length,2);b.kind='cow';s.time=31;tickAnimals(s,1);assert.equal(s.animals.length,2);});
test('food lures animals without consuming it; walls prevent feeding and mating',()=>{const s=flat(),p=s.players[0]!,a=cow(1,64.5,62.5);s.animals=[a];p.selected=GRAIN;p.inventory={[GRAIN]:2};tickAnimals(s,.1);assert.ok(a.z>62.5);assert.equal(p.inventory[GRAIN],2);p.pitch=-.2;assert.equal(aimedAnimal(s,p)?.id,1);for(let y=6;y<9;y++)edit(s,index(64,y,64),3);assert.equal(aimedAnimal(s,p),undefined);s.animals=[{...cow(1,64.5,63.5),loveUntil:30},{...cow(2,64.5,65.5),loveUntil:30}];tickAnimals(s,1);assert.equal(s.animals.length,2);});
test('babies drop nothing and the herd cap never consumes extra breeding food',()=>{const s=flat(),p=s.players[0]!;s.animals=Array.from({length:ANIMAL_LIMIT},(_,i)=>cow(i+1));p.selected=GRAIN;p.inventory={[GRAIN]:1};assert.throws(()=>feedAnimal(s,p,s.animals[0]!),/48/);assert.equal(p.inventory[GRAIN],1);assert.deepEqual(animalLoot({...cow(),adultAt:300},0),{});});
test('save roundtrip preserves animals, growth, crop type and breeding cooldown; invalid animals are atomic',()=>{const s=make(),i=index(60,30,60);edit(s,i,FARMLAND);s.farms=[{i,crop:POTATO,plantedAt:0,readyAt:360}];s.animals[0]!.adultAt=300;s.animals[1]!.breedAt=300;const save=serializeWorld(s);assertSerializable(save);const restored=make();restoreWorld(restored,structuredClone(save));assert.deepEqual(restored.animals,s.animals);assert.deepEqual(restored.farms,s.farms);const bad=structuredClone(save);bad.animals.push({...bad.animals[0]!});assert.throws(()=>restoreWorld(s,bad),/animal/);assert.deepEqual(serializeWorld(s),save);});
test('held command retries spend one seed and leave one crop; mine harvests instead of destroying soil',()=>{const s=flat(),p=s.players[0]!,i=index(64,5,65);edit(s,i,FARMLAND);p.inventory={[SEEDS]:2};const input={...neutral(),looking:true,pitch:-.9,slot:SEEDS,command:{seq:1,type:'use' as const}};for(let n=0;n<30;n++)rules.tick(s,new Map([['p',input]]),1/30,0);assert.equal(s.farms.length,1);assert.equal(p.inventory[SEEDS],1);rules.tick(s,new Map([['p',{...input,command:null,mine:true}]]),1/30,0);assert.equal(s.farms.length,0);assert.equal(s.grid[i],FARMLAND);});

test('the crosshair selects the cow under it instead of a nearer cow standing beside it',()=>{const s=flat(),p=s.players[0]!;p.z=69.5;p.pitch=-.3;s.animals=[cow(1,64.5,67.3),cow(2,65.05,67.4)];assert.equal(aimedAnimal(s,p)?.id,1);p.yaw=-.25;assert.equal(aimedAnimal(s,p)?.id,2);});
