import { test } from 'node:test';
import assert from 'node:assert/strict';
import { rules } from './legacy';
import { craft, growTree, serializeWorld, restoreWorld } from '../src/server';
import { terrain, fits, ray } from '../src/terrain';
import { index, neutral, W, H, TOOL, BERRIES, CACHE_ITEM_LIMIT } from '../src/model';
const ctx={roomId:'room',roundId:'round',seed:99,nowMs:1000,players:Array.from({length:10},(_,i)=>({id:`p${i}`,name:`Explorer${i}`,color:'#ffaa55'}))};
const make=(mode:'survival'|'creative'='survival')=>rules.create(ctx,{mode,seed:38471,terrainVersion:2});
const tick=(s:ReturnType<typeof make>,id:string,input:ReturnType<typeof neutral>,seconds:number)=>{for(let n=0;n<Math.ceil(seconds*30);n++)rules.tick(s,new Map([[id,{...input,looking:true}]]),1/30,1000+n*1000/30);};
test('saves accept every legal world-edge position reached by movement',()=>{
  const s=make('creative'),p=s.players[0]!;
  tick(s,p.id,{...neutral(),fly:true,jump:true},100/30);
  tick(s,p.id,{...neutral(),fly:true,x:-1},428/30);
  tick(s,p.id,{...neutral(),fly:true,x:-1/30},1/30);
  assert.ok(p.x>=.29&&p.x<.3);assert.ok(fits(s.grid,p.x,p.y,p.z));
  const loaded=make('creative');restoreWorld(loaded,JSON.parse(JSON.stringify(serializeWorld(s))));
  assert.equal(loaded.players[0]!.x,p.x);assert.equal(loaded.players[0]!.y,p.y);
  for(const axis of ['x','z'] as const)for(const edge of [.29,W-.290001]){
    p[axis]=edge;assert.ok(fits(s.grid,p.x,p.y,p.z));
    restoreWorld(loaded,JSON.parse(JSON.stringify(serializeWorld(s))));assert.equal(loaded.players[0]![axis],edge);
  }
});
test('repeated death keeps all earlier supplies in the latest recovery crate, including stacks above inventory capacity',()=>{
  const s=make(),p=s.players[0]!;
  const die=(x:number)=>{p.x=x;p.y=9;p.z=70;p.food=0;p.health=1;p.hunger=35;s.time+=2;rules.tick(s,new Map(),1/30,0);};
  p.inventory={3:999,4:8,[TOOL]:1};die(70);
  p.inventory[3]=500;p.inventory[2]=2;die(72);
  assert.equal(s.caches.length,1);assert.deepEqual(s.caches[0]!.items,{2:2,3:1499,4:8});assert.equal(s.caches[0]!.x,72);assert.equal(p.inventory[TOOL],1);
  const loaded=make();restoreWorld(loaded,JSON.parse(JSON.stringify(serializeWorld(s))));assert.deepEqual(loaded.caches[0]!.items,s.caches[0]!.items);
  const q=loaded.players[0]!,cache=loaded.caches[0]!;Object.assign(q,{x:cache.x,y:cache.y,z:cache.z});rules.tick(loaded,new Map(),1/30,0);
  assert.equal(q.inventory[3],999);assert.equal(loaded.caches[0]!.items[3],500);assert.equal(q.inventory[4],8);assert.equal(q.inventory[2],2);
});
test('terrain is deterministic, seeded, bounded, and all ten camp spawns are safe',()=>{assert.deepEqual(terrain(38471),terrain(38471));assert.notDeepEqual(terrain(38471),terrain(101));const s=make();assert.equal(s.grid.length,W*W*H);for(const p of s.players)assert.ok(fits(s.grid,p.x,p.y,p.z));assert.ok(s.grid.includes(8)&&s.grid.includes(9)&&s.grid.includes(6));});
test('input rejects nonfinite look, invalid block IDs and omitted fields',()=>{for(const v of [{...neutral(),yaw:Infinity},{...neutral(),slot:14},{...neutral(),pitch:2},{x:0}])assert.throws(()=>rules.parseInput(v));assert.deepEqual(rules.parseInput(neutral()),neutral());});
test('wall collision and world bounds prevent tunnelling; jumping lands',()=>{const s=make(),p=s.players[0]!;tick(s,p.id,{...neutral(),x:-1},20);assert.ok(p.x>=.29);assert.ok(fits(s.grid,p.x,p.y,p.z));p.x=64;p.y=9;p.z=64;tick(s,p.id,neutral(),.1);tick(s,p.id,{...neutral(),jump:true},.2);assert.ok(p.y>9);tick(s,p.id,neutral(),2);assert.ok(Math.abs(p.y-9)<.11);});
test('ray stops at nearest solid surface and reports adjacent placement cell',()=>{const grid=new Uint8Array(W*W*H);grid[index(4,3,4)]=3;grid[index(4,3,2)]=9;const hit=ray(grid,4.5,3.5,7,0,0);assert.equal(hit?.i,index(4,3,4));assert.deepEqual(hit?.previous,{x:4,y:3,z:5});assert.equal(ray(grid,4.5,3.5,12,0,0),null);});
test('hand mining conserves resource and two miners cannot duplicate one block',()=>{const s=make(),p=s.players[0]!,q=s.players[1]!;s.grid[index(62,10,62)]=4;for(const a of [p,q]){a.x=62.5;a.y=9;a.z=64;a.yaw=0;a.pitch=0;}for(let n=0;n<25;n++)rules.tick(s,new Map([[p.id,{...neutral(),mine:true}],[q.id,{...neutral(),mine:true}]]),1/30,n*1000/30);assert.equal(s.grid[index(62,10,62)],0);assert.equal((p.inventory[4]??0)+(q.inventory[4]??0),1);});
test('tool tiers enforce wood to stone to copper to crystal',()=>{const s=make(),p=s.players[0]!;assert.throws(()=>craft(s,p,'twig'));p.inventory[4]=4;craft(s,p,'twig');assert.equal(p.inventory[4],2);assert.equal(p.tier,1);assert.throws(()=>craft(s,p,'twig'));p.inventory[3]=4;craft(s,p,'stone');assert.equal(p.tier,2);p.inventory[8]=4;craft(s,p,'copper');assert.equal(p.tier,3);assert.equal(p.inventory[4],0);assert.throws(()=>craft(s,p,'fake'));});
test('placement cannot overlap players and spends exactly one item per placed block',()=>{const s=make(),p=s.players[0]!;p.x=64.5;p.z=64.5;p.y=9;p.inventory[10]=10;tick(s,p.id,{...neutral(),pitch:-1.4,place:true},.1);assert.equal(p.built,0);s.players.slice(1).forEach(a=>a.connected=false);p.z=65.8;tick(s,p.id,{...neutral(),pitch:-.6,place:true},.4);assert.ok(p.built>=1);assert.equal(p.inventory[10],10-p.built);});
test('disconnect preserves inventory and clears mining; absent input cannot mine',()=>{const s=make(),p=s.players[0]!;p.inventory[4]=7;p.progress=.5;rules.onPresenceChange(s,p.id,false,0);assert.equal(p.progress,0);tick(s,p.id,{...neutral(),mine:true,x:1},1);assert.equal(p.inventory[4],7);assert.equal(p.x,64.5);rules.onPresenceChange(s,p.id,true,0);assert.equal(p.inventory[4],7);});
test('save roundtrip preserves world and inventory; invalid import never mutates live state',()=>{const s=make(),p=s.players[0]!;p.inventory[4]=12;s.edits.set(index(20,15,20),10);s.grid[index(20,15,20)]=10;s.revision++;const raw=serializeWorld(s),loaded=make();restoreWorld(loaded,JSON.parse(JSON.stringify(raw)));assert.deepEqual(loaded.grid,s.grid);assert.deepEqual(loaded.players[0]!.inventory,p.inventory);const before=serializeWorld(loaded);for(const patch of [{edits:[[0,0]]},{edits:[[999999,2]]},{players:[{...raw.players[0],inventory:{4:-1}}]},{seed:NaN}]){assert.throws(()=>restoreWorld(loaded,{...raw,...patch}));assert.deepEqual(serializeWorld(loaded),before);}});
test('public projection never exposes inventories and edits stay sparse',()=>{const s=make(),v=rules.publicView(s,{nowMs:0,phase:'playing'});assert.equal(v.edits.length,0);assert.ok(!('inventory'in v.players[0]!));assert.ok(JSON.stringify(v).length<6000);});
test('creative construction uses no resource, beacon can be placed, session stays open',()=>{const s=make('creative'),p=s.players[0]!;s.players.slice(1).forEach(a=>a.connected=false);p.x=64.5;p.y=9;p.z=66.5;const before=p.inventory[13];tick(s,p.id,{...neutral(),slot:13,pitch:-.6,place:true},.4);assert.ok(s.beacon);assert.equal(p.inventory[13],before);assert.equal(rules.outcome(s).complete,false);});
test('hunger death respawns with tools and leaves a recoverable cache',()=>{const s=make(),p=s.players[0]!;p.health=1;p.food=0;p.inventory={[TOOL]:1,4:8};p.hunger=34.99;tick(s,p.id,neutral(),.1);assert.equal(p.health,8);assert.equal(p.inventory[TOOL],1);assert.ok(s.caches.length===1||p.inventory[4]===8);assert.ok(fits(s.grid,p.x,p.y,p.z));});
test('boundary ray hits cannot alias an unrelated voxel',()=>{const s=make('creative'),p=s.players[0]!;p.x=.31;p.y=24;p.z=32;const before=s.grid.slice();tick(s,p.id,{...neutral(),yaw:Math.PI/2,mine:true},.15);assert.deepEqual(s.grid,before);});
test('death and imported blocked positions find safe footing above a built camp',()=>{const s=make(),p=s.players[0]!;for(let x=60;x<=68;x++)for(let z=60;z<=68;z++)for(let y=9;y<=13;y++){s.grid[index(x,y,z)]=10;s.edits.set(index(x,y,z),10);}p.health=1;p.food=0;p.hunger=34.99;tick(s,p.id,neutral(),.05);assert.ok(fits(s.grid,p.x,p.y,p.z));assert.ok(p.y>=14);const saved=serializeWorld(s);saved.players[0]!.y=9;const loaded=rules.loadSave!(ctx,saved,{mode:'survival',seed:38471});assert.ok(fits(loaded.state.grid,loaded.state.players[0]!.x,loaded.state.players[0]!.y,loaded.state.players[0]!.z));});
test('creative flight rises, remains airborne on released input and descends deliberately',()=>{const s=make('creative'),p=s.players[0]!;tick(s,p.id,{...neutral(),fly:true,jump:true},1);assert.ok(p.y>15);const y=p.y;rules.tick(s,new Map(),1/30,0);assert.equal(p.y,y);tick(s,p.id,{...neutral(),fly:true,down:true},.5);assert.ok(p.y<y);});
test('version-one saves migrate coordinates and tool IDs without losing placed blocks',()=>{const s=make(),old={format:'blockwild',version:1,seed:38471,mode:'survival',time:45,beacon:false,edits:[[20+20*64+15*4096,10]],players:[{name:'Explorer0',x:32.5,y:9,z:34.5,health:10,food:8,mined:20,built:1,inventory:{4:12,16:1,19:5}}]};restoreWorld(s,old);assert.equal(s.terrainVersion,1);assert.equal(s.grid[index(52,15,52)],10);assert.equal(s.players[0]!.x,64.5);assert.equal(s.players[0]!.inventory[TOOL],1);assert.equal(s.players[0]!.inventory[BERRIES],5);assert.equal(serializeWorld(s).version,2);});
test('all 16384 worst-case edits and maximum roster fit the 256KiB save envelope',()=>{const s=make('creative');for(let i=0;i<16384;i++)s.edits.set(W*W*H-1-i,23);for(const p of s.players){p.name='SixteenCharacter';p.mined=p.built=1e9;p.x=120.123456789;p.z=120.123456789;}s.time=1e9;const bytes=Buffer.byteLength(JSON.stringify(serializeWorld(s)));assert.ok(bytes<256*1024,`${bytes} bytes`);});
test('held crafting commands acknowledge once, reject stale duplicates and exceed 256 commands',()=>{const s=make(),p=s.players[0]!;p.inventory[4]=2;const input={...neutral(),command:{seq:1,type:'craft' as const,recipe:'planks'}};tick(s,p.id,input,1);assert.equal(p.inventory[10],4);assert.equal(p.inventory[4],1);assert.equal(p.commandAck,1);tick(s,p.id,{...neutral(),command:{seq:2,type:'craft',recipe:'copper'}},.1);assert.equal(p.commandAck,2);assert.match(p.commandResult,/Need/);tick(s,p.id,input,.1);assert.equal(p.inventory[10],4);s.mode='creative';for(let seq=3;seq<=400;seq++)rules.tick(s,new Map([[p.id,{...neutral(),command:{seq,type:'craft',recipe:'planks'}}]]),1/30,seq);assert.equal(p.commandAck,400);assert.equal(rules.playerView(s,p.id,{nowMs:0,phase:'playing'}).commandAck,400);});
test('save player fields cannot overwrite roster identity, presence or command acknowledgements',()=>{const s=make(),raw=serializeWorld(s),before=serializeWorld(s);for(const extra of [{id:'attacker'},{connected:false},{commandAck:999},{color:'#000000'},{tier:99}]){const bad={...raw,players:raw.players.map((p,i)=>i===0?{...p,...extra}:p)};assert.throws(()=>restoreWorld(s,bad));assert.deepEqual(serializeWorld(s),before);assert.equal(s.players[0]!.id,'p0');assert.equal(s.players[0]!.commandAck,0);assert.equal(s.players[0]!.connected,true);}});
test('duplicate names restore each inventory and cache once in original join order',()=>{const s=make();s.players[0]!.name=s.players[1]!.name='Twins';s.players[0]!.inventory[4]=99;s.players[1]!.inventory[4]=21;s.caches.push({id:'c',owner:s.players[0]!.id,x:64,y:9,z:64,items:{4:5}});const raw=serializeWorld(s);restoreWorld(s,raw);assert.equal(s.players[0]!.inventory[4],99);assert.equal(s.players[1]!.inventory[4],21);assert.equal(s.caches.length,1);assert.equal(s.caches[0]!.owner,s.players[0]!.id);assert.equal(s.caches[0]!.items[4],5);assert.equal(s.players[0]!.id,'p0');assert.equal(s.players[1]!.id,'p1');});
test('Grow tree spends exactly one earth/berry, creates renewable timber, and survives save roundtrip',()=>{const s=make(),p=s.players[0]!;p.pitch=-.65;p.inventory[2]=1;const before=s.grid.filter(b=>b===4).length,berries=p.inventory[BERRIES]!;growTree(s,p);assert.equal(p.inventory[2],0);assert.equal(p.inventory[BERRIES],berries-1);assert.equal(s.grid.filter(b=>b===4).length,before+5);assert.ok(p.built>5);const loaded=make();restoreWorld(loaded,serializeWorld(s));assert.deepEqual(loaded.grid,s.grid);assert.deepEqual(loaded.players[0]!.inventory,p.inventory);});
test('blocked, occupied, out-of-bounds and full-budget growth is atomic',()=>{for(const kind of ['block','player','bounds','budget']){const s=make(),p=s.players[0]!;p.pitch=-.65;p.inventory[2]=1;if(kind==='block')s.grid[index(62,11,64)]=3;if(kind==='player'){s.players[1]!.x=64.5;s.players[1]!.y=10;s.players[1]!.z=64.5;}if(kind==='bounds'){p.x=1.5;for(let x=0;x<4;x++)for(let z=63;z<68;z++)for(let y=8;y<16;y++)s.grid[index(x,y,z)]=y===8?2:0;}if(kind==='budget')for(let i=0;i<16384;i++)s.edits.set(W*W+i,23);const grid=s.grid.slice(),inventory={...p.inventory},edits=[...s.edits],revision=s.revision;assert.throws(()=>growTree(s,p),Error,kind);assert.deepEqual(s.grid,grid);assert.deepEqual(p.inventory,inventory);assert.deepEqual([...s.edits],edits);assert.equal(s.revision,revision);}});
test('held Grow tree sequence is accepted once despite repeated heartbeat delivery',()=>{const s=make(),p=s.players[0]!;p.inventory[2]=2;tick(s,p.id,{...neutral(),pitch:-.65,command:{seq:1,type:'grow'}},.5);assert.equal(p.commandAck,1);assert.equal(p.inventory[2],1);assert.equal(p.inventory[BERRIES],4);const built=p.built;tick(s,p.id,{...neutral(),pitch:-.65,command:{seq:1,type:'grow'}},.5);assert.equal(p.built,built);assert.equal(p.inventory[2],1);});
test('save inventories and recovery caches reject leading-zero material aliases',()=>{const s=make(),raw=serializeWorld(s);for(const kind of ['inventory','cache']){const bad=structuredClone(raw);if(kind==='inventory')Object.assign(bad.players[0]!.inventory,{'0004':999});else bad.caches=[{ownerName:s.players[0]!.name,x:64,y:9,z:64,items:Object.assign({} as Record<number,number>,{'0004':999})}];assert.throws(()=>restoreWorld(s,bad));assert.deepEqual(serializeWorld(s),raw);}});
test('brambles can hit adjacent explorers but cannot attack through distant floors or ceilings',()=>{for(const high of [false,true]){const s=make(),p=s.players[0]!;p.x=64.5;p.y=high?20:9;p.z=64.5;s.time=160;s.creatures=[{id:1,x:65,y:9,z:64.5,health:6,hitAt:160}];rules.tick(s,new Map(),1/30,0);assert.equal(p.health,high?10:9);}});
test('multi-output crafts reject insufficient stack capacity before spending resources',()=>{const s=make(),p=s.players[0]!;p.inventory[4]=2;p.inventory[10]=998;assert.throws(()=>craft(s,p,'planks'),/Make room/);assert.equal(p.inventory[4],2);assert.equal(p.inventory[10],998);p.inventory[10]=995;craft(s,p,'planks');assert.equal(p.inventory[10],999);assert.equal(p.inventory[4],1);p.inventory[8]=1;p.inventory[12]=998;assert.throws(()=>craft(s,p,'lantern'),/Make room/);assert.equal(p.inventory[4],1);assert.equal(p.inventory[8],1);p.inventory[12]=997;craft(s,p,'lantern');assert.equal(p.inventory[12],999);assert.equal(p.inventory[4],0);assert.equal(p.inventory[8],0);});
test('Survival mining checks actual leaf yield capacity; Creative still mines full stacks',()=>{for(const mode of ['survival','creative'] as const){const s=make(mode),p=s.players[0]!;p.x=62.5;p.y=9;p.z=64;s.grid[index(62,10,62)]=5;p.inventory[BERRIES]=999;tick(s,p.id,{...neutral(),mine:true},.5);assert.equal(s.grid[index(62,10,62)],mode==='survival'?5:0);assert.equal(p.inventory[BERRIES],999);if(mode==='survival'){assert.equal(p.mined,0);p.inventory[BERRIES]=998;tick(s,p.id,{...neutral(),mine:true},.7);assert.equal(s.grid[index(62,10,62)],0);assert.equal(p.inventory[BERRIES],999);assert.equal(p.mined,1);}}});
test('recovery transfers only available room and retains every remaining item across repeated ticks and saves',()=>{const s=make(),p=s.players[0]!;p.inventory[3]=998;p.inventory[4]=1;s.caches.push({id:'supplies',owner:p.id,x:p.x,y:p.y,z:p.z,items:{3:5}});rules.tick(s,new Map(),1/30,0);assert.equal(p.inventory[3],999);assert.equal(s.caches[0]!.items[3],4);for(let i=0;i<10;i++)rules.tick(s,new Map(),1/30,0);assert.equal(p.inventory[3]+s.caches[0]!.items[3],1003);assert.equal(serializeWorld(s).caches[0]!.items[3],4);craft(s,p,'stone');assert.equal(p.inventory[3],995);rules.tick(s,new Map(),1/30,0);assert.equal(p.inventory[3],999);assert.equal(s.caches.length,0);rules.tick(s,new Map(),1/30,0);assert.equal(p.inventory[3],999);});

test('cache capacity keeps overflow with the explorer and rejects unsafe or duplicate imported caches atomically',()=>{
  const s=make(),p=s.players[0]!;p.inventory={3:2};s.caches=[{id:'full',owner:p.id,x:70,y:9,z:70,items:{3:CACHE_ITEM_LIMIT}}];p.x=72;p.y=9;p.z=70;p.food=0;p.health=1;p.hunger=35;
  rules.tick(s,new Map(),1/30,0);assert.equal(p.inventory[3],2);assert.equal(s.caches[0]!.items[3],CACHE_ITEM_LIMIT);assert.equal(s.caches[0]!.x,72);
  const raw=serializeWorld(s),loaded=make();restoreWorld(loaded,JSON.parse(JSON.stringify(raw)));assert.equal(loaded.players[0]!.inventory[3],2);
  for(const caches of [[{...raw.caches[0]!,items:{3:Number.MAX_SAFE_INTEGER}}],[raw.caches[0]!,raw.caches[0]!]]){const before=serializeWorld(loaded);assert.throws(()=>restoreWorld(loaded,{...raw,caches}));assert.deepEqual(serializeWorld(loaded),before);}
});

