/* Quiz Panic content banks (server only; never imported by client code). Every question and category is original.
   Trivia rows read 'Question | right answer | wrong | wrong | wrong'; the server shuffles the options. */

export type Trivia = { category: string; text: string; answer: string; wrong: [string, string, string]; adult?: true };
export type Category = { name: string; yes: string[]; no: string[]; adult?: true };

const bank = (category: string, rows: string[], adult = false): Trivia[] => rows.map(row => {
  const [text, answer, ...wrong] = row.split(' | ');
  return { category, text: text!, answer: answer!, wrong: wrong as [string, string, string], ...(adult ? { adult: true as const } : {}) };
});

export const TRIVIA: readonly Trivia[] = [
  ...bank('Things That Go Bump', [
    'Before pumpkins caught on, which vegetable did people in Ireland carve into lanterns? | Turnip | Carrot | Cabbage | Potato',
    'What is a group of crows called? | A murder | A coven | A haunting | A choir',
    'A fear of spiders is called what? | Arachnophobia | Agoraphobia | Claustrophobia | Acrophobia',
    'Bram Stoker’s 1897 novel is named after which count? | Dracula | Orlok | Frankenstein | Monte Cristo',
    'Who wrote the novel Frankenstein? | Mary Shelley | Bram Stoker | Edgar Allan Poe | Jane Austen',
    'In Mary Shelley’s novel, who or what is Frankenstein? | The scientist | The monster | The village | The castle',
    'Which bird keeps saying “Nevermore” in a famous Edgar Allan Poe poem? | A raven | A crow | An owl | A parrot',
    'Which mammal is the only one capable of true flight? | Bat | Flying squirrel | Sugar glider | Flying lemur',
    'What do vampire bats feed on? | Blood | Fruit | Nectar | Beetles',
    'On which date is Halloween celebrated? | 31 October | 1 November | 30 October | 13 October',
    'In folklore, werewolves transform under which phase of the moon? | Full moon | New moon | Half moon | Crescent moon',
    'In many old stories, what is the surest way to stop a werewolf? | A silver bullet | A garlic necklace | A bucket of water | A loud whistle',
    'During mummification, which organ did ancient Egyptians remove through the nose? | Brain | Heart | Liver | Lungs',
    'What is the name of the three-headed dog guarding the Greek underworld? | Cerberus | Hydra | Orthrus | Chimera',
    'In Irish folklore, what is a banshee famous for? | Wailing | Dancing | Granting wishes | Stealing shoes',
    'The region of Transylvania is in which country? | Romania | Hungary | Bulgaria | Poland',
    'Triskaidekaphobia is the fear of which number? | 13 | 666 | 4 | 7',
    'In Japan, which number is often avoided because it sounds like the word for death? | 4 | 9 | 13 | 7',
    'In Washington Irving’s Sleepy Hollow, who haunts the road at night? | The Headless Horseman | The Pale Knight | The Midnight Miller | The Grey Lady',
    'Who wrote A Christmas Carol, the ghost story starring Ebenezer Scrooge? | Charles Dickens | Mark Twain | Jane Austen | Oscar Wilde',
    'Who wrote the comic story The Canterville Ghost? | Oscar Wilde | Charles Dickens | Bram Stoker | Lewis Carroll',
    'Which deep-sea fish dangles a glowing lure to catch prey in the dark? | Anglerfish | Swordfish | Pufferfish | Catfish',
    'Which creature’s name comes from an Arabic word for a desert demon? | Ghoul | Goblin | Zombie | Vampire',
    'What is the Mexican festival honouring loved ones who have died? | Day of the Dead | Night of Lanterns | Feast of Bones | Festival of Ghosts',
    'In folklore, what do witches traditionally ride through the sky? | Broomsticks | Rakes | Ladders | Mops',
    'Which dwarf planet is named after the Roman god of the underworld? | Pluto | Ceres | Eris | Haumea',
  ]),
  ...bank('Creature Feature', [
    'What is a baby kangaroo called? | Joey | Kit | Cub | Calf',
    'How many legs does a spider have? | 8 | 6 | 10 | 12',
    'What is the largest animal known to have ever lived? | Blue whale | African elephant | Megalodon | Sperm whale',
    'Which animal is nicknamed the “ship of the desert”? | Camel | Horse | Llama | Donkey',
    'Which bird is the fastest animal in a dive? | Peregrine falcon | Golden eagle | Ostrich | Swift',
    'What is the largest living bird? | Ostrich | Emu | Albatross | Condor',
    'What is a group of lions called? | A pride | A pack | A herd | A gaggle',
    'How many hearts does an octopus have? | 3 | 1 | 2 | 8',
    'Which of these mammals lays eggs? | Platypus | Beaver | Otter | Mole',
    'A tadpole grows up to become which animal? | Frog | Dragonfly | Lizard | Snail',
    'What colour is a polar bear’s skin? | Black | White | Pink | Grey',
    'How do honeybees tell each other where to find flowers? | A waggle dance | Changing colour | Clicking their jaws | Drumming on wood',
    'What is a male duck called? | Drake | Gander | Cob | Rooster',
    'Which reptile can move each eye independently and change colour? | Chameleon | Iguana | Gecko | Komodo dragon',
    'What is the largest species of big cat? | Tiger | Lion | Jaguar | Leopard',
    'A caterpillar forms a chrysalis before turning into what? | A butterfly | A beetle | A bee | A dragonfly',
    'Which mythical animal is the national animal of Scotland? | Unicorn | Dragon | Griffin | Phoenix',
    'What is a baby swan called? | Cygnet | Gosling | Duckling | Fawn',
    'How many legs does an insect have? | 6 | 4 | 8 | 10',
    'What is the fastest land animal? | Cheetah | Lion | Pronghorn | Greyhound',
    'Which animal is the tallest in the world? | Giraffe | Elephant | Ostrich | Moose',
    'What do you call an animal that eats only plants? | Herbivore | Carnivore | Omnivore | Insectivore',
    'Which sea creature has eight arms and can squirt ink? | Octopus | Starfish | Jellyfish | Sea urchin',
    'Where does a koala spend most of its time? | In eucalyptus trees | In burrows | In rivers | In caves',
    'A snail glides along on a single what? | Foot | Fin | Wheel | Tentacle',
    'Which bird can fly backwards? | Hummingbird | Sparrow | Penguin | Pelican',
  ]),
  ...bank('Lost in Space', [
    'Which planet is closest to the Sun? | Mercury | Venus | Mars | Earth',
    'Which planet is known as the Red Planet? | Mars | Jupiter | Venus | Saturn',
    'What is the largest planet in our solar system? | Jupiter | Saturn | Neptune | Earth',
    'Roughly how long does Earth take to orbit the Sun? | 365 days | 30 days | 24 hours | 100 days',
    'Who was the first person to walk on the Moon? | Neil Armstrong | Buzz Aldrin | Yuri Gagarin | John Glenn',
    'Who was the first human to travel into space? | Yuri Gagarin | Neil Armstrong | Alan Shepard | Valentina Tereshkova',
    'What is the name of our galaxy? | The Milky Way | Andromeda | The Whirlpool | The Sombrero',
    'Which planet rolls around the Sun tipped almost on its side? | Uranus | Neptune | Mars | Mercury',
    'Which planet has the hottest surface? | Venus | Mercury | Mars | Jupiter',
    'What is a space rock called once it lands on Earth? | Meteorite | Meteor | Comet | Asteroid belt',
    'Compared with Earth, how strong is gravity on the Moon? | About one sixth | Twice as strong | The same | About half',
    'What was the name of the first artificial satellite, launched in 1957? | Sputnik 1 | Explorer 1 | Vostok 1 | Telstar',
    'About how long does sunlight take to reach Earth? | 8 minutes | 8 seconds | 8 hours | 8 days',
    'On which planet is one day longer than one year? | Venus | Mercury | Mars | Neptune',
    'The Great Red Spot is a giant storm on which planet? | Jupiter | Mars | Saturn | Neptune',
    'What is a “shooting star” really? | A meteor | A falling star | A comet | A satellite',
    'What kind of object is the Sun? | A star | A planet | A comet | A nebula',
    'Which planet is famous for its bright, wide rings? | Saturn | Mars | Venus | Mercury',
    'What do astronomers call a huge cloud of gas and dust in space? | Nebula | Quasar | Pulsar | Galaxy',
    'Which planet is farthest from the Sun? | Neptune | Uranus | Saturn | Jupiter',
  ]),
  ...bank('Globe Trotter', [
    'What is the capital of Australia? | Canberra | Sydney | Melbourne | Perth',
    'What is the capital of Canada? | Ottawa | Toronto | Vancouver | Montreal',
    'Which is the longest river in Africa? | Nile | Congo | Niger | Zambezi',
    'What is the largest ocean on Earth? | Pacific | Atlantic | Indian | Arctic',
    'What is the largest hot desert in the world? | Sahara | Gobi | Kalahari | Mojave',
    'Which is the highest mountain above sea level? | Mount Everest | K2 | Kilimanjaro | Mont Blanc',
    'Which country is shaped like a boot? | Italy | Greece | Spain | Portugal',
    'What is the capital of Japan? | Tokyo | Kyoto | Osaka | Hiroshima',
    'In which country is the ancient Inca city of Machu Picchu? | Peru | Mexico | Chile | Bolivia',
    'Which river flows through Paris? | Seine | Thames | Danube | Rhine',
    'Which river flows through London? | Thames | Seine | Severn | Tyne',
    'What is the smallest country in the world? | Vatican City | Monaco | San Marino | Liechtenstein',
    'Which country has a red maple leaf on its flag? | Canada | Japan | Switzerland | Denmark',
    'The Great Barrier Reef lies off the coast of which country? | Australia | Brazil | Indonesia | Philippines',
    'What is the capital of Egypt? | Cairo | Alexandria | Giza | Luxor',
    'Which US state is made up entirely of islands? | Hawaii | Alaska | Florida | Rhode Island',
    'Mount Kilimanjaro is in which country? | Tanzania | Kenya | Uganda | Ethiopia',
    'What is the capital of Iceland? | Reykjavík | Oslo | Helsinki | Copenhagen',
    'Which ocean lies between Africa and Australia? | Indian Ocean | Pacific Ocean | Atlantic Ocean | Arctic Ocean',
    'Venice is famous for streets made of what? | Canals | Bridges of rope | Glass | Cobbled tunnels',
    'Which continent is the coldest? | Antarctica | Europe | Asia | North America',
    'The Andes mountains run along which continent? | South America | Africa | Asia | Europe',
    'What is the capital of Spain? | Madrid | Barcelona | Seville | Lisbon',
    'Which country is home to the city of Marrakech? | Morocco | Egypt | Tunisia | Algeria',
  ]),
  ...bank('Midnight Snacks', [
    'Guacamole is mainly made from which fruit? | Avocado | Lime | Cucumber | Green pepper',
    'Marzipan is made mostly from which nut? | Almond | Peanut | Walnut | Cashew',
    'Sushi rice is seasoned with which ingredient? | Vinegar | Milk | Honey | Coffee',
    'What is the main ingredient in hummus? | Chickpeas | Lentils | Black beans | Peas',
    'Which fruit wears its seeds on the outside? | Strawberry | Raspberry | Blueberry | Kiwi',
    'Which spice gives many curries a golden-yellow colour? | Turmeric | Paprika | Cinnamon | Nutmeg',
    'Tofu is made from which bean? | Soybean | Kidney bean | Broad bean | Black-eyed pea',
    'Sauerkraut is made by fermenting which vegetable? | Cabbage | Cucumber | Carrot | Onion',
    'Which chemical gives chilli peppers their heat? | Capsaicin | Caffeine | Lactose | Gluten',
    'Popcorn is made from which grain? | Corn | Rice | Wheat | Oats',
    'Which spice is the most expensive by weight? | Saffron | Vanilla | Cardamom | Black pepper',
    'A raisin is a dried what? | Grape | Plum | Fig | Apricot',
    'A prune is a dried what? | Plum | Grape | Date | Cherry',
    'Which food can stay edible for thousands of years if sealed well? | Honey | Bread | Cheese | Butter',
    'Kimchi is a famous dish from which country? | Korea | Japan | Thailand | Vietnam',
    'Paella is a rice dish from which country? | Spain | Italy | Mexico | Greece',
    'Which pastry is shaped like a crescent? | Croissant | Éclair | Strudel | Scone',
    'Which nut grows underground? | Peanut | Hazelnut | Walnut | Pecan',
    'What is the main ingredient of a traditional omelette? | Eggs | Potatoes | Rice | Bread',
    'Which squash is most often carved into a jack-o’-lantern? | Pumpkin | Butternut squash | Courgette | Spaghetti squash',
    'Pesto is traditionally made with which herb? | Basil | Mint | Parsley | Rosemary',
    'Which drink is brewed from roasted beans? | Coffee | Tea | Lemonade | Milk',
  ]),
  ...bank('Mad Science', [
    'What is the chemical symbol for gold? | Au | Ag | Go | Gd',
    'At sea level, water boils at what temperature? | 100 °C | 90 °C | 120 °C | 80 °C',
    'Which gas do plants take in from the air to make food? | Carbon dioxide | Oxygen | Nitrogen | Helium',
    'Which gas makes up most of Earth’s air? | Nitrogen | Oxygen | Carbon dioxide | Argon',
    'Which natural material is the hardest? | Diamond | Granite | Quartz | Iron',
    'What is the chemical symbol for iron? | Fe | Ir | In | I',
    'Bees make honey from what? | Nectar | Pollen | Tree sap | Morning dew',
    'Which metal is a liquid at room temperature? | Mercury | Lead | Tin | Aluminium',
    'Sound travels fastest through which of these? | Steel | Water | Air | Empty space',
    'At what temperature does water freeze on the Fahrenheit scale? | 32 °F | 0 °F | 100 °F | 212 °F',
    'Who came up with the theory of relativity? | Albert Einstein | Isaac Newton | Galileo Galilei | Marie Curie',
    'Who discovered penicillin in 1928? | Alexander Fleming | Louis Pasteur | Marie Curie | Edward Jenner',
    'Iron rusts when it reacts with oxygen and what? | Water | Salt | Sunlight | Sand',
    'Which colour of visible light has the longest wavelength? | Red | Violet | Green | Blue',
    'A pH of 7 means a liquid is what? | Neutral | Acidic | Alkaline | Radioactive',
    'What is H₂O better known as? | Water | Salt | Hydrogen peroxide | Ammonia',
    'What is the centre of an atom called? | Nucleus | Electron | Orbit | Molecule',
    'Which scientist is famous for laws of motion and gravity? | Isaac Newton | Charles Darwin | Thomas Edison | Nikola Tesla',
    'What do you call a substance that speeds up a chemical reaction without being used up? | Catalyst | Solvent | Fuel | Isotope',
    'Which force pulls objects toward the centre of the Earth? | Gravity | Magnetism | Friction | Static',
    'What is the chemical symbol for sodium? | Na | So | Sd | S',
    'Dry ice is the solid form of which gas? | Carbon dioxide | Oxygen | Nitrogen | Hydrogen',
  ]),
  ...bank('Skeleton Crew', [
    'How many bones are in an adult human body? | 206 | 106 | 306 | 212',
    'What is the largest organ of the human body? | Skin | Liver | Brain | Lungs',
    'Which is the longest bone in the human body? | Femur | Tibia | Humerus | Fibula',
    'Where is the smallest bone in the human body? | In the ear | In the toe | In the nose | In the finger',
    'How many teeth does a full adult set usually have, wisdom teeth included? | 32 | 28 | 24 | 36',
    'Which blood cells fight infections? | White blood cells | Red blood cells | Platelets | Plasma cells',
    'What is the coloured part of the eye called? | Iris | Pupil | Retina | Cornea',
    'Which bean-shaped organs filter waste out of your blood? | Kidneys | Lungs | Tonsils | Appendix',
    'Which dome-shaped muscle under your lungs helps you breathe? | Diaphragm | Biceps | Abdominal | Trachea',
    'When you hit your “funny bone”, what are you really hitting? | A nerve | A bone | A muscle | A tendon',
    'How many chambers does the human heart have? | 4 | 2 | 3 | 6',
    'Sunlight on your skin helps your body make which vitamin? | Vitamin D | Vitamin C | Vitamin A | Vitamin K',
    'What is the common name for the patella? | Kneecap | Collarbone | Shoulder blade | Shin bone',
    'Which body part protects the brain? | Skull | Ribcage | Pelvis | Spine',
    'Which tiny tubes carry blood between arteries and veins? | Capillaries | Tendons | Nerves | Ligaments',
  ]),
  ...bank('History Mystery', [
    'Who was the first President of the United States? | George Washington | Abraham Lincoln | Thomas Jefferson | John Adams',
    'In which year did the Titanic sink? | 1912 | 1905 | 1921 | 1898',
    'Which of the Seven Wonders of the Ancient World still stands? | Great Pyramid of Giza | Colossus of Rhodes | Hanging Gardens of Babylon | Lighthouse of Alexandria',
    'Who painted the Mona Lisa? | Leonardo da Vinci | Michelangelo | Raphael | Vincent van Gogh',
    'Which Roman town was buried by the eruption of Mount Vesuvius in AD 79? | Pompeii | Ostia | Ravenna | Verona',
    'In which city was the Colosseum built? | Rome | Athens | Naples | Istanbul',
    'Who was the first woman to win a Nobel Prize? | Marie Curie | Rosalind Franklin | Ada Lovelace | Florence Nightingale',
    'In which year did the Berlin Wall fall? | 1989 | 1979 | 1991 | 1969',
    'Which ship carried the Pilgrims to America in 1620? | Mayflower | Santa María | Endeavour | Beagle',
    'Which Egyptian boy king’s tomb was found almost intact in 1922? | Tutankhamun | Ramesses II | Khufu | Akhenaten',
    'Who was the first person to fly solo nonstop across the Atlantic? | Charles Lindbergh | Amelia Earhart | Orville Wright | Howard Hughes',
    'Near which town did the Wright brothers make their first powered flight in 1903? | Kitty Hawk | Paris | Chicago | Dayton',
    'Which British queen reigned for 63 years, from 1837 to 1901? | Victoria | Elizabeth I | Mary I | Anne',
    'Who was the first emperor of Rome? | Augustus | Julius Caesar | Nero | Caligula',
    'Which people sailed longships and raided coasts from Scandinavia? | Vikings | Romans | Normans | Celts',
    'Which wall did the Romans build across northern England? | Hadrian’s Wall | The Great Wall | Offa’s Dyke | The Antonine Wall',
    'Who was the famous nurse nicknamed “The Lady with the Lamp”? | Florence Nightingale | Mary Seacole | Edith Cavell | Clara Barton',
    'In which year did humans first land on the Moon? | 1969 | 1959 | 1975 | 1965',
    'What did ancient Egyptians use to write on, made from a river reed? | Papyrus | Parchment | Bamboo | Clay tablets',
  ]),
  ...bank('Sporting Spirits', [
    'How many players does a football (soccer) team have on the pitch? | 11 | 9 | 10 | 12',
    'How many rings are on the Olympic flag? | 5 | 4 | 6 | 7',
    'In tennis, what is a score of zero called? | Love | Nil | Duck | Zip',
    'How many points is a touchdown worth in American football? | 6 | 3 | 7 | 5',
    'Which sport uses a shuttlecock? | Badminton | Squash | Table tennis | Volleyball',
    'In golf, what is one stroke under par called? | Birdie | Eagle | Bogey | Albatross',
    'In which sport might you see a slam dunk? | Basketball | Volleyball | Netball | Tennis',
    'How many players per team are on a basketball court? | 5 | 6 | 7 | 4',
    'In ten-pin bowling, what is three strikes in a row called? | A turkey | A hat-trick | A triple | A gobbler',
    'About how long is a marathon? | 42 km | 21 km | 50 km | 10 km',
    'In cricket, how many balls are in a standard over? | 6 | 5 | 8 | 10',
    'What is the highest score possible with three darts? | 180 | 150 | 160 | 200',
    'How many holes does a standard round of golf have? | 18 | 9 | 12 | 21',
    'Which martial art’s name means “the gentle way”? | Judo | Karate | Taekwondo | Kung fu',
    'In which sport do players use a puck? | Ice hockey | Curling | Polo | Lacrosse',
    'How many pins stand at the end of a ten-pin bowling lane? | 10 | 9 | 12 | 8',
    'How long is an Olympic swimming pool? | 50 metres | 25 metres | 100 metres | 75 metres',
    'A boxing match takes place in a ring that is actually what shape? | Square | Circle | Octagon | Triangle',
  ]),
  ...bank('Haunted Opera House', [
    'How many keys does a standard piano have? | 88 | 76 | 66 | 100',
    'How many strings does a standard guitar have? | 6 | 4 | 5 | 8',
    'Which famous composer kept writing music after losing his hearing? | Beethoven | Mozart | Bach | Chopin',
    'How many lines are in a musical staff? | 5 | 4 | 6 | 7',
    'What is a violin usually played with? | A bow | A pick | Mallets | Brushes',
    'To which instrument family does the trumpet belong? | Brass | Woodwind | Strings | Percussion',
    'Despite its metal body, the saxophone belongs to which family? | Woodwind | Brass | Strings | Percussion',
    'Which musical term means getting gradually louder? | Crescendo | Diminuendo | Staccato | Legato',
    'How many musicians play in a quartet? | 4 | 3 | 5 | 8',
    'Which instrument is nicknamed the “squeezebox”? | Accordion | Bagpipes | Harmonica | Ukulele',
    'Which instrument is especially linked with Scotland? | Bagpipes | Banjo | Sitar | Didgeridoo',
    'What is the highest standard female singing voice? | Soprano | Alto | Tenor | Baritone',
    'Which instrument has a keyboard, pedals and pipes, and haunts many old churches? | Pipe organ | Harpsichord | Accordion | Celesta',
    'What does a conductor usually hold to lead an orchestra? | A baton | A bow | A drumstick | A wand',
    'Which Australian instrument is a long wooden tube played with a drone? | Didgeridoo | Ukulele | Sitar | Kazoo',
    'Which note is held for four beats in 4/4 time? | Whole note (semibreve) | Half note (minim) | Quarter note (crotchet) | Eighth note (quaver)',
  ]),
  ...bank('Word Witchery', [
    'What is the plural of “mouse”? | Mice | Mouses | Meese | Mousen',
    'How many letters are in the English alphabet? | 26 | 24 | 28 | 25',
    'Which letter is used most often in English? | E | A | T | S',
    'A word that means the same as another word is called what? | Synonym | Antonym | Homophone | Acronym',
    'Words that sound the same but are spelt differently are called what? | Homophones | Synonyms | Anagrams | Palindromes',
    'Which language has the most native speakers? | Mandarin Chinese | English | Spanish | Hindi',
    'What is the official language of Brazil? | Portuguese | Spanish | Brazilian | French',
    'What is an invitation asking when it says RSVP? | Please reply | Bring food | Dress up | Arrive early',
    'Which of these words is a palindrome? | Level | Lever | Label | Ladle',
    'What does “nocturnal” mean? | Active at night | Afraid of the dark | Living in caves | Eating insects',
    'What is the opposite of “ancient”? | Modern | Antique | Elderly | Historic',
    'Which word is an anagram of “listen”? | Silent | Stolen | Lentils | Glisten',
    'What do you call a word made from the first letters of other words, like “laser”? | Acronym | Synonym | Haiku | Idiom',
    'Which of these is a Japanese poem with three short lines? | Haiku | Sonnet | Limerick | Ballad',
    '“Bonjour” means hello in which language? | French | Italian | Spanish | Dutch',
    'How many syllables does the word “skeleton” have? | 3 | 2 | 4 | 5',
  ]),
  ...bank('Counting Coffins', [
    'What is 7 × 8? | 56 | 54 | 48 | 64',
    'How many sides does a hexagon have? | 6 | 5 | 7 | 8',
    'How many degrees are in a right angle? | 90 | 45 | 180 | 360',
    'What is the square root of 81? | 9 | 8 | 7 | 18',
    'How many minutes are there in a day? | 1,440 | 1,240 | 1,600 | 3,600',
    'How many seconds are in an hour? | 3,600 | 360 | 6,000 | 1,440',
    'What is 15% of 200? | 30 | 15 | 20 | 35',
    'Which Roman numeral stands for 50? | L | C | X | D',
    'Which Roman numeral stands for 100? | C | M | L | D',
    'How many zeros are in one million? | 6 | 5 | 7 | 9',
    'The angles inside a triangle add up to how many degrees? | 180 | 90 | 270 | 360',
    'Which is the next prime number after 7? | 11 | 9 | 13 | 15',
    'How many is a dozen dozens? | 144 | 124 | 120 | 112',
    'How many faces does a cube have? | 6 | 4 | 8 | 12',
    'What is 1,000 divided by 8? | 125 | 120 | 108 | 150',
    'What do you call a shape with eight sides? | Octagon | Hexagon | Pentagon | Decagon',
    'How many days are in a leap year? | 366 | 365 | 364 | 367',
    'What is 13 × 3? | 39 | 33 | 36 | 42',
  ]),
  ...bank('Mad Inventors', [
    'Who received the first US patent for the telephone, in 1876? | Alexander Graham Bell | Thomas Edison | Nikola Tesla | Samuel Morse',
    'Morse code is made of what? | Dots and dashes | Colours | Musical notes | Letters and stars',
    'Who built Europe’s first printing press with movable metal type? | Johannes Gutenberg | Leonardo da Vinci | Isaac Newton | Galileo Galilei',
    'Thomas Edison’s lab made a long-lasting version of which invention in 1879? | Light bulb | Telephone | Radio | Television',
    'Who invented the World Wide Web? | Tim Berners-Lee | Bill Gates | Steve Jobs | Alan Turing',
    'What did Louis Braille create? | A raised-dot alphabet | The hot-air balloon | Sign language | Shorthand',
    'What does a seismograph measure? | Earthquakes | Wind speed | Rainfall | Air pressure',
    'In 1783, the Montgolfier brothers launched people in what? | A hot-air balloon | An airship | A glider | A rocket',
    'James Watt is famous for improving which machine? | The steam engine | The bicycle | The telescope | The clock',
    'Which instrument lets you see very distant objects in the night sky? | Telescope | Microscope | Periscope | Stethoscope',
    'What does a compass needle point toward? | Magnetic north | The Sun | The Moon | Magnetic south',
    'Which device do doctors use to listen to your heartbeat? | Stethoscope | Thermometer | Otoscope | Microscope',
  ]),
  ...bank('Dark and Stormy', [
    'What is the calm centre of a hurricane called? | The eye | The heart | The core | The well',
    'Balls of ice that fall during thunderstorms are called what? | Hail | Sleet | Frost | Dew',
    'Which tree grows acorns? | Oak | Maple | Pine | Birch',
    'Which fluffy, cotton-wool clouds often appear on sunny days? | Cumulus | Cirrus | Stratus | Nimbostratus',
    'Traditionally, how many colours are in a rainbow? | 7 | 5 | 6 | 9',
    'Which kind of tree is the tallest in the world? | Coast redwood | Giant sequoia | Douglas fir | Baobab',
    'Which of these is hotter? | A lightning bolt | The Sun’s surface | Lava | A candle flame',
    'What do you call a scientist who studies the weather? | Meteorologist | Geologist | Astronomer | Botanist',
    'What does a Venus flytrap catch for food? | Insects | Fruit | Fish | Seeds',
    'Young plants of which flower turn to follow the sun across the sky? | Sunflower | Daisy | Tulip | Rose',
    'Stalactites hang from where? | Cave ceilings | Cave floors | Cliff tops | Tree branches',
    'What is molten rock called once it erupts onto the surface? | Lava | Magma | Basalt | Pumice',
    'Which is the only continent with no native trees? | Antarctica | Australia | Africa | Europe',
    'You see lightning before you hear thunder because light is what? | Faster than sound | Louder than sound | Closer than sound | Brighter at night',
    'What gas do trees release that we need to breathe? | Oxygen | Carbon dioxide | Helium | Nitrogen',
  ]),
  ...bank('Room Service', [
    'How many hours are in a week? | 168 | 144 | 172 | 186',
    'Mixing blue and yellow paint makes which colour? | Green | Purple | Orange | Brown',
    'Which month usually has the fewest days? | February | April | June | November',
    'How many sides does a standard stop sign have? | 8 | 6 | 5 | 10',
    'On a standard dice, opposite faces always add up to what? | 7 | 6 | 8 | 12',
    'How many squares are on a chessboard? | 64 | 48 | 81 | 100',
    'In chess, which piece moves only diagonally? | Bishop | Rook | Knight | Pawn',
    'How many cards are in a standard deck, without jokers? | 52 | 54 | 48 | 50',
    'Which colour do you get by mixing red and blue paint? | Purple | Green | Orange | Pink',
    'How many minutes are in three hours? | 180 | 160 | 200 | 300',
    'What is the freezing point of water in Celsius? | 0 °C | 32 °C | -10 °C | 4 °C',
    'When you flip a coin, which side usually shows a face? | Heads | Tails | Edges | Rims',
    'How many days are in a fortnight? | 14 | 10 | 12 | 15',
    'A “baker’s dozen” is how many? | 13 | 12 | 14 | 15',
  ]),
  ...bank('Haunted Gallery', [
    'Who painted The Starry Night? | Vincent van Gogh | Claude Monet | Pablo Picasso | Salvador Dalí',
    'Who wrote Romeo and Juliet? | William Shakespeare | Christopher Marlowe | Charles Dickens | Geoffrey Chaucer',
    'Which artist is famous for paintings of melting clocks? | Salvador Dalí | Pablo Picasso | Henri Matisse | Andy Warhol',
    'Who wrote Alice’s Adventures in Wonderland? | Lewis Carroll | Roald Dahl | C. S. Lewis | Beatrix Potter',
    'In which city is the Louvre museum? | Paris | Rome | London | Madrid',
    'Who carved the giant marble statue of David in Florence? | Michelangelo | Auguste Rodin | Raphael | Leonardo da Vinci',
    'Who created the detective Sherlock Holmes? | Arthur Conan Doyle | Agatha Christie | Charles Dickens | Edgar Allan Poe',
    'Claude Monet is a leading painter of which art movement? | Impressionism | Cubism | Surrealism | Pop art',
    'Who wrote The Hobbit? | J. R. R. Tolkien | C. S. Lewis | Roald Dahl | Philip Pullman',
    'Which artist co-founded Cubism? | Pablo Picasso | Claude Monet | Rembrandt | Frida Kahlo',
    'Which Mexican artist is famous for her bold self-portraits? | Frida Kahlo | Georgia O’Keeffe | Mary Cassatt | Tamara de Lempicka',
    'What is a painting of fruit, flowers or objects on a table called? | A still life | A landscape | A portrait | A mural',
    'Who wrote the poem The Raven? | Edgar Allan Poe | Robert Frost | Emily Dickinson | Walt Whitman',
    'Which Dutch artist painted Girl with a Pearl Earring? | Johannes Vermeer | Rembrandt | Vincent van Gogh | Piet Mondrian',
  ]),
  ...bank('Last Orders', [
    'Which spirit is the base of a classic margarita? | Tequila | Rum | Gin | Vodka',
    'A mojito is made with which spirit? | Rum | Tequila | Whisky | Gin',
    'Real champagne must come from which country? | France | Italy | Spain | Germany',
    'Which spirit gets its flavour from juniper berries? | Gin | Vodka | Rum | Brandy',
    'Sake is brewed from what? | Rice | Potatoes | Barley | Grapes',
    'By law, bourbon must be made from at least half what? | Corn | Rice | Oats | Rye',
    'Which brunch cocktail mixes vodka with tomato juice? | Bloody Mary | Zombie | Corpse Reviver | Black Widow',
    'The fruity Zombie cocktail is built mainly on which spirit? | Rum | Gin | Vodka | Tequila',
    'What is the scientific name for a hangover? | Veisalgia | Vertigo | Neuralgia | Nostalgia',
    'Which drink is a mix of beer and lemonade? | Shandy | Spritzer | Snakebite | Bellini',
    'Which cocktail mixes prosecco with peach purée? | Bellini | Mimosa | Kir Royale | Spritz',
    'Which fortified wine is named after the Portuguese city of Porto? | Port | Sherry | Madeira | Marsala',
    'Absinthe is famously what colour? | Green | Blue | Red | Gold',
    'Which country does Scotch whisky come from? | Scotland | Ireland | Wales | Canada',
    'Which drink is made from fermented apples? | Cider | Mead | Perry | Kombucha',
    'Mead is an ancient drink brewed from what? | Honey | Milk | Apples | Rice',
  ], true),
];

export const CATEGORIES: readonly Category[] = [
  { name: 'Fruits', yes: ['Apple', 'Banana', 'Mango', 'Cherry', 'Pear', 'Pineapple', 'Grape', 'Kiwi'], no: ['Carrot', 'Potato', 'Onion', 'Celery', 'Broccoli', 'Lettuce', 'Spinach'] },
  { name: 'Vegetables', yes: ['Carrot', 'Potato', 'Onion', 'Celery', 'Cabbage', 'Spinach', 'Lettuce', 'Leek'], no: ['Apple', 'Orange', 'Bread', 'Cheese', 'Chocolate', 'Honey', 'Banana'] },
  { name: 'Mammals', yes: ['Dolphin', 'Bat', 'Whale', 'Elephant', 'Kangaroo', 'Mouse', 'Horse', 'Human'], no: ['Shark', 'Penguin', 'Crocodile', 'Frog', 'Salmon', 'Eagle', 'Lizard', 'Octopus'] },
  { name: 'Birds', yes: ['Penguin', 'Ostrich', 'Owl', 'Flamingo', 'Parrot', 'Robin', 'Emu', 'Peacock'], no: ['Bat', 'Butterfly', 'Flying fish', 'Dragonfly', 'Bee', 'Pterodactyl', 'Squirrel'] },
  { name: 'Insects', yes: ['Ant', 'Bee', 'Beetle', 'Butterfly', 'Ladybird', 'Grasshopper', 'Mosquito', 'Wasp'], no: ['Spider', 'Scorpion', 'Worm', 'Snail', 'Centipede', 'Tick', 'Slug'] },
  { name: 'Planets', yes: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'], no: ['Pluto', 'The Moon', 'The Sun', 'Titan', 'Ceres', 'Halley’s Comet', 'Sirius'] },
  { name: 'Countries in Europe', yes: ['France', 'Spain', 'Norway', 'Poland', 'Greece', 'Portugal', 'Ireland', 'Austria'], no: ['Brazil', 'Japan', 'Canada', 'Egypt', 'Peru', 'Kenya', 'Australia', 'India'] },
  { name: 'Countries in Africa', yes: ['Kenya', 'Egypt', 'Nigeria', 'Ghana', 'Morocco', 'Ethiopia', 'Senegal', 'Zambia'], no: ['Brazil', 'India', 'Chile', 'Spain', 'Vietnam', 'Mexico', 'Iceland'] },
  { name: 'Capital cities', yes: ['Paris', 'Tokyo', 'Rome', 'Cairo', 'Madrid', 'Ottawa', 'Canberra', 'Nairobi'], no: ['Sydney', 'New York', 'Toronto', 'Barcelona', 'Milan', 'Istanbul', 'Rio de Janeiro', 'Los Angeles'] },
  { name: 'Stringed instruments', yes: ['Violin', 'Guitar', 'Harp', 'Cello', 'Banjo', 'Ukulele', 'Double bass', 'Sitar'], no: ['Trumpet', 'Flute', 'Drum', 'Clarinet', 'Trombone', 'Harmonica', 'Xylophone', 'Tuba'] },
  { name: 'Woodwind instruments', yes: ['Flute', 'Clarinet', 'Oboe', 'Bassoon', 'Saxophone', 'Piccolo', 'Recorder'], no: ['Trumpet', 'Trombone', 'Tuba', 'Violin', 'Drum', 'French horn', 'Harp'] },
  { name: 'Brass instruments', yes: ['Trumpet', 'Trombone', 'Tuba', 'French horn', 'Cornet', 'Bugle', 'Euphonium'], no: ['Flute', 'Saxophone', 'Clarinet', 'Oboe', 'Violin', 'Harp', 'Xylophone'] },
  { name: 'Percussion instruments', yes: ['Drum', 'Xylophone', 'Cymbals', 'Tambourine', 'Triangle', 'Maracas', 'Timpani', 'Bongos'], no: ['Violin', 'Flute', 'Trumpet', 'Harp', 'Cello', 'Oboe', 'Bagpipes'] },
  { name: 'Shapes with only straight sides', yes: ['Triangle', 'Square', 'Pentagon', 'Hexagon', 'Rectangle', 'Octagon', 'Rhombus'], no: ['Circle', 'Oval', 'Crescent', 'Semicircle', 'Heart', 'Ellipse'] },
  { name: 'Prime numbers', yes: ['2', '3', '5', '7', '11', '13', '17', '19', '23'], no: ['1', '4', '9', '15', '21', '27', '33', '49', '51'] },
  { name: 'Numbers divisible by 3', yes: ['12', '21', '33', '45', '51', '81', '99'], no: ['10', '22', '25', '41', '52', '70', '100'] },
  { name: 'Games played with a deck of cards', yes: ['Poker', 'Snap', 'Solitaire', 'Rummy', 'Bridge', 'Go Fish', 'Blackjack'], no: ['Chess', 'Draughts', 'Backgammon', 'Mahjong', 'Dominoes', 'Hopscotch', 'Tag'] },
  { name: 'Sports played with a ball', yes: ['Football', 'Tennis', 'Golf', 'Cricket', 'Rugby', 'Basketball', 'Baseball', 'Volleyball'], no: ['Badminton', 'Ice hockey', 'Archery', 'Fencing', 'Swimming', 'Boxing', 'Cycling', 'Judo'] },
  { name: 'Animals that lay eggs', yes: ['Chicken', 'Crocodile', 'Platypus', 'Salmon', 'Turtle', 'Frog', 'Spider', 'Ant'], no: ['Cow', 'Dog', 'Whale', 'Bat', 'Kangaroo', 'Horse', 'Human', 'Dolphin'] },
  { name: 'Animals with a shell', yes: ['Tortoise', 'Snail', 'Crab', 'Lobster', 'Oyster', 'Clam', 'Mussel'], no: ['Frog', 'Slug', 'Octopus', 'Jellyfish', 'Earthworm', 'Seal', 'Rabbit'] },
  { name: 'Mostly nocturnal animals', yes: ['Owl', 'Bat', 'Hedgehog', 'Badger', 'Moth', 'Raccoon', 'Aye-aye'], no: ['Squirrel', 'Butterfly', 'Eagle', 'Bee', 'Pigeon', 'Tortoise'] },
  { name: 'Greek gods', yes: ['Zeus', 'Poseidon', 'Hades', 'Athena', 'Apollo', 'Hermes', 'Aphrodite', 'Ares'], no: ['Thor', 'Odin', 'Jupiter', 'Anubis', 'Ra', 'Loki', 'Mercury'] },
  { name: 'Norse gods', yes: ['Odin', 'Thor', 'Loki', 'Freya', 'Frigg', 'Baldur', 'Tyr', 'Heimdall'], no: ['Zeus', 'Apollo', 'Ra', 'Anubis', 'Venus', 'Hermes', 'Isis', 'Poseidon'] },
  { name: 'Colours of the rainbow', yes: ['Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Indigo', 'Violet'], no: ['Pink', 'Brown', 'Black', 'White', 'Grey', 'Gold', 'Silver', 'Turquoise'] },
  { name: 'Chess pieces', yes: ['King', 'Queen', 'Bishop', 'Knight', 'Rook', 'Pawn'], no: ['Jack', 'Ace', 'Joker', 'Duke', 'Prince', 'Wizard', 'Jester'] },
  { name: 'Palindromes', yes: ['Level', 'Radar', 'Kayak', 'Racecar', 'Civic', 'Rotor', 'Madam', 'Refer'], no: ['Lever', 'Rabbit', 'Canoe', 'Robot', 'Rocket', 'Motor', 'Paddle', 'Banana'] },
  { name: 'Bones in the human body', yes: ['Femur', 'Tibia', 'Rib', 'Radius', 'Ulna', 'Patella', 'Fibula', 'Skull'], no: ['Biceps', 'Liver', 'Tendon', 'Kidney', 'Spleen', 'Aorta', 'Tonsil', 'Pancreas'] },
  { name: 'Organs in the human body', yes: ['Heart', 'Liver', 'Lungs', 'Kidney', 'Brain', 'Stomach', 'Spleen', 'Pancreas'], no: ['Femur', 'Elbow', 'Rib', 'Eyebrow', 'Fingernail', 'Kneecap', 'Skull'] },
  { name: 'Gemstones', yes: ['Diamond', 'Ruby', 'Emerald', 'Sapphire', 'Amethyst', 'Topaz', 'Opal'], no: ['Granite', 'Marble', 'Chalk', 'Slate', 'Sandstone', 'Limestone', 'Coal'] },
  { name: 'Metals', yes: ['Iron', 'Copper', 'Gold', 'Silver', 'Tin', 'Zinc', 'Aluminium', 'Lead'], no: ['Oxygen', 'Helium', 'Carbon', 'Sulphur', 'Neon', 'Nitrogen', 'Wood', 'Glass'] },
  { name: 'Gases at room temperature', yes: ['Oxygen', 'Helium', 'Neon', 'Nitrogen', 'Hydrogen', 'Argon', 'Chlorine'], no: ['Iron', 'Mercury', 'Gold', 'Copper', 'Sulphur', 'Carbon', 'Silicon'] },
  { name: 'Dog breeds', yes: ['Poodle', 'Beagle', 'Dalmatian', 'Labrador', 'Dachshund', 'Husky', 'Pug', 'Corgi'], no: ['Siamese', 'Persian', 'Maine Coon', 'Sphynx', 'Clydesdale', 'Merino', 'Angora'] },
  { name: 'Cat breeds', yes: ['Siamese', 'Persian', 'Maine Coon', 'Sphynx', 'Bengal', 'Ragdoll', 'Burmese'], no: ['Poodle', 'Beagle', 'Dalmatian', 'Husky', 'Pug', 'Corgi', 'Collie'] },
  { name: 'Pasta shapes', yes: ['Spaghetti', 'Penne', 'Fusilli', 'Farfalle', 'Linguine', 'Rigatoni', 'Macaroni', 'Tagliatelle'], no: ['Risotto', 'Paella', 'Tortilla', 'Focaccia', 'Bruschetta', 'Polenta', 'Tiramisu'] },
  { name: 'Cheeses', yes: ['Cheddar', 'Brie', 'Gouda', 'Mozzarella', 'Parmesan', 'Feta', 'Stilton', 'Camembert'], no: ['Hummus', 'Tofu', 'Butter', 'Yoghurt', 'Mayonnaise', 'Custard', 'Mustard'] },
  { name: 'Citrus fruits', yes: ['Lemon', 'Lime', 'Orange', 'Grapefruit', 'Tangerine', 'Clementine', 'Kumquat'], no: ['Apple', 'Banana', 'Mango', 'Kiwi', 'Grape', 'Peach', 'Strawberry'] },
  { name: 'Spices', yes: ['Cinnamon', 'Paprika', 'Turmeric', 'Nutmeg', 'Cumin', 'Cloves', 'Saffron'], no: ['Sugar', 'Flour', 'Rice', 'Butter', 'Vinegar', 'Honey', 'Salt'] },
  { name: 'Herbs', yes: ['Basil', 'Mint', 'Parsley', 'Rosemary', 'Thyme', 'Oregano', 'Sage', 'Coriander'], no: ['Cinnamon', 'Ginger', 'Cumin', 'Nutmeg', 'Saffron', 'Turmeric', 'Paprika'] },
  { name: 'Words that rhyme with GHOST', yes: ['Toast', 'Most', 'Host', 'Post', 'Coast', 'Roast', 'Boast'], no: ['Cost', 'Lost', 'Ghoul', 'Goose', 'Guest', 'Frost', 'Gust'] },
  { name: 'Words that rhyme with NIGHT', yes: ['Bite', 'Kite', 'Light', 'Fright', 'White', 'Height', 'Write', 'Sight'], no: ['Weight', 'Eight', 'Bit', 'Wit', 'Neat', 'Nut', 'Fruit'] },
  { name: 'Plays by Shakespeare', yes: ['Hamlet', 'Macbeth', 'Othello', 'King Lear', 'The Tempest', 'Twelfth Night', 'Romeo and Juliet'], no: ['Oliver Twist', 'Pride and Prejudice', 'Dracula', 'Frankenstein', 'Moby-Dick', 'Jane Eyre', 'Emma'] },
  { name: 'Books by Charles Dickens', yes: ['Oliver Twist', 'Great Expectations', 'Bleak House', 'Hard Times', 'David Copperfield', 'A Christmas Carol'], no: ['Hamlet', 'Emma', 'Dracula', 'Jane Eyre', 'Frankenstein', 'Moby-Dick', 'Little Women'] },
  { name: 'Moons of planets', yes: ['Titan', 'Europa', 'Ganymede', 'Io', 'Callisto', 'Phobos', 'Deimos', 'Triton'], no: ['Mars', 'Venus', 'Pluto', 'Ceres', 'Sirius', 'Polaris', 'Andromeda'] },
  { name: 'Constellations', yes: ['Orion', 'Cassiopeia', 'Leo', 'Scorpius', 'Ursa Major', 'Cygnus', 'Gemini', 'Taurus'], no: ['Sirius', 'Polaris', 'Betelgeuse', 'Jupiter', 'Halley’s Comet', 'The Moon', 'Milky Way'] },
  { name: 'Oceans and seas', yes: ['Pacific', 'Atlantic', 'Indian', 'Arctic', 'Mediterranean', 'Caribbean', 'Baltic'], no: ['Nile', 'Amazon', 'Danube', 'Thames', 'Mississippi', 'Superior', 'Ganges'] },
  { name: 'Rivers', yes: ['Nile', 'Amazon', 'Danube', 'Thames', 'Mississippi', 'Ganges', 'Yangtze', 'Seine'], no: ['Everest', 'Sahara', 'Baltic', 'Kilimanjaro', 'Gobi', 'Alps', 'Caribbean'] },
  { name: 'Mountains', yes: ['Everest', 'K2', 'Kilimanjaro', 'Mont Blanc', 'Matterhorn', 'Fuji', 'Denali', 'Ben Nevis'], no: ['Sahara', 'Nile', 'Gobi', 'Amazon', 'Danube', 'Baltic', 'Kalahari'] },
  { name: 'Deserts', yes: ['Sahara', 'Gobi', 'Kalahari', 'Atacama', 'Mojave', 'Namib', 'Sonoran'], no: ['Everest', 'Amazon', 'Nile', 'Alps', 'Andes', 'Siberia', 'Serengeti'] },
  { name: 'US states', yes: ['Texas', 'Ohio', 'Florida', 'Alaska', 'Nevada', 'Oregon', 'Maine', 'Utah'], no: ['Toronto', 'Ontario', 'Quebec', 'Yukon', 'Tasmania', 'Bavaria', 'Manitoba'] },
  { name: 'Things with wheels', yes: ['Bicycle', 'Skateboard', 'Wheelbarrow', 'Train', 'Bus', 'Tractor', 'Shopping trolley'], no: ['Sledge', 'Canoe', 'Kayak', 'Hot-air balloon', 'Surfboard', 'Snowboard', 'Rowing boat'] },
  { name: 'Painters', yes: ['Picasso', 'Van Gogh', 'Monet', 'Rembrandt', 'Frida Kahlo', 'Vermeer', 'Botticelli'], no: ['Mozart', 'Beethoven', 'Shakespeare', 'Einstein', 'Newton', 'Darwin', 'Dickens'] },
  { name: 'Composers', yes: ['Mozart', 'Beethoven', 'Bach', 'Chopin', 'Vivaldi', 'Handel', 'Tchaikovsky'], no: ['Picasso', 'Monet', 'Newton', 'Darwin', 'Shakespeare', 'Rembrandt', 'Galileo'] },
  { name: 'Scientists', yes: ['Newton', 'Einstein', 'Darwin', 'Marie Curie', 'Galileo', 'Faraday', 'Pasteur'], no: ['Mozart', 'Picasso', 'Monet', 'Bach', 'Chopin', 'Dickens', 'Rembrandt'] },
  { name: 'Words with a silent first letter', yes: ['Knight', 'Knee', 'Wrist', 'Write', 'Gnome', 'Psychic', 'Honest', 'Wrap'], no: ['Kite', 'Window', 'Garden', 'Pirate', 'Hotel', 'Night', 'Grape'] },
  { name: 'Units of length', yes: ['Metre', 'Mile', 'Inch', 'Foot', 'Yard', 'Kilometre', 'Centimetre', 'Furlong'], no: ['Litre', 'Gram', 'Pound', 'Ounce', 'Second', 'Kelvin', 'Gallon', 'Acre'] },
  { name: 'Units of time', yes: ['Second', 'Minute', 'Hour', 'Day', 'Week', 'Fortnight', 'Decade', 'Century'], no: ['Metre', 'Mile', 'Litre', 'Gram', 'Pint', 'Acre', 'Volt'] },
  { name: 'Languages', yes: ['French', 'Spanish', 'Swahili', 'Hindi', 'Japanese', 'Portuguese', 'Arabic', 'Welsh'], no: ['Brazilian', 'Mexican', 'Austrian', 'Belgian', 'Canadian', 'American', 'Swiss'] },
  { name: 'Chemical elements', yes: ['Oxygen', 'Carbon', 'Gold', 'Helium', 'Iron', 'Sodium', 'Neon', 'Calcium'], no: ['Water', 'Salt', 'Steel', 'Bronze', 'Brass', 'Glass', 'Air', 'Plastic'] },
  { name: 'Alloys', yes: ['Steel', 'Bronze', 'Brass', 'Pewter', 'Sterling silver', 'Solder'], no: ['Iron', 'Copper', 'Gold', 'Tin', 'Zinc', 'Aluminium'] },
  { name: 'Reptiles', yes: ['Snake', 'Lizard', 'Crocodile', 'Tortoise', 'Turtle', 'Gecko', 'Iguana', 'Chameleon'], no: ['Frog', 'Toad', 'Newt', 'Salamander', 'Eel', 'Shark', 'Penguin'] },
  { name: 'Amphibians', yes: ['Frog', 'Toad', 'Newt', 'Salamander', 'Axolotl', 'Caecilian'], no: ['Lizard', 'Crocodile', 'Turtle', 'Snake', 'Eel', 'Seal', 'Otter'] },
  { name: 'Fish', yes: ['Salmon', 'Shark', 'Tuna', 'Cod', 'Goldfish', 'Eel', 'Seahorse', 'Trout'], no: ['Whale', 'Dolphin', 'Starfish', 'Jellyfish', 'Octopus', 'Crab', 'Seal', 'Penguin'] },
  { name: 'Sports played on ice', yes: ['Ice hockey', 'Curling', 'Figure skating', 'Speed skating', 'Bandy', 'Ice dancing'], no: ['Skiing', 'Snowboarding', 'Surfing', 'Rowing', 'Tennis', 'Golf', 'Rugby'] },
  { name: 'Water sports', yes: ['Swimming', 'Surfing', 'Rowing', 'Diving', 'Water polo', 'Canoeing', 'Sailing', 'Kayaking'], no: ['Archery', 'Fencing', 'Golf', 'Tennis', 'Cycling', 'Darts', 'Boxing', 'Bowling'] },
  { name: 'Martial arts', yes: ['Karate', 'Judo', 'Taekwondo', 'Kung fu', 'Aikido', 'Jujitsu', 'Capoeira'], no: ['Ballet', 'Yoga', 'Pilates', 'Tango', 'Zumba', 'Gymnastics', 'Hula'] },
  { name: 'Dances', yes: ['Waltz', 'Tango', 'Salsa', 'Foxtrot', 'Cha-cha', 'Ballet', 'Flamenco'], no: ['Karate', 'Judo', 'Sudoku', 'Origami', 'Haiku', 'Fencing', 'Croquet'] },
  { name: 'Words borrowed from Japanese', yes: ['Sushi', 'Origami', 'Haiku', 'Karaoke', 'Tsunami', 'Kimono', 'Emoji', 'Bonsai'], no: ['Pizza', 'Ballet', 'Tango', 'Croissant', 'Safari', 'Pyjamas', 'Kindergarten'] },
  { name: 'Words borrowed from French', yes: ['Ballet', 'Croissant', 'Bouquet', 'Rendezvous', 'Déjà vu', 'Souvenir', 'Chauffeur'], no: ['Pizza', 'Sushi', 'Kindergarten', 'Safari', 'Karaoke', 'Tsunami', 'Pyjamas'] },
  { name: 'Plant-eating animals', yes: ['Cow', 'Rabbit', 'Giraffe', 'Elephant', 'Horse', 'Koala', 'Deer', 'Zebra'], no: ['Lion', 'Wolf', 'Shark', 'Tiger', 'Eagle', 'Crocodile', 'Polar bear'] },
  { name: 'Words hiding an animal', yes: ['Scatter', 'Bratty', 'Infantry', 'Doggedly', 'Cowboy', 'Batch', 'Pigment', 'Grateful'], no: ['Window', 'Tulip', 'Monday', 'Thunder', 'Lettuce', 'Picnic', 'Purple', 'Silver'] },
  { name: 'Body parts with three letters', yes: ['Arm', 'Leg', 'Ear', 'Eye', 'Hip', 'Lip', 'Toe', 'Jaw', 'Rib'], no: ['Nose', 'Hand', 'Knee', 'Neck', 'Chin', 'Foot', 'Shin'] },
  { name: 'Creatures from Greek myth', yes: ['Minotaur', 'Medusa', 'Cyclops', 'Hydra', 'Pegasus', 'Centaur', 'Cerberus'], no: ['Yeti', 'Bigfoot', 'Kraken', 'Banshee', 'Leprechaun', 'Golem', 'Kelpie'] },
  { name: 'Animals with eight legs', yes: ['Spider', 'Scorpion', 'Tick', 'Mite', 'Tarantula', 'Harvestman'], no: ['Ant', 'Beetle', 'Crab', 'Centipede', 'Fly', 'Lobster', 'Bee'] },
  { name: 'Cocktails', yes: ['Mojito', 'Margarita', 'Martini', 'Daiquiri', 'Negroni', 'Cosmopolitan', 'Bellini'], no: ['Cappuccino', 'Smoothie', 'Lemonade', 'Milkshake', 'Kombucha', 'Latte', 'Horchata'], adult: true },
  { name: 'Styles of beer', yes: ['Lager', 'Stout', 'Porter', 'Pilsner', 'IPA', 'Bitter'], no: ['Merlot', 'Chardonnay', 'Prosecco', 'Rum', 'Gin', 'Vodka', 'Brandy'], adult: true },
  { name: 'Wine grapes', yes: ['Merlot', 'Chardonnay', 'Pinot Noir', 'Shiraz', 'Riesling', 'Sauvignon Blanc'], no: ['Stout', 'Lager', 'Pilsner', 'Bourbon', 'Tequila', 'Cider', 'Mead'], adult: true },
  { name: 'Spirits', yes: ['Vodka', 'Gin', 'Rum', 'Tequila', 'Whisky', 'Brandy'], no: ['Cider', 'Lager', 'Prosecco', 'Merlot', 'Sake', 'Stout', 'Champagne'], adult: true },
];

/** Scramble words: spooky, 5–8 letters, none with a common anagram. */
export const WORDS: readonly string[] = [
  'GHOST', 'GHOUL', 'COFFIN', 'GOBLIN', 'ZOMBIE', 'PUMPKIN', 'SKELETON', 'CAULDRON', 'HAUNTED', 'CRYPT', 'WITCH', 'SPOOKY', 'PHANTOM', 'BANSHEE',
  'VAMPIRE', 'MUMMY', 'WEREWOLF', 'COBWEB', 'LANTERN', 'SHADOW', 'SKULL', 'BROOM', 'CREEPY', 'CLOAK', 'MONSTER', 'GARGOYLE', 'KEYHOLE', 'CHILLS',
];

export const triviaPool = (family: boolean) => family ? TRIVIA.filter(t => !t.adult) : TRIVIA;
export const categoryPool = (family: boolean) => family ? CATEGORIES.filter(c => !c.adult) : CATEGORIES;
