// Server-only original prompts. Never import this file from a client entry.
import type { Format } from './types';
export type Prompt = { id: string; category: string; question: string; format: Format };
const numbers: [string, string, number][] = [
  ['Snack quantities', 'How many mini pancakes would make your ideal breakfast?', 20],
  ['Everyday minutes', 'How many minutes would you wait in line for a free cookie?', 60],
  ['Comfort ratings', 'From 0 to 10, how cozy is a rainy afternoon indoors?', 10],
  ['Party quantities', 'How many balloons does a room need before it feels like a party?', 30],
  ['Everyday hours', 'At what hour would you happily wake up on a free day? Use 0–23.', 23],
  ['Confidence ratings', 'From 0 to 10, how confident are you at wrapping a strangely shaped gift?', 10],
  ['Snack quantities', 'How many olives would you put on your own small pizza?', 20],
  ['Everyday minutes', 'How many minutes could you spend happily watching ducks?', 60],
  ['Adventure ratings', 'From 0 to 10, how keen are you to try a mystery-flavor jelly bean?', 10],
  ['Party quantities', 'How many people make your ideal board-game evening?', 20],
  ['Everyday hours', 'At what hour should a weekend brunch start? Use 0–23.', 23],
  ['Confidence ratings', 'From 0 to 10, how well could you imitate a squeaky door?', 10],
  ['Snack quantities', 'How many marshmallows belong in one mug of cocoa?', 20],
  ['Everyday minutes', 'How many minutes would you spend building a sandcastle?', 60],
  ['Comfort ratings', 'From 0 to 10, how appealing is a nap in a hammock?', 10],
  ['Party quantities', 'How many party hats would you stack on your head for a photo?', 20],
  ['Everyday hours', 'At what hour should a backyard movie begin? Use 0–23.', 23],
  ['Adventure ratings', 'From 0 to 10, how excited would you be to camp in your own living room?', 10],
];
const choices: [string, string, string[]][] = [
  ['A cozy room', 'Where would you search first for a missing TV remote?', ['Sofa', 'Kitchen', 'Bookshelf', 'Window']],
  ['Party supplies', 'Which item would make the best emergency crown?', ['Paper cups', 'Ribbon', 'Napkins', 'Balloons']],
  ['Weather', 'Which forecast would improve a day spent reading indoors?', ['Rain', 'Snow', 'Sun', 'Wind']],
  ['Friendly animals', 'Which animal would be the funniest front-desk receptionist?', ['Otter', 'Owl', 'Tortoise', 'Llama']],
  ['A packed bag', 'Which item would you most regret forgetting on a picnic?', ['Blanket', 'Spoon', 'Hat', 'Book']],
  ['Musical sounds', 'Which instrument should announce the arrival of dessert?', ['Trumpet', 'Triangle', 'Drum', 'Flute']],
  ['Party supplies', 'Which item would you use to build a tiny boat?', ['Paper cups', 'Ribbon', 'Napkins', 'Balloons']],
  ['A cozy room', 'Where would a tiny dragon probably take a nap?', ['Sofa', 'Kitchen', 'Bookshelf', 'Window']],
  ['Weather', 'Which weather would be the hardest to explain to a snowman?', ['Rain', 'Snow', 'Sun', 'Wind']],
  ['Friendly animals', 'Which animal would you trust to guard a tower of biscuits?', ['Otter', 'Owl', 'Tortoise', 'Llama']],
  ['A packed bag', 'Which item could you turn into a puppet most easily?', ['Blanket', 'Spoon', 'Hat', 'Book']],
  ['Musical sounds', 'Which instrument best matches someone tiptoeing past a sleeping cat?', ['Trumpet', 'Triangle', 'Drum', 'Flute']],
  ['Tiny transport', 'How should a mouse commute to its office?', ['Skateboard', 'Toy train', 'Balloon', 'Roller skate']],
  ['Garden finds', 'Which would make the best trophy for a snail race?', ['Leaf', 'Pebble', 'Acorn', 'Flower']],
  ['Kitchen tools', 'Which would make the silliest pretend microphone?', ['Whisk', 'Spatula', 'Ladle', 'Rolling pin']],
  ['Holiday activities', 'Which activity would you choose on a day with no clocks?', ['Baking', 'Hiking', 'Drawing', 'Napping']],
  ['Tiny transport', 'Which vehicle would look best parked outside a fairy bakery?', ['Skateboard', 'Toy train', 'Balloon', 'Roller skate']],
  ['Garden finds', 'Which would you put in a miniature museum first?', ['Leaf', 'Pebble', 'Acorn', 'Flower']],
];
const texts: [string, string][] = [
  ['A food', 'Name a food that would be difficult to eat while wearing mittens.'],
  ['An animal', 'Name an animal that would make a surprisingly polite housemate.'],
  ['A household object', 'Name a household object that looks like it might secretly be a robot.'],
  ['A place', 'Name a place where a surprise marching band would be especially confusing.'],
  ['A color', 'Name the color you would paint a very sleepy spaceship.'],
  ['A hobby', 'Name a hobby a retired pirate might enjoy.'],
  ['A food', 'Name a food that would make a terrible pillow.'],
  ['An animal', 'Name an animal you would put in charge of a library.'],
  ['A household object', 'Name a household object that could serve as a tiny stage.'],
  ['A place', 'Name a place where you would hide a birthday present the size of a bicycle.'],
  ['A color', 'Name a color that sounds right for a cheerful raincoat.'],
  ['A hobby', 'Name a hobby that a cloud might take up.'],
  ['A food', 'Name a food that deserves its own tiny parade.'],
  ['An animal', 'Name an animal whose footsteps would sound funny upstairs.'],
  ['A household object', 'Name a household object you would put in a time capsule.'],
  ['A place', 'Name a place where you would like to find a secret slide.'],
  ['A color', 'Name a color for a dragon who prefers gardening to roaring.'],
  ['A hobby', 'Name a hobby that would be tricky to do on a trampoline.'],
];
// Interleave formats, then the rules shuffle the whole deck from the room seed.
export const prompts: readonly Prompt[] = numbers.flatMap(([category, question, max], i) => [
  { id: `number-${i + 1}`, category, question, format: { kind: 'number' as const, min: 0, max } },
  { id: `choice-${i + 1}`, category: choices[i][0], question: choices[i][1], format: { kind: 'choice' as const, options: choices[i][2] } },
  { id: `text-${i + 1}`, category: texts[i][0], question: texts[i][1], format: { kind: 'text' as const, maxLength: 48 } },
]);
