import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { parseDrawing } from '../../../party-contract/src/index';
import type { Drawing, Outcome } from '../../../party-contract/src/index';
import { ArcadeButton, Countdown, DrawingPad, DrawingRenderer, Eyebrow, Panel, StatusNotice, TextInput } from '../../../party-ui/src/index';
import type { GameClientModule, GameViewProps, SettingsViewProps, ResultsViewProps } from '../../../party-ui/src/index';
import type { Action, PrivateView, PublicView, Settings } from './types';
import { ArtistChip, GalleryArt } from './art';
import './style.css';
type Props = GameViewProps<null, Action, PublicView, PrivateView>;
const empty: Drawing = { strokes: [] };
const phaseNames = { drawing: 'Make your masterpiece', caption: 'Sell a believable bluff', vote: 'Find the real caption', reveal: 'The label comes off', results: 'Gallery closed' };
function Header({ publicView: view, serverNowMs }: Props) {
  return <header className="sketch-bluff-header"><div><Eyebrow>Sketch Bluff · Gallery {view.gallery}/{view.galleries}</Eyebrow><h1 className="kp-display">{phaseNames[view.phase]}</h1></div><div className="sketch-bluff-clock">{view.expected > 0 && <span className="sketch-bluff-meter" role="status"><strong>{view.submitted}<small>/{view.expected}</small></strong><span>submitted</span></span>}{view.phase !== 'results' && <Countdown deadline={view.deadline} serverNowMs={serverNowMs} />}</div></header>;
}
function Standings({ view, rows, playerId }: { view: PublicView; rows?: Outcome['rows']; playerId?: string | null }) {
  const sorted = rows ?? [...view.players].sort((a, b) => b.score - a.score).map(player => ({ playerId: player.id, score: player.score, rank: 1 + view.players.filter(other => other.score > player.score).length }));
  return <ol className={`sketch-bluff-standings ${view.players.length > 6 ? 'sketch-bluff-standings-dense' : ''}`}>{sorted.map(row => { const player = view.players.find(item => item.id === row.playerId)!; return <li key={player.id} data-leading={row.rank === 1}><span className="sketch-bluff-rank" aria-label={`Place ${row.rank}`}>{row.rank}</span><ArtistChip player={player} compact /><span className="sketch-bluff-standing-score">{player.id === playerId && <small>You</small>}<strong className="kp-numeral">{row.score ?? 0}</strong></span></li>; })}</ol>;
}
function Visitors({ view, ids }: { view: PublicView; ids: string[] }) {
  return <span className="sketch-bluff-visitors">{ids.length ? ids.map(id => <ArtistChip key={id} player={view.players.find(player => player.id === id)!} compact />) : <span className="sketch-bluff-muted">Nobody</span>}</span>;
}
function Exhibit({ view }: { view: PublicView }) {
  const artist = view.players.find(player => player.id === view.artistId)!;
  return <><figure key={`${view.gallery}:${view.exhibit}`} className="sketch-bluff-frame" style={{ '--sketch-bluff-artist': artist.color } as CSSProperties}><div className="sketch-bluff-canvas">{view.drawing && <DrawingRenderer drawing={view.drawing} label={`Drawing by ${artist.name}`} />}</div><figcaption><Eyebrow>Exhibit {String(view.exhibit).padStart(2, '0')} / {String(view.exhibitCount).padStart(2, '0')}</Eyebrow><ArtistChip player={artist} />{view.reveal && <div className="sketch-bluff-title-reveal"><span>Original title</span><h2>{view.reveal.answer}</h2></div>}</figcaption></figure>{view.phase === 'reveal' && view.reveal ? <section className="sketch-bluff-reveal"><div className="sketch-bluff-reveal-heading"><Eyebrow>The label comes off</Eyebrow><h2>Who fooled whom?</h2></div><div className={`sketch-bluff-verdicts ${view.choices.length > 5 ? 'sketch-bluff-verdicts-dense' : ''}`}>{view.reveal.choices.map((choice, index) => <Panel className={`sketch-bluff-verdict ${choice.truth ? 'sketch-bluff-truth' : ''}`} key={choice.id} data-many-voters={choice.voters.length > 3}><div className="sketch-bluff-verdict-title"><b className="sketch-bluff-ballot-number" aria-hidden="true">{index + 1}</b>{choice.truth ? <strong>Original prompt <span className="sketch-bluff-stamp">REAL</span></strong> : <strong>{choice.text}</strong>}</div>{!choice.truth && <div className="sketch-bluff-credit"><span>{choice.authors.length ? 'Bluff by' : 'Gallery decoy'}</span>{choice.authors.length > 0 && <Visitors view={view} ids={choice.authors} />}</div>}{choice.voters.length > 0 && <div className="sketch-bluff-credit"><span>{choice.truth ? 'Found by' : 'Fooled'}</span><Visitors view={view} ids={choice.voters} /></div>}</Panel>)}</div><div className="sketch-bluff-gains" aria-label="Points earned this exhibit">{view.players.filter(player => view.reveal!.gains[player.id]! > 0).map(player => <div key={player.id}><strong className="kp-numeral" style={{ color: player.color }}>+{view.reveal!.gains[player.id]}</strong><ArtistChip player={player} compact /></div>)}{!Object.values(view.reveal.gains).some(points => points > 0) && <p>No points this exhibit. The mystery lives on.</p>}</div></section> : view.phase === 'vote' ? <ol className={`sketch-bluff-labels ${view.choices.length > 5 ? 'sketch-bluff-labels-dense' : ''}`}>{view.choices.map((choice, index) => <li key={choice.id}><b className="sketch-bluff-ballot-number" aria-hidden="true">{index + 1}</b><span>{choice.text}</span></li>)}</ol> : <div className="sketch-bluff-stage-note"><Eyebrow>Every picture needs a story</Eyebrow><h2>Make your label<br />sound like the real thing.</h2><p>Everyone except the artist: write a caption that could fool the room.</p><div className="sketch-bluff-note-mark" aria-hidden="true">?</div></div>}</>;
}
function DisplayView(props: Props) {
  const view = props.publicView;
  return <main className={`sketch-bluff sketch-bluff-display sketch-bluff-phase-${view.phase}`}><Header {...props} /><div className="sketch-bluff-gallery">{view.phase === 'drawing' ? <section className="sketch-bluff-intro"><GalleryArt /><h2>Secrets on phones.<br />Masterpieces on the wall.</h2><p>Draw your secret prompt without letters or numbers. Keep it to yourself.</p><div className="sketch-bluff-score-guide"><span><strong>1,000</strong>Find the truth</span><span><strong>500</strong>Fool a friend</span><span><strong>250</strong>Get understood</span></div></section> : <section className="sketch-bluff-exhibit"><Exhibit view={view} /></section>}<aside className="sketch-bluff-score-rail"><Eyebrow>Gallery standings</Eyebrow><Standings view={view} /></aside></div></main>;
}
function PhoneExhibit({ view, children }: { view: PublicView; children: ReactNode }) {
  const artist = view.players.find(player => player.id === view.artistId);
  return <div className="sketch-bluff-phone-exhibit">{view.drawing && <div className="sketch-bluff-thumb" style={{ '--sketch-bluff-artist': artist?.color } as CSSProperties}><DrawingRenderer drawing={view.drawing} label={`Drawing by ${artist?.name ?? 'the artist'}`} /></div>}<div>{children}{artist && <ArtistChip player={artist} compact />}</div></div>;
}
function PhoneReveal({ view, playerId }: { view: PublicView; playerId: string | null }) {
  const reveal = view.reveal!;
  const gained = reveal.gains[playerId!] ?? 0;
  const correct = reveal.choices.find(choice => choice.truth)!.voters;
  const fooled = reveal.choices.filter(choice => !choice.truth && choice.authors.includes(playerId!)).flatMap(choice => choice.voters.filter(voter => voter !== playerId));
  return <section className="sketch-bluff-phone-reveal"><PhoneExhibit view={view}><Eyebrow>The real caption</Eyebrow><h2>{reveal.answer}</h2></PhoneExhibit><div className="sketch-bluff-personal-gain" data-earned={gained > 0}><strong className="kp-numeral">+{gained}</strong><span>points this exhibit</span></div><p>{view.artistId === playerId ? `${correct.length} ${correct.length === 1 ? 'visitor understood' : 'visitors understood'} your drawing.` : correct.includes(playerId!) ? 'You found the real caption.' : 'Your guess missed the real caption.'}</p>{fooled.length > 0 && <><p>Your bluff fooled:</p><Visitors view={view} ids={fooled} /></>}</section>;
}
function ResultsView({ publicView: view, outcome, playerId }: ResultsViewProps<PublicView>) {
  const winners = view.players.filter(player => outcome.winners.includes(player.id));
  return <section className="sketch-bluff sketch-bluff-results"><div className="sketch-bluff-results-hero"><GalleryArt /><Eyebrow>Sketch Bluff · Final collection</Eyebrow><h1 className="kp-display">Gallery closed.</h1><p>{winners.length === 1 ? 'Best in show' : `${winners.length} artists share first place`}</p><div className="sketch-bluff-winners">{winners.map(player => <ArtistChip key={player.id} player={player} />)}</div>{view.skipped > 0 && <p className="sketch-bluff-muted">{view.skipped} blank or missing {view.skipped === 1 ? 'drawing was' : 'drawings were'} skipped.</p>}</div><div className="sketch-bluff-final-standings"><Eyebrow>The final standings</Eyebrow><Standings view={view} rows={outcome.rows} playerId={playerId} /></div></section>;
}
function loadDraft(key: string, fallback: Drawing): Drawing {
  try { const saved = sessionStorage.getItem(key); return saved ? parseDrawing(JSON.parse(saved)) : fallback; } catch { return fallback; }
}
function PhoneTurn(props: Props) {
  const view = props.publicView, privateView = props.privateView;
  const storageKey = `sketch-bluff:${props.roundId}:${props.playerId}:${view.turnId}`;
  const [drawing, setDrawing] = useState(() => loadDraft(storageKey, privateView?.draft ?? empty));
  const [caption, setCaption] = useState(() => { try { return sessionStorage.getItem(`${storageKey}:caption`) ?? privateView?.caption ?? ''; } catch { return privateView?.caption ?? ''; } });
  const [pending, setPending] = useState(false), [ack, setAck] = useState(''), [error, setError] = useState('');
  const sending = useRef(false);
  const [expired, setExpired] = useState(() => props.serverNowMs() >= view.deadline);
  useEffect(() => { const timer = setInterval(() => setExpired(props.serverNowMs() >= view.deadline), 200); return () => clearInterval(timer); }, [props.serverNowMs, view.deadline]);
  useEffect(() => { if (privateView?.submitted) { try { sessionStorage.removeItem(storageKey); sessionStorage.removeItem(`${storageKey}:caption`); } catch { /* Storage may be unavailable. */ } } }, [privateView?.submitted, storageKey]);
  const submitted = privateView?.submitted || ack === 'Submitted. Waiting for the gallery.';
  const disabled = pending || submitted || expired;
  async function send(action: Action) {
    if (sending.current || disabled) return;
    sending.current = true; setPending(true); setError('');
    try { const result = await props.sendAction(action); if (result.accepted) setAck(action.type === 'save-draft' ? 'Draft saved. You can keep drawing.' : 'Submitted. Waiting for the gallery.'); else setError(result.reason ?? 'Submission was rejected. Try again.'); }
    catch { setError('Connection interrupted. Reconnect and try again.'); }
    finally { sending.current = false; setPending(false); }
  }
  function updateDrawing(next: Drawing) { setDrawing(next); setAck(''); try { sessionStorage.setItem(storageKey, JSON.stringify(next)); } catch { /* The explicit save button remains available. */ } }
  if (!privateView) return <StatusNotice>Waiting for your player view. A watching display has no player seat.</StatusNotice>;
  return <>{error && <StatusNotice tone="error">{error}</StatusNotice>}{pending && <StatusNotice>Sending…</StatusNotice>}{(submitted || ack) && <StatusNotice tone="success">{submitted ? 'Submitted. Waiting for the gallery.' : ack}</StatusNotice>}{expired && view.phase !== 'results' && <StatusNotice>Time is up. Waiting for the next exhibit.</StatusNotice>}
    {view.phase === 'drawing' ? <><Panel><Eyebrow>Your secret drawing prompt</Eyebrow><h2>{privateView.prompt}</h2><p>Draw it without letters or numbers. A blank submission skips your exhibit.</p></Panel><DrawingPad value={drawing} onChange={updateDrawing} disabled={disabled} label="Draw your secret prompt" /><div className="sketch-bluff-actions"><ArcadeButton tone="ghost" disabled={disabled} onClick={() => void send({ type: 'save-draft', turnId: view.turnId, drawing })}>Save draft</ArcadeButton><ArcadeButton tone="sky" disabled={disabled} onClick={() => void send({ type: 'drawing', turnId: view.turnId, drawing })}>{drawing.strokes.length ? 'Submit drawing' : 'Skip blank drawing'}</ArcadeButton></div><p>Drafts stay on this phone. Save draft also keeps a copy for reconnecting on another device.</p></> : view.phase === 'caption' ? privateView.isArtist ? <Panel className="sketch-bluff-artist-wait"><PhoneExhibit view={view}><Eyebrow>Your work is on the wall</Eyebrow><h2>Let them wonder.</h2></PhoneExhibit><p>This is your drawing. Enjoy the bluffs; keep its real caption secret.</p></Panel> : <form onSubmit={event => { event.preventDefault(); void send({ type: 'caption', turnId: view.turnId, text: caption }); }}><PhoneExhibit view={view}><label htmlFor="sketch-bluff-caption">Invent a believable caption</label><p>What could this drawing be?</p></PhoneExhibit><TextInput id="sketch-bluff-caption" value={caption} maxLength={100} autoComplete="off" disabled={disabled} onChange={event => { setCaption(event.target.value); try { sessionStorage.setItem(`${storageKey}:caption`, event.target.value); } catch { /* Keep in React state. */ } }} /><p>{caption.length}/100 characters</p><ArcadeButton type="submit" tone="sky" disabled={disabled || !caption.trim()}>Submit caption</ArcadeButton></form> : view.phase === 'vote' ? privateView.isArtist ? <Panel className="sketch-bluff-artist-wait"><PhoneExhibit view={view}><Eyebrow>Your work is on the wall</Eyebrow><h2>Watch them choose.</h2></PhoneExhibit><p>You cannot vote on your own drawing. Each correct guess earns you 250 points.</p></Panel> : <section><PhoneExhibit view={view}><h2>Find the original title.</h2><p>Pick the real drawing prompt.</p></PhoneExhibit><div className="sketch-bluff-votes">{view.choices.map((choice, index) => <ArcadeButton key={choice.id} tone={privateView.vote === choice.id ? 'lime' : 'sky'} disabled={disabled} onClick={() => void send({ type: 'vote', turnId: view.turnId, choiceId: choice.id })}><b className="sketch-bluff-ballot-number" aria-hidden="true">{index + 1}</b><span>{choice.text}{privateView.vote === choice.id && ' · Your vote'}</span></ArcadeButton>)}</div><p className="sketch-bluff-muted">Your own bluff earns no points from your self-vote.</p></section> : view.phase === 'reveal' ? <PhoneReveal view={view} playerId={props.playerId} /> : <><h2>Your gallery results</h2><Standings view={view} /></>}
  </>;
}
function ControllerView(props: Props) { return <main className="sketch-bluff sketch-bluff-phone"><Header {...props} />{props.privateView ? <PhoneTurn key={`${props.roundId}:${props.playerId}:${props.publicView.turnId}`} {...props} /> : <StatusNotice>Waiting for your private player view.</StatusNotice>}</main>; }
function SettingsView({ settings, onChange, disabled }: SettingsViewProps<Settings>) {
  return <section className="sketch-bluff sketch-bluff-settings"><label>Gallery length<select value={settings.length} disabled={disabled} onChange={event => { const length = event.target.value as Settings['length']; onChange({ length, drawingSeconds: length === 'short' ? 60 : 120, captionSeconds: length === 'short' ? 25 : 45, voteSeconds: length === 'short' ? 20 : 30 }); }}><option value="standard">Standard · about 10–15 minutes</option><option value="short">Short · one drawing each, faster timers</option></select></label><p>Standard: two drawings each with 3–5 players; one each with 6–10. Fast submissions finish sooner.</p>{(['drawingSeconds', 'captionSeconds', 'voteSeconds'] as const).map((key, index) => <label key={key}>{['Drawing seconds', 'Caption seconds', 'Voting seconds'][index]}<TextInput type="number" min={[30, 15, 10][index]} max={[180, 90, 60][index]} step={1} value={settings[key]} disabled={disabled} onChange={event => { const number = Number(event.target.value); if (Number.isInteger(number) && number >= [30, 15, 10][index]! && number <= [180, 90, 60][index]!) onChange({ ...settings, [key]: number }); }} /></label>)}</section>;
}
function InstructionsView() { return <section className="sketch-bluff"><h2>A midnight gallery of questionable masterpieces</h2><ol><li>Draw the secret prompt on your phone. No letters or numbers.</li><li>For each exhibit, everyone except its artist writes a convincing fake caption.</li><li>Pick the real caption from the shuffled labels. The artist sits out.</li><li>Earn 1,000 for a correct guess, 500 per other player fooled by your bluff, and 250 as artist per correct guess.</li></ol><p>Equivalent captions share one choice. Each matching bluff author gets the full 500 for each other player fooled. A caption matching the truth earns no bluff points; you can still guess. Blank or missing drawings are skipped. Timers keep the gallery moving when someone disconnects.</p></section>; }
export const client: GameClientModule<null, Action, Settings, PublicView, PrivateView> = { DisplayView, ControllerView, SettingsView, InstructionsView, ResultsView, prepare() {}, dispose() {} };
export default client;
