// Server only: never import this bank from a client entry point.
export const prompts = [
  'a librarian shelving tiny thunderstorms', 'a cactus applying for a hug license',
  'a ghost ironing its spare sheet', 'a submarine stuck in a teacup',
  'a moon with a very bad haircut', 'a snail delivering emergency confetti',
  'a robot teaching a toaster ballet', 'a pirate searching for the television remote',
  'a jellyfish wearing oven mitts', 'a dinosaur returning an overdue library book',
  'a cloud taking its pet puddle for a walk', 'a vampire opening a garlic bakery',
  'a raccoon inspecting a royal crown', 'an astronaut mowing a tiny planet',
  'a mermaid fixing a flat unicycle tire', 'a wizard accidentally summoning a sandwich',
  'a penguin selling invisible umbrellas', 'a giraffe hiding behind a houseplant',
  'a dragon roasting a single marshmallow', 'a detective interrogating a suspicious sock',
  'a whale trying to fit in a photo booth', 'a mountain wearing fuzzy slippers',
  'a frog conducting an orchestra of spoons', 'a skeleton forgetting where it put its knees',
  'a potato winning a beauty contest', 'a snowman ordering extra hot soup',
  'a mailbox spitting out birthday cake', 'a knight rescuing a trapped pizza',
  'a telescope watching television', 'a kangaroo carrying a tiny office',
  'a mushroom hosting a weather report', 'a shark flossing with a jump rope',
  'a duck painting a portrait of a puddle', 'a castle balancing on a roller skate',
  'a worm reading a very long map', 'a refrigerator going on a beach holiday',
  'a walrus knitting a mustache warmer', 'a comet waiting at a bus stop',
  'a squirrel building an acorn elevator', 'a pancake escaping through a window',
  'a broom interviewing for a flying job', 'a lion practicing a polite whisper',
  'a jellybean running a construction site', 'a ferry carrying one enormous rubber duck',
  'a giraffe using a periscope underground', 'a scarecrow afraid of popcorn',
  'a cactus trying on a wool sweater', 'an octopus untangling eight headphones',
  'a birthday candle making its own wish', 'a crab playing chess against a boot',
  'a sleeping volcano wearing a nightcap', 'a bicycle growing a vegetable garden',
  'a robot sneezing spare buttons', 'a crocodile performing a puppet show',
  'a cloud vacuuming a rainbow', 'a goblin running a lost tooth museum',
  'a polar bear sunbathing on a waffle', 'a traffic cone leading a royal parade',
  'a unicorn charging its horn at a wall socket', 'a goose auditioning to be a doorbell',
] as const;

export const houseCaptions = [
  'a suspiciously formal picnic', 'the annual umbrella inspection',
  'a midnight lesson in good manners', 'the smallest parade in town',
  'an unusual way to deliver breakfast', 'a very complicated birthday surprise',
];
